"Name: \FU:J_1B_NFE_UPDATE_ACTIVE\SE:BEGIN\EI
ENHANCEMENT 0 Z_FILL_HEMI.
* Preencher Hora Emissão
  IF i_doc IS NOT INITIAL AND i_doc-hemi IS INITIAL.

    i_doc-hemi = i_doc-cretim.

  ENDIF.

  "Correção para não sobrepor o protocolo de autorização caso o cancelamento tenha sido rejeitado
  IF ( I_ACTTAB-DOCNUM IS NOT INITIAL ) AND ( I_ACTTAB-DOCSTA EQ '1' OR I_ACTTAB-DOCSTA IS INITIAL ) AND
     ( I_ACTTAB-AUTHCOD IS INITIAL OR
       I_ACTTAB-DOCNUM9 IS INITIAL OR
       I_ACTTAB-CDV     IS INITIAL ).

    SELECT SINGLE *
      FROM J_1BNFE_ACTIVE INTO @DATA(WL_ACTIVE_AUX)
     WHERE DOCNUM = @I_ACTTAB-DOCNUM.

    IF ( SY-SUBRC EQ 0 ) AND ( WL_ACTIVE_AUX-AUTHCOD IS NOT INITIAL ) .

      IF I_ACTTAB-DOCSTA IS INITIAL.

        I_ACTTAB-DOCSTA  = WL_ACTIVE_AUX-DOCSTA.

        IF ( I_ACTTAB-SCSSTA IS INITIAL ) AND  ( WL_ACTIVE_AUX-SCSSTA IS NOT INITIAL ).
          I_ACTTAB-SCSSTA = WL_ACTIVE_AUX-SCSSTA.
        ENDIF.

        IF ( I_ACTTAB-ACTION_REQU IS INITIAL ) AND ( WL_ACTIVE_AUX-ACTION_REQU IS NOT INITIAL ).
          I_ACTTAB-ACTION_REQU = WL_ACTIVE_AUX-ACTION_REQU.
        ENDIF.

        IF ( I_ACTTAB-MSSTAT IS INITIAL ) AND ( WL_ACTIVE_AUX-MSSTAT IS NOT INITIAL ).
          I_ACTTAB-MSSTAT = WL_ACTIVE_AUX-MSSTAT.
        ENDIF.

      ENDIF.

      I_ACTTAB-AUTHCOD     = WL_ACTIVE_AUX-AUTHCOD.
      I_ACTTAB-AUTHDATE    = WL_ACTIVE_AUX-AUTHDATE.
      I_ACTTAB-AUTHTIME    = WL_ACTIVE_AUX-AUTHTIME.
      I_ACTTAB-CODE        = WL_ACTIVE_AUX-CODE.

      IF ( WL_ACTIVE_AUX-DOCNUM9 IS NOT INITIAL ).
        I_ACTTAB-DOCNUM9   = WL_ACTIVE_AUX-DOCNUM9.
      ENDIF.

      IF WL_ACTIVE_AUX-CDV IS NOT INITIAL.
        I_ACTTAB-CDV       = WL_ACTIVE_AUX-CDV.
      ENDIF.

    ENDIF.

  ENDIF.

  "Correção para não sobrepor o protocolo de autorização caso o cancelamento tenha sido rejeitado - Fim

ENDENHANCEMENT.
