FUNCTION ZDENQUEUE_SD_CAD_ROTEIRO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(CHAVE) TYPE  KUNNR
*"     REFERENCE(_SCOPE) DEFAULT '3'
*"     REFERENCE(_SYNCHRON) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT ' '
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __SYNCHRON  TYPE DDENQSYNC.

  __SYNCHRON = _SYNCHRON.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_IT_ZSDT0132,
          MANDT	 TYPE SY-MANDT,
          KUNNR TYPE ZSDT0132-KUNNR,
        END OF %A_IT_ZSDT0132.

  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_IT_ZSDT0132.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_IT_ZSDT0132-MANDT.
  ENDIF.

  MOVE: CHAVE TO %A_IT_ZSDT0132-KUNNR.

* Preencher tab.bloqueio:

  __SEQTA_TAB-GNAME = 'IT_ZSDT0132'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG  = %A_IT_ZSDT0132.
  APPEND __SEQTA_TAB.

* Lock assigned:
  PERFORM SEND_ENQUEUE(SAPLSENA) TABLES __SEQTA_TAB USING '2' __SCOPE ' ' __SYNCHRON 'EZ_ZSDT0132' _COLLECT.

ENDFUNCTION.
