FUNCTION ZSDAJ007_EXIT.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  TABLES
*"      SHLP_TAB TYPE  SHLP_DESCT
*"      RECORD_TAB STRUCTURE  SEAHLPRES
*"  CHANGING
*"     REFERENCE(SHLP) TYPE  SHLP_DESCR
*"     VALUE(CALLCONTROL) TYPE  DDSHF4CTRL
*"----------------------------------------------------------------------

  DATA: LS_FIELDDESCR TYPE DFIES, "loc str for shlp-fielddescr
        LS_SELOPT     TYPE DDSHSELOPT.  "loc str for shlp-selopt

*Local structure for itab record_tab
  DATA: BEGIN OF LS_RECORD.
          INCLUDE STRUCTURE SEAHLPRES.
  DATA: END OF LS_RECORD.

  DATA: LS_NAME1 TYPE NAME1_GP,
        LS_START TYPE STRING,
        LS_END   TYPE STRING,
        V_KUNNR  TYPE KUNNR.

*Internal table to store Customer Name
  DATA: BEGIN OF GT_KNA1 OCCURS 0,
          KUNNR LIKE KNA1-KUNNR,
          NAME1 LIKE KNA1-NAME1,
        END OF GT_KNA1.

  RANGES: LR_KUNNR FOR KNA1-KUNNR.  "Ranges for customer number

  CHECK CALLCONTROL-STEP = 'DISP'.

*  LOOP AT SHLP-FIELDDESCR INTO LS_FIELDDESCR.
*    CASE LS_FIELDDESCR-FIELDNAME.
*      WHEN 'KUNNR'.
*        LS_FIELDDESCR-INTLEN = LS_FIELDDESCR-OUTPUTLEN = 45.
*        MODIFY SHLP-FIELDDESCR FROM LS_FIELDDESCR INDEX SY-TABIX.
*      WHEN 'ERNAM'.
*        LS_FIELDDESCR-OFFSET = 63.
*        MODIFY SHLP-FIELDDESCR FROM LS_FIELDDESCR INDEX SY-TABIX.
*      WHEN 'ERDAT'.
*        LS_FIELDDESCR-OFFSET = 75.
*        MODIFY SHLP-FIELDDESCR FROM LS_FIELDDESCR INDEX SY-TABIX.
*      WHEN 'VBELN'.
*        LS_FIELDDESCR-OFFSET = 83.
*        MODIFY SHLP-FIELDDESCR FROM LS_FIELDDESCR INDEX SY-TABIX.
*    ENDCASE.
*  ENDLOOP.

*Build range for customer number
  LOOP AT SHLP-SELOPT INTO LS_SELOPT WHERE SHLPFIELD = 'KUNNR'.
    LR_KUNNR-SIGN = LS_SELOPT-SIGN.
    LR_KUNNR-OPTION = LS_SELOPT-OPTION.
    LR_KUNNR-LOW = LS_SELOPT-LOW.
    LR_KUNNR-HIGH = LS_SELOPT-HIGH.
    APPEND LR_KUNNR.
    CLEAR: LR_KUNNR.
  ENDLOOP.

*Select Customer name
  SELECT KUNNR NAME1
    FROM KNA1
    INTO TABLE GT_KNA1
    WHERE KUNNR IN LR_KUNNR.

*Modify record_tab to append Customer name to customer number
  LOOP AT RECORD_TAB INTO LS_RECORD.
    V_KUNNR = LS_RECORD-STRING+13(10).
    READ TABLE GT_KNA1 WITH KEY KUNNR = V_KUNNR.
    IF SY-SUBRC = 0.
*      LS_START = LS_RECORD-STRING+0(23).
*      LS_END = LS_RECORD-STRING+23(*).
*      CLEAR: LS_RECORD-STRING.
*      LS_RECORD-STRING+0(23) = LS_START.
*      LS_RECORD-STRING+24(1) = '-'.
*      LS_RECORD-STRING+25(31) = GT_KNA1-NAME1.
*      LS_RECORD-STRING+61(*) = LS_END.
      LS_RECORD-STRING+93(35) = GT_KNA1-NAME1.
      MODIFY RECORD_TAB FROM LS_RECORD.
      CLEAR: LS_RECORD,LS_START,LS_END,GT_KNA1,V_KUNNR.
    ENDIF.
  ENDLOOP.

  DELETE RECORD_TAB WHERE STRING+14(1) EQ SPACE.

ENDFUNCTION.
