FUNCTION ZDENQUEUE_SD_LOTE_INSUMOS.
*"--------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(CHAVE) TYPE  ZNRO_LOTE
*"     REFERENCE(_SCOPE) DEFAULT '3'
*"     REFERENCE(_SYNCHRON) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT ' '
*"--------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __SYNCHRON  TYPE DDENQSYNC.

  __SYNCHRON = _SYNCHRON.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_IT_ZSDT0129,
          MANDT	   TYPE SY-MANDT,
          NRO_LOTE TYPE ZSDT0129-NRO_LOTE,
        END OF %A_IT_ZSDT0129.

  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_IT_ZSDT0129.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_IT_ZSDT0129-MANDT.
  ENDIF.

  MOVE: CHAVE TO %A_IT_ZSDT0129-NRO_LOTE.

* Preencher tab.bloqueio:

  __SEQTA_TAB-GNAME = 'IT_ZSDT0129'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG  = %A_IT_ZSDT0129.
  APPEND __SEQTA_TAB.

* Lock assigned:
  PERFORM SEND_ENQUEUE(SAPLSENA) TABLES __SEQTA_TAB USING '2' __SCOPE ' ' __SYNCHRON 'EZ_ZSDT0129' _COLLECT.

ENDFUNCTION.
