PROCESS BEFORE OUTPUT.
  MODULE STATUS_5510.

  CALL SUBSCREEN SUB551A INCLUDING SY-CPROG VG_SUBT_LOTE.
*  CALL SUBSCREEN SUB511B INCLUDING SY-CPROG '5120'.

PROCESS AFTER INPUT.
  MODULE USER_COMMAND_5510.

  CALL SUBSCREEN SUB551A.
*  CALL SUBSCREEN SUB511B.
