PROCESS BEFORE OUTPUT.
  MODULE ABAS_SET.
  CALL SUBSCREEN ABAS_SCA "SUBTELA
  INCLUDING G_ABAS-PROG G_ABAS-SUBSCREEN.

  MODULE STATUS_7000.
*
PROCESS AFTER INPUT.
  CALL SUBSCREEN ABAS_SCA. "SUBTELA

  MODULE ABAS_GET.

  CHAIN.
    FIELD C_BUSCAR.

    MODULE BUSCA_PLACA ON CHAIN-INPUT.
  ENDCHAIN.

  MODULE USER_COMMAND_7000.
