PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLEST0007 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLEST0007-ID_INTERFACE .
    FIELD ZLEST0007-ID_CTG .
    FIELD ZLEST0007-PREFIX .
    FIELD ZLEST0007-PATHWIN .
    FIELD ZLEST0007-PATHUNIX .
    FIELD ZLEST0007-USUARIO .
    FIELD ZLEST0007-PATHWIN_REDE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLEST0007-ID_INTERFACE .
    FIELD ZLEST0007-ID_CTG .
    FIELD ZLEST0007-PREFIX .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
