PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLEST0001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLEST0001-BUKRS .
    FIELD ZLEST0001-BRANCH .
    FIELD ZLEST0001-SUBOBJ1 .
    FIELD ZLEST0001-NRRANGE1 .
    FIELD ZLEST0001-SUBOBJ2 .
    FIELD ZLEST0001-NRRANGE2 .
    FIELD ZLEST0001-SERIES .
    FIELD ZLEST0001-MARGADTO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLEST0001-BUKRS .
    FIELD ZLEST0001-BRANCH .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
