
PROCESS BEFORE OUTPUT.

  MODULE DISPLAY_0100.

  MODULE STATUS_0100.

PROCESS AFTER INPUT.

  "MODULE LEAVE_100 AT EXIT-COMMAND.

  CHAIN.
    FIELD ZLEST0026-CK_CREDITA_PED.
    MODULE ALTEROU_CK_CREDITO_PED ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD ZLEST0101-CD_CID_ORIGEM.
    FIELD ZLEST0101-CD_CID_DESTINO.
    MODULE ALTEROU_ORG_DEST ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD ZLEST0026-TP_ADMIM_PED.
    MODULE ALTEROU_TP_ADMIM_PED ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD ZLEST0026-TP_ADMIM_FRETE.
    MODULE ALTEROU_TP_ADMIM_FRETE ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0100.
