PROCESS BEFORE OUTPUT.
  MODULE ZM_STATUS_9002.
*
PROCESS AFTER INPUT.

  MODULE ZM_EXIT AT EXIT-COMMAND.

  CHAIN.
    FIELD W_PARAMETROS-INST_PORTUARIA
                      MODULE W_PARAMETROS-INST_PORT_DESC.
  ENDCHAIN.

  MODULE ZM_USER_COMMAND_9002.
