PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLEST0004 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLEST0004-SERIE_DESPACHO .
    FIELD ZLEST0004-NR_DESPACHO .
    FIELD ZLEST0004-EMISSAO .
    FIELD ZLEST0004-ORIGEM .
    FIELD ZLEST0004-DESTINO .
    FIELD ZLEST0004-MERCADORIA .
    FIELD ZLEST0004-PESO .
    FIELD ZLEST0004-TARIFA .
    FIELD ZLEST0004-VLR_TOTAL_FRETE .
    FIELD ZLEST0004-VLR_TOTAL_TAXAS .
    FIELD ZLEST0004-VLR_TOTAL .
    FIELD ZLEST0004-BASE_CALCULO .
    FIELD ZLEST0004-ALIQUOTA .
    FIELD ZLEST0004-VLR_ICMS .
    FIELD ZLEST0004-NR_FATURA .
    FIELD ZLEST0004-CGC_REMETENTE .
    FIELD ZLEST0004-CGC_DEST .
    FIELD ZLEST0004-ARQ_ORI .
    FIELD ZLEST0004-LOTE .
    FIELD ZLEST0004-DATA .
    FIELD ZLEST0004-HORA .
    FIELD ZLEST0004-USUARIO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLEST0004-SERIE_DESPACHO .
    FIELD ZLEST0004-NR_DESPACHO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
