PROCESS BEFORE OUTPUT.
  MODULE LISTE_INITIALISIEREN.
  LOOP AT EXTRACT WITH CONTROL
   TCTRL_ZLEST0030 CURSOR NEXTLINE.
    MODULE LISTE_SHOW_LISTE.
  ENDLOOP.
*
PROCESS AFTER INPUT.
  MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
  MODULE LISTE_BEFORE_LOOP.
  LOOP AT EXTRACT.
    MODULE LISTE_INIT_WORKAREA.
    CHAIN.
      FIELD ZLEST0030-DIRECT .
      FIELD ZLEST0030-DSTCAT .
      FIELD ZLEST0030-INDUSTRY .
      FIELD ZLEST0030-TPPARCEIRO .
      FIELD ZLEST0030-VKAUS .
      FIELD ZLEST0030-CFOP .
      FIELD ZLEST0030-CFOTXT .
      FIELD ZLEST0030-CFOP_UF_EMIT_DIF_PREST.
      FIELD ZLEST0030-TDLNR .
      FIELD ZLEST0030-BUKRS .
      MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    ENDCHAIN.
    FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
    CHAIN.
      FIELD ZLEST0030-DIRECT .
      FIELD ZLEST0030-DSTCAT .
      FIELD ZLEST0030-INDUSTRY .
      FIELD ZLEST0030-TPPARCEIRO .
      FIELD ZLEST0030-VKAUS .
      FIELD ZLEST0030-TDLNR .
      FIELD ZLEST0030-BUKRS .
      MODULE LISTE_UPDATE_LISTE.
    ENDCHAIN.
  ENDLOOP.
  MODULE LISTE_AFTER_LOOP.
