*----------------------------------------------------------------------*
***INCLUDE MZBALANCO_1106 .
*----------------------------------------------------------------------*

DATA: BALANCO_CONTAINER_1106 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      BALANCO_ALV_1106       TYPE REF TO CL_GUI_ALV_GRID,
      BALANCO_CATALOGO_1106  TYPE LVC_T_FCAT,
      BALANCO_GS_LAYOUT_1106 TYPE LVC_S_LAYO.

*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_1106  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_1106 INPUT.

  IF BALANCO_ALV_1106 IS NOT INITIAL.
    CALL METHOD BALANCO_ALV_1106->FREE.
  ENDIF.

  IF BALANCO_CONTAINER_1106 IS NOT INITIAL.
    CALL METHOD BALANCO_CONTAINER_1106->FREE.
  ENDIF.

  CLEAR: BALANCO_ALV_1106, BALANCO_CONTAINER_1106.

  LEAVE TO SCREEN 0.
ENDMODULE.                 " USER_COMMAND_1106  INPUT

*&---------------------------------------------------------------------*
*&      Module  STATUS_1106  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_1106 OUTPUT.

*  DATA: TEXT01c TYPE SCRTEXT_S,
*        TEXT02c TYPE SCRTEXT_S,
*        TEXT01  TYPE SCRTEXT_S,
*        TEXT02  TYPE SCRTEXT_S,
*        TEXT03  TYPE SCRTEXT_S,
*        VG_GJAHR    TYPE GJAHR,
*        VG_MONAT    TYPE MONAT,
*        VT_GJAHR(4),
*        VT_MONAT(2).

  SET PF-STATUS 'PF1105'.
  SET TITLEBAR  'TL1106'.

  IF BALANCO_CONTAINER_1106 IS INITIAL.

    CREATE OBJECT BALANCO_CONTAINER_1106
      EXPORTING
        CONTAINER_NAME = 'ALV_1106'.

    CREATE OBJECT BALANCO_ALV_1106
      EXPORTING
        I_PARENT = BALANCO_CONTAINER_1106.

    MOVE P_GJAHR TO VT_GJAHR.
    MOVE P_MONAT TO VT_MONAT.
    CONCATENATE VT_MONAT '/' VT_GJAHR INTO TEXT01.

    MOVE P_GJAHR TO VG_GJAHR.
    ADD -1 TO VG_GJAHR.
    MOVE VG_GJAHR TO VT_GJAHR.
    MOVE P_MONAT  TO VT_MONAT.
    CONCATENATE VT_MONAT '/' VT_GJAHR INTO TEXT02.

    MOVE P_GJAHR TO VG_GJAHR.
    ADD -1 TO VG_GJAHR.
    MOVE VG_GJAHR TO VT_GJAHR.
    CONCATENATE  '12/' VT_GJAHR INTO TEXT03.

    TEXT01c = 'Conta Razão'.
    TEXT02c = 'Desc. Conta Razão'.

    CLEAR: BALANCO_CATALOGO_1106.

    PERFORM Z_ESTRUTURA_FIELDCAT TABLES BALANCO_CATALOGO_1106 USING:
        'IT_CONTAS_AUX' 'SAKNR'     TEXT01c ' ' 01 12 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
        'IT_CONTAS_AUX' 'TEXTO'     TEXT02c ' ' 02 38 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
        'IT_CONTAS_AUX' 'VALOR_01'  TEXT01  ' ' 03 15 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
        'IT_CONTAS_AUX' 'VALOR_02'  TEXT02  ' ' 04 15 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
        'IT_CONTAS_AUX' 'VALOR_03'  TEXT03  ' ' 05 15 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE.

    CLEAR: IT_CONTAS_AUX[].
    MOVE IT_CONTAS_SALDO[] TO IT_CONTAS_AUX[].

    CLEAR: BALANCO_GS_LAYOUT_1106.
    BALANCO_GS_LAYOUT_1106-ZEBRA    = ABAP_TRUE.
    BALANCO_GS_LAYOUT_1106-SEL_MODE = 'A'.
    BALANCO_GS_LAYOUT_1106-ZEBRA    = abap_true.

    CALL METHOD BALANCO_ALV_1106->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        I_DEFAULT       = SPACE
        IS_LAYOUT       = BALANCO_GS_LAYOUT_1106
      CHANGING
        IT_FIELDCATALOG = BALANCO_CATALOGO_1106
        IT_OUTTAB       = IT_CONTAS_AUX[].

  ENDIF.

  CALL METHOD BALANCO_ALV_1106->REFRESH_TABLE_DISPLAY.

ENDMODULE.                 " STATUS_1106  OUTPUT
