*----------------------------------------------------------------------*
***INCLUDE MZBALANCO_1108 .
*----------------------------------------------------------------------*
DATA: BALANCO_CONTAINER_1108 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      BALANCO_ALV_1108       TYPE REF TO CL_GUI_ALV_GRID,
      BALANCO_CATALOGO_1108  TYPE LVC_T_FCAT,
      BALANCO_GS_LAYOUT_1108 TYPE LVC_S_LAYO.


*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_1108  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_1108 INPUT.

  IF BALANCO_ALV_1108 IS NOT INITIAL.
    CALL METHOD BALANCO_ALV_1108->FREE.
  ENDIF.

  IF BALANCO_CONTAINER_1108 IS NOT INITIAL.
    CALL METHOD BALANCO_CONTAINER_1108->FREE.
  ENDIF.

  CLEAR: BALANCO_ALV_1108, BALANCO_CONTAINER_1108.

  LEAVE TO SCREEN 0.

ENDMODULE.                 " USER_COMMAND_1108  INPUT


*&---------------------------------------------------------------------*
*&      Module  STATUS_1108  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_1108 OUTPUT.

  SET PF-STATUS 'PF1105'.
  SET TITLEBAR  'TL1108'.

  IF BALANCO_CONTAINER_1108 IS INITIAL.

    CREATE OBJECT BALANCO_CONTAINER_1108
      EXPORTING
        CONTAINER_NAME = 'ALV_1108'.

    CREATE OBJECT BALANCO_ALV_1108
      EXPORTING
        I_PARENT = BALANCO_CONTAINER_1108.

    MOVE P_GJAHR TO VT_GJAHR.
    MOVE P_MONAT TO VT_MONAT.
    CONCATENATE VT_MONAT '/' VT_GJAHR INTO TEXT01.

    MOVE P_GJAHR TO VG_GJAHR.
    ADD -1 TO VG_GJAHR.
    MOVE VG_GJAHR TO VT_GJAHR.
    MOVE P_MONAT  TO VT_MONAT.
    CONCATENATE VT_MONAT '/' VT_GJAHR INTO TEXT02.

    MOVE P_GJAHR TO VG_GJAHR.
    ADD -1 TO VG_GJAHR.
    MOVE VG_GJAHR TO VT_GJAHR.
    CONCATENATE  '12/' VT_GJAHR INTO TEXT03.

    CLEAR: BALANCO_CATALOGO_1108.

    IF TL_1101_01 EQ TL_1103.
      PERFORM Z_ESTRUTURA_FIELDCAT TABLES BALANCO_CATALOGO_1108 USING:
          'TG_CONSOL'  'BUKRS'     'Empresa'      ' ' 01 08 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'MONAT'     'Mês'          ' ' 02 08 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'GJAHR'     'Ano'          ' ' 03 08 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'SAKNR'     'Conta'        ' ' 04 10 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'VBUND'     'Soc.Parc.'    ' ' 08 08 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'VLR_REA'   'Valor'        ' ' 10 20 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE.
    ELSE.
      PERFORM Z_ESTRUTURA_FIELDCAT TABLES BALANCO_CATALOGO_1108 USING:
          'TG_CONSOL'  'BUKRS'     'Empresa'      ' ' 01 08 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'MONAT'     'Mês'          ' ' 02 08 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'GJAHR'     'Ano'          ' ' 03 08 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'SAKNR'     'Conta'        ' ' 04 10 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'KOSTL'     'C.Custo'      ' ' 05 10 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'PRCTR'     'C.Lucro'      ' ' 06 10 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'MATKL'     'Grp.Material' ' ' 07 10 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'VBUND'     'Soc.Parc.'    ' ' 08 08 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'QTD_TON'   'Quantidade'   ' ' 09 20 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'VLR_REA'   'Valor Int.'   ' ' 10 20 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'VLR_DOLAR' 'Valor Forte'  ' ' 11 20 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
          'TG_CONSOL'  'VLR_GRUPO' 'Valor Grupo'  ' ' 12 20 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE.
    ENDIF.

    CLEAR: BALANCO_GS_LAYOUT_1108.
    BALANCO_GS_LAYOUT_1108-ZEBRA    = ABAP_TRUE.
    BALANCO_GS_LAYOUT_1108-SEL_MODE = 'A'.
    BALANCO_GS_LAYOUT_1108-ZEBRA    = ABAP_TRUE.

    CALL METHOD BALANCO_ALV_1108->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        I_DEFAULT       = SPACE
        IS_LAYOUT       = BALANCO_GS_LAYOUT_1108
      CHANGING
        IT_FIELDCATALOG = BALANCO_CATALOGO_1108
        IT_OUTTAB       = TG_CONSOL[].

  ENDIF.

  CALL METHOD BALANCO_ALV_1108->REFRESH_TABLE_DISPLAY.

ENDMODULE.                 " STATUS_1108  OUTPUT
