*----------------------------------------------------------------------*
***INCLUDE MZBALANCO_1105 .
*----------------------------------------------------------------------*

DATA: BALANCO_CONTAINER_1105 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      BALANCO_ALV_1105       TYPE REF TO CL_GUI_ALV_GRID,
      BALANCO_CATALOGO_1105  TYPE LVC_T_FCAT,
      BALANCO_GS_LAYOUT_1105 TYPE LVC_S_LAYO.

*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_1105  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_1105 INPUT.

  IF BALANCO_ALV_1105 IS NOT INITIAL.
    CALL METHOD BALANCO_ALV_1105->FREE.
  ENDIF.

  IF BALANCO_CONTAINER_1105 IS NOT INITIAL.
    CALL METHOD BALANCO_CONTAINER_1105->FREE.
  ENDIF.

  CLEAR: BALANCO_ALV_1105, BALANCO_CONTAINER_1105.

  LEAVE TO SCREEN 0.
ENDMODULE.                 " USER_COMMAND_1105  INPUT

*&---------------------------------------------------------------------*
*&      Module  STATUS_1105  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_1105 OUTPUT.

  DATA: TEXT01c TYPE SCRTEXT_S,
        TEXT02c TYPE SCRTEXT_S,
        TEXT01  TYPE SCRTEXT_S,
        TEXT02  TYPE SCRTEXT_S,
        TEXT03  TYPE SCRTEXT_S,
        VG_GJAHR    TYPE GJAHR,
        VG_MONAT    TYPE MONAT,
        VT_GJAHR(4),
        VT_MONAT(2).

  SET PF-STATUS 'PF1105'.
  SET TITLEBAR  'TL1105'.

  IF BALANCO_CONTAINER_1105 IS INITIAL.

    CREATE OBJECT BALANCO_CONTAINER_1105
      EXPORTING
        CONTAINER_NAME = 'ALV_1105'.

    CREATE OBJECT BALANCO_ALV_1105
      EXPORTING
        I_PARENT = BALANCO_CONTAINER_1105.

    MOVE P_GJAHR TO VT_GJAHR.
    MOVE P_MONAT TO VT_MONAT.
    CONCATENATE VT_MONAT '/' VT_GJAHR INTO TEXT01.

    MOVE P_GJAHR TO VG_GJAHR.
    ADD -1 TO VG_GJAHR.
    MOVE VG_GJAHR TO VT_GJAHR.
    MOVE P_MONAT  TO VT_MONAT.
    CONCATENATE VT_MONAT '/' VT_GJAHR INTO TEXT02.

    MOVE P_GJAHR TO VG_GJAHR.
    ADD -1 TO VG_GJAHR.
    MOVE VG_GJAHR TO VT_GJAHR.
    CONCATENATE  '12/' VT_GJAHR INTO TEXT03.

    TEXT01c = 'Conta Razão'.
    TEXT02c = 'Desc. Conta Razão'.

    CLEAR: BALANCO_CATALOGO_1105.

    PERFORM Z_ESTRUTURA_FIELDCAT TABLES BALANCO_CATALOGO_1105 USING:
        'IT_CONTAS_AUX' 'SAKNR'     TEXT01c ' ' 01 12 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
        'IT_CONTAS_AUX' 'TEXTO'     TEXT02c ' ' 02 38 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
        'IT_CONTAS_AUX' 'VALOR_01'  TEXT01  ' ' 03 15 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
        'IT_CONTAS_AUX' 'VALOR_02'  TEXT02  ' ' 04 15 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE,
        'IT_CONTAS_AUX' 'VALOR_03'  TEXT03  ' ' 05 15 SPACE SPACE SPACE SPACE SPACE SPACE SPACE SPACE.

    CLEAR: IT_CONTAS_AUX[].
    MOVE IT_CONTAS_SOLTAS[] TO IT_CONTAS_AUX[].

    CLEAR: BALANCO_GS_LAYOUT_1105.
    BALANCO_GS_LAYOUT_1105-ZEBRA    = ABAP_TRUE.
    BALANCO_GS_LAYOUT_1105-SEL_MODE = 'A'.
    BALANCO_GS_LAYOUT_1105-ZEBRA    = abap_true.

    CALL METHOD BALANCO_ALV_1105->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        I_DEFAULT       = SPACE
        IS_LAYOUT       = BALANCO_GS_LAYOUT_1105
      CHANGING
        IT_FIELDCATALOG = BALANCO_CATALOGO_1105
        IT_OUTTAB       = IT_CONTAS_AUX[].

  ENDIF.

  CALL METHOD BALANCO_ALV_1105->REFRESH_TABLE_DISPLAY.

ENDMODULE.                 " STATUS_1105  OUTPUT
