*&---------------------------------------------------------------------*
*& Include MZLES003TOP                                       PoolMóds.        SAPMZLES003
*&
*&---------------------------------------------------------------------*

PROGRAM  SAPMZLES003 MESSAGE-ID ZPFE.

"Tabelas Utilizadas
TABLES: ZPFE_LOTE, ZPFE_LOTE_ITEM, LFA1.

"Bibliotecas
TYPE-POOLS: ICON.

"Constantes de Tela
DATA: C_0001 TYPE SY-DYNNR VALUE '0001',
      C_0002 TYPE SY-DYNNR VALUE '0002',
      C_0003 TYPE SY-DYNNR VALUE '0003',
      C_0004 TYPE SY-DYNNR VALUE '0004',
      C_0005 TYPE SY-DYNNR VALUE '0005',
      C_0006 TYPE SY-DYNNR VALUE '0006',
      C_2001 TYPE SY-DYNNR VALUE '2001',
      C_5001 TYPE SY-DYNNR VALUE '5001',
      C_1001 TYPE SY-DYNNR VALUE '1001',
      C_1002 TYPE SY-DYNNR VALUE '1002',
      C_1003 TYPE SY-DYNNR VALUE '1003',
      C_9002 TYPE SY-DYNNR VALUE '9002',
      C_9003 TYPE SY-DYNNR VALUE '9003'.

"Comandos de Tela
DATA: WA_FCODE         TYPE SY-UCOMM,
      IT_FCODE         LIKE TABLE OF WA_FCODE,
      OK_CODE          TYPE SY-UCOMM,
      OK_CODE_ARQ      TYPE SY-UCOMM,
      OK_BACK          TYPE SY-UCOMM VALUE 'BACK',
      OK_EXIT          TYPE SY-UCOMM VALUE 'EXIT',
      OK_CANCEL        TYPE SY-UCOMM VALUE 'CANCEL',
      OK_PESQ          TYPE SY-UCOMM VALUE 'PESQ',
      OK_BTNE          TYPE SY-UCOMM VALUE 'BTNE',
      OK_BTNC          TYPE SY-UCOMM VALUE 'BTNC',
      OK_ARQUIVO       TYPE SY-UCOMM VALUE 'ARQUIVO',
      OK_ARQUIVO_C     TYPE SY-UCOMM VALUE 'ARQUIVO_C',
      OK_TABLOTE       TYPE SY-UCOMM VALUE 'TABLOTE',
      OK_TABOPER       TYPE SY-UCOMM VALUE 'TABOPER',
      OK_TABCONFER     TYPE SY-UCOMM VALUE 'TABCONFER',
      OK_TABCONFER_ADM TYPE SY-UCOMM VALUE 'TABCONFER_ADM',
      OK_LERARQ        TYPE SY-UCOMM VALUE 'LERARQ',
      OK_ATUALIZA      TYPE SY-UCOMM VALUE 'ATUALIZA',
      OK_GERAR         TYPE SY-UCOMM VALUE 'GERA_FINAN',
      OK_CONTB         TYPE SY-UCOMM VALUE 'GERA_CONTB',
      OK_DELOTE        TYPE SY-UCOMM VALUE 'DEL_LOTE',
      OK_EDITAR        TYPE SY-UCOMM VALUE 'EDIT_FINAN',
      OK_SALV_CONF     TYPE SY-UCOMM VALUE 'SALV_CONF',
      OK_LOG_PROC      TYPE SY-UCOMM VALUE 'LOG_PROC',
      OK_DT_BAIXA      TYPE SY-UCOMM VALUE 'DATA_BAIXA'.

"Variáveis de Controle de Tela
DATA: VG_TELA_0001  TYPE SY-DYNNR,
      VG_TELA_0002  TYPE SY-DYNNR,
      VG_TELA_0003  TYPE SY-DYNNR,
      VG_TELA_0003B TYPE SY-DYNNR,
      VG_TELA_0005  TYPE SY-DYNNR,
      VG_TELA_9002  TYPE SY-DYNNR,
      VG_TELA_9003  TYPE SY-DYNNR.

"Variáveis da Data de Baixa
DATA: WA_DT_BAIXA TYPE SY-DATUM.


"Variáveis de Controle de Criação de ALV
DATA: COCKPIT_PRIM_LOTES TYPE C LENGTH 1,
      COCKPIT_PRIM_ITEM  TYPE C LENGTH 1,
      COCKPIT_PRIM_CONF  TYPE C LENGTH 1.

"Controles de Tela
CONTROLS: TAB_CONTROL_0002 TYPE TABSTRIP,
          TABLOTE          TYPE TABLEVIEW USING SCREEN 0002.

"Objetos ALV
DATA: COCKPIT_GS_LAYOUT            TYPE LVC_S_LAYO,
      COCKPIT_CONTAINER_LOTES      TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      COCKPIT_CONTAINER_LOTES_ITEM TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      COCKPIT_CONTAINER_LOTES_CONF TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      COCKPIT_CONTAINER_LOTES_ADM  TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      COCKPIT_ALV_LOTES            TYPE REF TO CL_GUI_ALV_GRID,
      COCKPIT_ALV_LOTES_ITEM       TYPE REF TO CL_GUI_ALV_GRID,
      COCKPIT_ALV_LOTES_CONF_ADM   TYPE REF TO CL_GUI_ALV_GRID,
      COCKPIT_ALV_LOTES_CONF       TYPE REF TO CL_GUI_ALV_GRID,
      VG_SCROLL_COL                TYPE LVC_S_COL,
      VG_SCROLL_ROW                TYPE LVC_S_ROID,
      IT_COCKPIT_CATALOG           TYPE LVC_T_FCAT,
      IS_VARIANT                   TYPE DISVARIANT,
      ES_ROW_NO	                   TYPE LVC_S_ROID,
      ES_ROW_INFO	                 TYPE LVC_S_ROW,
      ES_COL_INFO	                 TYPE LVC_S_COL.

DATA: IT_SELECTED_ROWS TYPE LVC_T_ROW,
      WA_SELECTED_ROWS TYPE LVC_S_ROW.

DATA: IT_SELECTED_ROWS_IT TYPE LVC_T_ROW,
      WA_SELECTED_ROWS_IT TYPE LVC_S_ROW.

"Contantes
CONSTANTS: C_X               TYPE C LENGTH 1 VALUE 'X',
           C_GRID_COLOR_C100 TYPE C LENGTH 04 VALUE 'C100',
           C_GRID_COLOR_C200 TYPE C LENGTH 04 VALUE 'C200',
           C_GRID_COLOR_C300 TYPE C LENGTH 04 VALUE 'C300',
           C_GRID_COLOR_C400 TYPE C LENGTH 04 VALUE 'C400',
           C_GRID_COLOR_C500 TYPE C LENGTH 04 VALUE 'C500',
           C_GRID_COLOR_C600 TYPE C LENGTH 04 VALUE 'C600',
           C_GRID_COLOR_C700 TYPE C LENGTH 04 VALUE 'C700',
           C_GRID_COLOR_C800 TYPE C LENGTH 04 VALUE 'C800'.

"Tabelas de Lotes
DATA: IT_LOTES     TYPE TABLE OF ZPFE_LOTE,
      IT_LOTES_ALV TYPE TABLE OF ZPFE_LOTE_ALV,
      IT_LOTES_SEL TYPE TABLE OF ZPFE_LOTE_ALV,
      IT_RETORNO   TYPE TABLE OF BAPIRET2.

"Work Área
DATA: WA_LOTES        TYPE ZPFE_LOTE,
      WA_LOTES_ALV    TYPE ZPFE_LOTE_ALV,
      WA_LOTES_DELETE TYPE ZPFE_LOTE.

"Tabela de Itens
DATA:  BEGIN OF IT_LOTES_ITEM_COF_ADM OCCURS 0.
        INCLUDE STRUCTURE ZPFE_LOTE_ITEM.
DATA:   DESCHVID       TYPE ZPFE_LOTE_ITEM_ALV-DESCHVID,
        STATUS_CONF(4),
        END OF IT_LOTES_ITEM_COF_ADM.

DATA: IT_LOTES_ITEM             TYPE TABLE OF ZPFE_LOTE_ITEM     WITH HEADER LINE,
      IT_LOTES_ITEM_ALV         TYPE TABLE OF ZPFE_LOTE_ITEM_ALV WITH HEADER LINE,
      IT_LOTES_ITEM_COF_ADM_AUX TYPE TABLE OF ZPFE_LOTE_ITEM     WITH HEADER LINE,
*      IT_LOTES_ITEM_COF_ADM TYPE TABLE OF ZPFE_LOTE_ITEM     WITH HEADER LINE,
      IT_LOTES_ITEM_SEL         TYPE TABLE OF ZPFE_LOTE_ITEM_ALV,
      TG_0062                   TYPE TABLE OF ZLEST0062 WITH HEADER LINE.

"Work Área
DATA: WA_LOTES_ITEM      TYPE ZPFE_LOTE_ITEM,
      WA_LOTES_ITEM_ALV  TYPE ZPFE_LOTE_ITEM_ALV,
      WA_LOTES_ITEM_CONF TYPE ZPFE_LOTE_ITEM_ALV,
      WA_ZCTE_CIOT       TYPE ZCTE_CIOT.


"Variáveis
DATA: VG_ALTEROU_CONF  TYPE C LENGTH 1,
      VG_SELECIONOU    TYPE C LENGTH 1,
      VG_SEL_AJUSTE    TYPE C LENGTH 1,
      VG_CORTROCA      TYPE C LENGTH 4,
      VG_PESO_DIGITAR  TYPE C LENGTH 1,
      VG_PESO_DIGITADO TYPE ZCTE_CIOT-QUANTIDADE.

"Ranges
DATA: RG_NR_LOTE_ADM TYPE LXHME_RANGE_C10_T WITH HEADER LINE,
      RG_NR_LOTE     TYPE LXHME_RANGE_C10_T WITH HEADER LINE,
      RG_CHVID       TYPE LXHME_RANGE_C2_T  WITH HEADER LINE,
      RG_NUCONTRATO  TYPE LXHME_RANGE_C12_T WITH HEADER LINE,
      RG_ID_TIPO     TYPE LXHME_RANGE_C1_T  WITH HEADER LINE.
