*&---------------------------------------------------------------------*
*& Include MZREMZARMTOP                                      PoolMóds.        SAPMZREMZARM
*&
*&---------------------------------------------------------------------*

PROGRAM  SAPMZREMZARM  MESSAGE-ID ZARM.

TABLES: EKKO, EKPO, EKET.

TYPE-POOLS: ZARM,
            ICON.

DATA: G_CONTAINER          TYPE SCRFNAME VALUE 'CC_CONTABIL',
      G_CUSTOM_CONTAINER   TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      OBG_CONTEINER        TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      CONTAINER_1          TYPE REF TO CL_GUI_CONTAINER,
      CONTAINER_2          TYPE REF TO CL_GUI_CONTAINER,
      SPLITTER             TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
      GRID1                TYPE REF TO CL_GUI_ALV_GRID,
      GS_VARIANT_C         TYPE DISVARIANT,
*      OBG_TOOLBAR          TYPE REF TO LCL_ALV_TOOLBAR,
      C_ALV_TOOLBARMANAGER TYPE REF TO CL_ALV_GRID_TOOLBAR_MANAGER,
      OBG_DOCKING          TYPE REF TO CL_GUI_DOCKING_CONTAINER,
      WA_STYLE             TYPE LVC_S_STYL,
      STYLE                TYPE LVC_T_STYL   WITH HEADER LINE,
      STYLE2               TYPE LVC_T_STYL   WITH HEADER LINE.

DATA: TG_FIELDCATALOG     TYPE LVC_T_FCAT,
      WG_FIELDCATALOG     TYPE LVC_S_FCAT,
      WA_LAYOUT           TYPE LVC_S_LAYO,
      WA_STABLE           TYPE LVC_S_STBL.

DATA: TL_INDEX_ROWS   TYPE LVC_T_ROW,
      WL_INDEX_ROWS   TYPE LVC_S_ROW.


"Constantes de Tela
CONSTANTS: C_1000 TYPE C LENGTH 4 VALUE '1000',
           C_1001 TYPE C LENGTH 4 VALUE '1001',
           C_1002 TYPE C LENGTH 4 VALUE '1002',
           C_2000 TYPE C LENGTH 4 VALUE '2000',
           C_2001 TYPE C LENGTH 4 VALUE '2001'.

"Constantes de Comando tela 1000
CONSTANTS: C_BACK       TYPE SY-UCOMM VALUE 'BACK',
           C_EXIT       TYPE SY-UCOMM VALUE 'EXIT',
           C_CANCEL     TYPE SY-UCOMM VALUE 'CANCEL',
           C_PSREMESSAS TYPE SYUCOMM VALUE 'PSREMESSAS',
           C_PSROMANEIO TYPE SYUCOMM VALUE 'PSROMANEIO',
           C_PSROMANEIE TYPE SYUCOMM VALUE 'PSROMANEIE'.

"Constantes de Comando tela 2000
CONSTANTS: C_BACKR     TYPE SY-UCOMM VALUE 'BACKR',
           C_EXITR     TYPE SY-UCOMM VALUE 'EXITR',
           C_CANCELR   TYPE SY-UCOMM VALUE 'CANCELR',
           C_ROSAIDA   TYPE SY-UCOMM VALUE 'ROSAIDA',
           C_ROLOGSA   TYPE SY-UCOMM VALUE 'ROLOGSA',
           C_RODOCM    TYPE SY-UCOMM VALUE 'RODOCM',
           C_ROESTORNO TYPE SY-UCOMM VALUE 'ROESTORNO'.

"Constantes para utilização livre
CONSTANTS: C_ZARM TYPE C LENGTH 4 VALUE 'ZARM',
           C_04   TYPE C LENGTH 2 VALUE '04',
           C_X    TYPE C LENGTH 1 VALUE 'X',
           C_S    TYPE C LENGTH 1 VALUE 'S',
           C_W    TYPE C LENGTH 1 VALUE 'W',
           C_E    TYPE C LENGTH 1 VALUE 'E'.

DATA: VG_DYNNR_000 TYPE SY-DYNNR,
      OK_CODE      TYPE SY-UCOMM,
      VG_TABIX     TYPE SY-TABIX,
      WA_PEDIDOS   TYPE ZARM_PEDIDO,
      WA_ROMANEIO  TYPE ZARM_ROMANEIO,
      WA_FORNECE   TYPE ZARM_FORNECEDOR,
      WA_FCODE     TYPE SY-UCOMM,
      WA_MESSTAB   TYPE BDCMSGCOLL,
      WA_MESSAGEM  TYPE ZARM_MSG_PROC,
      VG_RETORNO   TYPE C LENGTH 1.

DATA: IT_PEDIDOS  TYPE TABLE OF ZARM_PEDIDO     INITIAL SIZE 0 WITH HEADER LINE,
      IT_FORNECE  TYPE TABLE OF ZARM_FORNECEDOR INITIAL SIZE 0 WITH HEADER LINE,
      IT_ROMANEIO TYPE STANDARD TABLE OF ZARM_ROMANEIO INITIAL SIZE 0 WITH HEADER LINE,
      IT_BDC      TYPE TABLE OF BDCDATA         INITIAL SIZE 0 WITH HEADER LINE,
      IT_MESSAGEM TYPE TABLE OF ZARM_MSG_PROC   INITIAL SIZE 0 WITH HEADER LINE,
      IT_MESSTAB  TYPE TABLE OF BDCMSGCOLL,
      IT_FCODE    LIKE TABLE OF WA_FCODE.

DATA: tl_bdc TYPE TABLE OF bdcdata,
      wl_bdc TYPE bdcdata.

SELECTION-SCREEN BEGIN OF SCREEN 1001 AS SUBSCREEN NESTING LEVEL 3.
SELECTION-SCREEN BEGIN OF BLOCK ZB01 WITH FRAME TITLE TEXT-S01.
SELECT-OPTIONS:   P_EBELN FOR EKKO-EBELN NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN END OF BLOCK ZB01.
SELECTION-SCREEN BEGIN OF BLOCK ZB02 WITH FRAME TITLE TEXT-S02.
SELECT-OPTIONS:   P_BUKRS FOR EKKO-BUKRS NO-EXTENSION NO INTERVALS,
                  P_WERKS FOR EKPO-WERKS NO-EXTENSION NO INTERVALS,
                  P_LIFNR FOR EKKO-LIFNR NO-EXTENSION NO INTERVALS,
                  P_MATNR FOR EKPO-MATNR NO-EXTENSION NO INTERVALS,
                  P_LGORT FOR EKPO-LGORT NO-EXTENSION NO INTERVALS,
                  P_CHARG FOR EKET-CHARG NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN END OF BLOCK ZB02.
SELECTION-SCREEN END OF SCREEN 1001.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TAB_PEDIDOS' ITSELF
CONTROLS: TAB_PEDIDOS TYPE TABLEVIEW USING SCREEN 1002.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TAB_ROMANEIOS' ITSELF
CONTROLS: TAB_ROMANEIOS TYPE TABLEVIEW USING SCREEN 2001.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TAB_LOG_MSG' ITSELF
CONTROLS: TAB_LOG_MSG TYPE TABLEVIEW USING SCREEN 9999.
