*----------------------------------------------------------------------*
***INCLUDE MZSEGTRANSPORTE1131.
*----------------------------------------------------------------------*

DATA: CTL_ALV_1131 TYPE REF TO CL_GUI_ALV_GRID,
      CTL_CON_1131 TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA: GS_LAYOUT_1131       TYPE LVC_S_LAYO,
      GS_VARIANT_1131      TYPE DISVARIANT,
      IT_FIELDCATALOG_1131 TYPE LVC_T_FCAT,
      WA_FIELDCATALOG_1131 TYPE LVC_S_FCAT.

DATA: IT_EXCLUDE_FCODE_1131 TYPE UI_FUNCTIONS,
      WA_EXCLUDE_FCODE_1131 LIKE LINE OF IT_EXCLUDE_FCODE_1131.

DATA: GS_SCROLL_COL_1131 TYPE LVC_S_COL,
      GS_SCROLL_ROW_1131 TYPE LVC_S_ROID.

DATA: IT_ZLEST0116_2     TYPE TABLE OF ZLEST0116 WITH HEADER LINE,
      IT_ZLEST0116_ALV_2 TYPE TABLE OF ZDE_ZLEST0116_ALV WITH HEADER LINE,
      CK_CONFIRMADO_1131 TYPE CHAR01.

DATA: IT_SELECTED_ROWS_1131 TYPE LVC_T_ROW,
      WA_SELECTED_ROWS_1131 TYPE LVC_S_ROW.

*&---------------------------------------------------------------------*
*&      Form  INCLUIR_GRUPOS_EXISTENTES
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM INCLUIR_GRUPOS_EXISTENTES .

  DATA: IT_EMPRESAS TYPE TABLE OF T001 WITH HEADER LINE,
        IT_GRUPOS   TYPE TABLE OF T023T WITH HEADER LINE.

  CLEAR: IT_ZLEST0116_2[], IT_ZLEST0116_ALV_2[].

  SELECT * INTO TABLE IT_ZLEST0116_2
    FROM ZLEST0116.

  CHECK SY-SUBRC IS INITIAL.

  SORT IT_ZLEST0116_2 BY CD_EMPRESA CD_GRUPO.
  DELETE ADJACENT DUPLICATES FROM IT_ZLEST0116_2 COMPARING CD_EMPRESA CD_GRUPO.

  SELECT * INTO TABLE IT_EMPRESAS
    FROM T001
     FOR ALL ENTRIES IN IT_ZLEST0116_2
   WHERE BUKRS EQ IT_ZLEST0116_2-CD_EMPRESA.

  SORT IT_EMPRESAS BY BUKRS.

  SELECT * INTO TABLE IT_GRUPOS
    FROM T023T
     FOR ALL ENTRIES IN IT_ZLEST0116_2
   WHERE SPRAS EQ SY-LANGU
     AND MATKL EQ IT_ZLEST0116_2-CD_GRUPO.

  SORT IT_GRUPOS BY MATKL.

  LOOP AT IT_ZLEST0116_2.
    CLEAR: IT_ZLEST0116_ALV_2.

    MOVE-CORRESPONDING IT_ZLEST0116_2 TO IT_ZLEST0116_ALV_2.

    IT_ZLEST0116_ALV_2-CD_APOLICE = ZDE_ZLEST0115_ALV-CD_APOLICE.

    READ TABLE IT_EMPRESAS WITH KEY BUKRS = IT_ZLEST0116_2-CD_EMPRESA BINARY SEARCH.
    IF SY-SUBRC IS INITIAL.
      IT_ZLEST0116_ALV_2-DS_EMPRESA = IT_EMPRESAS-BUTXT.
    ENDIF.

    READ TABLE IT_GRUPOS   WITH KEY MATKL = IT_ZLEST0116_2-CD_GRUPO BINARY SEARCH.
    IF SY-SUBRC IS INITIAL.
      IT_ZLEST0116_ALV_2-DS_GRUPO = IT_GRUPOS-WGBEZ.
    ENDIF.

    APPEND IT_ZLEST0116_ALV_2.

  ENDLOOP.

  LOOP AT IT_ZLEST0116_ALV.
    DELETE IT_ZLEST0116_ALV_2 WHERE CD_EMPRESA EQ IT_ZLEST0116_ALV-CD_EMPRESA
                                AND CD_GRUPO   EQ IT_ZLEST0116_ALV-CD_GRUPO.
  ENDLOOP.

  CK_CONFIRMADO_1131 = ABAP_FALSE.

  CALL SCREEN 1131 STARTING AT 7 5.

  IF CK_CONFIRMADO_1131 EQ ABAP_TRUE.
    CLEAR: IT_SELECTED_ROWS_1131, IT_SELECTED_ROWS_1131[].

    CALL METHOD CTL_ALV_1131->GET_SELECTED_ROWS
      IMPORTING
        ET_INDEX_ROWS = IT_SELECTED_ROWS_1131.

    LOOP AT IT_SELECTED_ROWS_1131 INTO WA_SELECTED_ROWS_1131.
      READ TABLE IT_ZLEST0116_ALV_2 INDEX WA_SELECTED_ROWS_1131-INDEX.
      APPEND IT_ZLEST0116_ALV_2 TO IT_ZLEST0116_ALV.
    ENDLOOP.

    PERFORM ATUALIZA_TELA_1131.

  ENDIF.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_1131_EXIT  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_1131_EXIT INPUT.
  LEAVE TO SCREEN 0.
ENDMODULE.

*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_1131  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_1131 INPUT.

  CASE OK_CODE.
    WHEN OK_SELECIONA.
      CK_CONFIRMADO_1131 = ABAP_TRUE.
      CLEAR OK_CODE.
      LEAVE TO SCREEN 0.
  ENDCASE.

ENDMODULE.

*&---------------------------------------------------------------------*
*&      Module  STATUS_1131  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_1131 OUTPUT.
  SET PF-STATUS 'PF1131'.
  SET TITLEBAR 'TL1131'.

  "IT_ZLEST0116_ALV
  IF CTL_CON_1131 IS INITIAL.

    CREATE OBJECT CTL_CON_1131
      EXPORTING
        CONTAINER_NAME = 'ALV_1131'.

    CREATE OBJECT CTL_ALV_1131
      EXPORTING
        I_PARENT = CTL_CON_1131.

    PERFORM FILL_IT_FIELDCATALOG_1131.

*   Fill info for layout variant
    PERFORM FILL_GS_VARIANT_1131.

    "GS_LAYOUT_1131-GRID_TITLE = TEXT-003.
    GS_LAYOUT_1131-SEL_MODE   = 'A'.

    CALL METHOD CTL_ALV_1131->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT            = GS_LAYOUT_1131
        IS_VARIANT           = GS_VARIANT_1131
        IT_TOOLBAR_EXCLUDING = IT_EXCLUDE_FCODE_1131
        I_SAVE               = 'A'
      CHANGING
        IT_FIELDCATALOG      = IT_FIELDCATALOG_1131
        IT_OUTTAB            = IT_ZLEST0116_ALV_2[].

  ENDIF.

  CALL METHOD CTL_ALV_1131->REFRESH_TABLE_DISPLAY.

  CALL METHOD CTL_ALV_1131->GET_SCROLL_INFO_VIA_ID
    IMPORTING
      ES_COL_INFO = GS_SCROLL_COL_1131
      ES_ROW_NO   = GS_SCROLL_ROW_1131.

ENDMODULE.

*&---------------------------------------------------------------------*
*&      Form  FILL_IT_FIELDCATALOG_1131
*&---------------------------------------------------------------------*
FORM FILL_IT_FIELDCATALOG_1131 .

  FIELD-SYMBOLS: <FS_CAT_1131> TYPE LVC_S_FCAT.

  CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
    EXPORTING
      I_STRUCTURE_NAME = 'ZDE_ZLEST0116_ALV'
    CHANGING
      CT_FIELDCAT      = IT_FIELDCATALOG_1131.

  LOOP AT IT_FIELDCATALOG_1131 ASSIGNING <FS_CAT_1131>.
    IF <FS_CAT_1131>-FIELDNAME EQ 'CD_APOLICE'.
      <FS_CAT_1131>-NO_OUT = ABAP_TRUE.
    ENDIF.
  ENDLOOP.

ENDFORM.                    " FILL_IT_FIELDCATALOG


*&---------------------------------------------------------------------*
*&      Form  FILL_GS_VARIANT
*&---------------------------------------------------------------------*
FORM FILL_GS_VARIANT_1131 .

  GS_VARIANT_1131-REPORT      = SY-REPID.
  GS_VARIANT_1131-HANDLE      = '1130'.
  GS_VARIANT_1131-LOG_GROUP   = ABAP_FALSE.
  GS_VARIANT_1131-USERNAME    = ABAP_FALSE.
  GS_VARIANT_1131-VARIANT     = ABAP_FALSE.
  GS_VARIANT_1131-TEXT        = ABAP_FALSE.
  GS_VARIANT_1131-DEPENDVARS  = ABAP_FALSE.

ENDFORM.                    " FILL_GS_VARIANT
