
PROCESS BEFORE OUTPUT.

  MODULE status_0004.

  CALL SUBSCREEN: sub0000 INCLUDING sy-cprog vg_dynnr_000.

PROCESS AFTER INPUT.

  MODULE exit_aplicativo AT EXIT-COMMAND.

  CALL SUBSCREEN: sub0000 .
