
PROCESS BEFORE OUTPUT.

  MODULE STATUS_2003.

  CALL SUBSCREEN SUB2004 INCLUDING SY-CPROG VG_2004_9999.
*
PROCESS AFTER INPUT.

  CALL SUBSCREEN SUB2004.

  CHAIN.
    FIELD ZDOC_MEMORANDO-NR_MEMORANDO.
    FIELD ZDOC_MEMORANDO-CANCELADO.
    FIELD ZDOC_MEMORANDO-TP_FINALIDADE.
    FIELD ZDOC_MEMORANDO-NR_COMPLEMENTO.
    FIELD ZDOC_MEMORANDO-REPRESENTANTE.
    FIELD ZDOC_MEMORANDO-REMETENTE.
    FIELD ZDOC_MEMORANDO-TRANSPORTADOR.
    FIELD ZDOC_MEMORANDO-DT_EMISSAO_MEMO.
    FIELD ZDOC_MEMORANDO-QUANTIDADE_MEMO.
    FIELD ZDOC_MEMORANDO-NUMERO_MEMO.
    FIELD ZDOC_MEMORANDO-DIRECAO.
    FIELD ZDOC_MEMORANDO-FORMULARIO.
    FIELD ZDOC_MEMORANDO-PAIS_ORIGEM.
    FIELD ZDOC_MEMORANDO-UF_ORIGEM.
    FIELD ZDOC_MEMORANDO-PAIS_DESTINO.
    FIELD ZDOC_MEMORANDO-OBSERVACAO.
    FIELD ZDOC_MEMORANDO-RESPONSAVEL.
    FIELD ZDOC_MEMORANDO-STATUS.
    FIELD ZDOC_MEMORANDO-NR_DDE.
    FIELD ZDOC_MEMORANDO-DT_DDE.
    FIELD ZDOC_MEMORANDO-NR_RE.
    FIELD ZDOC_MEMORANDO-DT_RE.
    FIELD ZDOC_MEMORANDO-ID_TRANSPORTE.
    FIELD ZDOC_MEMORANDO-DS_NOME_TRANSPOR.
    MODULE SET_UPDATE_FLAG_MEMO ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_2003.
