
PROCESS BEFORE OUTPUT.

  MODULE TAB_ROMANEIOS_CHANGE_TC_ATTR.

  LOOP AT IT_ROMANEIO
       WITH CONTROL TAB_ROMANEIOS
       CURSOR TAB_ROMANEIOS-CURRENT_LINE.
  ENDLOOP.


PROCESS AFTER INPUT.

  LOOP AT IT_ROMANEIO.
    MODULE TAB_ROMANEIOS_MARK.
    FIELD IT_ROMANEIO-DOC_MATERIAL
    MODULE CHAMA_DOC_MATERIAL AT CURSOR-SELECTION.
    FIELD IT_ROMANEIO-ICONE
    MODULE CHAMA_MOV_MERCADORIA AT CURSOR-SELECTION.
    FIELD IT_ROMANEIO-VBELN.
    MODULE GRAVA_PEDIDOS.
  ENDLOOP.

PROCESS ON VALUE-REQUEST.
  FIELD IT_ROMANEIO-VBELN  MODULE MOSTRA_PEDIDOS.
