
PROCESS BEFORE OUTPUT.

  MODULE TAB_MEMO_TODOS_CHANGE_TC_ATTR.

*&SPWIZARD: MODULE TAB_MEMO_TODOS_CHANGE_COL_ATTR.
  LOOP AT   IT_MEMORANDO_TELA
       WITH CONTROL TAB_MEMO_TODOS
       CURSOR TAB_MEMO_TODOS-CURRENT_LINE.
*&SPWIZARD:   MODULE TAB_MEMO_TODOS_CHANGE_FIELD_ATTR
  ENDLOOP.

  MODULE STATUS_2002.

  "MODULE CRIA_ALV_EDITAR_FIELDCAT.
*
PROCESS AFTER INPUT.


*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TAB_MEMO_TODOS'
  LOOP AT IT_MEMORANDO_TELA.
    CHAIN.
      FIELD IT_MEMORANDO_TELA-ICONE.
      FIELD IT_MEMORANDO_TELA-TP_FINALIDADE.
      FIELD IT_MEMORANDO_TELA-DIRECAO.
      FIELD IT_MEMORANDO_TELA-NR_COMPLEMENTO.
      FIELD IT_MEMORANDO_TELA-REPRESENTANTE.
      FIELD IT_MEMORANDO_TELA-REMETENTE.
      FIELD IT_MEMORANDO_TELA-DT_EMISSAO_MEMO.
      FIELD IT_MEMORANDO_TELA-QUANTIDADE_MEMO.
      FIELD IT_MEMORANDO_TELA-NUMERO_MEMO.
      FIELD IT_MEMORANDO_TELA-STATUS.
      FIELD IT_MEMORANDO_TELA-VG_NOME_REPRESENTANTE.
      FIELD IT_MEMORANDO_TELA-VG_NOME_REMETENTE.
      FIELD IT_MEMORANDO_TELA-VG_NOME_PAIS_ORIGEM.
      FIELD IT_MEMORANDO_TELA-VG_NOME_PAIS_DESTINO.
      FIELD IT_MEMORANDO_TELA-VG_NOME_UF_ORIGEM.
    ENDCHAIN.
    FIELD IT_MEMORANDO_TELA-MARK
      MODULE TAB_MEMO_TODOS_MARK ON REQUEST.
  ENDLOOP.
*&SPWIZARD: MODULE TAB_MEMO_TODOS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TAB_MEMO_TODOS_CHANGE_COL_ATTR.

  MODULE FUNCTION.

  MODULE USER_COMMAND_2002.
