
PROCESS BEFORE OUTPUT.

  MODULE CRIA_ALV_REMESSA.

  MODULE STATUS_0042.
*
PROCESS AFTER INPUT.

  FIELD: WA_VINC_REMESSA-VBELN            MODULE ZM_VBELN ON REQUEST,
         WA_VINC_REMESSA-NR_REGISTRO_EXPO MODULE ZM_REGIS ON REQUEST,
         WA_VINC_REMESSA-NUMERO_DUE       MODULE ZM_DUE   ON REQUEST,
         WA_VINC_REMESSA-ID_ESTADO        MODULE ZM_ESTADO ON REQUEST.

  MODULE USER_COMMAND_0021_EXIT AT EXIT-COMMAND.

  MODULE USER_COMMAND_0042.

PROCESS ON VALUE-REQUEST.
  FIELD WA_VINC_REMESSA-VBELN MODULE BUSCA_REMESSA.
  FIELD WA_VINC_REMESSA-NR_REGISTRO_EXPO MODULE BUSCA_RE.
  FIELD WA_VINC_REMESSA-NUMERO_DUE MODULE BUSCA_DUE.
