
PROCESS BEFORE OUTPUT.

  MODULE STATUS_9008.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_9008_EXIT AT EXIT-COMMAND.

*  FIELD ZGL015_DRE_EST05-PRCTR MODULE VALIDA_AREA_CUSTO_01 ON REQUEST.
*  FIELD LS_PRCTR_2 MODULE VALIDA_AREA_CUSTO_02 ON REQUEST.
*  FIELD LS_PRCTR_3 MODULE VALIDA_AREA_CUSTO_03 ON REQUEST.
*  FIELD LS_PRCTR_4 MODULE VALIDA_AREA_CUSTO_04 ON REQUEST.
*  FIELD LS_PRCTR_5 MODULE VALIDA_AREA_CUSTO_05 ON REQUEST.
*
*  FIELD LS_KOKRS_1 MODULE VALIDA_AREA_CUSTO_01 ON REQUEST.
*  FIELD LS_KOKRS_2 MODULE VALIDA_AREA_CUSTO_02 ON REQUEST.
*  FIELD LS_KOKRS_3 MODULE VALIDA_AREA_CUSTO_03 ON REQUEST.
*  FIELD LS_KOKRS_4 MODULE VALIDA_AREA_CUSTO_04 ON REQUEST.
*  FIELD LS_KOKRS_5 MODULE VALIDA_AREA_CUSTO_05 ON REQUEST.

  MODULE USER_COMMAND_9008.
