
PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TAB_PEDIDOS'
  MODULE TAB_PEDIDOS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TAB_PEDIDOS_CHANGE_COL_ATTR.
  LOOP AT   IT_PEDIDOS
       WITH CONTROL TAB_PEDIDOS
       CURSOR TAB_PEDIDOS-CURRENT_LINE.
*&SPWIZARD:   MODULE TAB_PEDIDOS_CHANGE_FIELD_ATTR
  ENDLOOP.

* MODULE STATUS_1002.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TAB_PEDIDOS'
  LOOP AT IT_PEDIDOS.
    FIELD IT_PEDIDOS-MARCK
      MODULE TAB_PEDIDOS_MARK ON REQUEST.
  ENDLOOP.
*&SPWIZARD: MODULE TAB_PEDIDOS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TAB_PEDIDOS_CHANGE_COL_ATTR.

* MODULE USER_COMMAND_1002.
