
PROCESS BEFORE OUTPUT.
  MODULE STATUS_0035.
*
PROCESS AFTER INPUT.
* MODULE USER_COMMAND_0035.

  CHAIN.
    FIELD WA_FILTRO_REMETENTE-NR_QTD_VINC.
    FIELD WA_QTD_CARAC-REMET.
    FIELD WA_QTD_CARAC-RET.
    FIELD WA_QTD_CARAC-NR_NF.
  ENDCHAIN.
