*&---------------------------------------------------------------------*
*& Include SAPMZSEGTRANSPORTETOP                             PoolMóds.        SAPMZSEGTRANSPORTE
*&
*&---------------------------------------------------------------------*
PROGRAM SAPMZSEGTRANSPORTE MESSAGE-ID ZSEGTRANS.

TABLES: ZLEST0115, ZLEST0116, ZDE_ZLEST0115_ALV, ZDE_ZLEST0116_ALV.

CONSTANTS: TL_1100 TYPE SY-DYNNR VALUE '1100',
           TL_1110 TYPE SY-DYNNR VALUE '1110',
           TL_1111 TYPE SY-DYNNR VALUE '1111',
           TL_1120 TYPE SY-DYNNR VALUE '1120'.

CONSTANTS: OK_PESQUISAR TYPE SY-UCOMM VALUE 'PESQUISAR',
           OK_INCLUIR   TYPE SY-UCOMM VALUE 'INCLUIR',
           OK_MODIFICAR TYPE SY-UCOMM VALUE 'MODIFICAR',
           OK_CONSULTAR TYPE SY-UCOMM VALUE 'CONSULTAR',
           OK_EXCLUIR   TYPE SY-UCOMM VALUE 'EXCLUIR',
           OK_FILTRAR   TYPE SY-UCOMM VALUE 'FILTRAR',
           OK_SALVAR    TYPE SY-UCOMM VALUE 'SALVAR',
           OK_COPIA     TYPE SY-UCOMM VALUE 'COPIA',
           OK_ATIVAR    TYPE SY-UCOMM VALUE 'ATIVAR',
           OK_SELECIONA TYPE SY-UCOMM VALUE 'SELECIONA',
           OK_ADICIONAR TYPE SY-UCOMM VALUE 'ADICIONAR'.

DATA: OK_CODE TYPE SY-UCOMM.

DATA: VG_TELA_1000 TYPE SY-DYNNR.

DATA: CK_OPERACAO  TYPE CHAR01.  "I - Inclusão / A - Modificação / C - Consulta

DATA: IT_ZLEST0115     TYPE TABLE OF ZLEST0115 WITH HEADER LINE,
      IT_ZLEST0115_ALV TYPE TABLE OF ZDE_ZLEST0115_ALV WITH HEADER LINE,
      IT_ZLEST0115_SEL TYPE TABLE OF ZDE_ZLEST0115_ALV WITH HEADER LINE,
      IT_ZLEST0116     TYPE TABLE OF ZLEST0116 WITH HEADER LINE,
      IT_ZLEST0116_ALV TYPE TABLE OF ZDE_ZLEST0116_ALV WITH HEADER LINE,
      IT_ZLEST0116_SEL TYPE TABLE OF ZDE_ZLEST0116_ALV WITH HEADER LINE.

DATA: WA_ZLEST0115_ALV    TYPE ZDE_ZLEST0115_ALV,
      WA_ZLEST0116_ALV    TYPE ZDE_ZLEST0116_ALV,
      DT_INICIAL_VALIDADE TYPE SY-DATUM.
