*----------------------------------------------------------------------*
*   INCLUDE HBRCVTR0TOP                                                *
*----------------------------------------------------------------------*

DATA: BEGIN OF coll_tab OCCURS 0.
DATA: bukrs       LIKE p0001-bukrs,
      werks       LIKE p0001-werks,
      btrtl       LIKE p0001-btrtl,
      rz_soc      LIKE p0001-btrtl,
      cnpj        TYPE pbr_num_cnpj,
      pernr       LIKE pernr-pernr,
      pnalt       LIKE p0032-pnalt,
      persg       LIKE p0001-persg,
      persk       LIKE p0001-persk,
      ename       LIKE p0002-cname,
      ause        TYPE i,
      feri        TYPE i,
      days        TYPE i,
      alim        LIKE pc207-betrg,
      lanche      LIKE pc207-betrg,
      total       LIKE pc207-betrg,
      cpf         TYPE p0465-cpf_nr,
      pis         TYPE pbr_psnr,
      sexo        TYPE c,
      estadocivil TYPE c,
      endereco    LIKE p0006-stras,
      complemento LIKE p0736-stras,
      numero      LIKE p0006-hsnmr,
      cep         LIKE p0006-pstlz,
      municipio   LIKE p0006-ort01,
      bairro      LIKE p0006-ort02,
      estado      LIKE p0006-state,
      mae         LIKE p0021-fcnam,
      inf15_exs   TYPE i,
      entrydate   LIKE p0000-begda,
      leavingdate LIKE p0000-begda,
      kostl       LIKE p0001-kostl.
DATA: END OF coll_tab.

DATA: BEGIN OF alv_tab OCCURS 0.
DATA: bukrs       LIKE p0001-bukrs,
      bukrst      LIKE hrca_company-comp_name,
      werks       LIKE p0001-werks,
      btrtl       LIKE p0001-btrtl,
      btrtlt      LIKE t001p-btext,
      rz_soc      LIKE p0001-btrtl,
      cnpj        TYPE pbr_num_cnpj,
      pernr       LIKE pernr-pernr,
      ename       LIKE p0002-cname,
      persg       LIKE p0001-persg,
      persgt      LIKE t501t-ptext,
      persk       LIKE p0001-persk,
      perskt      LIKE t503t-ptext,
      entrydate   LIKE p0000-begda,
      leavingdate LIKE p0000-begda,
      kostl       LIKE p0001-kostl,
      ause        TYPE i,
      feri        TYPE i,
      days        TYPE i,
      alim        LIKE pc207-betrg,
      lanche      LIKE pc207-betrg,
      total       LIKE pc207-betrg.
DATA: END OF alv_tab.


DATA: BEGIN OF layout_hearder OCCURS 0.
DATA: tipo        TYPE c LENGTH 1,
      data_pedido TYPE c LENGTH 8,
      canal       TYPE c LENGTH 4,
      razao_soc   TYPE c LENGTH 35,
      cnpj        TYPE c LENGTH 14,
      cpf         TYPE c LENGTH 11,
      contrato    TYPE c LENGTH 11,
      num_pedido  TYPE c LENGTH 6,
      data_efet   TYPE c LENGTH 8,
      codigo      TYPE c LENGTH 1,
      tipo_pedido TYPE c LENGTH 1,
      mes_comp    TYPE c LENGTH 6,
      reserv1     TYPE c LENGTH 18,
      versao      TYPE c LENGTH 3,
      reserv2     TYPE c LENGTH 267,
      seq         TYPE c LENGTH 6.
DATA: END OF layout_hearder.

DATA: BEGIN OF layout_filial OCCURS 0.
DATA: tipo        TYPE c LENGTH 1,
      cnpj        TYPE c LENGTH 14,
      codigopj    TYPE c LENGTH 10,
      nomefilial  TYPE c LENGTH 35,
      ddd         TYPE c LENGTH 4,
      nomeinterl1 TYPE c LENGTH 35,
      endereco1   TYPE c LENGTH 40,
      telefone1   TYPE c LENGTH 12,
      ramal1      TYPE c LENGTH 6,
      nomeinterl2 TYPE c LENGTH 35,
      endereco2   TYPE c LENGTH 40,
      telefone2   TYPE c LENGTH 12,
      ramal2      TYPE c LENGTH 6,
      nomeinterl3 TYPE c LENGTH 35,
      endereco3   TYPE c LENGTH 40,
      telefone3   TYPE c LENGTH 12,
      ramal3      TYPE c LENGTH 6,
      codigofil   TYPE c LENGTH 20,
      reserv1     TYPE c LENGTH 31,
      sequencia   TYPE c LENGTH 6.
DATA: END OF layout_filial.

DATA: BEGIN OF layout_detalhe OCCURS 0.
DATA: tipo        TYPE c LENGTH 1,
      valor       TYPE c LENGTH 11,
      reservado1  TYPE c LENGTH 1,
      matricula   TYPE c LENGTH 13,
      reservado2  TYPE c LENGTH 54,
      datanasc    TYPE c LENGTH 8,
      cpf         TYPE c LENGTH 11,
      tipodocid   TYPE c LENGTH 1,
      docid       TYPE c LENGTH 13,
      orgaoemiss  TYPE c LENGTH 20,
      estadoemiss TYPE c LENGTH 6,
      pis         TYPE c LENGTH 15,
      sexo        TYPE c LENGTH 1,
      estadocivil TYPE c LENGTH 1,
      endereco    TYPE c LENGTH 35,
      complemento TYPE c LENGTH 10,
      numero      TYPE c LENGTH 5,
      cep         TYPE c LENGTH 8,
      municipio   TYPE c LENGTH 28,
      bairro      TYPE c LENGTH 30,
      estado      TYPE c LENGTH 2,
      nomemae     TYPE c LENGTH 35,
      codopcaoend TYPE c LENGTH 1,
      dddcomerc   TYPE c LENGTH 4,
      telefone    TYPE c LENGTH 8,
      ramal       TYPE c LENGTH 4,
      dddresid    TYPE c LENGTH 4,
      telresid    TYPE c LENGTH 8,
      escolaridad TYPE c LENGTH 1,
      dataadm     TYPE c LENGTH 8,
      reservado3  TYPE c LENGTH 1,
      usu         TYPE c LENGTH 40,
      reservado4  TYPE c LENGTH 6,
      sequencia   TYPE c LENGTH 6
      .
DATA: END OF layout_detalhe.
