"Name: \FU:J_1B_NFE_CANCEL\SE:BEGIN\EI
ENHANCEMENT 0 Z_1B_NFE_CANCEL.

   IF I_DOCSTAT EQ C_DENIED.
     SELECT SINGLE *
       FROM J_1BNFLIN INTO @DATA(LWA_J_1BNFLIN_CK)
      WHERE DOCNUM EQ @I_DOCNUM.

     IF ( SY-SUBRC EQ 0 ) AND ( LWA_J_1BNFLIN_CK-REFTYP EQ 'ZW' ).
       EXIT.
     ENDIF.
   ENDIF.

ENDENHANCEMENT.
