*&---------------------------------------------------------------------*
*&  Include           Z_1BNFE_MONITOR_F05
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  fill_it_fieldcatalog2
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM FILL_IT_FIELDCATALOG2 .

* Build the fieldcat2 according to DDIC structure J_1BNFE_ACTIVE:
  CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
    EXPORTING
      I_STRUCTURE_NAME = 'J_1BNFE_HISTORY'
    CHANGING
      CT_FIELDCAT      = IT_FIELDCATALOG2.

* Add a field for the DOC Status text
  WA_FIELDCATALOG2-FIELDNAME = 'DOCSTAT'.
  WA_FIELDCATALOG2-REPTEXT   = TEXT-150.
  WA_FIELDCATALOG2-OUTPUTLEN = 25.
  APPEND WA_FIELDCATALOG2 TO IT_FIELDCATALOG2.

* Add a field for the SCS Status text
  WA_FIELDCATALOG2-FIELDNAME = 'SCSSTAT'.
  WA_FIELDCATALOG2-REPTEXT   = TEXT-140.
  WA_FIELDCATALOG2-OUTPUTLEN = 35.
  APPEND WA_FIELDCATALOG2 TO IT_FIELDCATALOG2.

* Add a field for the Status-Code text
  WA_FIELDCATALOG2-FIELDNAME = 'CODET'.
  WA_FIELDCATALOG2-REPTEXT   = TEXT-180.
  WA_FIELDCATALOG2-OUTPUTLEN = 35.
  APPEND WA_FIELDCATALOG2 TO IT_FIELDCATALOG2.

  LOOP AT IT_FIELDCATALOG2 INTO WA_FIELDCATALOG2.
*   Hide column for Counter
    IF WA_FIELDCATALOG2-FIELDNAME = 'COUNTER'.
      WA_FIELDCATALOG2-NO_OUT = C_X.
    ENDIF.

*   Define column position
    CASE WA_FIELDCATALOG2-FIELDNAME.
      WHEN 'DOCNUM'.
        WA_FIELDCATALOG2-COL_POS   = 1.
      WHEN 'DOCSTA'.
        WA_FIELDCATALOG2-COL_POS   = 2.
      WHEN 'DOCSTAT'.
        WA_FIELDCATALOG2-COL_POS   = 3.
      WHEN 'SCSSTA'.
        WA_FIELDCATALOG2-COL_POS   = 4.
      WHEN 'SCSSTAT'.
        WA_FIELDCATALOG2-COL_POS   = 5.
      WHEN 'MSSTAT'.
        WA_FIELDCATALOG2-COL_POS   = 6.
      WHEN 'CONTING_S'.
        WA_FIELDCATALOG2-COL_POS   = 7.
      WHEN 'CONTING'.
        WA_FIELDCATALOG2-COL_POS   = 8.
      WHEN 'CANCEL'.
        WA_FIELDCATALOG2-COL_POS   = 9.
      WHEN 'CODE'.
        WA_FIELDCATALOG2-COL_POS   = 10.
      WHEN 'CODET'.
        WA_FIELDCATALOG2-COL_POS   = 11.
      WHEN 'PRINTD'.
        WA_FIELDCATALOG2-COL_POS   = 12.
      WHEN OTHERS.
        WA_FIELDCATALOG2-COL_POS   = WA_FIELDCATALOG2-COL_POS + 4.
    ENDCASE.

*   Output of Field: Cancellation Reason Description          "1144194
    IF WA_FIELDCATALOG-FIELDNAME = 'REASON_T'.              "1144194
      WA_FIELDCATALOG-OUTPUTLEN = 20.                       "1144194
    ENDIF.                                                  "1144194

    MODIFY IT_FIELDCATALOG2 FROM WA_FIELDCATALOG2 INDEX SY-TABIX.

  ENDLOOP.

ENDFORM.                    " fill_it_fieldcatalog2
*&---------------------------------------------------------------------*
*&      Form  FILL_IT_FIELDCATALOG3
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM FILL_IT_FIELDCATALOG3 .
  CLEAR WA_FIELDCATALOG3.
  WA_FIELDCATALOG3-COL_POS   = 1.
  WA_FIELDCATALOG3-FIELDNAME = 'GRUPO'.
  WA_FIELDCATALOG3-REPTEXT   = 'Grupo'.
  WA_FIELDCATALOG3-OUTPUTLEN = 10.
  WA_FIELDCATALOG3-F4AVAILABL = 'X'.
  WA_FIELDCATALOG3-EDIT       = 'X'.
  WA_FIELDCATALOG3-REF_TABLE     = 'ZSDT0080'.
  WA_FIELDCATALOG3-REF_FIELD     = 'GRUPO'.
  APPEND WA_FIELDCATALOG3 TO IT_FIELDCATALOG3.


  CLEAR WA_FIELDCATALOG3.
  WA_FIELDCATALOG3-COL_POS   = 2.
  WA_FIELDCATALOG3-FIELDNAME = 'CAMPO'.
  WA_FIELDCATALOG3-REPTEXT   = 'Campo'.
  WA_FIELDCATALOG3-OUTPUTLEN = 15.
  WA_FIELDCATALOG3-F4AVAILABL = 'X'.
  WA_FIELDCATALOG3-EDIT       = 'X'.
  WA_FIELDCATALOG3-REF_TABLE     = 'ZSDT0080'.
  WA_FIELDCATALOG3-REF_FIELD     = 'CAMPO'.
  APPEND WA_FIELDCATALOG3 TO IT_FIELDCATALOG3.

  CLEAR WA_FIELDCATALOG3.
  WA_FIELDCATALOG3-COL_POS   = 3.
  WA_FIELDCATALOG3-FIELDNAME = 'PC_VEICULO'.
  WA_FIELDCATALOG3-REPTEXT   = 'Placa'.
  WA_FIELDCATALOG3-DRDN_HNDL = '1'.
  WA_FIELDCATALOG3-OUTPUTLEN = 10.
  WA_FIELDCATALOG3-EDIT       = 'X'.
  WA_FIELDCATALOG3-NO_OUT       = 'X'.
  WA_FIELDCATALOG3-CHECKTABLE = '!'.
  APPEND WA_FIELDCATALOG3 TO IT_FIELDCATALOG3.

  CLEAR WA_FIELDCATALOG3.
  WA_FIELDCATALOG3-COL_POS   = 4.
  WA_FIELDCATALOG3-FIELDNAME = 'CHAVE'.
  WA_FIELDCATALOG3-REPTEXT   = 'Chave'.
  WA_FIELDCATALOG3-DRDN_HNDL = '2'.
  WA_FIELDCATALOG3-OUTPUTLEN = 50.
  WA_FIELDCATALOG3-EDIT       = 'X'.
  WA_FIELDCATALOG3-NO_OUT       = 'X'.
  WA_FIELDCATALOG3-CHECKTABLE = '!'.
  APPEND WA_FIELDCATALOG3 TO IT_FIELDCATALOG3.

  CLEAR WA_FIELDCATALOG3.
  WA_FIELDCATALOG3-COL_POS    = 5.
  WA_FIELDCATALOG3-FIELDNAME  = 'VALOR'.
  WA_FIELDCATALOG3-REPTEXT    = 'Valor'.
  WA_FIELDCATALOG3-OUTPUTLEN  = 124.
  WA_FIELDCATALOG3-F4AVAILABL = ''.
  WA_FIELDCATALOG3-EDIT       = 'X'.
  WA_FIELDCATALOG3-REF_TABLE  = 'ZSDT0081'.
  WA_FIELDCATALOG3-REF_FIELD  = 'VALOR'.
  WA_FIELDCATALOG3-SCRTEXT_L  = 'Valor XML'.
  WA_FIELDCATALOG3-SCRTEXT_M  = 'Valor XML'.
  WA_FIELDCATALOG3-SCRTEXT_S  = 'Valor XML'.
  APPEND WA_FIELDCATALOG3 TO IT_FIELDCATALOG3.

  CLEAR WA_FIELDCATALOG3.
  WA_FIELDCATALOG3-COL_POS    = 6.
  WA_FIELDCATALOG3-FIELDNAME  = 'VALOR1'.
  WA_FIELDCATALOG3-REPTEXT    = 'Valor 1'.
  WA_FIELDCATALOG3-OUTPUTLEN  = 124.
  WA_FIELDCATALOG3-F4AVAILABL = ''.
  WA_FIELDCATALOG3-EDIT       = 'X'.
  WA_FIELDCATALOG3-REF_TABLE  = 'ZSDT0081'.
  WA_FIELDCATALOG3-REF_FIELD  = 'VALOR1'.
  WA_FIELDCATALOG3-SCRTEXT_L  = 'Valor XML 1'.
  WA_FIELDCATALOG3-SCRTEXT_M  = 'Valor XML 1'.
  WA_FIELDCATALOG3-SCRTEXT_S  = 'Valor XML 1' .
  APPEND WA_FIELDCATALOG3 TO IT_FIELDCATALOG3.

  CLEAR WA_FIELDCATALOG3.
  WA_FIELDCATALOG3-COL_POS    = 7.
  WA_FIELDCATALOG3-FIELDNAME  = 'VALOR2'.
  WA_FIELDCATALOG3-REPTEXT    = 'Valor 2'.
  WA_FIELDCATALOG3-OUTPUTLEN  = 124.
  WA_FIELDCATALOG3-F4AVAILABL = ''.
  WA_FIELDCATALOG3-EDIT       = 'X'.
  WA_FIELDCATALOG3-REF_TABLE  = 'ZSDT0081'.
  WA_FIELDCATALOG3-REF_FIELD  = 'VALOR2'.
  WA_FIELDCATALOG3-SCRTEXT_L  = 'Valor XML 2'.
  WA_FIELDCATALOG3-SCRTEXT_M  = 'Valor XML 2'.
  WA_FIELDCATALOG3-SCRTEXT_S  = 'Valor XML 2'.
  APPEND WA_FIELDCATALOG3 TO IT_FIELDCATALOG3.

  CLEAR WA_FIELDCATALOG3.
  WA_FIELDCATALOG3-COL_POS    = 8.
  WA_FIELDCATALOG3-FIELDNAME  = 'VALOR3'.
  WA_FIELDCATALOG3-REPTEXT    = 'Valor 3'.
  WA_FIELDCATALOG3-OUTPUTLEN  = 124.
  WA_FIELDCATALOG3-F4AVAILABL = ''.
  WA_FIELDCATALOG3-EDIT       = 'X'.
  WA_FIELDCATALOG3-REF_TABLE  = 'ZSDT0081'.
  WA_FIELDCATALOG3-REF_FIELD  = 'VALOR3'.
  WA_FIELDCATALOG3-SCRTEXT_L  = 'Valor XML 3'.
  WA_FIELDCATALOG3-SCRTEXT_M  = 'Valor XML 3'.
  WA_FIELDCATALOG3-SCRTEXT_S  = 'Valor XML 3'.
  APPEND WA_FIELDCATALOG3 TO IT_FIELDCATALOG3.


ENDFORM.                    " FILL_IT_FIELDCATALOG3
*&---------------------------------------------------------------------*
*&      Form  CAPTURAR_PLACAS
*&---------------------------------------------------------------------*
FORM CAPTURAR_PLACAS .

  DATA: LT_DROPDOWN TYPE LVC_T_DROP,
        LS_DROPDOWN TYPE LVC_S_DROP.

  DATA: LT_PLACAS TYPE TABLE OF ZCTE_TRANS,
        LW_PLACAS TYPE ZCTE_TRANS.

  DATA: TABIXCHAR TYPE C LENGTH 10.




  SELECT * FROM ZCTE_TRANS
  INTO TABLE LT_PLACAS
WHERE DOCNUM EQ WA_ALV_SELECTION-DOCNUM.

  LOOP AT LT_PLACAS INTO LW_PLACAS.
    LS_DROPDOWN-HANDLE = '1'.
    TABIXCHAR = SY-TABIX.
    CONDENSE TABIXCHAR NO-GAPS.
    CONCATENATE TABIXCHAR '-' INTO TABIXCHAR.
    CONCATENATE  TABIXCHAR LW_PLACAS-PC_VEICULO INTO LS_DROPDOWN-VALUE SEPARATED BY SPACE.
    APPEND LS_DROPDOWN TO LT_DROPDOWN.
    CLEAR: LW_PLACAS, LS_DROPDOWN.
  ENDLOOP.

  CALL METHOD CTL_ALV_CTE_CORR->SET_DROP_DOWN_TABLE
    EXPORTING
      IT_DROP_DOWN = LT_DROPDOWN.



ENDFORM.                    " CAPTURAR_PLACAS
*&---------------------------------------------------------------------*
*&      Form  CAPTURAR_CHAVES
*&---------------------------------------------------------------------*
FORM CAPTURAR_CHAVES .


  DATA: LT_DROPDOWN TYPE LVC_T_DROP,
        LS_DROPDOWN TYPE LVC_S_DROP.

  DATA: LT_CHAVES TYPE TABLE OF ZCTE_INFO_NOTA,
        LW_CHAVES TYPE ZCTE_INFO_NOTA.

  DATA: IT_ZLEST0067  TYPE TABLE OF ZLEST0067,
        P_ZLEST0066   TYPE ZLEST0066.

  DATA: TABIXCHAR TYPE C LENGTH 10.


  SELECT * FROM ZCTE_INFO_NOTA
  INTO TABLE LT_CHAVES
    WHERE DOCNUM EQ WA_ALV_SELECTION-DOCNUM.

  IF LT_CHAVES[] IS INITIAL.
    CLEAR: IT_ZLEST0067[].
    CALL FUNCTION 'Z_LES_INFO_AQUAV'
      EXPORTING
        P_CTE_AVULSO  = WA_ALV_SELECTION-DOCNUM
      IMPORTING
        P_ZLEST0066   = P_ZLEST0066
      TABLES
        IT_ZLEST0067 = IT_ZLEST0067.

    LOOP AT IT_ZLEST0067 INTO DATA(_WA_ZLEST0067).
      CLEAR LW_CHAVES.
      LW_CHAVES-CHAVE = _WA_ZLEST0067-CHAVE.
      APPEND LW_CHAVES TO LT_CHAVES.
    ENDLOOP.
  ENDIF.

  LOOP AT LT_CHAVES INTO LW_CHAVES.
    LS_DROPDOWN-HANDLE = '2'.

    TABIXCHAR = SY-TABIX.
    CONDENSE TABIXCHAR NO-GAPS.
    CONCATENATE TABIXCHAR '-' INTO TABIXCHAR.

    CONCATENATE  TABIXCHAR LW_CHAVES-CHAVE INTO LS_DROPDOWN-VALUE SEPARATED BY SPACE.

    APPEND LS_DROPDOWN TO LT_DROPDOWN.
    CLEAR: LW_CHAVES, LS_DROPDOWN.
  ENDLOOP.

  CALL METHOD CTL_ALV_CTE_CORR->SET_DROP_DOWN_TABLE
    EXPORTING
      IT_DROP_DOWN = LT_DROPDOWN.



ENDFORM.                    " CAPTURAR_CHAVES
