"Name: \PR:SAPLV56L\FO:CHECK_P_DISPO\SE:END\EI
ENHANCEMENT 0 Z_BLOCK_SEL_FORNECIMENTO_VT.

  IF ( SY-TCODE(4) EQ 'VT01' OR
       SY-TCODE(4) EQ 'VT02' ) AND SY-UCOMM EQ 'CRET'. "Botao Consultar

    IF S_VBELN[] IS INITIAL AND S_LIAVN[] IS INITIAL.
      MESSAGE 'Nenhum fornecimento(Campo Entrega/Recebimento) foi informado!' TYPE 'E'.
    ENDIF.

    DATA(LVA_COUNT) = 0.

    IF S_VBELN[] IS NOT INITIAL.

      SELECT COUNT(*) INTO LVA_COUNT
        FROM LIKP
       WHERE VBELN IN S_VBELN.

    ELSEIF S_LIAVN[] IS NOT INITIAL.

      SELECT COUNT(*) INTO LVA_COUNT
        FROM LIKP
       WHERE VBELN IN S_LIAVN.

    ENDIF.

    DATA(_MAX_SEL_REMESSA) = 500.

    SELECT SINGLE *
      FROM TVARVC INTO @DATA(LWA_TVARVC)
     WHERE NAME EQ 'VT01N_QTDE_REMESSA_SEL'.

    IF SY-SUBRC EQ 0 AND ( LWA_TVARVC-LOW IS NOT INITIAL ).
      _MAX_SEL_REMESSA = LWA_TVARVC-LOW.
    ENDIF.

    IF LVA_COUNT > _MAX_SEL_REMESSA.
      MESSAGE |Quantidade de fornecimentos(Campo Entrega/Recebimento) informado, excedem o limite permitido( { _MAX_SEL_REMESSA } fornecimentos)!| TYPE 'E'.
    ENDIF.
  ENDIF.

ENDENHANCEMENT.
