"Name: \FU:J_1B_NFE_PROCESS_OUTBOUND\SE:END\EI
ENHANCEMENT 0 Z_COMPLETAR_CHAVE_TERCEIRO.
*

  if CS_HEADER-FORM is INITIAL and ls_nfeactive-AUTHCOD is NOT INITIAL.

    CALL FUNCTION 'ZNFE_INBOUND_J_1BNFDOC'
      EXPORTING
        I_J_1BNFE_ATIVE       = ls_nfeactive
      CHANGING
        C_J_1BNFDOC           =  CS_HEADER.

  endif.


ENDENHANCEMENT.
