"Name: \FU:J_1B_NFE_FILL_MONITOR_TABLE\SE:END\EI
ENHANCEMENT 0 Z_COMPLETAR_CHAVE_TERCEIRO.
*

  if e_active-form is INITIAL.

    CALL FUNCTION 'ZNFE_INBOUND_J_1BNFE_ACTIVE'
      CHANGING
        C_J_1BNFE_ATIVE = e_active.

  endif.

ENDENHANCEMENT.
