"Name: \FU:LE_SHIPMENT_COPYDATE_CONFIRM\SE:END\EI
ENHANCEMENT 0 Z_CRIA_ETAPA_VT01N.
*
  IF sy-tcode = 'ZLES0106'.
    ct_SPOPLIST-SELFLAG = ''.
   MODIFY ct_SPOPLIST INDEX 1 TRANSPORTING SELFLAG.
  ENDIF.

ENDENHANCEMENT.
