"Name: \PR:SAPLJ_1B_NFE\FO:MAP_TAX_ICMS\SE:END\EI
ENHANCEMENT 0 Z_FILL_TAX_ICMS_PARTILHA.

  TYPES: BEGIN OF TY_ICMS_INTER,
           VBCUFDEST      TYPE J_1BTAXVAL,
           PFCPUFDEST     TYPE J_1BTAXVAL,
           PICMSUFDEST    TYPE J_1BTAXVAL,
           PICMSINTER     TYPE J_1BTAXVAL,
           PICMSINTERPART TYPE J_1BTAXVAL,
           VFCPUFDEST     TYPE J_1BTAXVAL,
           VICMSUFDEST    TYPE J_1BTAXVAL,
           VICMSUFREMET   TYPE J_1BTAXVAL,
         END OF TY_ICMS_INTER.

  DATA: V_ICMS_PART_CALC TYPE C,
        WL_ICMS_INTER    TYPE TY_ICMS_INTER.

  DELETE GT_RFC_TAX_ICMS_PAR_400 WHERE ID IS INITIAL.
  DELETE GT_RFC_TAX_ICMS_PAR_400 WHERE ID = P_LINEID.

  CLEAR: GS_RFC_TAX_ICMS_PAR_400.

  CLEAR: WL_ICMS_INTER.

  CALL FUNCTION 'ZCALC_ICMS_VENDA_INTERESTADUAL'
    EXPORTING
      I_DOCNUM         = XMLI-DOCNUM
      I_ITMNUM         = XMLI-ITMNUM
      I_CFOP           = XMLI-CFOP
    IMPORTING
      E_CALCULADO      = V_ICMS_PART_CALC
    CHANGING
      C_VBCUFDEST      = WL_ICMS_INTER-VBCUFDEST
      C_PFCPUFDEST     = WL_ICMS_INTER-PFCPUFDEST
      C_PICMSUFDEST    = WL_ICMS_INTER-PICMSUFDEST
      C_PICMSINTER     = WL_ICMS_INTER-PICMSINTER
      C_PICMSINTERPART = WL_ICMS_INTER-PICMSINTERPART
      C_VFCPUFDEST     = WL_ICMS_INTER-VFCPUFDEST
      C_VICMSUFDEST    = WL_ICMS_INTER-VICMSUFDEST
      C_VICMSUFREMET   = WL_ICMS_INTER-VICMSUFREMET.

  IF V_ICMS_PART_CALC IS NOT INITIAL.
    GS_RFC_TAX_ICMS_PAR_400-ID                  = P_LINEID.
    GS_RFC_TAX_ICMS_PAR_400-V_BCUF_DEST         = WL_ICMS_INTER-VBCUFDEST.
    GS_RFC_TAX_ICMS_PAR_400-P_FCPUF_DEST        = WL_ICMS_INTER-PFCPUFDEST.
    GS_RFC_TAX_ICMS_PAR_400-P_ICMSUF_DEST       = WL_ICMS_INTER-PICMSUFDEST.
    GS_RFC_TAX_ICMS_PAR_400-P_ICMS_INTER        = WL_ICMS_INTER-PICMSINTER.
    GS_RFC_TAX_ICMS_PAR_400-P_ICMS_INTER_PART   = WL_ICMS_INTER-PICMSINTERPART.
    GS_RFC_TAX_ICMS_PAR_400-V_FCPUF_DEST        = WL_ICMS_INTER-VFCPUFDEST.
    GS_RFC_TAX_ICMS_PAR_400-V_ICMSUF_DEST       = WL_ICMS_INTER-VICMSUFDEST.
    GS_RFC_TAX_ICMS_PAR_400-V_ICMSUF_REMET      = WL_ICMS_INTER-VICMSUFREMET.

    APPEND GS_RFC_TAX_ICMS_PAR_400 TO GT_RFC_TAX_ICMS_PAR_400.
  ENDIF.


ENDENHANCEMENT.
