FUNCTION-POOL Z_FI_BALANCETE MESSAGE-ID 8Z.

TABLES : J_1AINFT01 , J_1AINFT03, J_1AINFT08, J_1AINFT09.
*                                                         ,J_1AINFT11.
TABLES : T001,
         T009.
TABLES: J_1AINFMET,
        J_1AINFSKS,
        J_1AINFT04,
        J_1AINFT06,
        J_1AINFT20,
        J_1AINFT22,
        J_1AINFT24,
        J_1AINFT25,
        J_1AINFT26.


DATA : G_TRACE(1)             TYPE C,
       GENERAL_AMOUNT         LIKE  BSEG-DMBTR,
       GENERAL_AMOUNT_LONG    LIKE SKC1A-UMSAV,
       INFLATION_ORIGIN_DATE  TYPE D ,
       INFLATION_FINAL_DATE   TYPE D ,
       INDEX_VALUE_OD         TYPE F ,
       INDEX_VALUE_FD         TYPE F ,
       INFLATION_RATE         TYPE P DECIMALS 9.


DATA : BEGIN OF INT_SPECIFIC_INDEX OCCURS 10,
       INDEX           LIKE J_1AINFT25-J_1AINDX  ,
       FACTOR          LIKE J_1AINFT25-J_1AFACTOR,
       ADJ_AMOUNT      LIKE BSEG-DMBTR,
       ADJ_AMOUNT_LONG LIKE SKC1A-UMSAV,
       END OF INT_SPECIFIC_INDEX.

DATA : BEGIN OF INT_GENERAL_INDEX OCCURS 10,
       INDEX               LIKE J_1AINFT25-J_1AINDX  ,
       FACTOR              LIKE J_1AINFT25-J_1AFACTOR,
       GENERAL_AMOUNT      LIKE BSEG-DMBTR,
       GENERAL_AMOUNT_LONG LIKE SKC1A-UMSAV,
       END OF INT_GENERAL_INDEX.

*  data for inflation percentage calculation
DATA:  PERCENT_BASE_AMOUNT TYPE UMXXH, "base amount for perc. calc.
       PERCENT_INFL_AMOUNT TYPE UMXXH, "current perc. amount
       PERCENT_HELP_AMOUNT TYPE UMXXH,
       PERCENTAGE_SPECIFIC LIKE J_1AINFT24-J_1AINDDPE,
       PERCENTAGE_GENERAL  LIKE J_1AINFT24-J_1AINDDPE.

DATA : BEGIN OF INDEX_LOCK_DATE OCCURS 50,
       J_1AINDX   LIKE J_1AINFT26-J_1AINDX,
       J_1AVERSIO LIKE J_1AINFT26-J_1AVERSIO,
       J_1APROINP LIKE J_1AINFT26-J_1APROINP,
       J_1ALOCKPP LIKE J_1AINFT26-J_1ALOCKPP,
       END OF INDEX_LOCK_DATE .


DATA : BEGIN OF TBE_DATA OCCURS 100  .
        INCLUDE STRUCTURE J_1AINFT06.
DATA : END OF  TBE_DATA .

DATA : BEGIN OF INITIAL_LOCK_DATE .
        INCLUDE STRUCTURE INDEX_LOCK_DATE.
DATA : END OF INITIAL_LOCK_DATE.


DATA : BEGIN OF HIGH_LOCK_DATE  OCCURS 100  .
        INCLUDE STRUCTURE INDEX_LOCK_DATE.
DATA : END OF HIGH_LOCK_DATE.

DATA : G_PROV_FLAG.
DATA  INT_GENERAL_INDEX_LINES TYPE I.

* Global buffer for balance sheet correction
DATA: G_BUKRS LIKE T001-BUKRS.

TYPES: BEGIN OF S_INDEX_VALUE_BUFFER,
          INDEX          LIKE J_1AINFT25-J_1AINDX,
          INDATE         TYPE D,
          I_PROV         LIKE J_1AINFT20-J_1ACOINAP,
          VERSION        LIKE J_1AINFT20-J_1AVERACP,
          INDEX_VALUE_D  TYPE F,
          USED_VERSION   LIKE J_1AINFT20-J_1AVERACP,
          PROV_FLAG      TYPE C,
       END OF S_INDEX_VALUE_BUFFER.

TYPES: BEGIN OF S_TBE_DAY_BUFFER,
          TBE_NAME       LIKE J_1AINFT04-J_1ATBEDEP,
          REAL_DAT       LIKE J_1AINFT24-J_1AIDATEP,
          INFLATION_DATE TYPE D,
       END OF S_TBE_DAY_BUFFER.

* Global buffers for index rate rounding
DATA: BUFFER_TAB_1AINFT22 LIKE J_1AINFT22 OCCURS 0 WITH HEADER LINE.
