*&---------------------------------------------------------------------*
*&  Include           Z_FORM_SELECIONA_DADOS
*&---------------------------------------------------------------------*

*DATA: WA_DATA_GENERAL         TYPE BAPI_ITOB.
*REFRESH: IT_EQKT, IT_EQUI.
*
*IF ( NOT TBX_BUSC_CENTRO IS INITIAL ).
*  PERFORM: TBX_BUSC_CENTRO.
*
*ELSEIF ( NOT TBX_BUSC_EQUIPAMENTO IS INITIAL ).
*  PERFORM: TBX_BUSC_EQUIPAMENTO.

*ELSE.
*
*  SELECT *
*     INTO CORRESPONDING FIELDS OF TABLE IT_EQUI
*     FROM EQUI AS A
*    INNER JOIN EQUZ AS B ON A~EQUNR = B~EQUNR
*    INNER JOIN JEST AS C ON A~OBJNR = C~OBJNR
*    WHERE A~EQTYP IN ('V','F')
*      AND B~DATBI  = '99991231'.
*      AND C~STAT  NE 'I0076'
*      AND C~STAT  NE 'I0320'
*      AND C~INACT NE 'X'.

*  SELECT *
*    INTO CORRESPONDING FIELDS OF TABLE IT_EQKT
*    FROM EQKT AS A
*   INNER JOIN EQUZ AS B ON A~EQUNR = B~EQUNR
*   INNER JOIN ITOB AS C ON A~EQUNR = C~EQUNR
*   WHERE B~DATBI  = '99991231'
*     AND C~EQTYP IN ('V','F').

*ENDIF.

* Pegar a descrição do equipamento
*SELECT *
*   INTO CORRESPONDING FIELDS OF TABLE IT_EQKT
*   FROM EQKT
*FOR ALL ENTRIES IN IT_EQUI
*  WHERE EQUNR = IT_EQUI-EQUNR.

* Pegar o centro que está responsável pelo equipamento
*SELECT *
*  INTO CORRESPONDING FIELDS OF TABLE IT_EQUZ
*  FROM EQUZ
*FOR ALL ENTRIES IN IT_EQUI
* WHERE EQUNR = IT_EQUI-EQUNR
*  AND DATBI = '99991231'.

*SELECT DISTINCT
* IWERK EQUNR
*  INTO CORRESPONDING FIELDS OF TABLE IT_EQUZ
*  FROM EQUZ
*FOR ALL ENTRIES IN IT_EQUI
* WHERE EQUNR = IT_EQUI-EQUNR
*   AND DATBI = '99991231'.

* Organiza e deleta registros duplicados

*SORT IT_EQUI BY EQUNR.
*DELETE ADJACENT DUPLICATES FROM IT_EQKT.

*LOOP AT IT_EQUI INTO WA_EQUI.
*
*  CALL FUNCTION 'BAPI_EQUI_GETDETAIL'
*    EXPORTING
*      EQUIPMENT        = WA_EQUI-EQUNR
*    IMPORTING
*      DATA_GENERAL_EXP = WA_DATA_GENERAL.
*
*  READ TABLE IT_EQKT INTO WA_EQKT WITH KEY EQUNR = WA_EQUI-EQUNR.
**  READ TABLE IT_EQUZ INTO WA_EQUZ WITH KEY EQUNR = WA_EQUI-EQUNR.
*
*  WA_SAIDA-EQKTX = WA_EQKT-EQKTX.
*  WA_SAIDA-EQUNR = WA_EQUI-EQUNR.
*  WA_SAIDA-IWERK = WA_DATA_GENERAL-MAINTPLANT.
*  APPEND WA_SAIDA TO IT_SAIDA.
*  CLEAR: WA_EQUZ, WA_SAIDA, WA_EQKT.
*ENDLOOP.
