"Name: \PR:SAPLFAGL_COFI_ONLREC\FO:CHECK_IF_TRANSFER_TO_ACC\SE:BEGIN\EI
ENHANCEMENT 0 Z_KOB88_CTB.
*IF 'ID01_ID02_ID03_ID04_ID05_ID07_ZPM1_ZPM2_ZPM3_ZPM4_ZPM5_ZPM6_ZPM7' cs IS_COIOB_OBJNR-AUART .

*  DATA: T_auart                TYPE STANDARD TABLE OF  RGSB4 WITH HEADER LINE.
*   CALL FUNCTION 'G_SET_GET_ALL_VALUES'
*    EXPORTING
*      CLASS         = '0000'
*      SETNR         = 'MAGGI_KO88'
*    TABLES
*      SET_VALUES    = T_auart
*    EXCEPTIONS
*      SET_NOT_FOUND = 1
*      OTHERS        = 2.
*  IF SY-SUBRC <> 0.
**     MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
**             WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
*  ENDIF.
*  SORT T_auart BY FROM.
*  READ TABLE T_auart WITH KEY FROM = IS_COIOB_OBJNR-AUART.
*  IF sy-subrc = 0.
*      eb_transfer_to_acc = abap_true.
*  ENDIF.
*
*  READ TABLE T_auart WITH KEY FROM = IS_COIOB_PAROB1-AUART.
*  IF sy-subrc = 0.
*      eb_transfer_to_acc = abap_true.
*  ENDIF.

"CS2017002014 -
IF IS_COIOB_OBJNR-AUTYP = 30 or IS_COIOB_PAROB1-AUTYP = 30.
  eb_transfer_to_acc = abap_true.
ENDIF.

ENDENHANCEMENT.
