"Name: \PR:SAPMFDTA\FO:GET_DOWNLOAD_NAME\SE:BEGIN\EI
ENHANCEMENT 0 Z_LOCAL_FOLHA.
*
  DATA VVALFROM TYPE SETVALMIN.
  CONCATENATE TAB_REGUT-ZBUKR '-' TAB_REGUT-DTKEY INTO VVALFROM.

  DATA: T_SET TYPE STANDARD TABLE OF SETLEAF  WITH HEADER LINE.
  DATA: T_LAY TYPE STANDARD TABLE OF SETLINET WITH HEADER LINE.
  REFRESH: T_SET,T_LAY.
  SELECT *
  FROM  SETLEAF
  INTO TABLE T_SET
  WHERE SETCLASS      = '0000'
  AND   SETNAME       = 'MAGGI_LOCAL_FOLHA'
  AND   VALFROM       =  VVALFROM.

    IF T_SET[] IS NOT INITIAL.
      SELECT *
       FROM SETLINET
       INTO TABLE T_LAY
       FOR ALL ENTRIES IN T_SET
       WHERE SETCLASS   = T_SET-SETCLASS
       AND SUBCLASS     = T_SET-SUBCLASS
       AND SETNAME      = T_SET-SETNAME
       AND LINEID       = T_SET-LINEID.
      ENDIF.

      IF T_LAY[] IS NOT INITIAL.
        READ TABLE T_SET INDEX 1.
        IF SY-SUBRC = 0.
          READ TABLE T_LAY WITH KEY  SETCLASS   = T_SET-SETCLASS
                                     SUBCLASS   = T_SET-SUBCLASS
                                     SETNAME    = T_SET-SETNAME
                                     LINEID     = T_SET-LINEID.
          IF SY-SUBRC = 0.
            filename = T_LAY-DESCRIPT.
          ENDIF.
        ENDIF.
   ENDIF.


ENDENHANCEMENT.
