"Name: \FU:BORWE_VL_MM_CHECK_ASN_WE\SE:BEGIN\EI
ENHANCEMENT 0 Z_MIGO_AVISO.
*
  data: LV_CHARG_MIGO type mseg-charg.
  LV_CHARG_MIGO = IS_MSEG-CHARG.
  EXPORT LV_CHARG_MIGO TO MEMORY ID 'ZIV_CHARG_MIGO'.

ENDENHANCEMENT.
