"Name: \PR:SAPLMLSR\FO:FCODE_NEW_SHEET\SE:END\EI
ENHANCEMENT 0 Z_ML81N_INI.
*
  clear essr-bldat.

*  MESSAGE W000(Z01) DISPLAY LIKE 'E' WITH 'TRANSACAO INATIVADA!' .
*  LEAVE TO CURRENT TRANSACTION.

ENDENHANCEMENT.
