FUNCTION-POOL z_mm MESSAGE-ID z_mm      . "MESSAGE-ID ...
DATA DYNP_TITLE_TEXT(100).
DATA SAV_EINSCHRAENKUNG.
DATA: BEGIN OF DYNP_ANZEIGE_LISTE OCCURS 5,
        TEXT(100),
      END OF DYNP_ANZEIGE_LISTE.
DATA: DYNP_AUSWAHL(100).
