"Name: \PR:SAPMV45A\FO:FUNKTION_AUSFUEHREN\SE:BEGIN\EI
ENHANCEMENT 0 Z_MV45AF0F_BLOCK.
*
DATA ERRO TYPE C.
CLEAR ERRO.
ERRO = ZCL_SOLICITACAO_OV=>DOC_SUBSEQUENTE( I_VBELN = VBAK-VBELN
                                            I_UCOMM = SY-UCOMM ).
IF ERRO IS NOT INITIAL.
  MESSAGE I836(SD) WITH 'Ordem de venda não pode ser eliminada,' 'existem Doc. Contábeis Vinculados!'.
  LEAVE TO CURRENT TRANSACTION.
ENDIF.

ENDENHANCEMENT.
