"Name: \PR:SAPLIMSP\FO:LIMSPF00_PROPOSAL_CASE3\SE:END\EI
ENHANCEMENT 0 Z_RELEVANCIA_PERMIT_PM.
* Imperdir que o sistema remova a relevância das permits
  DATA: LV_AUART    TYPE AUFK-AUART.

  READ TABLE BELGNTAB INTO L_BELGNWA WITH KEY PMSOG = I_PMSOG
                                              LVORM = IMPRM_UNMARKED.
  IF sy-subrc is initial.
    IF SY-SUBRC IS INITIAL.
      SELECT SINGLE AUART
        FROM AUFK
        INTO LV_AUART
        WHERE AUFNR EQ L_BELGNWA-AUFNR.

      IF LV_AUART EQ 'ZPM7'.
        L_BELGNWA-K_SKIP = SPACE.
        MODIFY BELGNTAB FROM L_BELGNWA INDEX L_INDEX TRANSPORTING K_SKIP.
      ENDIF.
    ENDIF.
  ENDIF.
ENDENHANCEMENT.
