"Name: \PR:SAPLIMSP\FO:LIMSPF00_K_SKIP_UPDATE\SE:BEGIN\EI
ENHANCEMENT 0 Z_RELEVANCIA_PERMIT_PM.
*
  IF I_K_SKIP IS NOT INITIAL.
    DATA: LV_AUART    TYPE AUFK-AUART,
          WL_SCRGNTAB TYPE IMPRM_SCRGNWA_TYPE.

    CLEAR: WL_SCRGNTAB.
    READ TABLE SCRGNTAB INTO WL_SCRGNTAB INDEX I_INDEX.
    IF SY-SUBRC IS INITIAL.
      SELECT SINGLE AUART
        FROM AUFK
        INTO LV_AUART
        WHERE AUFNR EQ WL_SCRGNTAB-AUFNR.

      IF LV_AUART EQ 'ZPM7'.
        MESSAGE 'Relevância da permit não pode ser alterada' type 'S'.
        CLEAR I_K_SKIP.
      ENDIF.
    ENDIF.
  ENDIF.

ENDENHANCEMENT.
