"Name: \PR:SAPLSOE2\FO:GET_SENDER\SE:END\EI
ENHANCEMENT 0 Z_SET_NOREPLY_1.
* Alterar ordem de envio inserindo usuário JOBADM como remetente
  IF ( SENDER IS NOT INITIAL ).

    SELECT SNDYR, SNDNO, SNDNAM, SDDAT
      FROM SOOS
      INTO TABLE @DATA(T_USER)
      WHERE SNDNAM = 'JOBADM'.
    SORT T_USER[] BY SDDAT DESCENDING.
    IF ( SY-SUBRC = 0 ).

      TRY.
        DATA(W_USER) = T_USER[ 1 ].
      CATCH CX_SY_ITAB_LINE_NOT_FOUND.
      ENDTRY.

      USER-USRNAM = W_USER-SNDNAM.
      USER-SAPNAM = W_USER-SNDNAM.
      USER-USRNO = W_USER-SNDNO.
      USER-USRYR = W_USER-SNDYR.

      SENDER-ADDRESS = W_USER-SNDNAM.

      G_SENDER_ID-RECNO = W_USER-SNDNO.
      G_SENDER_ID-RECYR = W_USER-SNDYR.
    ENDIF.

  ENDIF.

ENDENHANCEMENT.
