FUNCTION Z_KP06_SYSPHERA.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_ANO) TYPE  GJAHR
*"     REFERENCE(I_MES) TYPE  MONAT
*"     REFERENCE(I_AREA) TYPE  KOKRS
*"  TABLES
*"      RESULTADO STRUCTURE  ZHCME_SYSPHERA_KP06
*"----------------------------------------------------------------------


  DATA: VKOSTL    TYPE KOSTL,
        VOBJ_INDX TYPE OBJ_INDX.

  DATA:
    IT_INDEXSTRUCTURE	TYPE STANDARD TABLE OF BAPIACISTRU, "TABLES PARAM
    WA_INDEXSTRUCTURE	LIKE LINE OF IT_INDEXSTRUCTURE,
    IT_COOBJECT	      TYPE STANDARD TABLE OF BAPIACIOBJ, "TABLES PARAM
    WA_COOBJECT	      LIKE LINE OF IT_COOBJECT,
    IT_PERVALUE	      TYPE STANDARD TABLE OF BAPIACIVAL, "TABLES PARAM
    WA_PERVALUE	      LIKE LINE OF IT_PERVALUE,
    IT_TOTVALUE	      TYPE STANDARD TABLE OF BAPIACITOT, "TABLES PARAM
    WA_TOTVALUE	      LIKE LINE OF IT_TOTVALUE,
    IT_RETURN	        TYPE STANDARD TABLE OF BAPIRET2, "TABLES PARAM
    WA_RETURN	        LIKE LINE OF IT_RETURN.

  IF RESULTADO[] IS INITIAL.
    MESSAGE 'Não retornou dados de importação!' TYPE 'I'.
    EXIT.
  ENDIF.

  DATA LD_HEADERINFO TYPE  BAPIPLNHDR.

  LD_HEADERINFO-CO_AREA         = I_AREA.
  LD_HEADERINFO-FISC_YEAR       = I_ANO.
  LD_HEADERINFO-PERIOD_FROM     = 1.
  LD_HEADERINFO-PERIOD_TO       = 12.
  LD_HEADERINFO-VERSION         = '0'.
  LD_HEADERINFO-DOC_HDR_TX      = 'Origem Sysphera'.
  LD_HEADERINFO-PLAN_CURRTYPE   = ''.


  SORT RESULTADO BY CENTRO_CUSTO MES.
  VOBJ_INDX = 1.
  READ TABLE RESULTADO INTO DATA(WA_KP06) INDEX 1.
  VKOSTL = WA_KP06-CENTRO_CUSTO.
  LOOP AT RESULTADO INTO WA_KP06.
    "populate fields of struture and append to itab
    WA_PERVALUE-VALUE_INDEX           = VOBJ_INDX.
    WA_PERVALUE-SEND_CCTR             = WA_KP06-CENTRO_CUSTO.
*    WA_PERVALUE-SEND_ACTIVITY         = 'UPM'.
    WA_PERVALUE-SENBUSPROC            = ''.
    WA_PERVALUE-ORDER_CELEM           = WA_KP06-COD_CONTA.
    CASE WA_KP06-MES.
      WHEN '01'. WA_PERVALUE-QUANTITY_FIX_PER01    = WA_KP06-VLR_LOCAL.
      WHEN '02'. WA_PERVALUE-QUANTITY_FIX_PER02    = WA_KP06-VLR_LOCAL.
      WHEN '03'. WA_PERVALUE-QUANTITY_FIX_PER03    = WA_KP06-VLR_LOCAL.
      WHEN '04'. WA_PERVALUE-QUANTITY_FIX_PER04    = WA_KP06-VLR_LOCAL.
      WHEN '05'. WA_PERVALUE-QUANTITY_FIX_PER05    = WA_KP06-VLR_LOCAL.
      WHEN '06'. WA_PERVALUE-QUANTITY_FIX_PER06    = WA_KP06-VLR_LOCAL.
      WHEN '07'. WA_PERVALUE-QUANTITY_FIX_PER07    = WA_KP06-VLR_LOCAL.
      WHEN '08'. WA_PERVALUE-QUANTITY_FIX_PER08    = WA_KP06-VLR_LOCAL.
      WHEN '09'. WA_PERVALUE-QUANTITY_FIX_PER09    = WA_KP06-VLR_LOCAL.
      WHEN '10'. WA_PERVALUE-QUANTITY_FIX_PER10    = WA_KP06-VLR_LOCAL.
      WHEN '11'. WA_PERVALUE-QUANTITY_FIX_PER11    = WA_KP06-VLR_LOCAL.
      WHEN '12'. WA_PERVALUE-QUANTITY_FIX_PER12    = WA_KP06-VLR_LOCAL.
    ENDCASE.

    IF VKOSTL NE WA_KP06-CENTRO_CUSTO.
      ADD 1 TO VOBJ_INDX.
      VKOSTL = WA_KP06-CENTRO_CUSTO.
      APPEND WA_PERVALUE TO IT_PERVALUE.
      "
      "populate fields of struture and append to itab
      WA_COOBJECT-OBJECT_INDEX  =  VOBJ_INDX.
      WA_COOBJECT-COSTCENTER    = WA_KP06-CENTRO_CUSTO.
*      WA_COOBJECT-ACTTYPE       = 'UPM'.
      WA_COOBJECT-CO_BUSPROC    = ''.
      WA_COOBJECT-ORDERID       = ''.
      WA_COOBJECT-WBS_ELEMENT   = ''.
      APPEND WA_COOBJECT TO IT_COOBJECT.
      "
      "populate fields of struture and append to itab
      WA_INDEXSTRUCTURE-OBJECT_INDEX = VOBJ_INDX.
      WA_INDEXSTRUCTURE-VALUE_INDEX  = VOBJ_INDX.
      APPEND WA_INDEXSTRUCTURE TO IT_INDEXSTRUCTURE.
    ENDIF.

  ENDLOOP.
  "
  IF VKOSTL EQ WA_KP06-CENTRO_CUSTO.
    APPEND WA_PERVALUE TO IT_PERVALUE.
    "populate fields of struture and append to itab
    WA_COOBJECT-OBJECT_INDEX  =  VOBJ_INDX.
    WA_COOBJECT-COSTCENTER    = WA_KP06-CENTRO_CUSTO.
*    WA_COOBJECT-ACTTYPE       = ''.
    WA_COOBJECT-CO_BUSPROC    = ''.
    WA_COOBJECT-ORDERID       = ''.
    WA_COOBJECT-WBS_ELEMENT   = ''.
    APPEND WA_COOBJECT TO IT_COOBJECT.
    "
    "populate fields of struture and append to itab
    WA_INDEXSTRUCTURE-OBJECT_INDEX = VOBJ_INDX.
    WA_INDEXSTRUCTURE-VALUE_INDEX  = VOBJ_INDX.
    APPEND WA_INDEXSTRUCTURE TO IT_INDEXSTRUCTURE.
  ENDIF.

  CALL FUNCTION 'BAPI_COSTACTPLN_POSTACTINPUT'
    EXPORTING
      HEADERINFO     = LD_HEADERINFO
      DELTA          = 'X'
    TABLES
      INDEXSTRUCTURE = IT_INDEXSTRUCTURE
      COOBJECT       = IT_COOBJECT
      PERVALUE       = IT_PERVALUE
      RETURN         = IT_RETURN.


  READ TABLE IT_RETURN INTO DATA(WA_BAPIRET) WITH KEY TYPE = 'E'.
  IF ( SY-SUBRC NE 0 ).
    CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
      EXPORTING
        WAIT = 'X'.
  ENDIF.


ENDFUNCTION.
