PROCESS BEFORE OUTPUT.
  MODULE STATUS_0200.
*
PROCESS AFTER INPUT.
*
  MODULE USER_COMMAND_0200_EXIT AT EXIT-COMMAND.

*  CHAIN.
*    FIELD ZAA004-GJAHR.
*    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
*  ENDCHAIN.

  MODULE USER_COMMAND_0200.
