*----------------------------------------------------------------------*
***INCLUDE LZBPCF02 .
*----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  ZSEL_DADOS_MOV_MENSAL
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*

FORM ZSELECIONA_DADOS_MOV_MENSAL .

  REFRESH : IT_SETLEAF, IT_ZGL029_DRE_DADOS, IT_CSKS, IT_ZGL029_DRE_DADOS, IT_MARA.

  LOOP AT IT_MOVIMENTO_MENSAL INTO WA_MOVIMENTO_MENSAL.

    IF WA_MOVIMENTO_MENSAL-CAMPO EQ 'BUKRS'.
      P_BUKRS-LOW    = WA_MOVIMENTO_MENSAL-VALOR_DE.
      P_BUKRS-HIGH   = WA_MOVIMENTO_MENSAL-VALOR_ATE.
      P_BUKRS-SIGN   = WA_MOVIMENTO_MENSAL-SIGN.
      P_BUKRS-OPTION = WA_MOVIMENTO_MENSAL-OPTION.
      APPEND P_BUKRS.
    ENDIF.

    IF WA_MOVIMENTO_MENSAL-CAMPO EQ 'GJAHR'.
      P_GJAHR-LOW    = WA_MOVIMENTO_MENSAL-VALOR_DE.
      P_GJAHR-HIGH   = WA_MOVIMENTO_MENSAL-VALOR_ATE.
      P_GJAHR-SIGN   = WA_MOVIMENTO_MENSAL-SIGN.
      P_GJAHR-OPTION = WA_MOVIMENTO_MENSAL-OPTION.
      APPEND P_GJAHR.
    ENDIF.

    IF WA_MOVIMENTO_MENSAL-CAMPO EQ 'MONAT'.
      P_MONAT-LOW    = WA_MOVIMENTO_MENSAL-VALOR_DE.
      P_MONAT-HIGH   = WA_MOVIMENTO_MENSAL-VALOR_ATE.
      P_MONAT-SIGN   = WA_MOVIMENTO_MENSAL-SIGN.
      P_MONAT-OPTION = WA_MOVIMENTO_MENSAL-OPTION.
      APPEND P_MONAT.
    ENDIF.

    IF WA_MOVIMENTO_MENSAL-CAMPO EQ 'SAKNR'.
      P_SAKNR-LOW    = WA_MOVIMENTO_MENSAL-VALOR_DE.
      P_SAKNR-HIGH   = WA_MOVIMENTO_MENSAL-VALOR_ATE.
      P_SAKNR-SIGN   = WA_MOVIMENTO_MENSAL-SIGN.
      P_SAKNR-OPTION = WA_MOVIMENTO_MENSAL-OPTION.
      APPEND P_SAKNR.
    ENDIF.

  ENDLOOP.

  "CSB Comentei esse techo
*  SELECT *
*    INTO TABLE it_setleaf
*    FROM setleaf
*   WHERE setname = 'MAGGI_ESTRUTURA_BPC'.
*
*  LOOP AT it_setleaf INTO wa_setleaf.
*    p_set-low    = wa_setleaf-valfrom.
*    p_set-high   = wa_setleaf-valto.
*    p_set-sign   = wa_setleaf-valsign.
*    p_set-option = wa_setleaf-valoption.
*  ENDLOOP.


  " Conforme solicitação chamado 97025
  RANGES:  RG_VERSN FOR ZGL029_DRE_DADOS-VERSN.
  REFRESH: RG_VERSN.
  CLEAR: IT_ZFIT0039,WA_ZFIT0039.

  SELECT *
    INTO TABLE IT_ZFIT0039
    FROM ZFIT0039
   WHERE BUKRS IN P_BUKRS.

  LOOP AT IT_ZFIT0039 INTO WA_ZFIT0039.
    RG_VERSN-SIGN   = 'I'.
    RG_VERSN-OPTION = 'EQ'.
    RG_VERSN-LOW    = WA_ZFIT0039-VERSN.
    APPEND RG_VERSN.
    CLEAR: RG_VERSN.
  ENDLOOP.

  SELECT *
    INTO TABLE IT_ZGL029_DRE_DADOS_AUX
    FROM ZGL029_DRE_DADOS
   WHERE BUKRS IN P_BUKRS
     "AND versn IN p_set
     AND VERSN IN RG_VERSN
     AND SAKNR IN P_SAKNR
     AND MONAT IN P_MONAT
     AND GJAHR IN P_GJAHR.

  SELECT KOSTL KOKRS
    INTO TABLE IT_CSKS
    FROM CSKS
    FOR ALL ENTRIES IN IT_ZGL029_DRE_DADOS_AUX
   WHERE KOSTL = IT_ZGL029_DRE_DADOS_AUX-KOSTL.

  IF IT_ZGL029_DRE_DADOS_AUX IS NOT INITIAL.

    SELECT *
      INTO TABLE IT_ZGL014_DRE_DEPA
      FROM ZGL014_DRE_DEPA
       FOR ALL ENTRIES IN IT_ZGL029_DRE_DADOS_AUX
     WHERE BUKRS = IT_ZGL029_DRE_DADOS_AUX-BUKRS
       AND PRCTR = IT_ZGL029_DRE_DADOS_AUX-PRCTR.

  ENDIF.

  IF IT_ZGL014_DRE_DEPA IS NOT INITIAL.

    SELECT *
      INTO TABLE IT_MARA
      FROM MARA
       FOR ALL ENTRIES IN IT_ZGL014_DRE_DEPA
     WHERE MATNR = IT_ZGL014_DRE_DEPA-MATNR.

  ENDIF.

  SORT: IT_ZGL014_DRE_DEPA BY BUKRS PRCTR,
        IT_MARA            BY MATNR.

  LOOP AT IT_ZGL029_DRE_DADOS_AUX INTO WA_ZGL029_DRE_DADOS_AUX .

    READ TABLE IT_ZGL014_DRE_DEPA INTO WA_ZGL014_DRE_DEPA WITH KEY BUKRS = WA_ZGL029_DRE_DADOS_AUX-BUKRS  PRCTR = WA_ZGL029_DRE_DADOS_AUX-PRCTR BINARY SEARCH.

    READ TABLE IT_MARA INTO WA_MARA WITH KEY MATNR = WA_ZGL014_DRE_DEPA-MATNR BINARY SEARCH.

    MOVE-CORRESPONDING WA_ZGL029_DRE_DADOS_AUX TO WA_ZGL029_DRE_DADOS.

    WA_ZGL029_DRE_DADOS-MATKL = WA_MARA-MATKL.

    APPEND WA_ZGL029_DRE_DADOS TO IT_ZGL029_DRE_DADOS.

  ENDLOOP.

ENDFORM.                    " ZSEL_DADOS_MOV_MENSAL
*&---------------------------------------------------------------------*
*&      Form  ZPROCESSA_RETORNO_MOV_MENSAL
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ZPROCESSA_RETORNO_MOV_MENSAL .
  SORT : IT_CSKS BY KOSTL.
  DATA: VL_CENTRO_AR     TYPE C LENGTH 1,
        V_MOEDA_EMPRESA  TYPE RGSBL-TITLE,
        T_USERMD         TYPE STANDARD TABLE OF  RGSB4 WITH HEADER LINE,
        WA_USERMD        TYPE RGSB4.


  LOOP AT IT_ZGL029_DRE_DADOS INTO WA_ZGL029_DRE_DADOS.

    READ TABLE IT_CSKS INTO WA_CSKS WITH KEY KOSTL = WA_ZGL029_DRE_DADOS-KOSTL.
    CLEAR VL_CENTRO_AR.

    SELECT SINGLE *
      FROM SETLEAF
      INTO WA_SETLEAF
    WHERE SETNAME = 'MAGGI_EMPRESA_EXTERIOR'
      AND VALFROM = WA_ZGL029_DRE_DADOS-BUKRS.

    IF SY-SUBRC IS INITIAL .
      VL_CENTRO_AR = 'S'.
      " Moeda da empresa

      CALL FUNCTION 'G_SET_GET_ALL_VALUES'
        EXPORTING
          CLASS           = '0000'
          SETNR           = 'MAGGI_EMPRESA_EXTERIOR'
          NO_DESCRIPTIONS = ' '
        TABLES
          SET_VALUES      = T_USERMD
        EXCEPTIONS
          SET_NOT_FOUND   = 1
          OTHERS          = 2.
      IF SY-SUBRC <> 0.
*     MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*             WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
      ENDIF.

      READ TABLE T_USERMD INTO WA_USERMD WITH KEY FROM = WA_ZGL029_DRE_DADOS-BUKRS.
      IF SY-SUBRC IS  INITIAL.
        V_MOEDA_EMPRESA =  WA_USERMD-TITLE.
      ENDIF.

    ELSE.
      VL_CENTRO_AR = 'N'.
    ENDIF.

    WA_RET_MOVIMENTO_MENSAL-EMPRESA             = WA_ZGL029_DRE_DADOS-BUKRS.
    WA_RET_MOVIMENTO_MENSAL-EXERCICIO           = WA_ZGL029_DRE_DADOS-GJAHR.
    WA_RET_MOVIMENTO_MENSAL-MES_EXERCICIO       = WA_ZGL029_DRE_DADOS-MONAT.
    WA_RET_MOVIMENTO_MENSAL-CONTA_RAZAO         = WA_ZGL029_DRE_DADOS-SAKNR.
    WA_RET_MOVIMENTO_MENSAL-SOCIEDADE_PARCEIRA  = WA_ZGL029_DRE_DADOS-VBUND.
    WA_RET_MOVIMENTO_MENSAL-CENTRO_CUSTO        = WA_ZGL029_DRE_DADOS-KOSTL.
    WA_RET_MOVIMENTO_MENSAL-KOKRS               = WA_CSKS-KOKRS.
    WA_RET_MOVIMENTO_MENSAL-GRUPO_MERCADORIA    = WA_ZGL029_DRE_DADOS-MATKL.
    WA_RET_MOVIMENTO_MENSAL-MOEDA               = 'BRL'.
    IF VL_CENTRO_AR = 'S' .
      WA_RET_MOVIMENTO_MENSAL-MOVIMENTACAO_MENSAL = WA_ZGL029_DRE_DADOS-VLR_GRUPO." Caso argentina
    ELSE.
      WA_RET_MOVIMENTO_MENSAL-MOVIMENTACAO_MENSAL = WA_ZGL029_DRE_DADOS-VLR_REA.
    ENDIF.

    COLLECT WA_RET_MOVIMENTO_MENSAL INTO IT_RET_MOVIMENTO_MENSAL.

    WA_RET_MOVIMENTO_MENSAL-EMPRESA             = WA_ZGL029_DRE_DADOS-BUKRS.
    WA_RET_MOVIMENTO_MENSAL-EXERCICIO           = WA_ZGL029_DRE_DADOS-GJAHR.
    WA_RET_MOVIMENTO_MENSAL-MES_EXERCICIO       = WA_ZGL029_DRE_DADOS-MONAT.
    WA_RET_MOVIMENTO_MENSAL-CONTA_RAZAO         = WA_ZGL029_DRE_DADOS-SAKNR.
    WA_RET_MOVIMENTO_MENSAL-SOCIEDADE_PARCEIRA  = WA_ZGL029_DRE_DADOS-VBUND.
    WA_RET_MOVIMENTO_MENSAL-CENTRO_CUSTO        = WA_ZGL029_DRE_DADOS-KOSTL.
    WA_RET_MOVIMENTO_MENSAL-KOKRS               = WA_CSKS-KOKRS.
    WA_RET_MOVIMENTO_MENSAL-GRUPO_MERCADORIA    = WA_ZGL029_DRE_DADOS-MATKL.
    WA_RET_MOVIMENTO_MENSAL-MOEDA               = 'USD'.
    WA_RET_MOVIMENTO_MENSAL-MOVIMENTACAO_MENSAL = WA_ZGL029_DRE_DADOS-VLR_DOLAR.

    COLLECT  WA_RET_MOVIMENTO_MENSAL INTO IT_RET_MOVIMENTO_MENSAL.

    IF VL_CENTRO_AR = 'S' .

      WA_RET_MOVIMENTO_MENSAL-EMPRESA             = WA_ZGL029_DRE_DADOS-BUKRS.
      WA_RET_MOVIMENTO_MENSAL-EXERCICIO           = WA_ZGL029_DRE_DADOS-GJAHR.
      WA_RET_MOVIMENTO_MENSAL-MES_EXERCICIO       = WA_ZGL029_DRE_DADOS-MONAT.
      WA_RET_MOVIMENTO_MENSAL-CONTA_RAZAO         = WA_ZGL029_DRE_DADOS-SAKNR.
      WA_RET_MOVIMENTO_MENSAL-SOCIEDADE_PARCEIRA  = WA_ZGL029_DRE_DADOS-VBUND.
      WA_RET_MOVIMENTO_MENSAL-CENTRO_CUSTO        = WA_ZGL029_DRE_DADOS-KOSTL.
      WA_RET_MOVIMENTO_MENSAL-KOKRS               = WA_CSKS-KOKRS.
      WA_RET_MOVIMENTO_MENSAL-GRUPO_MERCADORIA    = WA_ZGL029_DRE_DADOS-MATKL.
      WA_RET_MOVIMENTO_MENSAL-MOEDA               = V_MOEDA_EMPRESA.
      WA_RET_MOVIMENTO_MENSAL-MOVIMENTACAO_MENSAL = WA_ZGL029_DRE_DADOS-VLR_REA.

      COLLECT  WA_RET_MOVIMENTO_MENSAL INTO IT_RET_MOVIMENTO_MENSAL.
    ENDIF.

  ENDLOOP.

ENDFORM.                    " ZPROCESSA_RETORNO_MOV_MENSAL
