PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSDT0001PD CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSDT0001PD-ID_PRODUTOR .
    FIELD ZSDT0001PD-NR_SAFRA .
    FIELD ZSDT0001PD-ID_BUKRS .
    FIELD ZSDT0001PD-ID_BRANCH .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSDT0001PD-ID_PRODUTOR .
    FIELD ZSDT0001PD-NR_SAFRA .
    FIELD ZSDT0001PD-ID_BUKRS .
    FIELD ZSDT0001PD-ID_BRANCH .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
