*&---------------------------------------------------------------------*
*& Report  ZCARGAROMANEIO2
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZCARGAROMANEIO2.

DATA: WA_J_1BNFDOC TYPE J_1BNFDOC,
      WA_J_1BNFE_ACTIVE TYPE J_1BNFE_ACTIVE,
      IT_CIOT TYPE TABLE OF ZCTE_CIOT WITH HEADER LINE,
      WA_ZCTE_CIOT TYPE ZCTE_CIOT,
      WA_INFO_CTE  TYPE ZCARGA_CTE_TIP.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-S01.
PARAMETERS: P_DOCNUM TYPE J_1BDOCNUM OBLIGATORY,
            P_NUMERO TYPE J_1BNFNUM9 OBLIGATORY,
            P_DATA   TYPE J_1BDOCDAT OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.

START-OF-SELECTION.

  SELECT SINGLE * INTO WA_J_1BNFDOC FROM J_1BNFDOC WHERE DOCNUM EQ P_DOCNUM.

  IF SY-SUBRC IS INITIAL.

    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
      EXPORTING
        INPUT = P_NUMERO
     IMPORTING
       OUTPUT = WA_J_1BNFDOC-NFENUM.

    IF P_DATA IS NOT INITIAL.
      WA_J_1BNFDOC-DOCDAT = P_DATA.
      WA_J_1BNFDOC-PSTDAT = P_DATA.
      WA_J_1BNFDOC-CREDAT = P_DATA.
      WA_J_1BNFDOC-CHADAT = P_DATA.
    ENDIF.

    MODIFY J_1BNFDOC FROM WA_J_1BNFDOC.
    COMMIT WORK.
  ENDIF.

  SELECT SINGLE * INTO WA_J_1BNFE_ACTIVE FROM J_1BNFE_ACTIVE WHERE DOCNUM EQ P_DOCNUM.

  IF SY-SUBRC IS INITIAL.

    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
      EXPORTING
        INPUT = P_NUMERO
     IMPORTING
       OUTPUT = WA_J_1BNFE_ACTIVE-NFNUM9.

    IF P_DATA IS NOT INITIAL.
      WA_J_1BNFE_ACTIVE-CREDAT      = P_DATA.
      WA_J_1BNFE_ACTIVE-ACTION_DATE = P_DATA.
    ENDIF.

    MODIFY J_1BNFE_ACTIVE FROM WA_J_1BNFE_ACTIVE.
    COMMIT WORK.

  ENDIF.

  IF WA_J_1BNFDOC-MODEL EQ 57.

    SELECT SINGLE * INTO WA_INFO_CTE FROM ZCARGA_CTE_TIP WHERE CTENUM EQ WA_J_1BNFDOC-NFENUM AND ENVIADOCTE EQ ''.

    IF SY-SUBRC IS INITIAL.

      CALL FUNCTION 'Z_SD_INFO_CTE_AVULSO'
        EXPORTING
          P_CTE_AVULSO   = WA_J_1BNFDOC-DOCNUM
          P_CHAMAR_TELA  = SPACE
          P_GRAVAR_DADOS = 'X'
       TABLES
         IT_CIOT         = IT_CIOT[].

      READ TABLE IT_CIOT INDEX 1.
      IF SY-SUBRC IS NOT INITIAL.
        EXIT.
      ENDIF.

      SELECT SINGLE * INTO WA_ZCTE_CIOT FROM ZCTE_CIOT WHERE DOCNUM EQ WA_J_1BNFDOC-DOCNUM.
      IF SY-SUBRC IS NOT INITIAL.
        EXIT.
      ENDIF.

      WA_ZCTE_CIOT-NUCONTRATO	       = WA_INFO_CTE-NUCONTRATO.
      WA_ZCTE_CIOT-NR_CIOT   	       = WA_INFO_CTE-NR_CIOT.
      WA_ZCTE_CIOT-ID_OP_VIAGEM_ADM  = WA_INFO_CTE-ID_OP_VIAGEM_ADM.
      WA_ZCTE_CIOT-LINK_CONTRATO     = WA_INFO_CTE-LINK_CONTRATO.
      WA_ZCTE_CIOT-LINK_RESUMO       = WA_INFO_CTE-LINK_RESUMO.
      WA_ZCTE_CIOT-ST_CIOT           = '5'.
      MODIFY ZCTE_CIOT FROM WA_ZCTE_CIOT.

      CALL FUNCTION 'J_1B_NFE_SEND_C_NFE'
        EXPORTING
          IV_DOCNUM           = WA_J_1BNFDOC-DOCNUM
        EXCEPTIONS
          NOT_SENT            = 1
          NOT_ALLOWED_TO_SEND = 2
          OTHERS              = 3.

      IF SY-SUBRC <> 0.
        MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
      ELSE.
        WA_INFO_CTE-ENVIADOCTE = 'X'.
        MODIFY ZCARGA_CTE_TIP FROM WA_INFO_CTE.
        COMMIT WORK.
      ENDIF.

    ENDIF.

  ENDIF.
