PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCARGA_CTE_TIP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCARGA_CTE_TIP-CTENUM .
    FIELD ZCARGA_CTE_TIP-NUCONTRATO .
    FIELD ZCARGA_CTE_TIP-ID_OP_VIAGEM_ADM .
    FIELD ZCARGA_CTE_TIP-CONTRATANTE .
    FIELD ZCARGA_CTE_TIP-NR_CIOT .
    FIELD ZCARGA_CTE_TIP-LINK_CONTRATO .
    FIELD ZCARGA_CTE_TIP-LINK_RESUMO .
    FIELD ZCARGA_CTE_TIP-ENVIADOCTE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCARGA_CTE_TIP-CTENUM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
