PROCESS BEFORE OUTPUT.

  MODULE STATUS_9001.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_9001_EXIT AT EXIT-COMMAND.

  CHAIN.
    MODULE GET_SCROLL_INFO_9001.
    MODULE GET_SELECTED_ROWS_9001.
  ENDCHAIN.

  MODULE USER_COMMAND_9001.
