PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSDT0001OD CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSDT0001OD-ID_ORDEM .
    FIELD ZSDT0001OD-NR_ORDEM .
    FIELD ZSDT0001OD-NR_SAFRA .
    FIELD ZSDT0001OD-ID_BUKRS .
    FIELD ZSDT0001OD-ID_BRANCH .
    FIELD ZSDT0001OD-ID_BUKRS_AG .
    FIELD ZSDT0001OD-ID_BRANCH_AG .
    FIELD ZSDT0001OD-ID_LOCAL_COLETA .
    FIELD ZSDT0001OD-ID_LOCAL_DESTINO .
    FIELD ZSDT0001OD-ID_LOCAL_DESCARGA .
    FIELD ZSDT0001OD-ID_PRODUTO .
    FIELD ZSDT0001OD-ID_MOTORISTA .
    FIELD ZSDT0001OD-DS_PLACA_TRATOR .
    FIELD ZSDT0001OD-DS_PLACA_REBOQ_1 .
    FIELD ZSDT0001OD-DS_PLACA_REBOQ_2 .
    FIELD ZSDT0001OD-DS_PLACA_REBOQ_3 .
    FIELD ZSDT0001OD-TP_STATUS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSDT0001OD-ID_ORDEM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
