PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCARGA_ROMANEIO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCARGA_ROMANEIO-CH_REFERENCIA .
    FIELD ZCARGA_ROMANEIO-DT_NOTA .
    FIELD ZCARGA_ROMANEIO-NFENUM .
    FIELD ZCARGA_ROMANEIO-DOC_REM .
    FIELD ZCARGA_ROMANEIO-FATURA_PROD .
    FIELD ZCARGA_ROMANEIO-DOCNUM .
    FIELD ZCARGA_ROMANEIO-ENVIADO .
    FIELD ZCARGA_ROMANEIO-CHAVE_NFE .
    FIELD ZCARGA_ROMANEIO-CTEDOCNUM .
    FIELD ZCARGA_ROMANEIO-CTENUM .
    FIELD ZCARGA_ROMANEIO-NUCONTRATO .
    FIELD ZCARGA_ROMANEIO-ID_OP_VIAGEM_ADM .
    FIELD ZCARGA_ROMANEIO-NR_CIOT .
    FIELD ZCARGA_ROMANEIO-LINK_CONTRATO .
    FIELD ZCARGA_ROMANEIO-LINK_RESUMO .
    FIELD ZCARGA_ROMANEIO-ENVIADOCTE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCARGA_ROMANEIO-CH_REFERENCIA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
