PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZSDT0001OD-ID_ORDEM .
    FIELD ZSDT0001OD-NR_ORDEM .
    FIELD ZSDT0001OD-DT_EMISSAO .
    FIELD ZSDT0001OD-DT_VALIDADE .
    FIELD ZSDT0001OD-NR_SAFRA .
    FIELD ZSDT0001OD-ID_BUKRS .
    FIELD ZSDT0001OD-ID_BRANCH .
    FIELD ZSDT0001OD-ID_BUKRS_AG .
    FIELD ZSDT0001OD-ID_BRANCH_AG .
    FIELD ZSDT0001OD-ID_LOCAL_COLETA .
    FIELD ZSDT0001OD-ID_LOCAL_DESTINO .
    FIELD ZSDT0001OD-ID_LOCAL_DESCARGA .
    FIELD ZSDT0001OD-ID_PRODUTO .
    FIELD ZSDT0001OD-ID_MOTORISTA .
    FIELD ZSDT0001OD-DS_PLACA_TRATOR .
    FIELD ZSDT0001OD-DS_PLACA_REBOQ_1 .
    FIELD ZSDT0001OD-DS_PLACA_REBOQ_2 .
    FIELD ZSDT0001OD-DS_PLACA_REBOQ_3 .
    FIELD ZSDT0001OD-TP_STATUS .
    FIELD ZSDT0001OD-NR_PESO_ALVO .
    FIELD ZSDT0001OD-NR_FRETE_COMB .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZSDT0001OD-ID_ORDEM .
  module detail_pai.
 endchain.
