PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZSDT0001PD-ID_PRODUTOR .
    FIELD ZSDT0001PD-NR_SAFRA .
    FIELD ZSDT0001PD-ID_BUKRS .
    FIELD ZSDT0001PD-ID_BRANCH .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZSDT0001PD-ID_PRODUTOR .
    FIELD ZSDT0001PD-NR_SAFRA .
    FIELD ZSDT0001PD-ID_BUKRS .
    FIELD ZSDT0001PD-ID_BRANCH .
  module detail_pai.
 endchain.
