"Name: \FU:J_1B_NFE_PROCESS_OUTBOUND\SE:END\EI
ENHANCEMENT 0 ZCHANGE_ANZPK_J_1BNFDOC.

  DATA: V_MENGE_LIN  TYPE J_1BNFLIN-MENGE,
        V_MENGE_ANZPK TYPE J_1BNFLIN-MENGE.

  DATA(_PROCESS_MD_BI) = ABAP_FALSE.
  LOOP AT IT_NFLIN INTO DATA(LWA_LIN) WHERE REFTYP = 'BI' OR REFTYP EQ 'MD'.
    _PROCESS_MD_BI = ABAP_TRUE.
    EXIT.
  ENDLOOP.

  IF ( _PROCESS_MD_BI EQ ABAP_TRUE ) AND ( CS_HEADER-ANZPK IS NOT INITIAL ).
    CLEAR: V_MENGE_LIN, V_MENGE_ANZPK.

    V_MENGE_ANZPK = CS_HEADER-ANZPK.

    LOOP AT IT_NFLIN INTO LWA_LIN.
      ADD LWA_LIN-MENGE TO V_MENGE_LIN.
    ENDLOOP.

    IF V_MENGE_LIN > V_MENGE_ANZPK.
      CLEAR: CS_HEADER-ANZPK.
    ENDIF.
  ENDIF.

ENDENHANCEMENT.
