PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCIOT_PARCEIROS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCIOT_PARCEIROS-BUKRS .
    FIELD ZCIOT_PARCEIROS-PARID .
    FIELD ZCIOT_PARCEIROS-PARTYP .
    FIELD ZCIOT_PARCEIROS-ROUTE .
    FIELD ZCIOT_PARCEIROS-DT_INICIO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCIOT_PARCEIROS-BUKRS .
    FIELD ZCIOT_PARCEIROS-PARID .
    FIELD ZCIOT_PARCEIROS-PARTYP .
    FIELD ZCIOT_PARCEIROS-ROUTE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
