class ZCL_REPOSITORY_CLASSES definition
  public
  final
  create public .

public section.

  data AT_DELIVERY_AVISO type ref to ZCL_AVISO_RECEBIMENTO .
  data AT_REPOM type ref to ZCL_REPOM_VIAGEM_VPR .
  data AT_MIGO type ref to ZCL_MIGO .
  data AT_MIRO_FRETE type ref to ZCL_MIRO_FRETE .
  data AT_MIRO type ref to ZCL_MIRO .
  data AT_FISCAL type ref to ZCL_FISCAL .
  data AT_DEPARTAMENTO_NFE_INBOUND type ref to ZCL_MM_DEPARTAMENTO .
  data AT_NFE_INBOUND type ref to ZCL_NFE_INBOUND .
  class-data AT_PEDIDO_COMPRA type ref to ZCL_PEDIDO_COMPRA .
  data AT_CHARG type ref to ZCL_CHARG .
  data AT_ROMANEIO type ref to ZCL_ROMANEIO .
  data AT_FERROVIARIO_CHEGADA type ref to ZCL_FERROVIARIO_CHEGADA .
  data AT_FERROVIARIO_SAIDA type ref to ZCL_FERROVIARIO_SAIDA .

  methods DELIVERY_AVISO
    returning
      value(R_DELIVERY) type ref to ZCL_AVISO_RECEBIMENTO .
  methods REPOM .
  methods MIGO
    returning
      value(R_MIGO) type ref to ZCL_MIGO .
  methods MIRO
    returning
      value(R_MIRO) type ref to ZCL_MIRO .
  methods MIRO_FRETE
    returning
      value(R_MIRO_FRETE) type ref to ZCL_MIRO_FRETE .
  methods FISCAL
    returning
      value(R_FISCAL) type ref to ZCL_FISCAL .
  methods DEPARTAMENTO_NFE_INBOUND
    returning
      value(R_DEPARTAMENTO) type ref to ZCL_MM_DEPARTAMENTO .
  methods NFE_INBOUND
    returning
      value(R_NFE_INBOUND) type ref to ZCL_NFE_INBOUND .
  methods PEDIDO_COMPRA
    returning
      value(R_PEDIDO_COMPRA) type ref to ZCL_PEDIDO_COMPRA .
  methods FREE .
  methods CHARG
    returning
      value(R_CHARG) type ref to ZCL_CHARG .
  methods ROMANEIO
    returning
      value(R_ROMANEIO) type ref to ZCL_ROMANEIO .
  methods FERROVIARIO_CHEGADA
    returning
      value(R_FERROVIARIO_CHEGADA) type ref to ZCL_FERROVIARIO_CHEGADA .
  methods FERROVIARIO_SAIDA
    returning
      value(R_FERROVIARIO_SAIDA) type ref to ZCL_FERROVIARIO_SAIDA .
  PROTECTED SECTION.
private section.
ENDCLASS.



CLASS ZCL_REPOSITORY_CLASSES IMPLEMENTATION.


  METHOD CHARG.

    IF ME->AT_CHARG IS INITIAL.
      CREATE OBJECT ME->AT_CHARG.
    ENDIF.
    R_CHARG = ME->AT_CHARG.

  ENDMETHOD.


  METHOD DELIVERY_AVISO.
    IF ME->AT_DELIVERY_AVISO IS INITIAL.
      CREATE OBJECT ME->AT_DELIVERY_AVISO.
    ENDIF.
    R_DELIVERY = ME->AT_DELIVERY_AVISO.
  ENDMETHOD.


  METHOD DEPARTAMENTO_NFE_INBOUND.
    IF ME->AT_DEPARTAMENTO_NFE_INBOUND IS INITIAL.
      CREATE OBJECT ME->AT_DEPARTAMENTO_NFE_INBOUND.
    ENDIF.
    R_DEPARTAMENTO = ME->AT_DEPARTAMENTO_NFE_INBOUND.
  ENDMETHOD.


  METHOD FERROVIARIO_CHEGADA.

    IF ME->AT_FERROVIARIO_CHEGADA IS INITIAL.
      CREATE OBJECT ME->AT_FERROVIARIO_CHEGADA.
    ENDIF.
    R_FERROVIARIO_CHEGADA = ME->AT_FERROVIARIO_CHEGADA.

  ENDMETHOD.


  METHOD FERROVIARIO_SAIDA.
    IF ME->AT_FERROVIARIO_SAIDA IS INITIAL.
      CREATE OBJECT ME->AT_FERROVIARIO_SAIDA.
    ENDIF.
    R_FERROVIARIO_SAIDA = ME->AT_FERROVIARIO_SAIDA.
  ENDMETHOD.


  METHOD FISCAL.
    IF ME->AT_FISCAL IS INITIAL.
      CREATE OBJECT ME->AT_FISCAL.
    ENDIF.
    R_FISCAL = ME->AT_FISCAL.
  ENDMETHOD.


  METHOD FREE.

    IF ME->AT_NFE_INBOUND IS NOT INITIAL.
      ME->AT_NFE_INBOUND->FREE( ).
    ENDIF.

    "IF ME->AT_CARGA_RECEBIMENTO IS NOT INITIAL.
    "  TRY .
    "      ME->AT_CARGA_RECEBIMENTO->ZIF_CARGA~FREE( ).
    "    CATCH ZCX_CARGA.    "
    "  ENDTRY.
    "ENDIF.

    CLEAR: ME->AT_CHARG,
           ME->AT_DELIVERY_AVISO,
           ME->AT_DEPARTAMENTO_NFE_INBOUND,
           ME->AT_FERROVIARIO_CHEGADA,
           ME->AT_FERROVIARIO_SAIDA,
           ME->AT_FISCAL,
           ME->AT_MIGO,
           ME->AT_MIRO,
           ME->AT_MIRO_FRETE,
           ME->AT_NFE_INBOUND,
           ME->AT_PEDIDO_COMPRA,
           ME->AT_REPOM,
           ME->AT_ROMANEIO.
           "ME->AT_CARGA_RECEBIMENTO,
           "ME->AT_CLIENTES,
           "ME->AT_FORNECEDORES,
           "ME->AT_ORDEM_CARREGAMENTO,
           "ME->AT_ORDEM_VENDA,
           "ME->AT_JOB.

  ENDMETHOD.


  METHOD MIGO.
    IF ME->AT_MIGO IS INITIAL.
      CREATE OBJECT ME->AT_MIGO.
    ENDIF.
    R_MIGO = ME->AT_MIGO.
  ENDMETHOD.


  METHOD MIRO.
    IF ME->AT_MIRO IS INITIAL.
      CREATE OBJECT ME->AT_MIRO.
    ENDIF.
    R_MIRO = ME->AT_MIRO.
  ENDMETHOD.


  METHOD MIRO_FRETE.
    IF ME->AT_MIRO_FRETE IS INITIAL.
      CREATE OBJECT ME->AT_MIRO_FRETE.
    ENDIF.
    R_MIRO_FRETE = ME->AT_MIRO_FRETE.
  ENDMETHOD.


  METHOD NFE_INBOUND.
    IF ME->AT_NFE_INBOUND IS INITIAL.
      CREATE OBJECT ME->AT_NFE_INBOUND.
    ENDIF.
    R_NFE_INBOUND = ME->AT_NFE_INBOUND.
  ENDMETHOD.


  METHOD PEDIDO_COMPRA.
    IF ME->AT_PEDIDO_COMPRA IS INITIAL.
      CREATE OBJECT ME->AT_PEDIDO_COMPRA.
    ENDIF.
    R_PEDIDO_COMPRA = ME->AT_PEDIDO_COMPRA.
  ENDMETHOD.


  METHOD REPOM.

  ENDMETHOD.


  METHOD ROMANEIO.

    IF ME->AT_ROMANEIO IS INITIAL.
      CREATE OBJECT ME->AT_ROMANEIO.
    ENDIF.
    R_ROMANEIO = ME->AT_ROMANEIO.

  ENDMETHOD.
ENDCLASS.
