class ZCL_GW_ABASTECIMENTO_DPC_EXT definition
  public
  inheriting from ZCL_GW_ABASTECIMENTO_DPC
  create public .

public section.

  methods /IWBEP/IF_MGW_CORE_SRV_RUNTIME~CHANGESET_BEGIN
    redefinition .
protected section.

  methods APONTAMENTOSET_CREATE_ENTITY
    redefinition .
  methods CAUSAMANUTENCAO_GET_ENTITYSET
    redefinition .
  methods CENTROCUSTO_GET_ENTITYSET
    redefinition .
  methods LOCALINSTALACAO_GET_ENTITYSET
    redefinition .
  methods MATERIALAUXILIAR_GET_ENTITYSET
    redefinition .
  methods PLANOOPERACAO_GET_ENTITYSET
    redefinition .
  methods PONTOMEDICAO_GET_ENTITYSET
    redefinition .
  methods USUARIO_GET_ENTITYSET
    redefinition .
  methods VEICULOCOMPARTIM_GET_ENTITYSET
    redefinition .
  methods VEICULOOPERACAO_GET_ENTITYSET
    redefinition .
  methods VEICULO_GET_ENTITYSET
    redefinition .
ENDCLASS.



CLASS ZCL_GW_ABASTECIMENTO_DPC_EXT IMPLEMENTATION.


  METHOD APONTAMENTOSET_CREATE_ENTITY.
    DATA INPUT_TABLE TYPE TABLE OF ZCL_GW_ABASTECIMENTO_MPC=>TS_M_TRANSA_EXP_TERCEIRO.
    DATA RETURN TYPE BAPIRET2.
    DATA T_RETURN TYPE TABLE OF BAPIRET2.

    IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = ER_ENTITY ).
    APPEND ER_ENTITY TO INPUT_TABLE.

    CALL FUNCTION 'ZPM_IMPORTA_ABAST_DO_SAAF'
      IMPORTING
        E_RETURN = RETURN
      TABLES
        T_INPUT  = INPUT_TABLE
        T_RETURN = T_RETURN.

    IF T_RETURN IS NOT INITIAL.
      DATA(CONTAINER_MESSAGE) = /IWBEP/IF_MGW_CONV_SRV_RUNTIME~GET_MESSAGE_CONTAINER( ).

*      LOOP AT T_RETURN INTO DATA(_RETURN).
*
*      CONTAINER_MESSAGE->ADD_MESSAGE_TEXT_ONLY(
*        EXPORTING
*          IV_MSG_TYPE               = 'E'
*          IV_MSG_TEXT               = _RETURN-MESSAGE
**          IV_ERROR_CATEGORY         =
**          IV_IS_LEADING_MESSAGE     = ABAP_TRUE
**          IV_ENTITY_TYPE            =
**          IT_KEY_TAB                =
**          IV_ADD_TO_RESPONSE_HEADER = ABAP_FALSE
**          IV_MESSAGE_TARGET         =
*      ).
*      ENDLOOP.

      CONTAINER_MESSAGE->ADD_MESSAGES_FROM_BAPI(
        EXPORTING
          IT_BAPI_MESSAGES          = T_RETURN
*          IV_ERROR_CATEGORY         =
*          IV_DETERMINE_LEADING_MSG  =
*          IV_ENTITY_TYPE            =
*          IT_KEY_TAB                =
*          IV_ADD_TO_RESPONSE_HEADER = ABAP_FALSE
      ).

      RAISE EXCEPTION TYPE /IWBEP/CX_MGW_BUSI_EXCEPTION
        EXPORTING
          TEXTID            = /IWBEP/CX_MGW_BUSI_EXCEPTION=>BUSINESS_ERROR
          MESSAGE_CONTAINER = CONTAINER_MESSAGE.
    ENDIF.
  ENDMETHOD.


  METHOD CAUSAMANUTENCAO_GET_ENTITYSET.
    CALL FUNCTION 'ZPM_EXPORT_B_CAUS_TO_SAAF'
* IMPORTING
*   E_RETURN              =
      TABLES
        WIT_B_CAUS_SAAF = ET_ENTITYSET.

  ENDMETHOD.


  METHOD CENTROCUSTO_GET_ENTITYSET.
    CALL FUNCTION 'ZPM_EXPORT_B_CENT_TO_SAAF'
* IMPORTING
*   E_RETURN              =
      TABLES
        WIT_B_CENT_SAAF = ET_ENTITYSET.

  ENDMETHOD.


  METHOD LOCALINSTALACAO_GET_ENTITYSET.
    CALL FUNCTION 'ZPM_EXPORT_LOC_AB_TO_SAAF'
* IMPORTING
*   E_RETURN              =
      TABLES
        WIT_LOC_AB_SAAF = ET_ENTITYSET.

  ENDMETHOD.


  METHOD MATERIALAUXILIAR_GET_ENTITYSET.
    CALL FUNCTION 'ZPM_EXPORT_M_PROD_TO_SAAF'
* IMPORTING
*   E_RETURN              =
      TABLES
        WIT_M_PROD_SAAF = ET_ENTITYSET.

  ENDMETHOD.


  method PLANOOPERACAO_GET_ENTITYSET.
CALL FUNCTION 'ZPM_EXPORT_B_PLAN_TO_SAAF'
* IMPORTING
*   E_RETURN              =
  TABLES
    WIT_B_PLAN_SAAF       = ET_ENTITYSET
          .

  endmethod.


  METHOD PONTOMEDICAO_GET_ENTITYSET.
    CALL FUNCTION 'ZPM_EXPORT_B_COMP_TO_SAAF'
* IMPORTING
*   E_RETURN              =
      TABLES
        WIT_B_COMP_SAAF = ET_ENTITYSET.

  ENDMETHOD.


  METHOD USUARIO_GET_ENTITYSET.
    CALL FUNCTION 'ZPM_EXPORT_M_USER_TO_SAAF'
* IMPORTING
*   E_RETURN              =
      TABLES
        WIT_M_USER_SAAF = ET_ENTITYSET.

  ENDMETHOD.


  METHOD VEICULOCOMPARTIM_GET_ENTITYSET.
    CALL FUNCTION 'ZPM_EXPORT_C_VEIC_TO_SAAF'
* IMPORTING
*   E_RETURN              =
      TABLES
        WIT_C_VEIC_SAAF = ET_ENTITYSET.

  ENDMETHOD.


  METHOD VEICULOOPERACAO_GET_ENTITYSET.
    CALL FUNCTION 'ZPM_EXPORT_R_VE_OP_TO_SAAF'
* IMPORTING
*   E_RETURN               =
      TABLES
        WIT_R_VE_OP_SAAF = ET_ENTITYSET.

  ENDMETHOD.


  METHOD VEICULO_GET_ENTITYSET.
    CALL FUNCTION 'ZPM_EXPORT_M_VEIC_TO_SAAF'
* IMPORTING
*   E_RETURN              =
      TABLES
        WIT_M_VEIC_SAAF = ET_ENTITYSET.

  ENDMETHOD.
ENDCLASS.
