class ZCL_NBIOBSP_EXTRACTION definition
  public
  final
  create public .

public section.

  interfaces ZIF_NBIOBSP_EXTRACTION .

  methods CONSTRUCTOR
    importing
      !I_OLE_EXTRACTION type OLE2_OBJECT
    raising
      ZCX_NBIOBSP .
protected section.
private section.
ENDCLASS.



CLASS ZCL_NBIOBSP_EXTRACTION IMPLEMENTATION.


  method CONSTRUCTOR.

    IF I_OLE_EXTRACTION IS INITIAL.
      RAISE EXCEPTION TYPE ZCX_NBIOBSP
        EXPORTING
          TEXTID = VALUE #( MSGID  = ZCX_NBIOBSP=>ZCX_REF_OBJ_OLE_EXTRACTION-MSGID
                            MSGNO  = ZCX_NBIOBSP=>ZCX_REF_OBJ_OLE_EXTRACTION-MSGNO )
          MSGID  = ZCX_NBIOBSP=>ZCX_REF_OBJ_OLE_EXTRACTION-MSGID
          MSGNO  = ZCX_NBIOBSP=>ZCX_REF_OBJ_OLE_EXTRACTION-MSGNO
          MSGTY  = 'E'.
    ENDIF.

    ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION = I_OLE_EXTRACTION.

  endmethod.


  METHOD ZIF_NBIOBSP_EXTRACTION~CAPTURE.

    R_EXTRACTION = ME.
    CALL METHOD OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'Capture' EXPORTING #1 = I_NPURPOSE.

    IF ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORCODE( )->ERRORCODE IS NOT INITIAL.

      ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORDESCRIPTION( ).

      SY-MSGV2 = ME->ZIF_NBIOBSP_EXTRACTION~ERRORCODE.
      CONDENSE SY-MSGV2 NO-GAPS.

      RAISE EXCEPTION TYPE ZCX_NBIOBSP
        EXPORTING
          TEXTID = VALUE #( MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
                            MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
                            ATTR1  = 'ZIF_NBIOBSP_EXTRACTION~CAPTURE'
                            ATTR2  = CONV #( SY-MSGV2 )
                            ATTR3  = ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION )
          MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
          MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
          MSGTY  = 'E'
          MSGV1  = 'ZIF_NBIOBSP_EXTRACTION~CAPTURE'
          MSGV2  = SY-MSGV2
          MSGV3  = CONV #( ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION ).
    ENDIF.

  ENDMETHOD.


  method ZIF_NBIOBSP_EXTRACTION~GET_ERRORCODE.

    R_EXTRACTION = ME.
    GET PROPERTY OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'ErrorCode' = ME->ZIF_NBIOBSP_EXTRACTION~ERRORCODE.
    E_ERRORCODE = ME->ZIF_NBIOBSP_EXTRACTION~ERRORCODE.

  endmethod.


  method ZIF_NBIOBSP_EXTRACTION~GET_ERRORDESCRIPTION.

    R_EXTRACTION = ME.
    GET PROPERTY OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'ErrorDescription' = ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION.
    E_ERRORDESCRIPTION = ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION.

  endmethod.


  METHOD ZIF_NBIOBSP_EXTRACTION~GET_FIR.

    R_EXTRACTION = ME.
    GET PROPERTY OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'FIR' = ME->ZIF_NBIOBSP_EXTRACTION~FIR.
    E_FIR = ME->ZIF_NBIOBSP_EXTRACTION~FIR.

  ENDMETHOD.


  method ZIF_NBIOBSP_EXTRACTION~GET_TEXTENCODEFIR.

    R_EXTRACTION = ME.
    GET PROPERTY OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'TextEncodeFIR' = ME->ZIF_NBIOBSP_EXTRACTION~TEXTENCODEFIR.
    E_TEXTENCODEFIR = ME->ZIF_NBIOBSP_EXTRACTION~TEXTENCODEFIR.

  endmethod.


  METHOD ZIF_NBIOBSP_EXTRACTION~SET_FINGERWND.

    R_EXTRACTION = ME.
    SET PROPERTY OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'FingerWnd' = I_FINGERWND.

    IF ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORCODE( )->ERRORCODE IS NOT INITIAL.

      ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORDESCRIPTION( ).

      SY-MSGV2 = ME->ZIF_NBIOBSP_EXTRACTION~ERRORCODE.
      CONDENSE SY-MSGV2 NO-GAPS.

      RAISE EXCEPTION TYPE ZCX_NBIOBSP
        EXPORTING
          TEXTID = VALUE #( MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
                            MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
                            ATTR1  = 'ZIF_NBIOBSP_EXTRACTION~SET_FINGERWND'
                            ATTR2  = CONV #( SY-MSGV2 )
                            ATTR3  = ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION )
          MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
          MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
          MSGTY  = 'E'
          MSGV1  = 'ZIF_NBIOBSP_EXTRACTION~SET_FINGERWND'
          MSGV2  = SY-MSGV2
          MSGV3  = CONV #( ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION ).
    ENDIF.

  ENDMETHOD.


  method ZIF_NBIOBSP_EXTRACTION~SET_FPBACKCOLOR.

    R_EXTRACTION = ME.
    SET PROPERTY OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'FPBackColor' = I_FPBACKCOLOR.

    IF ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORCODE( )->ERRORCODE IS NOT INITIAL.

      ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORDESCRIPTION( ).

      SY-MSGV2 = ME->ZIF_NBIOBSP_EXTRACTION~ERRORCODE.
      CONDENSE SY-MSGV2 NO-GAPS.

      RAISE EXCEPTION TYPE ZCX_NBIOBSP
        EXPORTING
          TEXTID = VALUE #( MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
                            MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
                            ATTR1  = 'ZIF_NBIOBSP_EXTRACTION~SET_FPBACKCOLOR'
                            ATTR2  = CONV #( SY-MSGV2 )
                            ATTR3  = ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION )
          MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
          MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
          MSGTY  = 'E'
          MSGV1  = 'ZIF_NBIOBSP_EXTRACTION~SET_FPBACKCOLOR'
          MSGV2  = SY-MSGV2
          MSGV3  = CONV #( ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION ).
    ENDIF.

  endmethod.


  METHOD ZIF_NBIOBSP_EXTRACTION~SET_FPFORECOLOR.

    R_EXTRACTION = ME.
    SET PROPERTY OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'FPForeColor' = I_FPFORECOLOR.

    IF ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORCODE( )->ERRORCODE IS NOT INITIAL.

      ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORDESCRIPTION( ).

      SY-MSGV2 = ME->ZIF_NBIOBSP_EXTRACTION~ERRORCODE.
      CONDENSE SY-MSGV2 NO-GAPS.

      RAISE EXCEPTION TYPE ZCX_NBIOBSP
        EXPORTING
          TEXTID = VALUE #( MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
                            MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
                            ATTR1  = 'ZIF_NBIOBSP_EXTRACTION~SET_FPFORECOLOR'
                            ATTR2  = CONV #( SY-MSGV2 )
                            ATTR3  = ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION )
          MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
          MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
          MSGTY  = 'E'
          MSGV1  = 'ZIF_NBIOBSP_EXTRACTION~SET_FPFORECOLOR'
          MSGV2  = SY-MSGV2
          MSGV3  = CONV #( ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION ).
    ENDIF.

  ENDMETHOD.


  METHOD ZIF_NBIOBSP_EXTRACTION~SET_WINDOWOPTION.

    R_EXTRACTION = ME.
    CALL METHOD OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'Set_WindowOption' EXPORTING #1 = I_WINDOW_STYLE.

    IF ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORCODE( )->ERRORCODE IS NOT INITIAL.

      ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORDESCRIPTION( ).

      SY-MSGV2 = ME->ZIF_NBIOBSP_EXTRACTION~ERRORCODE.
      CONDENSE SY-MSGV2 NO-GAPS.

      RAISE EXCEPTION TYPE ZCX_NBIOBSP
        EXPORTING
          TEXTID = VALUE #( MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
                            MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
                            ATTR1  = 'ZIF_NBIOBSP_EXTRACTION~SET_WINDOWOPTION'
                            ATTR2  = CONV #( SY-MSGV2 )
                            ATTR3  = ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION )
          MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
          MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
          MSGTY  = 'E'
          MSGV1  = 'ZIF_NBIOBSP_EXTRACTION~SET_WINDOWOPTION'
          MSGV2  = SY-MSGV2
          MSGV3  = CONV #( ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION ).
    ENDIF.

  ENDMETHOD.


  METHOD ZIF_NBIOBSP_EXTRACTION~SET_WINDOWSTYLE.

    R_EXTRACTION = ME.
    SET PROPERTY OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'WindowStyle' = I_WINDOW_STYLE.
    "CALL METHOD OF ME->ZIF_NBIOBSP_EXTRACTION~EXTRACTION 'Set_WindowStyle' EXPORTING #1 = I_WINDOW_STYLE.

    IF ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORCODE( )->ERRORCODE IS NOT INITIAL.

      ME->ZIF_NBIOBSP_EXTRACTION~GET_ERRORDESCRIPTION( ).

      SY-MSGV2 = ME->ZIF_NBIOBSP_EXTRACTION~ERRORCODE.
      CONDENSE SY-MSGV2 NO-GAPS.

      RAISE EXCEPTION TYPE ZCX_NBIOBSP
        EXPORTING
          TEXTID = VALUE #( MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
                            MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
                            ATTR1  = 'ZIF_NBIOBSP_EXTRACTION~SET_WINDOWSTYLE'
                            ATTR2  = CONV #( SY-MSGV2 )
                            ATTR3  = ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION )
          MSGID  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGID
          MSGNO  = ZCX_NBIOBSP=>ZCX_ERRO_METODO-MSGNO
          MSGTY  = 'E'
          MSGV1  = 'ZIF_NBIOBSP_EXTRACTION~SET_WINDOWSTYLE'
          MSGV2  = SY-MSGV2
          MSGV3  = CONV #( ME->ZIF_NBIOBSP_EXTRACTION~ERRORDESCRIPTION ).
    ENDIF.

  ENDMETHOD.
ENDCLASS.
