class ZCL_LER_URL definition
  public
  final
  create public .

*"* public components of class ZCL_LER_URL
*"* do not include other source files here!!!
public section.

  class-methods LER_URL
    importing
      !I_URL type STRING
    returning
      value(E_TEXTO) type STRING
    exceptions
      ARGUMENT_NOT_FOUND
      PLUGIN_NOT_ACTIVE
      INTERNAL_ERROR
      HTTP_COMMUNICATION_FAILURE
      HTTP_INVALID_STATE
      HTTP_PROCESSING_FAILED
      HTTP_INVALID_TIMEOUT
      OUTROS .
protected section.
*"* protected components of class ZCL_LER_URL
*"* do not include other source files here!!!
private section.
*"* private components of class ZCL_LER_URL
*"* do not include other source files here!!!
ENDCLASS.



CLASS ZCL_LER_URL IMPLEMENTATION.


METHOD LER_URL.

  DATA: HTML  TYPE REF TO IF_HTTP_CLIENT.

  CALL METHOD CL_HTTP_CLIENT=>CREATE_BY_URL
    EXPORTING
      URL                = I_URL
    IMPORTING
      CLIENT             = HTML
    EXCEPTIONS
      ARGUMENT_NOT_FOUND = 1
      PLUGIN_NOT_ACTIVE  = 2
      INTERNAL_ERROR     = 3
      OTHERS             = 4.

  CASE SY-SUBRC.
    WHEN 1.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING ARGUMENT_NOT_FOUND.
    WHEN 2.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING PLUGIN_NOT_ACTIVE.
    WHEN 3.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING INTERNAL_ERROR.
    WHEN 4.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING OUTROS.
  ENDCASE.

  CALL METHOD HTML->SEND
    EXCEPTIONS
      HTTP_COMMUNICATION_FAILURE = 1
      HTTP_INVALID_STATE         = 2
      HTTP_PROCESSING_FAILED     = 3
      HTTP_INVALID_TIMEOUT       = 4
      OTHERS                     = 5.

  CASE SY-SUBRC.
    WHEN 1.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING HTTP_COMMUNICATION_FAILURE.
    WHEN 2.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING HTTP_INVALID_STATE.
    WHEN 3.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING HTTP_PROCESSING_FAILED.
    WHEN 4.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING HTTP_INVALID_TIMEOUT.
    WHEN 5.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING OUTROS.
  ENDCASE.

  CALL METHOD HTML->RECEIVE
    EXCEPTIONS
      HTTP_COMMUNICATION_FAILURE = 1
      HTTP_INVALID_STATE         = 2
      HTTP_PROCESSING_FAILED     = 3.

  CASE SY-SUBRC.
    WHEN 1.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING HTTP_COMMUNICATION_FAILURE.
    WHEN 2.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING HTTP_INVALID_STATE.
    WHEN 3.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING HTTP_PROCESSING_FAILED.
  ENDCASE.

  E_TEXTO = HTML->RESPONSE->GET_CDATA( ).

  HTML->CLOSE( ).

ENDMETHOD.
ENDCLASS.
