*&---------------------------------------------------------------------*
*& Report  ZCOPY_ANEXO_ZGL026
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZCOPY_ANEXO_ZGL026.
TYPES: BEGIN OF TY_CARGA,
         BUKRS TYPE BUKRS,
         MONAT TYPE MONAT,
         GJAHR TYPE GJAHR,
         SAKNR TYPE SAKNR,
       END OF TY_CARGA.

DATA GT_PLANILHA LIKE STANDARD TABLE OF ALSMEX_TABLINE.
DATA GT_CARGA    TYPE TABLE OF TY_CARGA.
DATA GT_SERVICES TYPE TGOS_SELS.
DATA WL_CARGA    TYPE TY_CARGA.
DATA LS_SOURCE   TYPE SIBFLPORB.
DATA LS_TARGET   TYPE SIBFLPORB.
DATA LS_SERVICE  TYPE SGOS_SELS.
DATA ANEXOS      TYPE TABLE OF BDN_CON.

PARAMETERS P_FILE TYPE SDBA_A_NAM.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.

  CALL FUNCTION 'WS_FILENAME_GET'
    EXPORTING
      DEF_FILENAME     = ' '
      DEF_PATH         = P_FILE
      MASK             = ',*.xlsx.'
      MODE             = 'O'
      TITLE            = 'Arquivo a importar'
    IMPORTING
      FILENAME         = P_FILE
    EXCEPTIONS
      INV_WINSYS       = 01
      NO_BATCH         = 02
      SELECTION_CANCEL = 03
      SELECTION_ERROR  = 04.

START-OF-SELECTION.

  CALL FUNCTION 'ALSM_EXCEL_TO_INTERNAL_TABLE'
    EXPORTING
      FILENAME                = P_FILE
      I_BEGIN_COL             = 1
      I_BEGIN_ROW             = 2
      I_END_COL               = 55
      I_END_ROW               = 10000
    TABLES
      INTERN                  = GT_PLANILHA
    EXCEPTIONS
      INCONSISTENT_PARAMETERS = 1
      UPLOAD_OLE              = 2
      OTHERS                  = 3.

  LS_SERVICE-SIGN   = 'I'.
  LS_SERVICE-OPTION = 'EQ'.
  LS_SERVICE-LOW    = 'PCATTA_CREA'.
  APPEND LS_SERVICE TO GT_SERVICES.

  LOOP AT GT_PLANILHA INTO DATA(WL_PLANILHA).

    CASE WL_PLANILHA-COL.
      WHEN 1.
        WL_CARGA-BUKRS = WL_PLANILHA-VALUE.
        PERFORM F_ADD_ZERO CHANGING WL_CARGA-BUKRS.
      WHEN 2.
        WL_CARGA-GJAHR = WL_PLANILHA-VALUE.
        PERFORM F_ADD_ZERO CHANGING WL_CARGA-GJAHR.
      WHEN 3.
        WL_CARGA-MONAT = WL_PLANILHA-VALUE.
        PERFORM F_ADD_ZERO CHANGING WL_CARGA-MONAT.
      WHEN 4.
        WL_CARGA-SAKNR = WL_PLANILHA-VALUE.
        PERFORM F_ADD_ZERO CHANGING WL_CARGA-SAKNR.
    ENDCASE.

    AT END OF ROW.

      "//Source
      LS_SOURCE-INSTID = |{ WL_CARGA-BUKRS }{ WL_CARGA-GJAHR }{ WL_CARGA-MONAT }{ WL_CARGA-SAKNR }|.
      LS_SOURCE-TYPEID = 'ZGL026'.
      LS_SOURCE-CATID  = 'BO'.

      "//Target
      LS_TARGET-INSTID = |{ WL_CARGA-MONAT }{ WL_CARGA-GJAHR }{ WL_CARGA-BUKRS }{ WL_CARGA-SAKNR }|.
      LS_TARGET-TYPEID = 'ZGL026'.
      LS_TARGET-CATID  = 'BO'.

      CALL FUNCTION 'BDS_GOS_CONNECTIONS_GET'
        EXPORTING
          CLASSNAME          = 'ZGL026'
          OBJKEY             = LS_SOURCE-INSTID
          CLIENT             = SY-MANDT
        TABLES
          GOS_CONNECTIONS    = ANEXOS
        EXCEPTIONS
          NO_OBJECTS_FOUND   = 1
          INTERNAL_ERROR     = 2
          INTERNAL_GOS_ERROR = 3
          OTHERS             = 4.

      IF ( ANEXOS IS NOT INITIAL ).

        CALL METHOD CL_GOS_SERVICE_TOOLS=>COPY_LINKED_OBJECTS
          EXPORTING
            IS_SOURCE            = LS_SOURCE
            IS_TARGET            = LS_TARGET
            IT_SERVICE_SELECTION = GT_SERVICES.

        COMMIT WORK.

        CALL METHOD CL_GOS_SERVICE_TOOLS=>DELETE_LINKED_OBJECTS
          EXPORTING
            IS_OBJECT = VALUE #( OBJKEY  = LS_SOURCE-INSTID
                                 OBJTYPE = LS_SOURCE-TYPEID ).
        COMMIT WORK.

        CLEAR ANEXOS.
      ENDIF.

    ENDAT.

  ENDLOOP.

FORM F_ADD_ZERO CHANGING VALUE.
  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT  = VALUE
    IMPORTING
      OUTPUT = VALUE.
ENDFORM.
