PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCOT0003 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCOT0003-TKNUM .
    FIELD ZCOT0003-FKNUM .
    FIELD ZCOT0003-EBELN .
    FIELD ZCOT0003-NUMERADOR .
    FIELD ZCOT0003-BELNR .
    FIELD ZCOT0003-EBELP .
    FIELD ZCOT0003-LBLNI .
    FIELD ZCOT0003-ADD03 .
    FIELD ZCOT0003-SHTYP .
    FIELD ZCOT0003-DT_MOV .
    FIELD ZCOT0003-DT_CHEGADA .
    FIELD ZCOT0003-MATNR .
    FIELD ZCOT0003-PESO_BRUTO .
    FIELD ZCOT0003-PESO_CHEGADA .
    FIELD ZCOT0003-EXTI1 .
    FIELD ZCOT0003-WERKS .
    FIELD ZCOT0003-LGORT .
    FIELD ZCOT0003-CHARG .
    FIELD ZCOT0003-TCODE .
    FIELD ZCOT0003-VLR_APROPR .
    FIELD ZCOT0003-DOC_APROPR .
    FIELD ZCOT0003-DT_ATUAL .
    FIELD ZCOT0003-HORA_ATUL .
    FIELD ZCOT0003-USNAM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCOT0003-TKNUM .
    FIELD ZCOT0003-FKNUM .
    FIELD ZCOT0003-EBELN .
    FIELD ZCOT0003-NUMERADOR .
    FIELD ZCOT0003-BELNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
