CLASS ZCX_PEDIDO_COMPRA DEFINITION
  PUBLIC
  INHERITING FROM ZCX_ERROR
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CONSTANTS:
      BEGIN OF ZCX_PEDIDO_NAO_ENCONTRADO,
        MSGID TYPE SYMSGID VALUE 'ZMMPED',
        MSGNO TYPE SYMSGNO VALUE '003',
        ATTR1 TYPE SCX_ATTRNAME VALUE 'MSGV1',
        ATTR2 TYPE SCX_ATTRNAME VALUE '',
        ATTR3 TYPE SCX_ATTRNAME VALUE '',
        ATTR4 TYPE SCX_ATTRNAME VALUE '',
      END OF ZCX_PEDIDO_NAO_ENCONTRADO .
    CONSTANTS:
      BEGIN OF ZCX_PEDIDO_TIPO_FRETE_ERR,
        MSGID TYPE SYMSGID VALUE 'ZMMPED',
        MSGNO TYPE SYMSGNO VALUE '014',
        ATTR1 TYPE SCX_ATTRNAME VALUE '',
        ATTR2 TYPE SCX_ATTRNAME VALUE '',
        ATTR3 TYPE SCX_ATTRNAME VALUE '',
        ATTR4 TYPE SCX_ATTRNAME VALUE '',
      END OF ZCX_PEDIDO_TIPO_FRETE_ERR .
    CONSTANTS:
      BEGIN OF ZCX_PEDIDO_ERRO_CONV_UNID,
        MSGID TYPE SYMSGID VALUE 'ZMMPED',
        MSGNO TYPE SYMSGNO VALUE '005',
        ATTR1 TYPE SCX_ATTRNAME VALUE 'MSGV1',
        ATTR2 TYPE SCX_ATTRNAME VALUE 'MSGV2',
        ATTR3 TYPE SCX_ATTRNAME VALUE 'MSGV3',
        ATTR4 TYPE SCX_ATTRNAME VALUE '',
      END OF ZCX_PEDIDO_ERRO_CONV_UNID .
    CONSTANTS:
      BEGIN OF ZCX_SOLICITACAO_NAO_ENCONTRADO,
        MSGID TYPE SYMSGID VALUE 'ZMMPED',
        MSGNO TYPE SYMSGNO VALUE '029',
        ATTR1 TYPE SCX_ATTRNAME VALUE 'MSGV1',
        ATTR2 TYPE SCX_ATTRNAME VALUE 'MSGV2',
        ATTR3 TYPE SCX_ATTRNAME VALUE 'MSGV3',
        ATTR4 TYPE SCX_ATTRNAME VALUE '',
      END OF ZCX_SOLICITACAO_NAO_ENCONTRADO.
    METHODS CONSTRUCTOR
      IMPORTING
        !TEXTID    LIKE IF_T100_MESSAGE=>T100KEY OPTIONAL
        !PREVIOUS  LIKE PREVIOUS OPTIONAL
        !MSGID     TYPE SYST_MSGID OPTIONAL
        !MSGNO     TYPE SYST_MSGNO OPTIONAL
        !MSGTY     TYPE SYST_MSGTY OPTIONAL
        !MSGV1     TYPE SYST_MSGV OPTIONAL
        !MSGV2     TYPE SYST_MSGV OPTIONAL
        !MSGV3     TYPE SYST_MSGV OPTIONAL
        !MSGV4     TYPE SYST_MSGV OPTIONAL
        !TRANSACAO TYPE TCODE OPTIONAL .
    METHODS PUBLISHED_ERRO .
protected section.
private section.
ENDCLASS.



CLASS ZCX_PEDIDO_COMPRA IMPLEMENTATION.


  method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
PREVIOUS = PREVIOUS
MSGID = MSGID
MSGNO = MSGNO
MSGTY = MSGTY
MSGV1 = MSGV1
MSGV2 = MSGV2
MSGV3 = MSGV3
MSGV4 = MSGV4
TRANSACAO = TRANSACAO
.
clear me->textid.
if textid is initial.
  IF_T100_MESSAGE~T100KEY = IF_T100_MESSAGE=>DEFAULT_TEXTID.
else.
  IF_T100_MESSAGE~T100KEY = TEXTID.
endif.
  endmethod.


  method PUBLISHED_ERRO.
  endmethod.
ENDCLASS.
