
PROCESS BEFORE OUTPUT.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TABDISP'
  MODULE TABDISP_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TABDISP_CHANGE_COL_ATTR.
  LOOP AT   IT_DISP
       INTO ZDCO_NOTA
       WITH CONTROL TABDISP
       CURSOR TABDISP-CURRENT_LINE.
*&SPWIZARD:   MODULE TABDISP_CHANGE_FIELD_ATTR
  ENDLOOP.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TABVINC'
  MODULE TABVINC_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TABVINC_CHANGE_COL_ATTR.
  LOOP AT   IT_VINC
       INTO ZDCO_NOTA_VINC
       WITH CONTROL TABVINC
       CURSOR TABVINC-CURRENT_LINE.
*&SPWIZARD:   MODULE TABVINC_CHANGE_FIELD_ATTR
  ENDLOOP.

  MODULE status_0001.

PROCESS AFTER INPUT.

*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TABDISP'
  LOOP AT IT_DISP.
    CHAIN.
      FIELD ZDCO_NOTA-DOCNUM.
      FIELD ZDCO_NOTA-ITMNUM.
      FIELD ZDCO_NOTA-DOCDATTXT.
      FIELD ZDCO_NOTA-SERIES.
      FIELD ZDCO_NOTA-NFNUM.
      FIELD ZDCO_NOTA-BRANCH.
      FIELD ZDCO_NOTA-MENGE.
    endchain.
    FIELD ZDCO_NOTA-MARK
      MODULE TABDISP_MARK ON REQUEST.
  ENDLOOP.
  MODULE TABDISP_USER_COMMAND.
*&SPWIZARD: MODULE TABDISP_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TABDISP_CHANGE_COL_ATTR.

*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TABVINC'
  LOOP AT IT_VINC.
    CHAIN.
      FIELD ZDCO_NOTA_VINC-DOCNUM.
      FIELD ZDCO_NOTA_VINC-ITMNUM.
      FIELD ZDCO_NOTA_VINC-DOCDATTXT.
      FIELD ZDCO_NOTA_VINC-SERIES.
      FIELD ZDCO_NOTA_VINC-NFNUM.
      FIELD ZDCO_NOTA_VINC-BRANCH.
      FIELD ZDCO_NOTA_VINC-MENGE.
    endchain.
    FIELD ZDCO_NOTA_VINC-MARK
      MODULE TABVINC_MARK ON REQUEST.
  ENDLOOP.
  MODULE TABVINC_USER_COMMAND.
*&SPWIZARD: MODULE TABVINC_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TABVINC_CHANGE_COL_ATTR.

  MODULE user_command_0001.
