FUNCTION ZENQUEUE_DOC_ELETRONICO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(DOCNUM) TYPE  J_1BDOCNUM
*"     REFERENCE(_SCOPE) DEFAULT '2'
*"     REFERENCE(_WAIT) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT SPACE
*"  EXCEPTIONS
*"      FOREIGN_LOCK
*"      SYSTEM_FAILURE
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __WAIT      TYPE DDENQWAIT.

  __WAIT = _WAIT.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_J_1BNFDOC,
          MANDT    TYPE SY-MANDT,
          DOCNUM   TYPE J_1BDOCNUM,
        END OF %A_J_1BNFDOC.

  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_J_1BNFDOC.

  MOVE: DOCNUM TO %A_J_1BNFDOC-DOCNUM.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_J_1BNFDOC-MANDT.
  ENDIF.

* Preencher tab.bloqueio:
  __SEQTA_TAB-GNAME = 'J_1BNFDOC'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG = %A_J_1BNFDOC.
  APPEND __SEQTA_TAB.

* Fixar bloqueio:
  PERFORM SEND_ENQUEUE(SAPLSENA)
   TABLES __SEQTA_TAB
    USING '1' __SCOPE __WAIT ' ' 'EJ_1BNFDOC' _COLLECT.

ENDFUNCTION.
