PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZDOC_MEMO_RESP-BUKRS .
    FIELD ZDOC_MEMO_RESP-BRANCH .
    FIELD ZDOC_MEMO_RESP-LIFNR .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZDOC_MEMO_RESP-BUKRS .
    FIELD ZDOC_MEMO_RESP-BRANCH .
  module detail_pai.
 endchain.
