"Name: \TY:CL_J_1BNFE_CF_SERVICE_COMM\ME:GET_RESPONSE_FROM_CLOUD\SE:END\EI
ENHANCEMENT 0 ZDRC_CLOSE_HTTP_CONNECTION.

    SELECT SINGLE *
      FROM TVARVC INTO @DATA(LWA_TVARV)
     WHERE NAME EQ 'DRC_PROG_CLOSE_CONNECTION'
       AND LOW  EQ @SY-CPROG.

    IF SY-SUBRC EQ 0.
      me->close_http_connection( ).
    ENDIF.

ENDENHANCEMENT.
