"Name: \TY:CL_NFE_DATE_TIME_UTILS\IN:IF_NFE_DATE_TIME_UTILS\ME:FIND_TIME_ZONE_BY_BRANCH\SE:BEGIN\EI
ENHANCEMENT 0 ZDRC_TIMEZONE_FILIAL_CTE.

   DATA: V_TIME_ZONE TYPE TZNZONE.

   CALL FUNCTION 'Z_FUSO_HORARIO_FILIAL'
     EXPORTING
       I_BUKRS    = iv_company_code
       I_BRANCH   = iv_business_place
     IMPORTING
       E_TZNZONE  = V_TIME_ZONE.

   IF V_TIME_ZONE IS NOT INITIAL.
     rv_time_zone = V_TIME_ZONE.
     exit.
   ENDIF.

ENDENHANCEMENT.
