FUNCTION ZDUE_GERAR_NR_RUC_WITH_SCREEN .
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_DADOS_GERACAO_RUC) TYPE  ZDE_DADOS_GERACAO_RUC
*"  EXPORTING
*"     REFERENCE(E_NUMERO_RUC) TYPE  ZDE_NUMERO_RUC
*"----------------------------------------------------------------------

  CLEAR: E_NUMERO_RUC, GWA_DADOS_GERACAO_RUC, GVA_NUMERO_RUC_GERADO_SEL.

  MOVE-CORRESPONDING I_DADOS_GERACAO_RUC TO GWA_DADOS_GERACAO_RUC.

  "PERFORM F_SELECIONAR_DADOS_0201.

  CALL SCREEN 0201 STARTING AT 10 02 ENDING AT 170 25.

  E_NUMERO_RUC = GVA_NUMERO_RUC_GERADO_SEL. "Retornar RUC Selecionada/Gerada

ENDFUNCTION.
