PROCESS BEFORE OUTPUT.

  MODULE STATUS_0100.

  CALL SUBSCREEN: SUB0100 INCLUDING SY-REPID DUE_DYNNR_000.

PROCESS AFTER INPUT.

  MODULE: USER_COMMAND_0100,
          TAB_ACTIVE_DUE.

  CALL SUBSCREEN: SUB0100.
