*         20020109
*-------------------------------------------------------------------*
*         Gerado por      SPROCWORK
*         Data:           26.10.09
*         Hora            14:26.05
*-------------------------------------------------------------------*

*-------------------------------------------------------------------*
*         Include fuer SAPFGVTR
*         Der Include ist generiert vom Programm RGUGVTR0
*         --> Bilanzkonten in T_BS_xxxxx
*             GuV-Konten in T_PL_xxxxx
*-------------------------------------------------------------------*
DATA: BEGIN OF T_BS_COFIS                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA RHRKFT LIKE GLU1-RHRKFT .
DATA ROBART LIKE GLU1-ROBART .
DATA RSCOPE LIKE GLU1-RSCOPE .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RFAREA LIKE GLU1-RFAREA .
DATA RFUND LIKE GLU1-RFUND .
DATA RGRANT_NBR LIKE GLU1-RGRANT_NBR .
DATA RLOGSYS LIKE GLU1-RLOGSYS .
DATA VRGNG LIKE GLU1-VRGNG .
DATA KOKRS LIKE GLU1-KOKRS .
DATA OCLNT LIKE GLU1-OCLNT .
DATA WRTTP LIKE GLU1-WRTTP .
DATA ACTIV LIKE GLU1-ACTIV .
DATA SBUKRS LIKE GLU1-SBUKRS .
DATA SACCT LIKE GLU1-SACCT .
DATA SHRKFT LIKE GLU1-SHRKFT .
DATA SOBART LIKE GLU1-SOBART .
DATA SSCOPE LIKE GLU1-SSCOPE .
DATA SBUSA LIKE GLU1-SBUSA .
DATA SFAREA LIKE GLU1-SFAREA .
DATA SFUND LIKE GLU1-SFUND .
DATA SGRANT_NBR LIKE GLU1-SGRANT_NBR .
DATA SLOGSYS LIKE GLU1-SLOGSYS .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_BS_COFIS                         .

DATA: BEGIN OF T_PL_COFIS                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA RHRKFT LIKE GLU1-RHRKFT .
DATA ROBART LIKE GLU1-ROBART .
DATA RSCOPE LIKE GLU1-RSCOPE .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RFAREA LIKE GLU1-RFAREA .
DATA RFUND LIKE GLU1-RFUND .
DATA RGRANT_NBR LIKE GLU1-RGRANT_NBR .
DATA RLOGSYS LIKE GLU1-RLOGSYS .
DATA VRGNG LIKE GLU1-VRGNG .
DATA KOKRS LIKE GLU1-KOKRS .
DATA OCLNT LIKE GLU1-OCLNT .
DATA WRTTP LIKE GLU1-WRTTP .
DATA ACTIV LIKE GLU1-ACTIV .
DATA SBUKRS LIKE GLU1-SBUKRS .
DATA SACCT LIKE GLU1-SACCT .
DATA SHRKFT LIKE GLU1-SHRKFT .
DATA SOBART LIKE GLU1-SOBART .
DATA SSCOPE LIKE GLU1-SSCOPE .
DATA SBUSA LIKE GLU1-SBUSA .
DATA SFAREA LIKE GLU1-SFAREA .
DATA SFUND LIKE GLU1-SFUND .
DATA SGRANT_NBR LIKE GLU1-SGRANT_NBR .
DATA SLOGSYS LIKE GLU1-SLOGSYS .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_PL_COFIS                         .

DATA: BEGIN OF T_BS_ECMCA                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RCOMP LIKE GLU1-RCOMP .
DATA RDIMEN LIKE GLU1-RDIMEN .
DATA RBUNIT LIKE GLU1-RBUNIT .
DATA RITCLG LIKE GLU1-RITCLG .
DATA RITEM LIKE GLU1-RITEM .
DATA RBUPTR LIKE GLU1-RBUPTR .
DATA RCONGR LIKE GLU1-RCONGR .
DATA ROBUKRS LIKE GLU1-ROBUKRS .
DATA RPFLG LIKE GLU1-RPFLG .
DATA RTFLG LIKE GLU1-RTFLG .
DATA SITYP LIKE GLU1-SITYP .
DATA SUBIT LIKE GLU1-SUBIT .
DATA PLEVL LIKE GLU1-PLEVL .
DATA DOCTY LIKE GLU1-DOCTY .
DATA YRACQ LIKE GLU1-YRACQ .
DATA PRACQ LIKE GLU1-PRACQ .
DATA COICU LIKE GLU1-COICU .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA UPDHP LIKE GLU1-UPDHP .
DATA: END OF T_BS_ECMCA                         .

DATA: BEGIN OF T_PL_ECMCA                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RCOMP LIKE GLU1-RCOMP .
DATA RDIMEN LIKE GLU1-RDIMEN .
DATA RBUNIT LIKE GLU1-RBUNIT .
DATA RITCLG LIKE GLU1-RITCLG .
DATA RITEM LIKE GLU1-RITEM .
DATA RBUPTR LIKE GLU1-RBUPTR .
DATA RCONGR LIKE GLU1-RCONGR .
DATA ROBUKRS LIKE GLU1-ROBUKRS .
DATA RPFLG LIKE GLU1-RPFLG .
DATA RTFLG LIKE GLU1-RTFLG .
DATA SITYP LIKE GLU1-SITYP .
DATA SUBIT LIKE GLU1-SUBIT .
DATA PLEVL LIKE GLU1-PLEVL .
DATA DOCTY LIKE GLU1-DOCTY .
DATA YRACQ LIKE GLU1-YRACQ .
DATA PRACQ LIKE GLU1-PRACQ .
DATA COICU LIKE GLU1-COICU .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_PL_ECMCA                         .

DATA: BEGIN OF T_BS_FAGLFLEXA                      OCCURS 0.
DATA RYEAR LIKE GLU1-RYEAR .
DATA ACTIV LIKE GLU1-ACTIV .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA AWTYP LIKE GLU1-AWTYP .
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RACCT LIKE GLU1-RACCT .
DATA COST_ELEM LIKE GLU1-COST_ELEM .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RCNTR LIKE GLU1-RCNTR .
DATA PRCTR LIKE GLU1-PRCTR .
DATA RFAREA LIKE GLU1-RFAREA .
DATA RBUSA LIKE GLU1-RBUSA .
DATA KOKRS LIKE GLU1-KOKRS .
DATA SEGMENT LIKE GLU1-SEGMENT .
DATA SCNTR LIKE GLU1-SCNTR .
DATA PPRCTR LIKE GLU1-PPRCTR .
DATA SFAREA LIKE GLU1-SFAREA .
DATA SBUSA LIKE GLU1-SBUSA .
DATA RASSC LIKE GLU1-RASSC .
DATA PSEGMENT LIKE GLU1-PSEGMENT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA GJAHR LIKE GLU1-GJAHR .
DATA BELNR LIKE GLU1-BELNR .
DATA BUZEI LIKE GLU1-BUZEI .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA OSL LIKE GLU1-OSL.
DATA MSL LIKE GLU1-MSL.
DATA TIMESTAMP LIKE GLU1-TIMESTAMP .
DATA: END OF T_BS_FAGLFLEXA                     .

DATA: BEGIN OF T_PL_FAGLFLEXA                      OCCURS 0.
DATA RYEAR LIKE GLU1-RYEAR .
DATA ACTIV LIKE GLU1-ACTIV .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA AWTYP LIKE GLU1-AWTYP .
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RACCT LIKE GLU1-RACCT .
DATA COST_ELEM LIKE GLU1-COST_ELEM .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RCNTR LIKE GLU1-RCNTR .
DATA PRCTR LIKE GLU1-PRCTR .
DATA RFAREA LIKE GLU1-RFAREA .
DATA RBUSA LIKE GLU1-RBUSA .
DATA KOKRS LIKE GLU1-KOKRS .
DATA SEGMENT LIKE GLU1-SEGMENT .
DATA SCNTR LIKE GLU1-SCNTR .
DATA PPRCTR LIKE GLU1-PPRCTR .
DATA SFAREA LIKE GLU1-SFAREA .
DATA SBUSA LIKE GLU1-SBUSA .
DATA RASSC LIKE GLU1-RASSC .
DATA PSEGMENT LIKE GLU1-PSEGMENT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA GJAHR LIKE GLU1-GJAHR .
DATA BELNR LIKE GLU1-BELNR .
DATA BUZEI LIKE GLU1-BUZEI .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA OSL LIKE GLU1-OSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_PL_FAGLFLEXA                     .

DATA: BEGIN OF T_BS_FBICRC001A                     OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RCOMP LIKE GLU1-RCOMP .
DATA ROBUKRS LIKE GLU1-ROBUKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA RASSC LIKE GLU1-RASSC .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RTYPE LIKE GLU1-RTYPE .
DATA RTCUR LIKE GLU1-RTCUR .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA: END OF T_BS_FBICRC001A                    .

DATA: BEGIN OF T_PL_FBICRC001A                     OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RCOMP LIKE GLU1-RCOMP .
DATA ROBUKRS LIKE GLU1-ROBUKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA RASSC LIKE GLU1-RASSC .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RTYPE LIKE GLU1-RTYPE .
DATA RTCUR LIKE GLU1-RTCUR .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA: END OF T_PL_FBICRC001A                    .

DATA: BEGIN OF T_BS_FBICRC002A                     OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RCOMP LIKE GLU1-RCOMP .
DATA ROBUKRS LIKE GLU1-ROBUKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA RASSC LIKE GLU1-RASSC .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RTYPE LIKE GLU1-RTYPE .
DATA RTCUR LIKE GLU1-RTCUR .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA: END OF T_BS_FBICRC002A                    .

DATA: BEGIN OF T_PL_FBICRC002A                     OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RCOMP LIKE GLU1-RCOMP .
DATA ROBUKRS LIKE GLU1-ROBUKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA RASSC LIKE GLU1-RASSC .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RTYPE LIKE GLU1-RTYPE .
DATA RTCUR LIKE GLU1-RTCUR .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA: END OF T_PL_FBICRC002A                    .

DATA: BEGIN OF T_BS_FILCA                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RCOMP LIKE GLU1-RCOMP .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RASSC LIKE GLU1-RASSC .
DATA ROBUKRS LIKE GLU1-ROBUKRS .
DATA RLEVL LIKE GLU1-RLEVL .
DATA DOCTY LIKE GLU1-DOCTY .
DATA RSUBD LIKE GLU1-RSUBD .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RYACQ LIKE GLU1-RYACQ .
DATA RPACQ LIKE GLU1-RPACQ .
DATA OCLNT LIKE GLU1-OCLNT .
DATA ADFLD1 LIKE GLU1-ADFLD1 .
DATA ADFLD2 LIKE GLU1-ADFLD2 .
DATA ADFLD3 LIKE GLU1-ADFLD3 .
DATA SCOMP LIKE GLU1-SCOMP .
DATA SACCT LIKE GLU1-SACCT .
DATA SBUSA LIKE GLU1-SBUSA .
DATA SASSC LIKE GLU1-SASSC .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA ASL LIKE GLU1-ASL.
DATA UPDHP LIKE GLU1-UPDHP .
DATA AUNIT LIKE GLU1-AUNIT .
DATA: END OF T_BS_FILCA                         .

DATA: BEGIN OF T_PL_FILCA                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RCOMP LIKE GLU1-RCOMP .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RASSC LIKE GLU1-RASSC .
DATA ROBUKRS LIKE GLU1-ROBUKRS .
DATA RLEVL LIKE GLU1-RLEVL .
DATA DOCTY LIKE GLU1-DOCTY .
DATA RSUBD LIKE GLU1-RSUBD .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RYACQ LIKE GLU1-RYACQ .
DATA RPACQ LIKE GLU1-RPACQ .
DATA OCLNT LIKE GLU1-OCLNT .
DATA ADFLD1 LIKE GLU1-ADFLD1 .
DATA ADFLD2 LIKE GLU1-ADFLD2 .
DATA ADFLD3 LIKE GLU1-ADFLD3 .
DATA SCOMP LIKE GLU1-SCOMP .
DATA SACCT LIKE GLU1-SACCT .
DATA SBUSA LIKE GLU1-SBUSA .
DATA SASSC LIKE GLU1-SASSC .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA ASL LIKE GLU1-ASL.
DATA: END OF T_PL_FILCA                         .

DATA: BEGIN OF T_BS_FMGLFLEXA                      OCCURS 0.
DATA RYEAR LIKE GLU1-RYEAR .
DATA ACTIV LIKE GLU1-ACTIV .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA AWTYP LIKE GLU1-AWTYP .
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RACCT LIKE GLU1-RACCT .
DATA COST_ELEM LIKE GLU1-COST_ELEM .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RBUSA LIKE GLU1-RBUSA .
DATA KOKRS LIKE GLU1-KOKRS .
DATA FIKRS LIKE GLU1-FIKRS .
DATA SFAREA LIKE GLU1-SFAREA .
DATA SBUSA LIKE GLU1-SBUSA .
DATA RASSC LIKE GLU1-RASSC .
DATA SFUND LIKE GLU1-SFUND .
DATA SGRANT_NBR LIKE GLU1-SGRANT_NBR .
DATA RFUND LIKE GLU1-RFUND .
DATA RGRANT_NBR LIKE GLU1-RGRANT_NBR .
DATA RFAREA LIKE GLU1-RFAREA .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA GJAHR LIKE GLU1-GJAHR .
DATA BELNR LIKE GLU1-BELNR .
DATA BUZEI LIKE GLU1-BUZEI .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA OSL LIKE GLU1-OSL.
DATA MSL LIKE GLU1-MSL.
DATA TIMESTAMP LIKE GLU1-TIMESTAMP .
DATA: END OF T_BS_FMGLFLEXA                     .

DATA: BEGIN OF T_PL_FMGLFLEXA                      OCCURS 0.
DATA RYEAR LIKE GLU1-RYEAR .
DATA ACTIV LIKE GLU1-ACTIV .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA AWTYP LIKE GLU1-AWTYP .
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RACCT LIKE GLU1-RACCT .
DATA COST_ELEM LIKE GLU1-COST_ELEM .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RBUSA LIKE GLU1-RBUSA .
DATA KOKRS LIKE GLU1-KOKRS .
DATA FIKRS LIKE GLU1-FIKRS .
DATA SFAREA LIKE GLU1-SFAREA .
DATA SBUSA LIKE GLU1-SBUSA .
DATA RASSC LIKE GLU1-RASSC .
DATA SFUND LIKE GLU1-SFUND .
DATA SGRANT_NBR LIKE GLU1-SGRANT_NBR .
DATA RFUND LIKE GLU1-RFUND .
DATA RGRANT_NBR LIKE GLU1-RGRANT_NBR .
DATA RFAREA LIKE GLU1-RFAREA .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA GJAHR LIKE GLU1-GJAHR .
DATA BELNR LIKE GLU1-BELNR .
DATA BUZEI LIKE GLU1-BUZEI .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA OSL LIKE GLU1-OSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_PL_FMGLFLEXA                     .

DATA: BEGIN OF T_BS_GLFUNCA                        OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RFAREA LIKE GLU1-RFAREA .
DATA OCLNT LIKE GLU1-OCLNT .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RASSC LIKE GLU1-RASSC .
DATA SBUKRS LIKE GLU1-SBUKRS .
DATA SACCT LIKE GLU1-SACCT .
DATA SBUSA LIKE GLU1-SBUSA .
DATA SFAREA LIKE GLU1-SFAREA .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_BS_GLFUNCA                       .

DATA: BEGIN OF T_PL_GLFUNCA                        OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RFAREA LIKE GLU1-RFAREA .
DATA OCLNT LIKE GLU1-OCLNT .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RASSC LIKE GLU1-RASSC .
DATA SBUKRS LIKE GLU1-SBUKRS .
DATA SACCT LIKE GLU1-SACCT .
DATA SBUSA LIKE GLU1-SBUSA .
DATA SFAREA LIKE GLU1-SFAREA .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_PL_GLFUNCA                       .

DATA: BEGIN OF T_BS_GLPCA                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RPRCTR LIKE GLU1-RPRCTR .
DATA RHOART LIKE GLU1-RHOART .
DATA RFAREA LIKE GLU1-RFAREA .
DATA RSCOPE LIKE GLU1-RSCOPE .
DATA KOKRS LIKE GLU1-KOKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA HRKFT LIKE GLU1-HRKFT .
DATA RASSC LIKE GLU1-RASSC .
DATA EPRCTR LIKE GLU1-EPRCTR .
DATA ACTIV LIKE GLU1-ACTIV .
DATA AFABE LIKE GLU1-AFABE .
DATA OCLNT LIKE GLU1-OCLNT .
DATA WERKS LIKE GLU1-WERKS .
DATA RMVCT LIKE GLU1-RMVCT .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA VERSA LIKE GLU1-VERSA .
DATA STAGR LIKE GLU1-STAGR .
DATA REP_MATNR LIKE GLU1-REP_MATNR .
DATA SBUKRS LIKE GLU1-SBUKRS .
DATA SPRCTR LIKE GLU1-SPRCTR .
DATA SHOART LIKE GLU1-SHOART .
DATA SFAREA LIKE GLU1-SFAREA .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_BS_GLPCA                         .

DATA: BEGIN OF T_PL_GLPCA                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RPRCTR LIKE GLU1-RPRCTR .
DATA RHOART LIKE GLU1-RHOART .
DATA RFAREA LIKE GLU1-RFAREA .
DATA RSCOPE LIKE GLU1-RSCOPE .
DATA KOKRS LIKE GLU1-KOKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA HRKFT LIKE GLU1-HRKFT .
DATA RASSC LIKE GLU1-RASSC .
DATA EPRCTR LIKE GLU1-EPRCTR .
DATA ACTIV LIKE GLU1-ACTIV .
DATA AFABE LIKE GLU1-AFABE .
DATA OCLNT LIKE GLU1-OCLNT .
DATA WERKS LIKE GLU1-WERKS .
DATA RMVCT LIKE GLU1-RMVCT .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA VERSA LIKE GLU1-VERSA .
DATA STAGR LIKE GLU1-STAGR .
DATA REP_MATNR LIKE GLU1-REP_MATNR .
DATA SBUKRS LIKE GLU1-SBUKRS .
DATA SPRCTR LIKE GLU1-SPRCTR .
DATA SHOART LIKE GLU1-SHOART .
DATA SFAREA LIKE GLU1-SFAREA .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_PL_GLPCA                         .

DATA: BEGIN OF T_BS_GLS0                           OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA BUKRS LIKE GLU1-BUKRS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RTCUR LIKE GLU1-RTCUR .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA: END OF T_BS_GLS0                          .

DATA: BEGIN OF T_PL_GLS0                           OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA BUKRS LIKE GLU1-BUKRS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RTCUR LIKE GLU1-RTCUR .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA: END OF T_PL_GLS0                          .

DATA: BEGIN OF T_BS_GLS1                           OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA BUKRS LIKE GLU1-BUKRS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA UMSKZ LIKE GLU1-UMSKZ .
DATA RMVCT LIKE GLU1-RMVCT .
DATA OCLNT LIKE GLU1-OCLNT .
DATA RASSC LIKE GLU1-RASSC .
DATA KOKRS LIKE GLU1-KOKRS .
DATA RCNTR LIKE GLU1-RCNTR .
*---> 26/05/2023 - Migração S4 - JS
* Campo não existe e não está sendo utilizado.
"DATA RACVT LIKE GLU1-RACVT .
*<--- 26/05/2023 - Migração S4 - JS
DATA SBUSA LIKE GLU1-SBUSA .
DATA SCNTR LIKE GLU1-SCNTR .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA ASL LIKE GLU1-ASL.
DATA AUNIT LIKE GLU1-AUNIT .
DATA: END OF T_BS_GLS1                          .

DATA: BEGIN OF T_PL_GLS1                           OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA BUKRS LIKE GLU1-BUKRS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA UMSKZ LIKE GLU1-UMSKZ .
DATA RMVCT LIKE GLU1-RMVCT .
DATA OCLNT LIKE GLU1-OCLNT .
DATA RASSC LIKE GLU1-RASSC .
DATA KOKRS LIKE GLU1-KOKRS .
DATA RCNTR LIKE GLU1-RCNTR .
*---> 26/05/2023 - Migração S4 - JS
* Campo não existe e não está sendo utilizado.
"DATA RACVT LIKE GLU1-RACVT .
*<--- 26/05/2023 - Migração S4 - JS
DATA SBUSA LIKE GLU1-SBUSA .
DATA SCNTR LIKE GLU1-SCNTR .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA ASL LIKE GLU1-ASL.
DATA: END OF T_PL_GLS1                          .

DATA: BEGIN OF T_BS_GLS2                           OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RCOMP LIKE GLU1-RCOMP .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RLEVL LIKE GLU1-RLEVL .
DATA DOCTY LIKE GLU1-DOCTY .
DATA RSUBD LIKE GLU1-RSUBD .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RASSC LIKE GLU1-RASSC .
DATA SBUSA LIKE GLU1-SBUSA .
DATA RYACQ LIKE GLU1-RYACQ .
DATA RPACQ LIKE GLU1-RPACQ .
DATA OCLNT LIKE GLU1-OCLNT .
DATA OBUKR LIKE GLU1-OBUKR .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA ASL LIKE GLU1-ASL.
DATA UPDHP LIKE GLU1-UPDHP .
DATA AUNIT LIKE GLU1-AUNIT .
DATA: END OF T_BS_GLS2                          .

DATA: BEGIN OF T_PL_GLS2                           OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RCOMP LIKE GLU1-RCOMP .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RLEVL LIKE GLU1-RLEVL .
DATA DOCTY LIKE GLU1-DOCTY .
DATA RSUBD LIKE GLU1-RSUBD .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RASSC LIKE GLU1-RASSC .
DATA SBUSA LIKE GLU1-SBUSA .
DATA RYACQ LIKE GLU1-RYACQ .
DATA RPACQ LIKE GLU1-RPACQ .
DATA OCLNT LIKE GLU1-OCLNT .
DATA OBUKR LIKE GLU1-OBUKR .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA ASL LIKE GLU1-ASL.
DATA: END OF T_PL_GLS2                          .

DATA: BEGIN OF T_BS_GLS3                           OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA BUKRS LIKE GLU1-BUKRS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RASSC LIKE GLU1-RASSC .
DATA SBUSA LIKE GLU1-SBUSA .
DATA RYACQ LIKE GLU1-RYACQ .
DATA RPACQ LIKE GLU1-RPACQ .
DATA RTCUR LIKE GLU1-RTCUR .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA: END OF T_BS_GLS3                          .

DATA: BEGIN OF T_PL_GLS3                           OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA BUKRS LIKE GLU1-BUKRS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RMVCT LIKE GLU1-RMVCT .
DATA RASSC LIKE GLU1-RASSC .
DATA SBUSA LIKE GLU1-SBUSA .
DATA RYACQ LIKE GLU1-RYACQ .
DATA RPACQ LIKE GLU1-RPACQ .
DATA RTCUR LIKE GLU1-RTCUR .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA: END OF T_PL_GLS3                          .

DATA: BEGIN OF T_BS_GLSPC                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA BUKRS LIKE GLU1-BUKRS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RACCT LIKE GLU1-RACCT .
DATA PRCTR LIKE GLU1-PRCTR .
DATA PPRCTR LIKE GLU1-PPRCTR .
DATA OCLNT LIKE GLU1-OCLNT .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_BS_GLSPC                         .

DATA: BEGIN OF T_PL_GLSPC                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA BUKRS LIKE GLU1-BUKRS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RACCT LIKE GLU1-RACCT .
DATA PRCTR LIKE GLU1-PRCTR .
DATA PPRCTR LIKE GLU1-PPRCTR .
DATA OCLNT LIKE GLU1-OCLNT .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_PL_GLSPC                         .

DATA: BEGIN OF T_BS_GMAVCA                         OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RGRANT_NBR LIKE GLU1-RGRANT_NBR .
DATA RFUND LIKE GLU1-RFUND .
DATA RSPONSORED_PROG LIKE GLU1-RSPONSORED_PROG .
DATA RSPONSORED_CLASS LIKE GLU1-RSPONSORED_CLASS .
DATA RBDGT_VLDTY_NBR LIKE GLU1-RBDGT_VLDTY_NBR .
DATA CEFFYEAR_9 LIKE GLU1-CEFFYEAR_9 .
DATA WFSTATE_9 LIKE GLU1-WFSTATE_9 .
DATA ALLOCTYPE_9 LIKE GLU1-ALLOCTYPE_9 .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA GRANTEE_FY_9 LIKE GLU1-GRANTEE_FY_9 .
DATA SBUKRS LIKE GLU1-SBUKRS .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_BS_GMAVCA                        .

DATA: BEGIN OF T_PL_GMAVCA                         OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RGRANT_NBR LIKE GLU1-RGRANT_NBR .
DATA RFUND LIKE GLU1-RFUND .
DATA RSPONSORED_PROG LIKE GLU1-RSPONSORED_PROG .
DATA RSPONSORED_CLASS LIKE GLU1-RSPONSORED_CLASS .
DATA RBDGT_VLDTY_NBR LIKE GLU1-RBDGT_VLDTY_NBR .
DATA CEFFYEAR_9 LIKE GLU1-CEFFYEAR_9 .
DATA WFSTATE_9 LIKE GLU1-WFSTATE_9 .
DATA ALLOCTYPE_9 LIKE GLU1-ALLOCTYPE_9 .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA GRANTEE_FY_9 LIKE GLU1-GRANTEE_FY_9 .
DATA SBUKRS LIKE GLU1-SBUKRS .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_PL_GMAVCA                        .

DATA: BEGIN OF T_BS_JVPSC01A                       OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RPSC_NAME LIKE GLU1-RPSC_NAME .
DATA RPSC_PRODUCT LIKE GLU1-RPSC_PRODUCT .
DATA RJVNAM LIKE GLU1-RJVNAM .
DATA REGROU LIKE GLU1-REGROU .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RCNTR LIKE GLU1-RCNTR .
DATA RORDNR LIKE GLU1-RORDNR .
DATA RPROJK LIKE GLU1-RPROJK .
DATA RPRCTR LIKE GLU1-RPRCTR .
DATA RAUFPL LIKE GLU1-RAUFPL .
DATA RAPLZL LIKE GLU1-RAPLZL .
DATA RRECIN LIKE GLU1-RRECIN .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA PSC_CALC_TYPE LIKE GLU1-PSC_CALC_TYPE .
DATA PSC_PER_COST LIKE GLU1-PSC_PER_COST .
DATA ANLN1 LIKE GLU1-ANLN1 .
DATA ANLN2 LIKE GLU1-ANLN2 .
DATA ANBWA LIKE GLU1-ANBWA .
DATA PARTN LIKE GLU1-PARTN .
DATA SPSC_NAME LIKE GLU1-SPSC_NAME .
DATA SPSC_PRODUCT LIKE GLU1-SPSC_PRODUCT .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA KOKRS LIKE GLU1-KOKRS .
DATA: END OF T_BS_JVPSC01A                      .

DATA: BEGIN OF T_PL_JVPSC01A                       OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RPSC_NAME LIKE GLU1-RPSC_NAME .
DATA RPSC_PRODUCT LIKE GLU1-RPSC_PRODUCT .
DATA RJVNAM LIKE GLU1-RJVNAM .
DATA REGROU LIKE GLU1-REGROU .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RCNTR LIKE GLU1-RCNTR .
DATA RORDNR LIKE GLU1-RORDNR .
DATA RPROJK LIKE GLU1-RPROJK .
DATA RPRCTR LIKE GLU1-RPRCTR .
DATA RAUFPL LIKE GLU1-RAUFPL .
DATA RAPLZL LIKE GLU1-RAPLZL .
DATA RRECIN LIKE GLU1-RRECIN .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA PSC_CALC_TYPE LIKE GLU1-PSC_CALC_TYPE .
DATA PSC_PER_COST LIKE GLU1-PSC_PER_COST .
DATA ANLN1 LIKE GLU1-ANLN1 .
DATA ANLN2 LIKE GLU1-ANLN2 .
DATA ANBWA LIKE GLU1-ANBWA .
DATA PARTN LIKE GLU1-PARTN .
DATA SPSC_NAME LIKE GLU1-SPSC_NAME .
DATA SPSC_PRODUCT LIKE GLU1-SPSC_PRODUCT .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_PL_JVPSC01A                      .

DATA: BEGIN OF T_BS_JVSO1                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RJVNAM LIKE GLU1-RJVNAM .
DATA REGROU LIKE GLU1-REGROU .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RKOKRS LIKE GLU1-RKOKRS .
DATA RCNTR LIKE GLU1-RCNTR .
DATA RORDNR LIKE GLU1-RORDNR .
DATA RPROJK LIKE GLU1-RPROJK .
DATA RPRCTR LIKE GLU1-RPRCTR .
DATA RANLN1 LIKE GLU1-RANLN1 .
DATA RANLN2 LIKE GLU1-RANLN2 .
DATA RANBWA LIKE GLU1-RANBWA .
DATA RRECIN LIKE GLU1-RRECIN .
DATA RPARTN LIKE GLU1-RPARTN .
DATA NPLNR LIKE GLU1-NPLNR .
DATA AUFPL LIKE GLU1-AUFPL .
DATA APLZL LIKE GLU1-APLZL .
DATA VORNR LIKE GLU1-VORNR .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_BS_JVSO1                         .

DATA: BEGIN OF T_PL_JVSO1                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RJVNAM LIKE GLU1-RJVNAM .
DATA REGROU LIKE GLU1-REGROU .
DATA RACCT LIKE GLU1-RACCT .
DATA RBUSA LIKE GLU1-RBUSA .
DATA RKOKRS LIKE GLU1-RKOKRS .
DATA RCNTR LIKE GLU1-RCNTR .
DATA RORDNR LIKE GLU1-RORDNR .
DATA RPROJK LIKE GLU1-RPROJK .
DATA RPRCTR LIKE GLU1-RPRCTR .
DATA RANLN1 LIKE GLU1-RANLN1 .
DATA RANLN2 LIKE GLU1-RANLN2 .
DATA RANBWA LIKE GLU1-RANBWA .
DATA RRECIN LIKE GLU1-RRECIN .
DATA RPARTN LIKE GLU1-RPARTN .
DATA NPLNR LIKE GLU1-NPLNR .
DATA AUFPL LIKE GLU1-AUFPL .
DATA APLZL LIKE GLU1-APLZL .
DATA VORNR LIKE GLU1-VORNR .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA: END OF T_PL_JVSO1                         .

DATA: BEGIN OF T_BS_JVSO2                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RJVNAM LIKE GLU1-RJVNAM .
DATA REGROU LIKE GLU1-REGROU .
DATA RPARTN LIKE GLU1-RPARTN .
DATA RBILID LIKE GLU1-RBILID .
DATA RPROJK LIKE GLU1-RPROJK .
DATA RDPOM LIKE GLU1-RDPOM .
DATA RDBILLM LIKE GLU1-RDBILLM .
DATA RTCUR LIKE GLU1-RTCUR .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA: END OF T_BS_JVSO2                         .

DATA: BEGIN OF T_PL_JVSO2                          OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RJVNAM LIKE GLU1-RJVNAM .
DATA REGROU LIKE GLU1-REGROU .
DATA RPARTN LIKE GLU1-RPARTN .
DATA RBILID LIKE GLU1-RBILID .
DATA RPROJK LIKE GLU1-RPROJK .
DATA RDPOM LIKE GLU1-RDPOM .
DATA RDBILLM LIKE GLU1-RDBILLM .
DATA RTCUR LIKE GLU1-RTCUR .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA: END OF T_PL_JVSO2                         .

DATA: BEGIN OF T_BS_TRACTSLA                       OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA ASL LIKE GLU1-ASL.
DATA AUNIT LIKE GLU1-AUNIT .
DATA: END OF T_BS_TRACTSLA                      .

DATA: BEGIN OF T_PL_TRACTSLA                       OCCURS 0.
DATA RLDNR LIKE GLU1-RLDNR .
DATA RRCTY LIKE GLU1-RRCTY .
DATA RVERS LIKE GLU1-RVERS .
DATA RYEAR LIKE GLU1-RYEAR .
DATA RBUKRS LIKE GLU1-RBUKRS .
DATA RACCT LIKE GLU1-RACCT .
DATA LOGSYS LIKE GLU1-LOGSYS .
DATA RTCUR LIKE GLU1-RTCUR .
DATA RUNIT LIKE GLU1-RUNIT .
DATA DRCRK LIKE GLU1-DRCRK .
DATA POPER LIKE GLU1-POPER .
DATA TSL LIKE GLU1-TSL.
DATA HSL LIKE GLU1-HSL.
DATA KSL LIKE GLU1-KSL.
DATA MSL LIKE GLU1-MSL.
DATA ASL LIKE GLU1-ASL.
DATA: END OF T_PL_TRACTSLA                      .
