FUNCTION Z_FI_INBOUND_INDICE_FINANCEIRO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  TABLES
*"      IT_TCURR STRUCTURE  ZMME_TCURR
*"      IT_RETORNO STRUCTURE  BDCMSGCOLL OPTIONAL
*"----------------------------------------------------------------------

************************************************************************
* 04.12.2008      Alteração       Marcus Barbara        DEVK905280     *
* 04.12.2008      Alteração       Marcus Barbara        DEVK905282     *
* 05.12.2008      Alteração       Marcus Barbara        DEVK905284     *
* 05.12.2008      Alteração       Marcus Barbara        DEVK905286     *
* 17.12.2008      Alteração       Marcus Barbara        DEVK905349     *
* 17.02.2009      Alteração       Marcus Barbara        DEVK905519     *
************************************************************************

  DATA: WA_TCURR   LIKE ZMME_TCURR,
        IT_VALIDAR LIKE ZMME_TCURR OCCURS 0,
        WA_RETORNO TYPE BDCMSGCOLL,
        LC_MODE    TYPE CHAR01.

  DATA: BEGIN OF TI_BDCDATA OCCURS 0.
          INCLUDE STRUCTURE BDCDATA.
  DATA: END OF TI_BDCDATA.

*  DATA OPT TYPE CTU_PARAMS.
  DATA: IT_MESSAGE LIKE BDCMSGCOLL OCCURS 0 WITH HEADER LINE.

  CLEAR: TI_BDCDATA, IT_RETORNO.

  LOOP AT IT_TCURR INTO WA_TCURR.

    CLEAR TI_BDCDATA[].

*   SAPL0SAP  0020  X
    MOVE:  'SAPL0SAP' TO TI_BDCDATA-PROGRAM,
           '0020'     TO TI_BDCDATA-DYNPRO,
           'X'        TO TI_BDCDATA-DYNBEGIN.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_CURSOR  V_TCURR-KURST(01)
    MOVE: 'BDC_CURSOR'        TO TI_BDCDATA-FNAM,
          'V_TCURR-KURST(01)' TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_OKCODE  =NEWL
    MOVE: 'BDC_OKCODE' TO TI_BDCDATA-FNAM,
          '=NEWL'      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   SAPL0SAP 0020  X
    MOVE:  'SAPL0SAP' TO TI_BDCDATA-PROGRAM,
           '0020'     TO TI_BDCDATA-DYNPRO,
           'X'        TO TI_BDCDATA-DYNBEGIN.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_CURSOR  RFCU9-KURSP(02)
    MOVE: 'BDC_CURSOR'      TO    TI_BDCDATA-FNAM,
          'RFCU9-KURSP(02)' TO    TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_OKCODE  /00
    MOVE: 'BDC_OKCODE'      TO    TI_BDCDATA-FNAM,
          '/00' TO    TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-KURST(01)  B
    MOVE: 'V_TCURR-KURST(01)' TO TI_BDCDATA-FNAM,
          WA_TCURR-KURST      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-KURST(01)  B
    MOVE: 'V_TCURR-KURST(02)' TO TI_BDCDATA-FNAM,
          WA_TCURR-KURST      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.
    "Ajuste 04/02/2015 - Paulo Bonetti
    WA_TCURR-GDATU = WA_TCURR-GDATU + 1.
    "Fim Ajuste 04/02/2015 - Paulo Bonetti
*   V_TCURR-GDATU(01)  08.09.2008
    MOVE: 'V_TCURR-GDATU(01)' TO TI_BDCDATA-FNAM.
    CONCATENATE WA_TCURR-GDATU+6(2) '.'
                WA_TCURR-GDATU+4(2) '.'
                WA_TCURR-GDATU(4) INTO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-GDATU(01)  08.09.2008
    MOVE: 'V_TCURR-GDATU(02)' TO TI_BDCDATA-FNAM.


    CONCATENATE WA_TCURR-GDATU+6(2) '.'
                WA_TCURR-GDATU+4(2) '.'
                WA_TCURR-GDATU(4) INTO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   RFCU9-KURSM(01)  2,000
    CALL FUNCTION 'STRING_REPLACE'
      EXPORTING
        PATTERN    = '.'
        SUBSTITUTE = ','
      CHANGING
        TEXT       = WA_TCURR-UKURS.

    MOVE: 'RFCU9-KURSM(01)' TO TI_BDCDATA-FNAM,
          WA_TCURR-UKURS    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-FCURR(01)  BRL
    MOVE: 'V_TCURR-FCURR(01)' TO TI_BDCDATA-FNAM,
          WA_TCURR-FCURR      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-FCURR(02) USD
    MOVE: 'V_TCURR-FCURR(02)' TO TI_BDCDATA-FNAM,
          WA_TCURR-TCURR TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   RFCU9-KURSP(02) 2,000
    MOVE: 'RFCU9-KURSP(02)' TO TI_BDCDATA-FNAM,
          WA_TCURR-UKURS    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-TCURR(01) USD
    MOVE: 'V_TCURR-TCURR(01)' TO TI_BDCDATA-FNAM,
          WA_TCURR-TCURR      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-TCURR(02) BRL
    MOVE: 'V_TCURR-TCURR(02)' TO TI_BDCDATA-FNAM,
          WA_TCURR-FCURR      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   SAPL0SAP  0020  X
    MOVE:  'SAPL0SAP' TO TI_BDCDATA-PROGRAM,
           '0020'     TO TI_BDCDATA-DYNPRO,
           'X'        TO TI_BDCDATA-DYNBEGIN.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_CURSOR  V_TCURR-KURST(03)
    MOVE: 'BDC_CURSOR'        TO TI_BDCDATA-FNAM,
          'V_TCURR-KURST(03)' TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_OKCODE  =SAVE
    MOVE: 'BDC_OKCODE' TO TI_BDCDATA-FNAM,
          '=SAVE'    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   SAPL0SAP  0020  X
    MOVE:  'SAPL0SAP' TO TI_BDCDATA-PROGRAM,
           '0020'     TO TI_BDCDATA-DYNPRO,
           'X'        TO TI_BDCDATA-DYNBEGIN.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_CURSOR  V_TCURR-KURST(03)
    MOVE: 'BDC_CURSOR' TO TI_BDCDATA-FNAM,
          'V_TCURR-KURST(03)'    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_OKCODE  =BACK
    MOVE: 'BDC_OKCODE' TO TI_BDCDATA-FNAM,
          '=BACK'    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   SAPL0SAP  0020  X
    MOVE:  'SAPL0SAP' TO TI_BDCDATA-PROGRAM,
           '0020'     TO TI_BDCDATA-DYNPRO,
           'X'        TO TI_BDCDATA-DYNBEGIN.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_CURSOR  V_TCURR-KURST(03)
    MOVE: 'BDC_CURSOR' TO TI_BDCDATA-FNAM,
          'V_TCURR-KURST(03)'    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_OKCODE  =BACK
    MOVE: 'BDC_OKCODE' TO TI_BDCDATA-FNAM,
          '=BACK'    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

    LC_MODE = 'N'.

    CLEAR: IT_MESSAGE[].
    CALL TRANSACTION 'OB08' USING TI_BDCDATA
                             MODE LC_MODE
                           UPDATE 'S'
                         MESSAGES INTO IT_MESSAGE.
    COMMIT WORK.

    IF SY-BATCH EQ ABAP_TRUE.
      CONCATENATE WA_TCURR-GDATU+6(2) '.'
                  WA_TCURR-GDATU+4(2) '.'
                  WA_TCURR-GDATU(4) INTO DATA(LVA_DT_COTACAO).

      MESSAGE |Mensagens Cadastro Taxa: Categoria: { WA_TCURR-KURST }  De Moeda: { WA_TCURR-FCURR } Para Moeda: { WA_TCURR-TCURR } Data: { LVA_DT_COTACAO } Taxa: { WA_TCURR-UKURS }!| TYPE 'S'.
    ENDIF.

    LOOP AT IT_MESSAGE INTO WA_RETORNO.

      IF SY-BATCH EQ ABAP_TRUE.
        MESSAGE ID WA_RETORNO-MSGID TYPE 'S' NUMBER WA_RETORNO-MSGNR WITH WA_RETORNO-MSGV1 WA_RETORNO-MSGV2 WA_RETORNO-MSGV3 WA_RETORNO-MSGV4.
      ENDIF.

      APPEND WA_RETORNO TO IT_RETORNO.
    ENDLOOP.




  ENDLOOP.

ENDFUNCTION.
