FUNCTION z_fi_inbound_indice_fin_arg.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  TABLES
*"      IT_TCURR STRUCTURE  ZMME_TCURR
*"      IT_RETORNO STRUCTURE  BDCMSGCOLL OPTIONAL
*"----------------------------------------------------------------------

************************************************************************
* 04.12.2008      Alteração       Marcus Barbara        DEVK905280     *
* 04.12.2008      Alteração       Marcus Barbara        DEVK905282     *
* 05.12.2008      Alteração       Marcus Barbara        DEVK905284     *
* 05.12.2008      Alteração       Marcus Barbara        DEVK905286     *
* 17.12.2008      Alteração       Marcus Barbara        DEVK905349     *
* 17.02.2009      Alteração       Marcus Barbara        DEVK905519     *
************************************************************************

  DATA: wa_tcurr   LIKE zmme_tcurr,
        it_validar LIKE zmme_tcurr OCCURS 0,
        wa_retorno TYPE bdcmsgcoll,
        lc_mode    TYPE char01.

  DATA: BEGIN OF ti_bdcdata OCCURS 0.
          INCLUDE STRUCTURE bdcdata.
        DATA: END OF ti_bdcdata.

*  DATA OPT TYPE CTU_PARAMS.
  DATA: it_message LIKE bdcmsgcoll OCCURS 0 WITH HEADER LINE.
  DATA: v_data TYPE sy-datum.
  CLEAR: ti_bdcdata, it_retorno.

  LOOP AT it_tcurr INTO wa_tcurr.

    CLEAR: ti_bdcdata[], v_data.

*   SAPL0SAP  0020  X
    MOVE:  'SAPL0SAP' TO TI_BDCDATA-PROGRAM,
           '0020'     TO TI_BDCDATA-DYNPRO,
           'X'        TO TI_BDCDATA-DYNBEGIN.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_CURSOR  V_TCURR-KURST(01)
    MOVE: 'BDC_CURSOR'        TO TI_BDCDATA-FNAM,
          'V_TCURR-KURST(01)' TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_OKCODE  =NEWL
    MOVE: 'BDC_OKCODE' TO TI_BDCDATA-FNAM,
          '=NEWL'      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   SAPL0SAP 0020  X
    MOVE:  'SAPL0SAP' TO TI_BDCDATA-PROGRAM,
           '0020'     TO TI_BDCDATA-DYNPRO,
           'X'        TO TI_BDCDATA-DYNBEGIN.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_CURSOR  RFCU9-KURSP(02)
    MOVE: 'BDC_CURSOR'      TO    TI_BDCDATA-FNAM,
          'RFCU9-KURSP(02)' TO    TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_OKCODE  /00
    MOVE: 'BDC_OKCODE'      TO    TI_BDCDATA-FNAM,
          '/00' TO    TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-KURST(01)  B
    MOVE: 'V_TCURR-KURST(01)' TO TI_BDCDATA-FNAM,
          WA_TCURR-KURST      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-KURST(01)  B
    MOVE: 'V_TCURR-KURST(02)' TO TI_BDCDATA-FNAM,
          WA_TCURR-KURST      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

    WA_TCURR-GDATU = WA_TCURR-GDATU.

    MOVE: 'V_TCURR-GDATU(01)' TO TI_BDCDATA-FNAM.
    CONCATENATE WA_TCURR-GDATU+6(2) '.'
                WA_TCURR-GDATU+4(2) '.'
                WA_TCURR-GDATU(4) INTO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-GDATU(01)  08.09.2008
    MOVE: 'V_TCURR-GDATU(02)' TO TI_BDCDATA-FNAM.


    CONCATENATE WA_TCURR-GDATU+6(2) '.'
                WA_TCURR-GDATU+4(2) '.'
                WA_TCURR-GDATU(4) INTO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   RFCU9-KURSM(01)  2,000
*** Stefanini - IR212656 - 11/12/2024 - LAZAROSR - Início de Alteração
*    CALL FUNCTION 'STRING_REPLACE'
*      EXPORTING
*        PATTERN    = '.'
*        SUBSTITUTE = ','
*      CHANGING
*        TEXT       = WA_TCURR-UKURS.
*** Stefanini - IR212656 - 11/12/2024 - LAZAROSR - Fim de Alteração

    MOVE: 'RFCU9-KURSM(01)' TO TI_BDCDATA-FNAM,
          WA_TCURR-UKURS    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-FCURR(01)  BRL
    MOVE: 'V_TCURR-FCURR(01)' TO TI_BDCDATA-FNAM,
          WA_TCURR-FCURR      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-FCURR(02) USD
    MOVE: 'V_TCURR-FCURR(02)' TO TI_BDCDATA-FNAM,
          WA_TCURR-TCURR TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   RFCU9-KURSP(02) 2,000
    MOVE: 'RFCU9-KURSP(02)' TO TI_BDCDATA-FNAM,
          WA_TCURR-UKURS    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-TCURR(01) USD
    MOVE: 'V_TCURR-TCURR(01)' TO TI_BDCDATA-FNAM,
          WA_TCURR-TCURR      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   V_TCURR-TCURR(02) BRL
    MOVE: 'V_TCURR-TCURR(02)' TO TI_BDCDATA-FNAM,
          WA_TCURR-FCURR      TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   SAPL0SAP  0020  X
    MOVE:  'SAPL0SAP' TO TI_BDCDATA-PROGRAM,
           '0020'     TO TI_BDCDATA-DYNPRO,
           'X'        TO TI_BDCDATA-DYNBEGIN.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_CURSOR  V_TCURR-KURST(03)
    MOVE: 'BDC_CURSOR'        TO TI_BDCDATA-FNAM,
          'V_TCURR-KURST(03)' TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_OKCODE  =SAVE
    MOVE: 'BDC_OKCODE' TO TI_BDCDATA-FNAM,
          '=SAVE'    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   SAPL0SAP  0020  X
    MOVE:  'SAPL0SAP' TO TI_BDCDATA-PROGRAM,
           '0020'     TO TI_BDCDATA-DYNPRO,
           'X'        TO TI_BDCDATA-DYNBEGIN.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_CURSOR  V_TCURR-KURST(03)
    MOVE: 'BDC_CURSOR' TO TI_BDCDATA-FNAM,
          'V_TCURR-KURST(03)'    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_OKCODE  =BACK
    MOVE: 'BDC_OKCODE' TO TI_BDCDATA-FNAM,
          '=BACK'    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   SAPL0SAP  0020  X
    MOVE:  'SAPL0SAP' TO TI_BDCDATA-PROGRAM,
           '0020'     TO TI_BDCDATA-DYNPRO,
           'X'        TO TI_BDCDATA-DYNBEGIN.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_CURSOR  V_TCURR-KURST(03)
    MOVE: 'BDC_CURSOR' TO TI_BDCDATA-FNAM,
          'V_TCURR-KURST(03)'    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

*   BDC_OKCODE  =BACK
    MOVE: 'BDC_OKCODE' TO TI_BDCDATA-FNAM,
          '=BACK'    TO TI_BDCDATA-FVAL.
    APPEND TI_BDCDATA.
    CLEAR TI_BDCDATA.

    LC_MODE = 'N'.

    CALL TRANSACTION 'OB08' USING TI_BDCDATA
                             MODE LC_MODE
                           UPDATE 'S'
                         MESSAGES INTO IT_MESSAGE.
    COMMIT WORK.

    LOOP AT IT_MESSAGE INTO WA_RETORNO.
      APPEND WA_RETORNO TO IT_RETORNO.
    ENDLOOP.

ENDLOOP.

ENDFUNCTION.
