PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIT0091 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIT0091-BUKRS .
    FIELD ZFIT0091-AUGBL .
    FIELD ZFIT0091-CNPJ_EMPRESA .
    FIELD ZFIT0091-BANCO .
    FIELD ZFIT0091-AGENCIA .
    FIELD ZFIT0091-CONTA_CORRENTE .
    FIELD ZFIT0091-DT_PGTO .
    FIELD ZFIT0091-VLR_PGTO .
    FIELD ZFIT0091-CNPJ_CPF_FORN .
    FIELD ZFIT0091-LIFNR .
    FIELD ZFIT0091-BCO_FAV .
    FIELD ZFIT0091-AG_FAV .
    FIELD ZFIT0091-DV_AG_FAV .
    FIELD ZFIT0091-CC_FAV .
    FIELD ZFIT0091-DV_FAV .
    FIELD ZFIT0091-COD_AUTENT .
    FIELD ZFIT0091-COD_BARRAS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIT0091-BUKRS .
    FIELD ZFIT0091-AUGBL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
