FUNCTION ZCATSXT_SIMPLE_TEXT_EDITOR2.
*"--------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(IM_TITLE) TYPE  SYTITLE
*"     REFERENCE(IM_DISPLAY_MODE) TYPE  XFELD DEFAULT SPACE
*"     REFERENCE(IM_START_COLUMN) TYPE  I DEFAULT 10
*"     REFERENCE(IM_START_ROW) TYPE  I DEFAULT 10
*"  EXPORTING
*"     REFERENCE(E_REPROC) TYPE  CHAR1
*"  CHANGING
*"     REFERENCE(CH_TEXT) TYPE  CATSXT_LONGTEXT_ITAB
*"--------------------------------------------------------------------
  CLEAR: WG_REPROC.
  CREATE OBJECT STE
    EXPORTING
      IM_TITLE        = IM_TITLE
      IM_DISPLAY_MODE = IM_DISPLAY_MODE
      IM_LONGTEXT_TAB = CH_TEXT.

  CALL SCREEN 400 STARTING AT IM_START_COLUMN
                              IM_START_ROW.

  CH_TEXT = STE->GET_TEXT( ).

  CALL METHOD STE->FREE.

  CLEAR STE.
  E_REPROC = WG_REPROC.
ENDFUNCTION.
