PROCESS BEFORE OUTPUT.
  MODULE TRATA_FIELDS.
  MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
  MODULE USER_COMMAND_0100.

PROCESS ON VALUE-REQUEST.
  FIELD WG_CADLAN-CD_MOD    MODULE SEARCH_MODAL.
  FIELD WG_CADLAN-ZLSCH     MODULE SEARCH_ZLSCH.
  FIELD WG_CADLAN-ZID_CONTR MODULE SEARCH_CTR.
  FIELD WG_CADLAN-HBKID     MODULE SEARCH_BANCO.
  FIELD WG_CADLAN-BVTYP     MODULE SEARCH_BVTYP.
  FIELD WG_CADLAN-NRO_SOL   MODULE SEARCH_SOLIC.
