*&---------------------------------------------------------------------*
*&  Include           ZFIR0055_FORM
*&---------------------------------------------------------------------*

FORM ESTRUTURA_ALV USING VALUE(P_COL_POS)       TYPE I
                         VALUE(P_REF_TABNAME)   LIKE DD02D-TABNAME
                         VALUE(P_REF_FIELDNAME) LIKE DD03D-FIELDNAME
                         VALUE(P_TABNAME)       LIKE DD02D-TABNAME
                         VALUE(P_FIELD)         LIKE DD03D-FIELDNAME
                         VALUE(P_SCRTEXT_L)     LIKE DD03P-SCRTEXT_L
                         VALUE(P_OUTPUTLEN)
                         VALUE(P_EDIT)
                         VALUE(P_SUM)
                         VALUE(P_EMPHASIZE)
                         VALUE(P_JUST)
                         VALUE(P_HOTSPOT)
                         VALUE(P_F4).

  CLEAR WA_FCAT.

  WA_FCAT-FIELDNAME   = P_FIELD.
  WA_FCAT-TABNAME     = P_TABNAME.
  WA_FCAT-REF_TABLE   = P_REF_TABNAME.
  WA_FCAT-REF_FIELD   = P_REF_FIELDNAME.
  WA_FCAT-KEY         = ' '.
  WA_FCAT-EDIT        = P_EDIT.
  WA_FCAT-COL_POS     = P_COL_POS.
  WA_FCAT-OUTPUTLEN   = P_OUTPUTLEN.
  WA_FCAT-NO_OUT      = ' '.
  WA_FCAT-SELTEXT     = P_SCRTEXT_L.
  WA_FCAT-REPTEXT     = P_SCRTEXT_L.
  WA_FCAT-SCRTEXT_S   = P_SCRTEXT_L.
  WA_FCAT-SCRTEXT_M   = P_SCRTEXT_L.
  WA_FCAT-SCRTEXT_L   = P_SCRTEXT_L.
  WA_FCAT-COLDDICTXT  = 'L'.
  WA_FCAT-SELDDICTXT  = 'L'.
  WA_FCAT-TIPDDICTXT  = 'L'.
  WA_FCAT-EMPHASIZE   = P_EMPHASIZE.
  WA_FCAT-STYLE       =
  WA_FCAT-JUST        = P_JUST.
  WA_FCAT-HOTSPOT     = P_HOTSPOT.
  WA_FCAT-F4AVAILABL  = P_F4.

  APPEND WA_FCAT TO IT_FCAT.

ENDFORM.                    " ESTRUTURA_ALV
*&---------------------------------------------------------------------*
*&      Form  ATRIB_CLASSIFICAO_FLX
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ATRIB_CLASSIFICAO_FLX .

  DATA: VAR_ANSWER TYPE C.

  DATA: WL_0121 TYPE ZFIT0121,
        WL_0077 TYPE ZFIT0077,
        TG_0080 TYPE TABLE OF ZFIT0080 WITH HEADER LINE.

  FIELD-SYMBOLS: <SAIDA> TYPE TY_SAIDA.

  CALL FUNCTION 'POPUP_TO_CONFIRM'
    EXPORTING
      TITLEBAR              = 'Confirmação'
      TEXT_QUESTION         = 'Deseja realmente classificar o(s) documento(s) selecionado(s)?'
      TEXT_BUTTON_1         = 'Sim'
      TEXT_BUTTON_2         = 'Não'
      DEFAULT_BUTTON        = '1'
      DISPLAY_CANCEL_BUTTON = ''
    IMPORTING
      ANSWER                = VAR_ANSWER
    EXCEPTIONS
      TEXT_NOT_FOUND        = 1
      OTHERS                = 2.

  CHECK VAR_ANSWER EQ '1'.

  CLEAR: WL_0077.
  IF WL_CLS_FLX IS NOT INITIAL.
    SELECT SINGLE *
      FROM ZFIT0077 INTO WL_0077
     WHERE COD_FLX = WL_CLS_FLX.

     IF SY-SUBRC NE 0.
       MESSAGE 'Houve um erro ao localizar o código de Fluxo.!' TYPE 'S'.
       RETURN.
     ENDIF.
  ENDIF.

  LOOP AT IT_SEL_ROWS INTO WA_SEL_ROWS.

    READ TABLE T_SAIDA ASSIGNING <SAIDA> INDEX WA_SEL_ROWS-INDEX.

    CHECK SY-SUBRC EQ 0.

    DELETE FROM ZFIT0121 WHERE BUKRS = <SAIDA>-BUKRS
                           AND BELNR = <SAIDA>-BELNR
                           AND GJAHR = <SAIDA>-BUDAT(4)
                           AND BUZEI = <SAIDA>-BUZEI.

    IF WL_CLS_FLX IS NOT INITIAL.
      CLEAR: WL_0121.
      WL_0121-BUKRS   = <SAIDA>-BUKRS.
      WL_0121-BELNR   = <SAIDA>-BELNR.
      WL_0121-GJAHR   = <SAIDA>-GJAHR.
      WL_0121-BUZEI   = <SAIDA>-BUZEI.
      WL_0121-COD_FLX = WL_CLS_FLX.
      MODIFY ZFIT0121 FROM WL_0121.

      IF SY-SUBRC NE 0.
        ROLLBACK WORK.
        MESSAGE 'Houve um erro ao classificar o(s) documento(s)!' TYPE 'S'.
        RETURN.
      ENDIF.

      <SAIDA>-COD_FLX  = WL_CLS_FLX.
      <SAIDA>-DESC_FLX = WL_0077-DESC_FLX.
      <SAIDA>-CLS_MN   = 'X'.
    ELSE.
      CLEAR: <SAIDA>-DESC_FLX, <SAIDA>-COD_FLX, <SAIDA>-CLS_MN.
    ENDIF.

    SELECT *
      FROM ZFIT0080 INTO TABLE TG_0080
     WHERE BUKRS = <SAIDA>-BUKRS
       AND BELNR = <SAIDA>-BELNR
       AND GJAHR = <SAIDA>-BUDAT(4)
       AND BUZEI = <SAIDA>-BUZEI.

    LOOP AT TG_0080.

      DELETE FROM ZFIT0080 WHERE BUKRS    = TG_0080-BUKRS
                             AND BELNR    = TG_0080-BELNR
                             AND GJAHR    = TG_0080-GJAHR
                             AND BUZEI    = TG_0080-BUZEI
                             AND HKONT    = TG_0080-HKONT
                             AND COD_FLX  = TG_0080-COD_FLX.

      TG_0080-COD_FLX =  WL_CLS_FLX.
      MODIFY ZFIT0080 FROM TG_0080.

      IF SY-SUBRC NE 0.
        ROLLBACK WORK.
        MESSAGE 'Houve um erro ao classificar o(s) documento(s)!' TYPE 'S'.
        RETURN.
      ENDIF.

    ENDLOOP.

  ENDLOOP.

  CALL METHOD OBJ_ALV->REFRESH_TABLE_DISPLAY
    EXPORTING
       IS_STABLE = WA_STABLE.

  LEAVE TO SCREEN 0.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  INF_CLASSIFICAO_FLX
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM INF_CLASSIFICAO_FLX .

  REFRESH: IT_SEL_ROWS[].
  CLEAR: WA_SEL_ROWS.

  CALL METHOD OBJ_ALV->GET_SELECTED_ROWS
    IMPORTING
      ET_INDEX_ROWS = IT_SEL_ROWS.

  CHECK IT_SEL_ROWS IS NOT INITIAL.

  CLEAR: WL_CLS_FLX.
  CALL SCREEN 0101 STARTING AT 20 08 ENDING AT 45 3.

ENDFORM.

FORM VALIDA_INFO_0102 USING P_VALIDA P_OPERACAO.

  DATA: WL_0121  TYPE ZFIT0121.

  CLEAR: P_VALIDA.

  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT    = ZFIT0121-BUKRS
    IMPORTING
      OUTPUT   = ZFIT0121-BUKRS.

  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT    = ZFIT0121-BELNR
    IMPORTING
      OUTPUT   = ZFIT0121-BELNR.

  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT    = ZFIT0121-BUZEI
    IMPORTING
      OUTPUT   = ZFIT0121-BUZEI.

  "Campos obrigatórios
  IF ( ZFIT0121-BUKRS    IS INITIAL ) OR
     ( ZFIT0121-BELNR    IS INITIAL ) OR
     ( ZFIT0121-GJAHR    IS INITIAL ) OR
     ( ZFIT0121-BUZEI    IS INITIAL ).
    MESSAGE 'Favor preecher todos os campos!' TYPE 'W'.
    RETURN.
  ENDIF.

  IF P_OPERACAO = 'I'.
    IF ( ZFIT0121-COD_FLX  IS INITIAL ) OR
       ( ZFIT0121-KOART    IS INITIAL ).
      MESSAGE 'Favor preecher todos os campos!' TYPE 'W'.
      RETURN.
    ENDIF.
  ENDIF.

  "Verificação se registro
  SELECT SINGLE *
    FROM ZFIT0121 INTO WL_0121
   WHERE BUKRS  = ZFIT0121-BUKRS
     AND BELNR  = ZFIT0121-BELNR
     AND GJAHR  = ZFIT0121-GJAHR
     AND BUZEI  = ZFIT0121-BUZEI
     AND MANUAL = 'X'.

  CASE P_OPERACAO.
    WHEN 'I'. "Inserção
      IF SY-SUBRC = 0.
        MESSAGE 'Documento já incluído/classificado no Fluxo de Caixa!' TYPE 'W'.
        RETURN.
      ENDIF.
    WHEN 'D'. "Exclusão
      IF SY-SUBRC NE 0.
        MESSAGE 'Documento não encontrado para exclusão!' TYPE 'W'.
        RETURN.
      ENDIF.
  ENDCASE.

  P_VALIDA = 'X'.

ENDFORM.

FORM GET_SALDO_CONTA  USING P_SAIDA_0103 TYPE TY_SAIDA_0103.

  DATA: IT_SALDO_CONTAS   TYPE TABLE OF ZDE_FI_GL_SALDO_FAGLFLEXT WITH HEADER LINE,
        IT_SALDO_CONTAS_2 TYPE TABLE OF ZDE_FI_GL_SALDO_FAGLFLEXT WITH HEADER LINE,
        IT_SALDO_CONTAS_3 TYPE TABLE OF ZDE_FI_GL_SALDO_FAGLFLEXT WITH HEADER LINE,

        WA_SALDO_CONTAS   TYPE ZDE_FI_GL_SALDO_FAGLFLEXT,
        WA_SALDO_CONTAS_2 TYPE ZDE_FI_GL_SALDO_FAGLFLEXT,
        WA_SALDO_CONTAS_3 TYPE ZDE_FI_GL_SALDO_FAGLFLEXT.

  DATA: IT_CONTAS TYPE TABLE OF ZLC_EMP_CONTAS,
        WA_CONTAS TYPE ZLC_EMP_CONTAS.

  CLEAR: IT_CONTAS[], WA_CONTAS.

  WA_CONTAS-BUKRS = ZFIT0080-BUKRS.
  WA_CONTAS-SAKNR = P_SAIDA_0103-SAKNR.
  APPEND WA_CONTAS TO IT_CONTAS.

  CALL FUNCTION 'Z_FI_GL_SALDO_FAGLFLEXT'
    EXPORTING
      RYEAR          = ZFIT0080-GJAHR
      CONTAS         = IT_CONTAS
      P_GERAR_TODAS  = ABAP_TRUE
      "RLDNR          = '50'
      "P_GERAR_FILIAL = ABAP_TRUE
    TABLES
      IT_SALDOS      = IT_SALDO_CONTAS
      IT_SALDOS_2    = IT_SALDO_CONTAS_2
      IT_SALDOS_3    = IT_SALDO_CONTAS_3
    EXCEPTIONS
      MOEDA_NAO_ADM  = 1
      ERRO_LEDGER    = 2
      OTHERS         = 3.

  READ TABLE IT_SALDO_CONTAS INTO WA_SALDO_CONTAS INDEX 1.
  READ TABLE IT_SALDO_CONTAS_2 INTO WA_SALDO_CONTAS_2 INDEX 1.
  READ TABLE IT_SALDO_CONTAS_3 INTO WA_SALDO_CONTAS_3 INDEX 1.

  CASE ZFIT0080-MONAT.

    WHEN '01'. "Janeiro

      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT + WA_SALDO_CONTAS_2-SL01.

    WHEN '02'. "Fevereiro

      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01   + WA_SALDO_CONTAS-SL02.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT + WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02.

    WHEN '03'. "Março

      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01   + WA_SALDO_CONTAS-SL02   + WA_SALDO_CONTAS-SL03.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT + WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02 + WA_SALDO_CONTAS_2-SL03.

    WHEN '04'. "Abril

      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01   + WA_SALDO_CONTAS-SL02   + WA_SALDO_CONTAS-SL03   + WA_SALDO_CONTAS-SL04.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT + WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02 + WA_SALDO_CONTAS_2-SL03 + WA_SALDO_CONTAS_2-SL04.

    WHEN '05'. "Maio

      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01  + WA_SALDO_CONTAS-SL02   + WA_SALDO_CONTAS-SL03   + WA_SALDO_CONTAS-SL04 +
                            WA_SALDO_CONTAS-SL05.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT +  WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02 + WA_SALDO_CONTAS_2-SL03 + WA_SALDO_CONTAS_2-SL04 +
                            WA_SALDO_CONTAS_2-SL05.

    WHEN '06'. "Junho

      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01 + WA_SALDO_CONTAS-SL02 + WA_SALDO_CONTAS-SL03 + WA_SALDO_CONTAS-SL04 +
                            WA_SALDO_CONTAS-SL05 + WA_SALDO_CONTAS-SL06.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT +  WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02 + WA_SALDO_CONTAS_2-SL03 + WA_SALDO_CONTAS_2-SL04 +
                            WA_SALDO_CONTAS_2-SL05 +  WA_SALDO_CONTAS_2-SL06.


    WHEN '07'. "Julho
      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01 + WA_SALDO_CONTAS-SL02 + WA_SALDO_CONTAS-SL03 + WA_SALDO_CONTAS-SL04 +
                            WA_SALDO_CONTAS-SL05 + WA_SALDO_CONTAS-SL06 + WA_SALDO_CONTAS-SL07.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT +  WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02 + WA_SALDO_CONTAS_2-SL03 + WA_SALDO_CONTAS_2-SL04 +
                            WA_SALDO_CONTAS_2-SL05 + WA_SALDO_CONTAS_2-SL06 + WA_SALDO_CONTAS_2-SL07.

    WHEN '08'. "Agosto
      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01 + WA_SALDO_CONTAS-SL02 + WA_SALDO_CONTAS-SL03 + WA_SALDO_CONTAS-SL04 +
                            WA_SALDO_CONTAS-SL05 + WA_SALDO_CONTAS-SL06 + WA_SALDO_CONTAS-SL07 + WA_SALDO_CONTAS-SL08.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT +  WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02 + WA_SALDO_CONTAS_2-SL03 + WA_SALDO_CONTAS_2-SL04 +
                            WA_SALDO_CONTAS_2-SL05 + WA_SALDO_CONTAS_2-SL06 + WA_SALDO_CONTAS_2-SL07 + WA_SALDO_CONTAS_2-SL08.

    WHEN '09'. "Setembro

      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01 + WA_SALDO_CONTAS-SL02 + WA_SALDO_CONTAS-SL03 + WA_SALDO_CONTAS-SL04 +
                            WA_SALDO_CONTAS-SL05 + WA_SALDO_CONTAS-SL06 + WA_SALDO_CONTAS-SL07 + WA_SALDO_CONTAS-SL08 +
                            WA_SALDO_CONTAS-SL09.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT +  WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02 + WA_SALDO_CONTAS_2-SL03 + WA_SALDO_CONTAS_2-SL04 +
                            WA_SALDO_CONTAS_2-SL05 + WA_SALDO_CONTAS_2-SL06 + WA_SALDO_CONTAS_2-SL07 + WA_SALDO_CONTAS_2-SL08 +
                            WA_SALDO_CONTAS_2-SL09.

    WHEN '10'. "Outubro

      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01 + WA_SALDO_CONTAS-SL02 + WA_SALDO_CONTAS-SL03 + WA_SALDO_CONTAS-SL04 +
                            WA_SALDO_CONTAS-SL05 + WA_SALDO_CONTAS-SL06 + WA_SALDO_CONTAS-SL07 + WA_SALDO_CONTAS-SL08 +
                            WA_SALDO_CONTAS-SL09 + WA_SALDO_CONTAS-SL10.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT +  WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02 + WA_SALDO_CONTAS_2-SL03 + WA_SALDO_CONTAS_2-SL04 +
                            WA_SALDO_CONTAS_2-SL05 + WA_SALDO_CONTAS_2-SL06 + WA_SALDO_CONTAS_2-SL07 + WA_SALDO_CONTAS_2-SL08 +
                            WA_SALDO_CONTAS_2-SL09 + WA_SALDO_CONTAS_2-SL10.

    WHEN '11'. "Novembro

      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01 + WA_SALDO_CONTAS-SL02 + WA_SALDO_CONTAS-SL03 + WA_SALDO_CONTAS-SL04 +
                            WA_SALDO_CONTAS-SL05 + WA_SALDO_CONTAS-SL06 + WA_SALDO_CONTAS-SL07 + WA_SALDO_CONTAS-SL08 +
                            WA_SALDO_CONTAS-SL09 + WA_SALDO_CONTAS-SL10 + WA_SALDO_CONTAS-SL11.

      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT +  WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02 + WA_SALDO_CONTAS_2-SL03 + WA_SALDO_CONTAS_2-SL04 +
                            WA_SALDO_CONTAS_2-SL05 + WA_SALDO_CONTAS_2-SL06 + WA_SALDO_CONTAS_2-SL07 + WA_SALDO_CONTAS_2-SL08 +
                            WA_SALDO_CONTAS_2-SL09 + WA_SALDO_CONTAS_2-SL10 + WA_SALDO_CONTAS_2-SL11.

    WHEN '12'. "Dezembro e não usa os complementares

      P_SAIDA_0103-DMBTR  = WA_SALDO_CONTAS-SLVT   + WA_SALDO_CONTAS-SL01 + WA_SALDO_CONTAS-SL02 + WA_SALDO_CONTAS-SL03  + WA_SALDO_CONTAS-SL04 +
                            WA_SALDO_CONTAS-SL05 + WA_SALDO_CONTAS-SL06 + WA_SALDO_CONTAS-SL07  + WA_SALDO_CONTAS-SL08 +
                            WA_SALDO_CONTAS-SL09 + WA_SALDO_CONTAS-SL10 + WA_SALDO_CONTAS-SL11  + WA_SALDO_CONTAS-SL12.


      P_SAIDA_0103-DMBE2  = WA_SALDO_CONTAS_2-SLVT +  WA_SALDO_CONTAS_2-SL01 + WA_SALDO_CONTAS_2-SL02 + WA_SALDO_CONTAS_2-SL03 + WA_SALDO_CONTAS_2-SL04 +
                            WA_SALDO_CONTAS_2-SL05 + WA_SALDO_CONTAS_2-SL06 + WA_SALDO_CONTAS_2-SL07 + WA_SALDO_CONTAS_2-SL08 +
                            WA_SALDO_CONTAS_2-SL09 + WA_SALDO_CONTAS_2-SL10 + WA_SALDO_CONTAS_2-SL11 + WA_SALDO_CONTAS_2-SL12.


  ENDCASE.



ENDFORM.
