DATA: IT_SAIDA_AUX TYPE TY_SAIDA_T,
      WA_SAIDA_AUX TYPE ZFIR0001,
      WA_SAIDA_RES TYPE ZFIR0001,
      V_VLR_PGTO   TYPE ZFIT0036-VLR_PGTO.

"Monta Saida resumo por lote/fornecedor
IT_SAIDA_AUX[] = IT_SAIDA[].
SORT:  IT_SAIDA     BY LOTE NAME1,
       IT_SAIDA_AUX BY LOTE NAME1.

DELETE ADJACENT DUPLICATES FROM IT_SAIDA_AUX COMPARING LOTE NAME1.
LOOP AT IT_SAIDA_AUX INTO WA_SAIDA_AUX.
  V_VLR_PGTO = 0.
  LOOP AT IT_SAIDA INTO WA_SAIDA WHERE LOTE  = WA_SAIDA_AUX-LOTE
                                 AND   NAME1 = WA_SAIDA_AUX-NAME1.
    MOVE-CORRESPONDING WA_SAIDA TO WA_SAIDA_RES.
    ADD  WA_SAIDA-VLR_PGTO TO V_VLR_PGTO.
  ENDLOOP.
  WA_SAIDA_RES-VLR_PGTO = V_VLR_PGTO.
  APPEND WA_SAIDA_RES TO IT_SAIDA_RES.

ENDLOOP.

IT_CABEC[] = IT_SAIDA[].
SORT: IT_CABEC BY BANKS_1 BANKL_1	BANKN_1 IBAN_1 LOTE NAME1,
      IT_SAIDA BY BANKS_1 BANKL_1	BANKN_1 IBAN_1 LOTE NAME1.
DELETE ADJACENT DUPLICATES FROM IT_CABEC COMPARING BANKS_1 BANKL_1  BANKN_1 IBAN_1.

*" Subtotal por  BANKS_1 BANKL_1  BANKN_1 IBAN_1.
*DATA: VBANKS_1   TYPE ZFIT0036-BANKS_1,
*      VBANKL_1   TYPE ZFIT0036-BANKL_1,
*      VBANKN_1   TYPE ZFIT0036-BANKN_1,
*      VIBAN_1    TYPE ZFIT0036-IBAN_1,
*      VSEQ       TYPE I.
*
*IT_SAIDA_AUX[] = IT_SAIDA_RES[].
*REFRESH IT_SAIDA_RES.
*SORT  IT_SAIDA_AUX BY BANKS_1 BANKL_1  BANKN_1 IBAN_1 LOTE NAME1.
*
*IF IT_SAIDA_AUX[] IS NOT INITIAL.
*  READ TABLE IT_SAIDA_AUX INTO WA_SAIDA_AUX INDEX 1.
*  MOVE:  WA_SAIDA_AUX-BANKS_1   TO VBANKS_1,
*         WA_SAIDA_AUX-BANKL_1   TO VBANKL_1,
*         WA_SAIDA_AUX-BANKN_1   TO VBANKN_1,
*         WA_SAIDA_AUX-IBAN_1    TO VIBAN_1.
*ENDIF.
*VSEQ = 0.
*V_VLR_PGTO = 0.
*LOOP AT IT_SAIDA_AUX INTO WA_SAIDA_AUX.
*  ADD 1 TO VSEQ.
*  ADD WA_SAIDA_RES-VLR_PGTO TO V_VLR_PGTO.
*
*  IF VBANKS_1 NE WA_SAIDA_AUX-BANKS_1 OR
*     VBANKL_1  NE WA_SAIDA_AUX-BANKL_1 OR
*     VBANKN_1 NE WA_SAIDA_AUX-BANKN_1 OR
*     VIBAN_1  NE WA_SAIDA_AUX-IBAN_1.
*    CLEAR WA_SAIDA_RES.
*    ADD 1 TO VSEQ.
*    WA_SAIDA_RES-SEQ      = VSEQ.
*    WA_SAIDA_RES-NAME1    = 'Total Banco/Conta'.
*    WA_SAIDA_RES-VLR_PGTO = V_VLR_PGTO.
*    APPEND WA_SAIDA_RES TO IT_SAIDA_RES.
*    V_VLR_PGTO = 0.
*  ENDIF.
*  MOVE-CORRESPONDING WA_SAIDA_AUX TO WA_SAIDA_RES.
*  WA_SAIDA_RES-SEQ      = VSEQ.
*  APPEND WA_SAIDA_RES TO IT_SAIDA_RES.
*ENDLOOP.
*IF  V_VLR_PGTO GT 0.
*  CLEAR WA_SAIDA_RES.
*  ADD 1 TO VSEQ.
*  WA_SAIDA_RES-SEQ      = VSEQ.
*  WA_SAIDA_RES-NAME1    = 'Total Banco/Conta'.
*  WA_SAIDA_RES-VLR_PGTO = V_VLR_PGTO.
*  APPEND WA_SAIDA_RES TO IT_SAIDA_RES.
*ENDIF.
*
*SORT IT_SAIDA_RES BY SEQ.


