
PROCESS BEFORE OUTPUT.
  CALL SUBSCREEN :
       SU_PAGAR          INCLUDING G_TAB_STRIP_IMP-PROG '6600',
       SU_ADIANTAMENTO   INCLUDING G_TAB_STRIP_IMP-PROG '6700'.

  MODULE STATUS_6000.
  MODULE TRATA_FIELDS_6000.
  MODULE CRIA_OBJETOS_6500.
*
PROCESS AFTER INPUT.
  MODULE USER_COMMAND_6500.
  MODULE USER_COMMAND_EXIT AT EXIT-COMMAND.
