
PROCESS BEFORE OUTPUT.
  CALL SUBSCREEN :
        SU_ADIANTAMENTO   INCLUDING G_TAB_STRIP_IMP-PROG '7100',
        SU_INVOICE        INCLUDING G_TAB_STRIP_IMP-PROG '7200'.

  MODULE STATUS_7000.
  "MODULE TRATA_FIELDS_7000.
  MODULE CRIA_OBJETOS_7000.
*
PROCESS AFTER INPUT.
  MODULE USER_COMMAND_7000.
  MODULE USER_COMMAND_EXIT AT EXIT-COMMAND.
