*----------------------------------------------------------------------*
***INCLUDE ZFIR0055_PBO.
*----------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&      Module  STATUS_0100  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_0100 OUTPUT.
  SET PF-STATUS 'PF0100'.
  SET TITLEBAR 'T0100'.
ENDMODULE.

*&---------------------------------------------------------------------*
*&      Module  CRIAR_OBJETOS_0100  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE CRIAR_OBJETOS_0100 OUTPUT.

  IF OBJ_CONTAINER IS INITIAL.

    PERFORM REFRESH_OBJETOS.
    PERFORM CRIAR_FIELD_CATALOG USING '0100'.

    CREATE OBJECT OBJ_CONTAINER
      EXPORTING
        CONTAINER_NAME = 'CC_ALV'.

    CREATE OBJECT OBJ_ALV
      EXPORTING
        I_PARENT = OBJ_CONTAINER.

    CREATE OBJECT OBJ_TOOLBAR
      EXPORTING
        IO_ALV_GRID = OBJ_ALV.

    GS_LAYOUT-ZEBRA    = 'X'.
    GS_VARIANT-REPORT  = SY-REPID.

    SET HANDLER: OBJ_TOOLBAR->ON_TOOLBAR          FOR OBJ_ALV,
                 OBJ_TOOLBAR->HANDLE_USER_COMMAND FOR OBJ_ALV.

    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_INSERT_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_DELETE_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_MOVE_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE_NEW_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_UNDO.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_CUT.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_REFRESH.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.

    CALL METHOD OBJ_ALV->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT            = GS_LAYOUT
        I_SAVE               = 'A'
        IT_TOOLBAR_EXCLUDING = IT_EXCLUDE_FCODE
        IS_VARIANT           = GS_VARIANT
      CHANGING
        IT_FIELDCATALOG      = IT_FCAT
        IT_OUTTAB            = T_SAIDA.

    SET HANDLER LCL_EVENT_HANDLER->HANDLE_HOTSPOT_CLICK FOR OBJ_ALV.

    CALL METHOD OBJ_ALV->REGISTER_EDIT_EVENT
      EXPORTING
        I_EVENT_ID = CL_GUI_ALV_GRID=>MC_EVT_ENTER.

    CALL METHOD OBJ_ALV->SET_READY_FOR_INPUT
      EXPORTING
        I_READY_FOR_INPUT = 1.

  ELSE.
    CALL METHOD OBJ_ALV->REFRESH_TABLE_DISPLAY
       EXPORTING
         IS_STABLE = WA_STABLE.
  ENDIF.


ENDMODULE.
*&---------------------------------------------------------------------*
*&      Module  STATUS_0101  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_0101 OUTPUT.
  SET PF-STATUS 'PF0101'.
  "SET TITLEBAR 'xxx'.
ENDMODULE.
*&---------------------------------------------------------------------*
*&      Module  STATUS_0102  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_0102 OUTPUT.

  DATA: VALUES  TYPE VRM_VALUES WITH HEADER LINE.

  SET PF-STATUS 'PF0102'.
*  SET TITLEBAR 'xxx'.

  REFRESH: VALUES.
  CLEAR: VALUES.

  VALUES-KEY  = 'D'.
  VALUES-TEXT = 'Cliente'.
  APPEND VALUES.

  VALUES-KEY  = 'K'.
  VALUES-TEXT = 'Fornecedor'.
  APPEND VALUES.

  VALUES-KEY  = 'S'.
  VALUES-TEXT = 'Razão'.
  APPEND VALUES.

  CALL FUNCTION 'VRM_SET_VALUES'
    EXPORTING
      ID              = 'ZFIT0121-KOART'
      VALUES          = VALUES[]
    EXCEPTIONS
      ID_ILLEGAL_NAME = 1
      OTHERS          = 2.


ENDMODULE.
*&---------------------------------------------------------------------*
*&      Module  STATUS_0103  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_0103 OUTPUT.
  SET PF-STATUS 'PF0103'.
  SET TITLEBAR 'T0103'.

  LOOP AT SCREEN.
    CASE SCREEN-NAME .
      WHEN 'ZFIT0080-BUKRS' OR
           'ZFIT0080-GJAHR' OR
           'ZFIT0080-MONAT'.

        IF T_SAIDA_0103[] IS NOT INITIAL.
          SCREEN-INPUT = '0'.
        ELSE.
          SCREEN-INPUT = '1'.
        ENDIF.

        MODIFY SCREEN.
    ENDCASE.
  ENDLOOP.

ENDMODULE.

MODULE CRIAR_OBJETOS_0103 OUTPUT.

   IF OBJ_CONTAINER_0103 IS INITIAL.

    PERFORM REFRESH_OBJETOS.
    PERFORM CRIAR_FIELD_CATALOG USING '0103'.

    CREATE OBJECT OBJ_CONTAINER_0103
      EXPORTING
        CONTAINER_NAME = 'CC_ALV_0103'.

    CREATE OBJECT OBJ_ALV_0103
      EXPORTING
        I_PARENT = OBJ_CONTAINER_0103.

    CREATE OBJECT OBJ_TOOLBAR_0103
      EXPORTING
        IO_ALV_GRID = OBJ_ALV_0103.

    GS_LAYOUT-ZEBRA    = 'X'.
    "GS_VARIANT-REPORT  = SY-REPID.

    SET HANDLER: OBJ_TOOLBAR_0103->ON_TOOLBAR          FOR OBJ_ALV_0103,
                 OBJ_TOOLBAR_0103->HANDLE_USER_COMMAND FOR OBJ_ALV_0103.

    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_INSERT_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    "WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_DELETE_ROW.
    "APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_MOVE_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE_NEW_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_UNDO.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_CUT.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_REFRESH.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.

    CALL METHOD OBJ_ALV_0103->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT            = GS_LAYOUT
        I_SAVE               = 'A'
        IT_TOOLBAR_EXCLUDING = IT_EXCLUDE_FCODE
        IS_VARIANT           = GS_VARIANT
      CHANGING
        IT_FIELDCATALOG      = IT_FCAT
        IT_OUTTAB            = T_SAIDA_0103.

    CALL METHOD OBJ_ALV_0103->REGISTER_EDIT_EVENT
      EXPORTING
        I_EVENT_ID = CL_GUI_ALV_GRID=>MC_EVT_ENTER.

    CALL METHOD OBJ_ALV_0103->SET_READY_FOR_INPUT
      EXPORTING
        I_READY_FOR_INPUT = 1.

  ELSE.
    CALL METHOD OBJ_ALV_0103->REFRESH_TABLE_DISPLAY
       EXPORTING
         IS_STABLE = WA_STABLE.
  ENDIF.


ENDMODULE.
