PROCESS BEFORE OUTPUT.
  MODULE STATUS_9000.
  CALL SUBSCREEN MAIN_TAB_TAB1_REF1
   INCLUDING I_MAIN_TAB-PROG I_MAIN_TAB-SUBSCREEN.
  CALL SUBSCREEN SCREEN_1010 INCLUDING SY-REPID '1010'.
*
PROCESS AFTER INPUT.
  CALL SUBSCREEN SCREEN_1010.
  CALL SUBSCREEN MAIN_TAB_TAB1_REF1.
  MODULE USER_COMMAND_9000.
  MODULE MAIN_TAB_ACTIVE_TAB_GET.
