*&---------------------------------------------------------------------*
*&  Include           ZFIR065_TOP
*&---------------------------------------------------------------------*

REPORT ZFIR065.

TABLES: T001, T001L, MARA, MCHB, T001W, J_1BBRANCH, S031, LFA1,MKPF, MBEW, MLKEY.

TYPES: BEGIN OF TY_ESTRUTURA.
         INCLUDE TYPE SLIS_FIELDCAT_MAIN.
         INCLUDE TYPE SLIS_FIELDCAT_ALV_SPEC.
       TYPES: END OF TY_ESTRUTURA.

TYPES: BEGIN OF TY_SAIDA_0100,
         BRANCH      TYPE J_1BBRANCH-BRANCH,
         WERKS       TYPE T001W-WERKS,
         DS_CENTRO   TYPE T001W-NAME1,
         LGORT       TYPE T001L-LGORT,
         LGOBE       TYPE T001L-LGOBE,
         LIFNR       TYPE LFA1-LIFNR,
         DS_FORN     TYPE LFA1-NAME1,
         CLASS       TYPE C LENGTH 30,
         MATNR       TYPE MARA-MATNR,
         MATKL       TYPE MARA-MATKL,
         MBWBEST     TYPE MBWBEST,
         NETPR       TYPE P LENGTH 16 DECIMALS 14,
         WBWBEST     TYPE WBWBEST,
         VLR_USD     TYPE CKMLCR-SALK3,
         VLR_UNT_USD TYPE CKMLCR-SALK3.
TYPES END OF TY_SAIDA_0100.

TYPES: BEGIN OF TY_MSLB,
         MATNR TYPE MSLB-MATNR,
         WERKS TYPE MSLB-WERKS,
         LIFNR TYPE MSLB-LIFNR,
         LBLAB TYPE MSLB-LBLAB,
         CHARG TYPE MSLB-CHARG,
         SOBKZ TYPE MSLB-SOBKZ,
         MATKL TYPE MATKL,
         LFGJA TYPE MSLB-LFGJA,
         LFMON TYPE MSLB-LFMON,
         SPMON TYPE ZDE_MC5_OUT-SPMON,
         NETPR TYPE P DECIMALS 14,
         AAMM  TYPE S031-SPMON.
TYPES END OF TY_MSLB.


DATA: BEGIN OF TG_ESTOQUE_MC_5 OCCURS 0,
        LIFNR       TYPE LFA1-LIFNR,
        NETPR       TYPE NETPR,
        ARMAZENAGEM TYPE C,
        DESMEMB     TYPE C.
        INCLUDE STRUCTURE ZDE_MC5_OUT.
      DATA: END OF TG_ESTOQUE_MC_5.

DATA: BEGIN OF TG_ESTOQUE_MC_5_USD OCCURS 0,
        LIFNR       TYPE LFA1-LIFNR,
        NETPR       TYPE NETPR,
        ARMAZENAGEM TYPE C,
        DESMEMB     TYPE C.
        INCLUDE STRUCTURE ZDE_MC5_OUT.
      DATA: END OF TG_ESTOQUE_MC_5_USD.

DATA: BEGIN OF TG_ESTOQUE_MB51 OCCURS 0,
        MATKL LIKE MARA-MATKL,
        MATNR LIKE MARA-MATNR,
        WERKS LIKE T001W-WERKS,
        LGORT LIKE MARD-LGORT,
        CHARG LIKE MCHB-CHARG,
        MENGE LIKE MARD-LABST,
        DMBTR TYPE DMBTR,
        NETPR TYPE P DECIMALS 14,
        LIFNR LIKE LFA1-LIFNR,
        EXBWR TYPE EXBWR.
DATA: END OF TG_ESTOQUE_MB51.


DATA: BEGIN OF TG_ENTRADA_ZCO0016 OCCURS 0,
        KALNR       TYPE CKMLHD-KALNR,
        MLAST       TYPE CKMLHD-MLAST,
        MATNR       TYPE CKMLHD-MATNR,
        BWKEY       TYPE CKMLHD-BWKEY,
        BWTAR       TYPE CKMLHD-BWTAR,
        SOBKZ       TYPE CKMLHD-SOBKZ,
        VBELN       TYPE CKMLHD-VBELN,
        POSNR       TYPE CKMLHD-POSNR,
        PSPNR       TYPE CKMLHD-PSPNR,
        BDATJ       TYPE CKMLPP-BDATJ,
        POPER       TYPE CKMLPP-POPER,
        STATUS      TYPE CKMLPP-STATUS,
        STATUS_TEXT TYPE DD07V-DDTEXT,
        KONTS       TYPE T030-KONTS,  "Conta razão
        CURTP       TYPE CKMLCR-CURTP,
        BKLAS       TYPE MBEW-BKLAS,
        WERKS       TYPE T001W-WERKS,
        MTART       TYPE MARA-MTART,
        MATKL       TYPE MARA-MATKL,
        SPART       TYPE MARA-SPART,
        KTEXT       TYPE MAKT-MAKTX,
        VPRSV       TYPE CKMLCR-VPRSV,
        LBKUM       TYPE CKMLPP-LBKUM, "quantidade estoque
        MEINS       TYPE MARA-MEINS,
        SALK3       TYPE CKMLCR-SALK3,
        SALK3_U     TYPE CKMLCR-SALK3,
        SALKV       TYPE CKMLCR-SALKV,
        EB_DIF      TYPE CKI_DOC_ML-EB_DIF,
        STPRS       TYPE CKMLCR-STPRS,
        PVPRS       TYPE CKMLCR-PVPRS,
        PRABW_PRZ   TYPE CK_PRABW_PRZ,
        PEINH       TYPE CKMLCR-PEINH,
        WAERS       TYPE WAERS,
        GSBER       TYPE T134G-GSBER.
DATA: END OF TG_ENTRADA_ZCO0016.



DATA: BAPI_GSTRU LIKE MCYA-GSTRU.

DATA: BEGIN OF CHARAC OCCURS 10.
        INCLUDE STRUCTURE FNAME.
      DATA: END OF CHARAC.

DATA: BEGIN OF PERFOR OCCURS 10.
        INCLUDE STRUCTURE FNAME.
      DATA: END OF PERFOR.

DATA: BEGIN OF VIEWBOX OCCURS 10.
        INCLUDE STRUCTURE FNAME.
      DATA: END OF VIEWBOX.

DATA: BEGIN OF SELPER OCCURS 10.
        INCLUDE STRUCTURE MCSELPER.
      DATA: END OF SELPER.

DATA: BEGIN OF SELCHA OCCURS 10.
        INCLUDE STRUCTURE MCSELPER.
      DATA: END OF SELCHA.

DATA BEGIN OF DATA OCCURS 10.
        INCLUDE STRUCTURE MCDATA.
DATA END OF DATA.

*---------------------------------------------------------------------*
*  Inicio Definition Classes
*---------------------------------------------------------------------*

CLASS LCL_ALV_TOOLBAR_0100 DEFINITION.
  PUBLIC SECTION.
*Constructor
    METHODS: CONSTRUCTOR
      IMPORTING IO_ALV_GRID TYPE REF TO CL_GUI_ALV_GRID,
*Event for toolbar
      ON_TOOLBAR FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
        IMPORTING E_OBJECT,

      HANDLE_USER_COMMAND FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
        IMPORTING E_UCOMM.

ENDCLASS.                    "LCL_ALV_TOOLBAR DEFINITION

CLASS LCL_EVENT_HANDLER_0100 DEFINITION.
  PUBLIC SECTION.

    CLASS-METHODS:
      CATCH_HOTSPOT FOR EVENT HOTSPOT_CLICK OF CL_GUI_ALV_GRID
        IMPORTING E_ROW_ID E_COLUMN_ID ES_ROW_NO.
ENDCLASS.

DATA: OBJ_ALV_0100       TYPE REF TO CL_GUI_ALV_GRID,
      OBJ_CONTAINER_0100 TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA: GT_CATALOG TYPE LVC_T_FCAT,
      GW_CATALOG TYPE LVC_S_FCAT.

DATA: OBJ_TOOLBAR_0100 TYPE REF TO LCL_ALV_TOOLBAR_0100.

* ALV field catalogs
DATA: IT_FCAT TYPE LVC_T_FCAT,
      WA_FCAT TYPE LVC_S_FCAT.

* ALV excluded functions
DATA: IT_EXCLUDE_FCODE TYPE UI_FUNCTIONS,
      WA_EXCLUDE_FCODE LIKE LINE OF IT_EXCLUDE_FCODE.

* Alv Styles
DATA: LS_EDIT TYPE LVC_S_STYL,
      LT_EDIT TYPE LVC_T_STYL.

* ALV layout variant
DATA: GS_VARIANT       TYPE DISVARIANT.

* ALV layout
DATA: GS_LAYOUT        TYPE LVC_S_LAYO.

* ALV Stable
DATA: WA_STABLE        TYPE LVC_S_STBL.

DATA: IT_SELECTEDCELL TYPE LVC_T_CELL,
      WA_SELECTEDCELL TYPE LVC_S_CELL.

DATA: IT_SEL_ROWS TYPE LVC_T_ROW,
      WA_SEL_ROWS TYPE LVC_S_ROW.

DATA: GT_ESTILO TYPE LVC_T_STYL WITH HEADER LINE,
      WL_ESTILO TYPE LVC_S_STYL.

DATA: GT_F4  TYPE LVC_T_F4 WITH HEADER LINE.

* Objetos
DATA: C_ALV_TOOLBARMANAGER TYPE REF TO CL_ALV_GRID_TOOLBAR_MANAGER,
      TY_TOOLBAR           TYPE STB_BUTTON.

DATA: WA_ESTRUTURA TYPE TY_ESTRUTURA,
      ESTRUTURA    TYPE TABLE OF TY_ESTRUTURA.

*-------------------------------------------------------------------
* Tabelas Internas and Work Areas.
*-------------------------------------------------------------------
DATA: IT_SAIDA_0100           TYPE TABLE OF TY_SAIDA_0100,
      WA_SAIDA_0100           TYPE TY_SAIDA_0100,
      TG_T001W                TYPE TABLE OF T001W WITH HEADER LINE,
      TG_T001L                TYPE TABLE OF T001L WITH HEADER LINE,
      TG_LFA1                 TYPE TABLE OF LFA1 WITH HEADER LINE,
      TG_MARA                 TYPE TABLE OF MARA WITH HEADER LINE,
      TG_MSLB_DT_BASE         TYPE TABLE OF TY_MSLB WITH HEADER LINE,
      TG_MSLB                 TYPE TABLE OF TY_MSLB WITH HEADER LINE,
      TG_MSLB_GRP             TYPE TABLE OF TY_MSLB WITH HEADER LINE,
      TG_ESTOQUE_MB51_GRP     LIKE TABLE OF TG_ESTOQUE_MB51 WITH HEADER LINE,
      TG_ESTOQUE_MC_5_AUX     LIKE TABLE OF TG_ESTOQUE_MC_5 WITH HEADER LINE,
      TG_ESTOQUE_MC_5_USD_AUX LIKE TABLE OF TG_ESTOQUE_MC_5 WITH HEADER LINE,
      TG_ZSDT_DEPARA_DEPO     TYPE TABLE OF ZSDT_DEPARA_DEPO WITH HEADER LINE,
      TG_ZSDT_DEPARA_CEN      TYPE TABLE OF ZSDT_DEPARA_CEN  WITH HEADER LINE,
      R_WERKS                 TYPE RANGE OF WERKS_D.

FIELD-SYMBOLS: <LT_DATA>      TYPE ANY TABLE,
               <LT_DATA_LINE> TYPE ANY TABLE,
               <LS_DATA>      TYPE ANY,
               <LS_DATA_LINE> TYPE ANY.

DATA: LR_DATA            TYPE REF TO DATA,
      LR_DATA_LINE       TYPE REF TO DATA,
      LR_DATA_DESCR      TYPE REF TO CL_ABAP_DATADESCR,
      LR_DATA_LINE_DESCR TYPE REF TO CL_ABAP_DATADESCR.

*-------------------------------------------------------------------
* Váriaveis
*-------------------------------------------------------------------
DATA: VG_OPERACAO TYPE C LENGTH 20,
      VAR_ANSWER  TYPE C.

*-------------------------------------------------------------------
* Váriaveis Titualo
*-------------------------------------------------------------------
DATA: VG_MATNR     TYPE C LENGTH 20,
      VG_DT_FIM    TYPE C LENGTH 20,
      VG_DT_FIM_IN TYPE SY-DATUM,
      VL_UNI_USD   TYPE P DECIMALS 14.

*----------------------------------------------------------------------*
* Tela de Seleção
*----------------------------------------------------------------------*
SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: "P_BUKRS  FOR T001-BUKRS        OBLIGATORY,
                P_BRANCH FOR J_1BBRANCH-BRANCH,
*                P_WERKS  FOR T001L-WERKS,
                P_WERKS  FOR MLKEY-WERKS_ML_PRODUCTIVE MEMORY ID WRK,
                P_LGORT  FOR T001L-LGORT,
                P_MATNR  FOR MARA-MATNR,
                P_MTART  FOR MARA-MTART MEMORY ID MTA,
                P_BKLAS  FOR MBEW-BKLAS,
                P_MATKL  FOR MARA-MATKL,
                P_LIFNR  FOR LFA1-LIFNR,
*                P_DTBASE FOR MKPF-BUDAT  NO-EXTENSION NO INTERVALS OBLIGATORY.
P_DTBASE FOR S031-SPMON NO-EXTENSION NO INTERVALS OBLIGATORY.

PARAMETERS: P_ARM TYPE C AS CHECKBOX.

SELECTION-SCREEN: END OF BLOCK B1.

AT SELECTION-SCREEN OUTPUT.

  IF P_BRANCH[] IS NOT INITIAL.

    SELECT *
      FROM ZSDT_DEPARA_CEN
      INTO TABLE @DATA(IT_ZSDT_DEPARA_CEN)
        WHERE CENTRO_REAL IN @P_BRANCH.

    LOOP AT IT_ZSDT_DEPARA_CEN INTO DATA(WA_DEPARA_CEN).
      APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = WA_DEPARA_CEN-CENTROV_1 ) TO R_WERKS.
    ENDLOOP.

  ENDIF.

  LOOP AT P_BRANCH.
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = P_BRANCH-LOW  ) TO R_WERKS.
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = P_BRANCH-HIGH ) TO R_WERKS.
  ENDLOOP.

  LOOP AT P_WERKS.
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = P_WERKS-LOW  ) TO R_WERKS.
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = P_WERKS-HIGH ) TO R_WERKS.
  ENDLOOP.

  SORT R_WERKS.
  DELETE ADJACENT DUPLICATES FROM R_WERKS COMPARING ALL FIELDS.



START-OF-SELECTION.

  PERFORM: F_SELECIONAR_DADOS,
           F_PROCESSA_DADOS.

  CALL SCREEN 0100.
