
PROCESS BEFORE OUTPUT.
  MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
  MODULE USER_COMMAND_0100.


PROCESS ON VALUE-REQUEST.
  FIELD WG_CADLAN-TIPO  MODULE SEARCH_TIPO.
  FIELD WG_CADLAN-PERFO MODULE SEARCH_PERFO.
