PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZFIT0014-TIPO_I .
    FIELD ZFIT0014-DATA_INI .
    FIELD ZFIT0014-DATA_FIM .
    FIELD ZFIT0014-PERCENTUAL .
    FIELD ZFIT0014-C_USER .
    FIELD ZFIT0014-DATA .
    FIELD ZFIT0014-HORA .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZFIT0014-TIPO_I .
    FIELD ZFIT0014-DATA_INI .
  module detail_pai.
 endchain.
