FUNCTION ZMMF_ATUALIZA_ZFIT0156.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(JSON_RESULT) TYPE  STRING
*"  EXPORTING
*"     REFERENCE(JSON_RESPONSE) TYPE  STRING
*"----------------------------------------------------------------------


TYPES: BEGIN OF TY_ZFIT0156_RESULT,
        IDEMPRESA TYPE BUKRS,
        NRDOCUMENTOCONTABIL TYPE BELNR_D,
        NRLANCAMENTODOCCONTABIL TYPE BUZEI,
        NRCONTAFORNECEDOR TYPE LIFNR,
        LOTESIGAM TYPE ZLOTE,
        VALORLOTE TYPE DMBTR,
        VALORRESI TYPE DMBTR,
        RGATUALIZADO TYPE CHAR1,
      END OF TY_ZFIT0156_RESULT.

DATA IT_ZFIT0156_API  TYPE TABLE OF  TY_ZFIT0156_RESULT.
DATA IT_ZFIT0156 TYPE TABLE OF ZFIT0156.
DATA WA_ZFIT0156 TYPE ZFIT0156.


/UI2/CL_JSON=>DESERIALIZE( EXPORTING JSON = JSON_RESULT PRETTY_NAME = /UI2/CL_JSON=>PRETTY_MODE-CAMEL_CASE CHANGING DATA = IT_ZFIT0156_API ).


LOOP AT IT_ZFIT0156_API INTO DATA(WA_ZFIT0156_API).

   WA_ZFIT0156-BUKRS = WA_ZFIT0156_API-IDEMPRESA.
   WA_ZFIT0156-BELNR = WA_ZFIT0156_API-NRDOCUMENTOCONTABIL.
   WA_ZFIT0156-BUZEI = WA_ZFIT0156_API-NRLANCAMENTODOCCONTABIL.
   WA_ZFIT0156-LIFNR = WA_ZFIT0156_API-NRCONTAFORNECEDOR.
   WA_ZFIT0156-LOTE  = WA_ZFIT0156_API-LOTESIGAM.
   WA_ZFIT0156-VLR_LOTE = WA_ZFIT0156_API-VALORLOTE.
   WA_ZFIT0156-VLR_RESI = WA_ZFIT0156_API-VALORRESI.
   WA_ZFIT0156-RG_ATUALIZADO = WA_ZFIT0156_API-RGATUALIZADO.

  APPEND WA_ZFIT0156 TO IT_ZFIT0156.

ENDLOOP.

MODIFY ZFIT0156 FROM TABLE IT_ZFIT0156.


JSON_RESPONSE =  COND #( WHEN SY-SUBRC IS INITIAL THEN '{ "RESULT": "SUCCESS" }' ELSE  '{ "RESULT": "ERROR" }' ).


ENDFUNCTION.
