PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIT0078 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIT0078-SAKNR .
    FIELD ZFIT0078-COD_FLX .
    FIELD ZFIT0078-MATKL .
    FIELD ZFIT0078-PRCTR .
    FIELD ZFIT0078-KIDNO .
    FIELD ZFIT0078-ZUONR .
    FIELD ZFIT0078-BLART .
    FIELD ZFIT0078-BSCHL .
    FIELD ZFIT0078-RMVCT .
    FIELD ZFIT0078-USNAM .
    FIELD ZFIT0078-DT_ATUAL .
    FIELD ZFIT0078-HR_ATUAL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIT0078-SAKNR .
    FIELD ZFIT0078-COD_FLX .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
