FUNCTION ZMMF_ATUALIZA_ZFIT0155.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(JSON_RESULT) TYPE  STRING
*"  EXPORTING
*"     REFERENCE(JSON_RESPONSE) TYPE  STRING
*"----------------------------------------------------------------------

TYPES: BEGIN OF TY_ZFIT0155_RESULT,
        IDEMPRESA TYPE BUKRS,
        NRDOCUMENTOCONTABIL TYPE BELNR_D,
        ANOEXERCICIO TYPE GJAHR,
        NRLANCAMENTODOCCONTABIL TYPE BUZEI,
        LOTESIGAM TYPE ZLOTE,
        RGATUALIZADO TYPE CHAR1,
      END OF TY_ZFIT0155_RESULT.
DATA IT_ZFIT0155_API  TYPE TABLE OF  TY_ZFIT0155_RESULT.

DATA IT_ZFIT0155 TYPE TABLE OF ZFIT0155.
DATA WA_ZFIT0155 TYPE ZFIT0155.


/UI2/CL_JSON=>DESERIALIZE( EXPORTING JSON = JSON_RESULT PRETTY_NAME = /UI2/CL_JSON=>PRETTY_MODE-CAMEL_CASE CHANGING DATA = IT_ZFIT0155_API ).


LOOP AT IT_ZFIT0155_API INTO DATA(WA_ZFIT0155_API).

   WA_ZFIT0155-BUKRS = WA_ZFIT0155_API-IDEMPRESA.
   WA_ZFIT0155-BELNR = WA_ZFIT0155_API-NRDOCUMENTOCONTABIL.
   WA_ZFIT0155-GJAHR = WA_ZFIT0155_API-ANOEXERCICIO.
   WA_ZFIT0155-BUZEI = WA_ZFIT0155_API-NRLANCAMENTODOCCONTABIL.
   WA_ZFIT0155-LOTE  = WA_ZFIT0155_API-LOTESIGAM.
   WA_ZFIT0155-RG_ATUALIZADO = WA_ZFIT0155_API-RGATUALIZADO.

  APPEND WA_ZFIT0155 TO IT_ZFIT0155.

ENDLOOP.

MODIFY ZFIT0155 FROM TABLE IT_ZFIT0155.

JSON_RESPONSE =  COND #( WHEN SY-SUBRC IS INITIAL THEN '{ "RESULT": "SUCCESS" }' ELSE  '{ "RESULT": "ERROR" }' ).

ENDFUNCTION.
