PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZFIT0015-SAKNR .
    FIELD ZFIT0015-BUKRS .
    FIELD ZFIT0015-WERKS .
    FIELD ZFIT0015-KOSTL .
    FIELD ZFIT0015-C_USER .
    FIELD ZFIT0015-DATA .
    FIELD ZFIT0015-HORA .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZFIT0015-SAKNR .
    FIELD ZFIT0015-BUKRS .
    FIELD ZFIT0015-WERKS .
    FIELD ZFIT0015-KOSTL .
  module detail_pai.
 endchain.
