PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIT0059 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIT0059-OPR_NUMERO .
    FIELD ZFIT0059-PFJ_CODIGO .
    FIELD ZFIT0059-MDO_TIPO .
    FIELD ZFIT0059-PFJ_AGENTE .
    FIELD ZFIT0059-DATA_REALIZACAO .
    FIELD ZFIT0059-DATA_VENCIMENTO .
    FIELD ZFIT0059-POSICAO .
    FIELD ZFIT0059-MDO_CODIGO .
    FIELD ZFIT0059-TIPO_OPERACAO .
    FIELD ZFIT0059-VALOR_OPERACAO .
    FIELD ZFIT0059-MOEDA .
    FIELD ZFIT0059-TX_DOLAR_IN_OP .
    FIELD ZFIT0059-INDEX_PASSIVO .
    FIELD ZFIT0059-TX_IND_ATIVO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIT0059-OPR_NUMERO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
