PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIT0133 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIT0133-CHAVE_REFERENCIA .
    FIELD ZFIT0133-MVT_CONTADOR .
    FIELD ZFIT0133-CONTRATO_NUMERO .
    FIELD ZFIT0133-DATA_ORIGEM .
    FIELD ZFIT0133-ID_SISTEMA .
    FIELD ZFIT0133-OPERACAO_ID .
    FIELD ZFIT0133-OPERACAO_DESCRICAO .
    FIELD ZFIT0133-DATA_BAIXA .
    FIELD ZFIT0133-TIPO .
    FIELD ZFIT0133-CREDITO_DEBITO .
    FIELD ZFIT0133-APROPRIACAO_CAIXA .
    FIELD ZFIT0133-VALOR_ORIGINAL_D .
    FIELD ZFIT0133-VALOR_ORIGINAL_R .
    FIELD ZFIT0133-VR_COTACAO .
    FIELD ZFIT0133-ID_EMPRESA_SAP .
    FIELD ZFIT0133-ID_FILIAL_SAP .
    FIELD ZFIT0133-PARCEIRO_ID .
    FIELD ZFIT0133-CONTA_CONTABIL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIT0133-CHAVE_REFERENCIA .
    FIELD ZFIT0133-MVT_CONTADOR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
