PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIT0049 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIT0049-DT_REFERENCIA .
    FIELD ZFIT0049-ME_ANO .
    FIELD ZFIT0049-TIPO .
    FIELD ZFIT0049-MATNR .
    FIELD ZFIT0049-VALOR_COTACAO .
    FIELD ZFIT0049-DATA_ATUAL .
    FIELD ZFIT0049-HORA_ATUAL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIT0049-DT_REFERENCIA .
    FIELD ZFIT0049-ME_ANO .
    FIELD ZFIT0049-TIPO .
    FIELD ZFIT0049-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
