PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIT0036 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIT0036-OBJ_KEY .
    FIELD ZFIT0036-BUKRS .
    FIELD ZFIT0036-INVOICE .
    FIELD ZFIT0036-NAVIO .
    FIELD ZFIT0036-LOTE .
    FIELD ZFIT0036-DT_PGTO .
    FIELD ZFIT0036-TX_CAMBIO .
    FIELD ZFIT0036-MOEDA_PGTO .
    FIELD ZFIT0036-VLR_PGTO .
    FIELD ZFIT0036-HBKID .
    FIELD ZFIT0036-OBSERVACAO .
    FIELD ZFIT0036-FORMA_PG .
    FIELD ZFIT0036-MOTIVO .
    FIELD ZFIT0036-STATUS .
    FIELD ZFIT0036-RG_ATUALIZADO .
    FIELD ZFIT0036-STATUS_CTAS_REC .
    FIELD ZFIT0036-STATUS_ARQ_INV .
    FIELD ZFIT0036-DATA_ATUAL .
    FIELD ZFIT0036-HORA_ATUAL .
    FIELD ZFIT0036-USUARIO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIT0036-OBJ_KEY .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
