PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIWRT2002 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIWRT2002-BWART .
    FIELD ZFIWRT2002-FUNCTION_NAME .
    FIELD ZFIWRT2002-PAR_NAME .
    FIELD ZFIWRT2002-PAR_NAME2 .
    FIELD ZFIWRT2002-PAR_VALUE .
    FIELD ZFIWRT2002-PAR_VALUE2 .
    FIELD ZFIWRT2002-PAR_FIXO .
    FIELD ZFIWRT2002-PAR_INPUT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIWRT2002-BWART .
    FIELD ZFIWRT2002-FUNCTION_NAME .
    FIELD ZFIWRT2002-PAR_NAME .
    FIELD ZFIWRT2002-PAR_NAME2 .
    FIELD ZFIWRT2002-PAR_VALUE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
