PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZFIWRT0029-BUKRS .
    FIELD ZFIWRT0029-WERKS .
    FIELD ZFIWRT0029-CFOPT .
    FIELD ZFIWRT0029-CFOPZ .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZFIWRT0029-BUKRS .
    FIELD ZFIWRT0029-WERKS .
    FIELD ZFIWRT0029-CFOPT .
  module detail_pai.
 endchain.
