PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZFIYT_EXCLUSION-BUKRS .
    FIELD ZFIYT_EXCLUSION-LIFNR .
    FIELD ZFIYT_EXCLUSION-FECHA .
    FIELD ZFIYT_EXCLUSION-HORA .
    FIELD ZFIYT_EXCLUSION-INDICADOR .
    FIELD ZFIYT_EXCLUSION-TEXTO .
    FIELD ZFIYT_EXCLUSION-TIPO .
    FIELD ZFIYT_EXCLUSION-STCD1 .
    FIELD ZFIYT_EXCLUSION-NAME1 .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZFIYT_EXCLUSION-BUKRS .
    FIELD ZFIYT_EXCLUSION-LIFNR .
    FIELD ZFIYT_EXCLUSION-FECHA .
    FIELD ZFIYT_EXCLUSION-HORA .
    FIELD ZFIYT_EXCLUSION-INDICADOR .
  module detail_pai.
 endchain.
