*&---------------------------------------------------------------------*
*&  Include           ZFIY0032_TOP
*&---------------------------------------------------------------------*

TYPES: BEGIN OF TY_ESTRUTURA.
        INCLUDE TYPE SLIS_FIELDCAT_MAIN.
        INCLUDE TYPE SLIS_FIELDCAT_ALV_SPEC.
TYPES: END OF TY_ESTRUTURA.

TYPES: BEGIN OF TY_SAIDA,
         ZBUKR           TYPE REGUP-ZBUKR,
         GJAHR           TYPE REGUP-GJAHR,
         LAUFI           TYPE REGUP-LAUFI,
         BELNR           TYPE REGUP-BELNR,
         XVORL           TYPE REGUP-XVORL,
         KIDNO           TYPE REGUP-KIDNO,
         FATURA          TYPE REGUP-XBLNR,
         PGTO_MERC       TYPE DMBTR,
         VLR_MERC        TYPE DMBTR,
         TOT_IVA         TYPE BSET-HWSTE,
         PERC_IVA        TYPE DMBTR,
         TOT_OPERC       TYPE DMBTR,
         FIN_PAG         TYPE DMBTR,
         LIFNR           TYPE ZMMT_EE_ZGR-LIFNR,
         CORRETOR        TYPE LFA1-NAME1,
         CD_FORN         TYPE ZMMT_EE_ZGR-LIFNR,
         VENDEDOR        TYPE LFA1-NAME1,
         IVA_PAG         TYPE REGUPW-WT_QSSHH,
         ALIQUOTA        TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_01     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_01     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_01     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_02     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_02     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_02     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_03     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_03     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_03     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_04     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_04     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_04     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_05     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_05     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_05     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_06     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_06     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_06     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_07     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_07     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_07     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_08     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_08     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_08     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_09     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_09     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_09     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_10     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_10     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_10     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_11     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_11     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_11     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_12     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_12     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_12     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_13     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_13     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_13     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_14     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_14     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_14     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_15     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_15     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_15     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_16     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_16     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_16     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_17     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_17     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_17     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_18     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_18     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_18     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_19     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_19     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_19     TYPE REGUPW-WT_QSSHH,

         WT_QSSHH_20     TYPE REGUPW-WT_QSSHH,
         WT_QBSHH_20     TYPE REGUPW-WT_QBSHH,
         PER_ALIQ_20     TYPE REGUPW-WT_QSSHH,

         PAGO            TYPE ZMMT_EE_ZGR-LIFNR,
         TP_COMPROB      TYPE C LENGTH 4,
         ORIG_MERC       TYPE C LENGTH 4,
         PO_NUMBER       TYPE ZMMT_EE_ZGR-PO_NUMBER,
         NRO_MIRO        TYPE ZMMT_EE_ZGR_DOCS-FT_BELNR,
         ENTRY_QNT       TYPE ZMMT_EE_ZGR-ENTRY_QNT,
         MATNR           TYPE ZMMT_EE_ZGR-MATERIAL,
         MAKTX           TYPE MAKT-MAKTX,
       END OF TY_SAIDA.

DATA: BEGIN OF TG_REGUP OCCURS 0,
        LAUFD   TYPE REGUP-LAUFD,
        ZBUKR   TYPE REGUP-ZBUKR,
        LIFNR   TYPE REGUP-LIFNR,
        LAUFI   TYPE REGUP-LAUFI,
        XVORL   TYPE REGUP-XVORL,
        BELNR   TYPE REGUP-BELNR,
        BUZEI   TYPE REGUP-BUZEI,
        GJAHR   TYPE REGUP-GJAHR,
        WAERS   TYPE REGUP-WAERS,
        HBKID   TYPE REGUP-HBKID,
        XBLNR   TYPE REGUP-XBLNR,
        BUDAT   TYPE REGUP-BUDAT,
        BLDAT   TYPE REGUP-BLDAT,
        DMBTR   TYPE REGUP-DMBTR,
        KIDNO   TYPE REGUP-KIDNO,
      END OF TG_REGUP,

      BEGIN OF TG_LFA1 OCCURS 0,
        LIFNR   TYPE LFA1-LIFNR,
        NAME1   TYPE LFA1-NAME1,
      END OF TG_LFA1,

      BEGIN OF TG_BKPF OCCURS 0,
        BUKRS	    TYPE BKPF-BUKRS,
        BELNR	    TYPE BKPF-BELNR,
        GJAHR	    TYPE BKPF-GJAHR,
        AWKEY     TYPE BKPF-AWKEY,
        USNAM     TYPE BKPF-USNAM,
        CPUDT     TYPE BKPF-CPUDT,
        CPUTM     TYPE BKPF-CPUTM,
        TCODE     TYPE BKPF-TCODE,
        XSPLIT    TYPE C,
        XAWKEY    TYPE BKPF-AWKEY,
      END OF TG_BKPF,

      BEGIN OF TG_EE_GR_DOC  OCCURS 0,
        OBJ_KEY   TYPE ZMMT_EE_ZGR_DOCS-OBJ_KEY,
        FT_BELNR  TYPE ZMMT_EE_ZGR_DOCS-FT_BELNR,
        FT_GJAHR  TYPE ZMMT_EE_ZGR_DOCS-FT_GJAHR,
        BUKRS     TYPE BKPF-BUKRS,
        GJAHR     TYPE BKPF-GJAHR,
        BELNR     TYPE BKPF-BELNR,
        IVA_BELNR TYPE BKPF-BELNR,
        TAX_CODE  TYPE ZMMT_EE_ZGR-TAX_CODE,
        XAWKEY    TYPE BKPF-AWKEY,
      END OF TG_EE_GR_DOC,

      BEGIN OF TG_EE_GR  OCCURS 0,
        OBJ_KEY       TYPE ZMMT_EE_ZGR-OBJ_KEY,
        PO_NUMBER     TYPE ZMMT_EE_ZGR-PO_NUMBER,
        ENTRY_QNT     TYPE ZMMT_EE_ZGR-ENTRY_QNT,
        TAX_CODE      TYPE ZMMT_EE_ZGR-TAX_CODE,
        GROSS_AMOUNT  TYPE ZMMT_EE_ZGR-GROSS_AMOUNT,
        VL_CMV        TYPE ZMMT_EE_ZGR-VL_CMV,
        LIFNR         TYPE ZMMT_EE_ZGR-LIFNR,
        MATERIAL      TYPE ZMMT_EE_ZGR-MATERIAL,
      END OF TG_EE_GR,

      BEGIN OF TG_MAKT OCCURS 0,
        MATNR TYPE MAKT-MATNR,
        MAKTX TYPE MAKT-MAKTX,
      END OF TG_MAKT,

      BEGIN OF TG_BSET OCCURS 0,
        BUKRS TYPE  BSET-BUKRS,
        BELNR TYPE  BSET-BELNR,
        GJAHR TYPE  BSET-GJAHR,
        BUZEI TYPE  BSET-BUZEI,
        MWSKZ TYPE  BSET-MWSKZ,
        HWSTE TYPE  BSET-HWSTE,
      END OF TG_BSET,

      BEGIN OF TG_REGUPW OCCURS 0,
        LAUFD       TYPE  REGUPW-LAUFD,
        LAUFI       TYPE  REGUPW-LAUFI,
        BUKRS       TYPE  REGUPW-BUKRS,
        BELNR       TYPE  REGUPW-BELNR,
        GJAHR       TYPE  REGUPW-GJAHR,
        BUZEI       TYPE  REGUPW-BUZEI,
        WT_QSSHH    TYPE  REGUPW-WT_QSSHH,
        WT_QBSHH    TYPE  REGUPW-WT_QBSHH,
        WITHT       TYPE  REGUPW-WITHT,
        WT_WITHCD   TYPE  REGUPW-WT_WITHCD,
      END OF TG_REGUPW,

      BEGIN OF TG_T059P OCCURS 0,
        LAND1   TYPE T059P-LAND1,
        WITHT   TYPE T059P-WITHT,
        TEXT40  TYPE T059U-TEXT40,
      END OF TG_T059P.

 DATA: TG_BKPF_IVA  LIKE TABLE OF TG_BKPF WITH HEADER LINE,
       TG_REGUP_AUX LIKE TABLE OF TG_REGUP WITH HEADER LINE,
       TG_BKPF_AUX  LIKE TABLE OF TG_BKPF  WITH HEADER LINE,
       IT_SAIDA TYPE TABLE OF TY_SAIDA,
       WA_SAIDA TYPE TY_SAIDA.

*---------------------------------------------------------------------*
*  Variáveis
*---------------------------------------------------------------------*

 DATA: VG_NOT_FOUND TYPE C.


*----------------------------------------------------------------------*
* Estruturas ALV
*----------------------------------------------------------------------*
DATA: XS_EVENTS    TYPE SLIS_ALV_EVENT,
      EVENTS       TYPE SLIS_T_EVENT,
      T_PRINT      TYPE SLIS_PRINT_ALV,
      ESTRUTURA    TYPE TABLE OF TY_ESTRUTURA,
      WA_ESTRUTURA TYPE TY_ESTRUTURA,
      V_REPORT     LIKE SY-REPID,
      T_TOP        TYPE SLIS_T_LISTHEADER,
      GS_VARIANT   TYPE DISVARIANT.


*-------------------------------------------------------------------
* Variaveis Colunns
*-------------------------------------------------------------------
DATA: WITHT_01 TYPE T059P-WITHT,
      WITHT_02 TYPE T059P-WITHT,
      WITHT_03 TYPE T059P-WITHT,
      WITHT_04 TYPE T059P-WITHT,
      WITHT_05 TYPE T059P-WITHT,
      WITHT_06 TYPE T059P-WITHT,
      WITHT_07 TYPE T059P-WITHT,
      WITHT_08 TYPE T059P-WITHT,
      WITHT_09 TYPE T059P-WITHT,
      WITHT_10 TYPE T059P-WITHT,
      WITHT_11 TYPE T059P-WITHT,
      WITHT_12 TYPE T059P-WITHT,
      WITHT_13 TYPE T059P-WITHT,
      WITHT_14 TYPE T059P-WITHT,
      WITHT_15 TYPE T059P-WITHT,
      WITHT_16 TYPE T059P-WITHT,
      WITHT_17 TYPE T059P-WITHT,
      WITHT_18 TYPE T059P-WITHT,
      WITHT_19 TYPE T059P-WITHT,
      WITHT_20 TYPE T059P-WITHT.
