
CLEAR: LV_IIBB, LV_INAC, LV_IVA, LV_IVA1,
       LV_ADRNR, LV_CODPOS, LV_DIR2.

* BUSCO DATOS DE IIBB
SELECT SINGLE PAVAL INTO LV_IIBB
         FROM T001Z
        WHERE BUKRS EQ GS_EMISOR-BUKRS
          AND PARTY EQ  'J1AGIB'.

CONCATENATE  LV_IIBB(3) LV_IIBB(6) LV_IIBB(1)
       INTO LV_IIBB SEPARATED BY '-'.

* BUSCO DATOS DE INCIO DE ACTIVIDAD
SELECT SINGLE PAVAL INTO LV_INAC
         FROM T001Z
        WHERE BUKRS EQ GS_EMISOR-BUKRS
          AND PARTY EQ  'J1AFDT'.

* BUSCO LA CONDICION DE IVA
SELECT SINGLE PAVAL INTO LV_IVA
         FROM T001Z
        WHERE BUKRS EQ GS_EMISOR-BUKRS
          AND PARTY EQ  'J1AFTV'.

 IF SY-SUBRC EQ 0.
   SELECT SINGLE TEXT60 INTO LV_IVA1
            FROM J_1AFITPVT
           WHERE SPRAS EQ SY-LANGU
             AND J_1AFITP EQ LV_IVA(2).
 ENDIF.

* BUSCO EL NRO DE DIRECCION INTERNO
SELECT SINGLE ADRNR INTO LV_ADRNR
         FROM T001
        WHERE BUKRS EQ GS_EMISOR-BUKRS.

IF SY-SUBRC EQ 0.
  SELECT SINGLE POST_CODE1 STR_SUPPL3
           INTO (LV_CODPOS, LV_DIR2)
           FROM ADRC
          WHERE ADDRNUMBER EQ LV_ADRNR.
ENDIF.



















