PROCESS BEFORE OUTPUT.

  MODULE STATUS_0100.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_0100_EXIT AT EXIT-COMMAND.

  MODULE GET_SCROLL_INFO_0100.

  MODULE GET_SELECTED_ROWS_0100.

  MODULE USER_COMMAND_0100.
