
DATA: STL_BKPF TYPE BKPF                   ,
      ST_BUKRS TYPE BUKRS                  ,
      STL_CURR TYPE TY_CURR                ,
      TL_CURR  TYPE TYT_CURR               ,
      VL_FECHA TYPE CHAR10                 ,
      VL_AUX   TYPE CHAR10                 ,
      VL_TABIX TYPE SY-TABIX               ,
      VL_WAERS TYPE WAERS                  ,
      VL_GDATU TYPE GDATU_INV              ,
      VL_DATUM TYPE DATUM                  ,
      VL_KURS2 TYPE CHAR8                  .

*Busco facturas que la moneda sea distinta a ars
LOOP AT GT_PAGO_POS INTO ST_PAGO_POS
WHERE WAERS NE 'ARS'.
  MOVE ST_PAGO_POS-WAERS  TO VL_WAERS .
  EXIT.
ENDLOOP.

IF VL_WAERS NE 'ARS'.

  SELECT SINGLE *
  FROM BKPF
  INTO STL_BKPF
  WHERE BELNR EQ GS_EMISOR-AUGBL
  AND   BUKRS EQ ST_BUKRS.

  IF STL_BKPF-WWERT IS INITIAL.
    STL_BKPF-WWERT = SY-DATUM.
  ENDIF.
  WRITE STL_BKPF-WWERT TO VL_GDATU.

*busco todo los tipo de cambio
  SELECT KURST
  FCURR
  TCURR
  GDATU
  UKURS
  FFACT
  TFACT
  FROM TCURR
  INTO TABLE TL_CURR
  WHERE KURST EQ 'M'
  AND   FCURR EQ VL_WAERS
  AND   TCURR EQ STL_BKPF-WAERS .
  IF SY-SUBRC EQ 0.
    LOOP AT TL_CURR INTO STL_CURR.
      VL_TABIX = SY-TABIX.

* convierto la fecha
      CALL FUNCTION 'CONVERSION_EXIT_INVDT_OUTPUT'
        EXPORTING
          INPUT  = STL_CURR-GDATU
        IMPORTING
          OUTPUT = VL_AUX.
* fecha
      VL_DATUM(4)   = VL_AUX+6(4).
      VL_DATUM+4(2) = VL_AUX+3(2).
      VL_DATUM+6(2) = VL_AUX(2)  .

      IF VL_DATUM GT STL_BKPF-WWERT.
        DELETE TL_CURR INDEX VL_TABIX.
      ELSE.
        STL_CURR-DATUM = VL_DATUM.
        MODIFY TL_CURR INDEX VL_TABIX FROM STL_CURR.
      ENDIF.
    ENDLOOP.
  ENDIF.
  SORT TL_CURR BY DATUM DESCENDING.

  IF VL_WAERS  EQ ' '.
    CONCATENATE 'Tipo de cambio'
    '0,000'
    INTO V_CAMBIOUSD SEPARATED BY SPACE.
  ELSE.

    IF VL_WAERS NE 'ARS' .
      READ TABLE TL_CURR  INTO STL_CURR
      WITH KEY DATUM = STL_BKPF-WWERT.
      IF SY-SUBRC EQ 0.
        WRITE STL_CURR-UKURS TO VL_KURS2 DECIMALS 3.
        CONDENSE VL_KURS2 NO-GAPS.
        CONCATENATE 'Tipo de cambio'
        VL_KURS2
        INTO V_CAMBIOUSD SEPARATED BY SPACE.
      ELSE.
*  busco la fecha mas proxima
        READ TABLE TL_CURR  INTO STL_CURR INDEX 1.
        WRITE STL_CURR-UKURS TO VL_KURS2 DECIMALS 3.
        CONDENSE VL_KURS2 NO-GAPS.
        CONCATENATE 'Tipo de cambio'
        VL_KURS2
        INTO V_CAMBIOUSD SEPARATED BY SPACE.
      ENDIF.
    ELSE.

      CONCATENATE 'Tipo de cambio'
      '0,000'
      INTO V_CAMBIOUSD SEPARATED BY SPACE.

    ENDIF.
  ENDIF.
ENDIF.
