
DATA: L_HBKID TYPE SKB1-HBKID,
      L_STRAS TYPE BNKA-STRAS,
      L_BANKA TYPE BNKA-BANKA,
      L_KOINH TYPE LFBK-KOINH.

write: ST_MPAGOS-FECHA to v_fechaM.
write: ST_MPAGOS-DMBTR to v_dmbtrM.
v_totalm = v_totalm + ST_MPAGOS-DMBTR.

condense v_fechaM NO-GAPS.
condense v_dmbtrM NO-GAPS.

CLEAR: VD_CUIT, VD_BCO, VD_CBU.

CLEAR: L_HBKID, L_STRAS, L_BANKA, L_KOINH.

SELECT SINGLE HBKID FROM SKB1 "#EC CI_DB_OPERATION_OK[2431747]
         INTO L_HBKID
        WHERE BUKRS EQ GS_EMISOR-BUKRS
          AND SAKNR EQ ST_MPAGOS-UBHKT.

 IF L_HBKID IS NOT INITIAL.
   SELECT SINGLE STRAS BANKA FROM BNKA
            INTO (L_STRAS, L_BANKA)
          WHERE BANKS EQ 'AR'
            AND BANKL EQ L_HBKID.
     IF SY-SUBRC EQ 0.
       VD_CUIT = L_STRAS(16).

*>>> begin - CH 2000053999 - Stefanini - 09/10/2025
*       VD_BCO = L_BANKA.
*<<< end - CH 2000053999 - Stefanini - 09/10/2025

SELECT SINGLE KOINH FROM LFBK
           INTO L_KOINH
        WHERE LIFNR EQ GS_EMISOR-LIFNR.

IF SY-SUBRC EQ 0.
  VD_CBU = L_KOINH(22).
ENDIF.

     ENDIF.
 ENDIF.





