FUNCTION ZSDMF003_REALIZA_CALCULO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_FIXACAO) TYPE  POSNR OPTIONAL
*"     REFERENCE(I_REPID) TYPE  SY-REPID OPTIONAL
*"  TABLES
*"      TI_ESQ_CALC STRUCTURE  ZSDS006
*"      TE_ESQ_CALC STRUCTURE  ZSDS006
*"----------------------------------------------------------------------

  DATA: WL_TABIX TYPE SY-TABIX,
        WL_DYN_D TYPE REF  TO CL_ABAP_ELEMDESCR,
        WL_DATA TYPE REF TO DATA,
        C_DECIMAIS TYPE I.

  FIELD-SYMBOLS: <FS_RESULT> TYPE ANY.

  REFRESH: TG_ESQ_CALC.
  TG_ESQ_CALC[] = TI_ESQ_CALC[].
  TE_ESQ_CALC[] = TI_ESQ_CALC[].





  LOOP AT TI_ESQ_CALC
    WHERE TIPO_CALC EQ 'C'
       or TIPO_CALC eq 'R'.
    WL_TABIX = SY-TABIX.
    C_DECIMAIS = TI_ESQ_CALC-C_DECIMAIS.
    CLEAR: WL_DYN_D.
    WL_DYN_D = CL_ABAP_ELEMDESCR=>GET_P( P_LENGTH = 13
                                         P_DECIMALS = C_DECIMAIS ).
    FREE WL_DATA.
    CREATE DATA WL_DATA TYPE HANDLE WL_DYN_D.
    UNASSIGN <FS_RESULT>.
    ASSIGN WL_DATA->* TO <FS_RESULT>.

    CALCULA TI_ESQ_CALC I_FIXACAO i_repid <FS_RESULT>. "RESULT.



    TI_ESQ_CALC-FORMULA = <FS_RESULT>.
    CONDENSE TI_ESQ_CALC-FORMULA NO-GAPS.
    MODIFY TE_ESQ_CALC FROM TI_ESQ_CALC INDEX WL_TABIX.


  ENDLOOP.

ENDFUNCTION.
