PROCESS BEFORE OUTPUT.

  MODULE STATUS_0100.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_0100_EXIT AT EXIT-COMMAND.

  FIELD ZDE_PEDIDO_CRIAR-SAFRA MODULE VALIDAR_PSAFRA ON REQUEST.
  FIELD ZDE_PEDIDO_CRIAR-BRANCH MODULE VALIDAR_PFILIA ON REQUEST.

  MODULE USER_COMMAND_0100.
