FUNCTION-POOL ZGF_PESQ_INSTRU_OV_ALGO.      "MESSAGE-ID ..

* INCLUDE LZGF_PESQ_INSTRU_OV_ALGOD...       " Local class definition

DATA: IT_ORDENS_VENDA TYPE ZSDT0001OV_ALGODAO_ALV_T,
      IT_ORDENS_SELEC TYPE ZSDT0001OV_ALGODAO_ALV_T,
      WA_ORDENS_VENDA TYPE ZSDT0001OV_ALGODAO_ALV,
      LC_SELECIONOU   TYPE C,
      OK_CODE         TYPE SY-UCOMM.

DATA: LC_VSTEL TYPE VSTEL,
      LC_CHARG TYPE CHARG_D.

TABLES: ZSDT0001OV, ZSDT0001OV_ALGODAO, VBAP.

SELECTION-SCREEN BEGIN OF SCREEN 0101 AS SUBSCREEN.

SELECT-OPTIONS: EVSTEL   FOR VBAP-VSTEL NO-EXTENSION NO INTERVALS OBLIGATORY DEFAULT LC_VSTEL,
                ECHARG   FOR VBAP-CHARG NO-EXTENSION NO INTERVALS OBLIGATORY DEFAULT LC_CHARG.

SELECTION-SCREEN SKIP.

SELECT-OPTIONS: EDSINSTR FOR ZSDT0001OV_ALGODAO-DS_INSTRUCAO NO-EXTENSION NO INTERVALS,
                EIDORDEM FOR ZSDT0001OV-NR_ORDEM_VENDA NO-EXTENSION NO INTERVALS,
                EIDMATNR FOR ZSDT0001OV_ALGODAO-MATNR NO-EXTENSION NO INTERVALS.

SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: CK_ST RADIOBUTTON GROUP RAD2.
SELECTION-SCREEN COMMENT 02(50) TEXT-001 FOR FIELD CK_ST.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: CK_ST_A RADIOBUTTON GROUP RAD2.
SELECTION-SCREEN COMMENT 02(50) TEXT-002 FOR FIELD CK_ST_A.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: CK_ST_L RADIOBUTTON GROUP RAD2 DEFAULT 'X'.
SELECTION-SCREEN COMMENT 02(50) TEXT-003 FOR FIELD CK_ST_L.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: CK_ST_D RADIOBUTTON GROUP RAD2.
SELECTION-SCREEN COMMENT 02(50) TEXT-004 FOR FIELD CK_ST_D.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: CK_ST_R RADIOBUTTON GROUP RAD2.
SELECTION-SCREEN COMMENT 02(50) TEXT-005 FOR FIELD CK_ST_R.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: CK_ST_P RADIOBUTTON GROUP RAD2.
SELECTION-SCREEN COMMENT 02(50) TEXT-006 FOR FIELD CK_ST_P.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF SCREEN 0101.

AT SELECTION-SCREEN OUTPUT.

  DATA: POS TYPE I.

  LOOP AT SCREEN.
    IF SCREEN-NAME EQ 'EVSTEL-LOW' OR SCREEN-NAME EQ 'ECHARG-LOW'.
      SCREEN-INPUT = 0.
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.

  SET CURSOR FIELD 'EDSINSTR-LOW' OFFSET POS.
