PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZAUTH_WEBSERVICE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZAUTH_WEBSERVICE-SERVICE .
    FIELD ZAUTH_WEBSERVICE-URL .
    FIELD ZAUTH_WEBSERVICE-USERNAME .
    FIELD ZAUTH_WEBSERVICE-PASSWORD .
    FIELD ZAUTH_WEBSERVICE-ADD01 .
    FIELD ZAUTH_WEBSERVICE-ADD02 .
    FIELD ZAUTH_WEBSERVICE-METHOD .
    FIELD ZAUTH_WEBSERVICE-CONTENT_TYPE .
    FIELD ZAUTH_WEBSERVICE-URL_TOKEN .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZAUTH_WEBSERVICE-SERVICE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
