PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZTPM_EXP_P_SAAF-TABELA .
    FIELD ZTPM_EXP_P_SAAF-CODIGO .
    FIELD ZTPM_EXP_P_SAAF-TIMESTAMP .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZTPM_EXP_P_SAAF-TABELA .
  module detail_pai.
 endchain.
