FUNCTION ZMF_ZMMT0105_CREATE_FROM_BSEG.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_BSEG) TYPE  BSEG
*"     REFERENCE(I_DS_CPF_TREINAMENTO) TYPE  PBR_CPFNR
*"     REFERENCE(I_ID_LMS_TREINAMENTO) TYPE  ZID_LMS
*"  RAISING
*"      ZCX_INTEGRACAO
*"----------------------------------------------------------------------

  DATA: WA_ZMMT0105 TYPE ZMMT0105.

  IF I_ID_LMS_TREINAMENTO IS INITIAL.
    RAISE EXCEPTION TYPE ZCX_INTEGRACAO
      EXPORTING
        TEXTID = VALUE #( MSGID = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_COD_TREINA-MSGID
                          MSGNO = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_COD_TREINA-MSGNO )
        MSGID  = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_COD_TREINA-MSGID
        MSGNO  = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_COD_TREINA-MSGNO
        MSGTY  = 'E'.
  ENDIF.

  IF I_DS_CPF_TREINAMENTO IS INITIAL.
    RAISE EXCEPTION TYPE ZCX_INTEGRACAO
      EXPORTING
        TEXTID = VALUE #( MSGID = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CPF_OBRIGA-MSGID
                          MSGNO = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CPF_OBRIGA-MSGNO )
        MSGID  = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CPF_OBRIGA-MSGID
        MSGNO  = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CPF_OBRIGA-MSGNO
        MSGTY  = 'E'.
  ENDIF.

  FIND REGEX '[0-9]{11}' IN I_DS_CPF_TREINAMENTO.
  IF SY-SUBRC IS NOT INITIAL.
    RAISE EXCEPTION TYPE ZCX_INTEGRACAO
      EXPORTING
        TEXTID = VALUE #( MSGID = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CPF_PADRAO-MSGID
                          MSGNO = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CPF_PADRAO-MSGNO )
        MSGID  = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CPF_PADRAO-MSGID
        MSGNO  = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CPF_PADRAO-MSGNO
        MSGTY  = 'E'.
  ENDIF.

  SELECT SINGLE * INTO @DATA(WA_ZMMT0103)
    FROM ZMMT0103
   WHERE SAKNR EQ @I_BSEG-HKONT.

  IF SY-SUBRC IS NOT INITIAL.
    RAISE EXCEPTION TYPE ZCX_INTEGRACAO
      EXPORTING
        TEXTID = VALUE #( MSGID = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CONTA_ERRO-MSGID
                          MSGNO = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CONTA_ERRO-MSGNO
                          ATTR1 = I_BSEG-SAKNR )
        MSGID  = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CONTA_ERRO-MSGID
        MSGNO  = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CONTA_ERRO-MSGNO
        MSGV1  = CONV #( I_BSEG-SAKNR )
        MSGTY  = 'E'.
  ENDIF.

                                                            "ZMM0148
  SELECT SINGLE * INTO @DATA(WA_ZMMT0104)
    FROM ZMMT0104
   WHERE CPF    EQ @I_DS_CPF_TREINAMENTO
     AND ID_LMS EQ @I_ID_LMS_TREINAMENTO.

  IF SY-SUBRC IS NOT INITIAL.
    RAISE EXCEPTION TYPE ZCX_INTEGRACAO
      EXPORTING
        TEXTID = VALUE #( MSGID = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CURSO_CPF-MSGID
                          MSGNO = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CURSO_CPF-MSGNO
                          ATTR1 = I_ID_LMS_TREINAMENTO
                          ATTR2 = I_DS_CPF_TREINAMENTO )
        MSGID  = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CURSO_CPF-MSGID
        MSGNO  = ZCX_INTEGRACAO=>ZCX_TREINAMENTO_CURSO_CPF-MSGNO
        MSGV1  = CONV #( I_ID_LMS_TREINAMENTO )
        MSGV2  = CONV #( I_DS_CPF_TREINAMENTO )
        MSGTY  = 'E'.
  ENDIF.

  CLEAR: WA_ZMMT0105.

  WA_ZMMT0105-BUKRS     = I_BSEG-BUKRS.
  WA_ZMMT0105-BELNR     = I_BSEG-BELNR.
  WA_ZMMT0105-GJAHR     = I_BSEG-GJAHR.
  WA_ZMMT0105-BUZEI     = I_BSEG-BUZEI.         "Nº item do documento de compra
  WA_ZMMT0105-EBELN     = I_BSEG-BELNR.         "Nº do documento de compras
  WA_ZMMT0105-EBELP     = I_BSEG-BUZEI.         "Nº item do documento de compra
  WA_ZMMT0105-CPF       = I_DS_CPF_TREINAMENTO. "Número no Cadastro de Pessoa Física (CPF)
  WA_ZMMT0105-ID_LMS    = I_ID_LMS_TREINAMENTO. "ID- Treinamento
  WA_ZMMT0105-TIPO      = 'R'.                  "Código de uma posição
  WA_ZMMT0105-DATA      = SY-DATUM.             "Data
  WA_ZMMT0105-HORA      = SY-UZEIT.             "Hora
  WA_ZMMT0105-USUARIO   = SY-UNAME.             "Nome do usuário

  "WA_ZMMT0105-LIFNR     = "Nº conta do fornecedor
  "WA_ZMMT0105-ATENCAO   = ' '.            "Indica Atenção
  "WA_ZMMT0105-LOTE      = "Lote - pagamento
  "WA_ZMMT0105-SEQ_LCTO  = "Seq. Lançamento
  "WA_ZMMT0105-SEQITEM   = "Campo numérico de comprimento 6

  MODIFY ZMMT0105 FROM WA_ZMMT0105.

  COMMIT WORK AND WAIT.

ENDFUNCTION.
