FUNCTION ZINTERFACE_RWBAPI01.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  TABLES
*"      IT_ACCIT STRUCTURE  ACCIT
*"      IT_ACCCR STRUCTURE  ACCCR
*"      RETURN STRUCTURE  BAPIRET2
*"      EXTENSION STRUCTURE  BAPIACEXTC
*"      IT_ACCWT STRUCTURE  ACCIT_WT
*"  CHANGING
*"     VALUE(DOCUMENT_HEADER) LIKE  ACCHD STRUCTURE  ACCHD
*"----------------------------------------------------------------------

  LOOP AT EXTENSION.
    IF EXTENSION-FIELD1+0(7) = 'DIVISAO'.
      READ TABLE IT_ACCIT WITH KEY POSNR = EXTENSION-FIELD2+0(3).
      IF SY-SUBRC IS INITIAL.
        IT_ACCIT-GSBER = EXTENSION-FIELD2+3(4).
        MODIFY IT_ACCIT INDEX SY-TABIX.
      ENDIF.
    ELSEIF EXTENSION-FIELD1+0(7) = 'SOCPARC'.
      READ TABLE IT_ACCIT WITH KEY POSNR = EXTENSION-FIELD2+0(10).
      IF SY-SUBRC IS INITIAL.
        IT_ACCIT-VBUND = EXTENSION-FIELD3+0(6).
        MODIFY IT_ACCIT INDEX SY-TABIX.
      ENDIF.
    ELSEIF EXTENSION-FIELD1+0(8) = 'ORDVENDA'.
      READ TABLE IT_ACCIT WITH KEY POSNR = EXTENSION-FIELD2+0(10).
      IF SY-SUBRC IS INITIAL.
        IT_ACCIT-HZUON = EXTENSION-FIELD3+0(10).
        MODIFY IT_ACCIT INDEX SY-TABIX.
      ENDIF.
    ELSEIF EXTENSION-FIELD1+0(5) = 'KIDNO'.
      READ TABLE IT_ACCIT WITH KEY POSNR = EXTENSION-FIELD2+0(10).
      IF SY-SUBRC IS INITIAL.
        IT_ACCIT-KIDNO = EXTENSION-FIELD3+0(30).
        MODIFY IT_ACCIT INDEX SY-TABIX.
      ENDIF.
    ELSEIF EXTENSION-FIELD1+0(5) = 'BUPLA'.
      READ TABLE IT_ACCIT WITH KEY POSNR = EXTENSION-FIELD2+0(10).
      IF SY-SUBRC IS INITIAL.
        IT_ACCIT-BUPLA = EXTENSION-FIELD3+0(4).
        MODIFY IT_ACCIT INDEX SY-TABIX.
      ENDIF.
    ELSEIF EXTENSION-FIELD1+0(5) = 'VORGN'.
      READ TABLE IT_ACCIT WITH KEY POSNR = EXTENSION-FIELD2+0(10).
      IF SY-SUBRC IS INITIAL.
        IT_ACCIT-VORGN = EXTENSION-FIELD3+0(4).
        MODIFY IT_ACCIT INDEX SY-TABIX.
      ENDIF.
    ELSEIF EXTENSION-FIELD1+0(5) = 'ANBWA'.
      READ TABLE IT_ACCIT WITH KEY POSNR = EXTENSION-FIELD2+0(10).
      IF SY-SUBRC IS INITIAL.
        IT_ACCIT-ANBWA = EXTENSION-FIELD3+0(3).
        MODIFY IT_ACCIT INDEX SY-TABIX.
      ENDIF.
    ELSEIF EXTENSION-FIELD1+0(6) = 'LEDGER'.
      READ TABLE IT_ACCIT WITH KEY POSNR = EXTENSION-FIELD2+0(10).
      IF SY-SUBRC IS INITIAL.
        DOCUMENT_HEADER-RLDNR = EXTENSION-FIELD3+0(2).
      ENDIF.
    ELSE.
      READ TABLE IT_ACCIT WITH KEY POSNR = EXTENSION(3).
      IF SY-SUBRC IS INITIAL.
        IT_ACCIT-RMVCT = EXTENSION+3(3).
        MODIFY IT_ACCIT INDEX SY-TABIX.
      ENDIF.
    ENDIF.
  ENDLOOP.

ENDFUNCTION.
