FUNCTION-POOL ZGF_RELA_INSTRU_OV_ALGO.      "MESSAGE-ID ..

DATA: IT_LANC         TYPE TABLE OF ZDE_CONS_INSTRUCAO,
      GT_LANC         TYPE ZDE_CONS_INSTRUCAO OCCURS 0,
      G_ALV_TREE      TYPE REF TO CL_GUI_ALV_TREE,
      LC_FILTRO_TEXTO TYPE STRING,
      GT_FIELDCATALOG TYPE LVC_T_FCAT.
