PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIWRT0007 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIWRT0007-OPERACAO .
    FIELD ZFIWRT0007-TIPO .
    FIELD ZFIWRT0007-NIVEL_APROV .
    FIELD ZFIWRT0007-BRANCH .
    FIELD ZFIWRT0007-USNAM .
    FIELD ZFIWRT0007-DEPARTAMENTO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIWRT0007-OPERACAO .
    FIELD ZFIWRT0007-TIPO .
    FIELD ZFIWRT0007-NIVEL_APROV .
    FIELD ZFIWRT0007-BRANCH .
    FIELD ZFIWRT0007-USNAM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
