FUNCTION ZSDMF001_ATUALI_OV_SIMULADOR .
*"----------------------------------------------------------------------
*"*"Interface local:
*"  TABLES
*"      TI_ITENS_OV STRUCTURE  ZSDT0041 OPTIONAL
*"      TE_SAIDA_EXEC STRUCTURE  ZSDS010 OPTIONAL
*"  EXCEPTIONS
*"      OV_NAO_ENCONTRADA
*"----------------------------------------------------------------------
  TYPES: BEGIN OF TY_SAIDA_ALV,
*           INCO1         TYPE ZSDT0041-WERKS,
*           SPART         TYPE ZSDT0041-SPART,
*           AUART         TYPE ZSDT0041-AUART,
*           DESC_ABSOLUTO TYPE  ZSDT0041-DESC_ABSOLUTO,
*           VLRTOT        TYPE ZSDT0041-VLRTOT,
*           WERKS         TYPE ZSDT0041-WERKS,
           VBELN         TYPE VBAK-VBELN,
           POSNR         TYPE VBAP-POSNR,
           MSG(255),
         END OF TY_SAIDA_ALV.

  DATA:
    WL_VBAP           TYPE VBAP,
    WL_ORDERHEADERINX TYPE BAPISDH1X,
    WL_LOGIC_SWITCH   TYPE BAPISDLS,
    TL_RETURN         TYPE TABLE OF BAPIRET2 WITH HEADER LINE,
    WL_RETURN         TYPE BAPIRET2,
    TL_SAIDA_ALV      TYPE TABLE OF TY_SAIDA_ALV WITH HEADER LINE,
    TL_CONDITIONS_IN  TYPE TABLE OF BAPICOND WITH HEADER LINE,
    TL_CONDITIONS_INX TYPE TABLE OF BAPICONDX WITH HEADER LINE,
    TL_ITENS          TYPE TABLE OF ZSDT0041 WITH HEADER LINE.

  IF TI_ITENS_OV[] IS INITIAL.
    RAISE OV_NAO_ENCONTRADA.
  ELSE.
    TL_ITENS[] = TI_ITENS_OV[].
  ENDIF.

  WL_ORDERHEADERINX-UPDATEFLAG = 'U'.
  WL_LOGIC_SWITCH-COND_HANDL   = 'X'.

  LOOP AT TL_ITENS .
    CLEAR: TL_CONDITIONS_IN[], TL_CONDITIONS_INX[], TL_RETURN[].

    SELECT SINGLE *
      FROM VBAP
      INTO WL_VBAP
     WHERE VBELN = TL_ITENS-VBELN
       AND MATNR = TL_ITENS-MATNR.

    TL_ITENS-DESC_ABSOLUTO      = TL_ITENS-DESC_ABSOLUTO * -1.

    TL_CONDITIONS_IN-ITM_NUMBER = WL_VBAP-POSNR.
    TL_CONDITIONS_IN-COND_COUNT = '01'.
    TL_CONDITIONS_IN-COND_TYPE  = 'RB00'.
    TL_CONDITIONS_IN-COND_VALUE = TL_ITENS-DESC_ABSOLUTO.
    TL_CONDITIONS_IN-CURRENCY   = WL_VBAP-WAERK.
    TL_CONDITIONS_INX-ITM_NUMBER = WL_VBAP-POSNR.
    TL_CONDITIONS_INX-COND_COUNT = '01'.
    TL_CONDITIONS_INX-COND_TYPE  = 'RB00'.
    TL_CONDITIONS_INX-UPDATEFLAG = 'U'.
    TL_CONDITIONS_INX-COND_VALUE = 'X'.
    TL_CONDITIONS_INX-CURRENCY   = 'X'.

    APPEND: TL_CONDITIONS_IN,
            TL_CONDITIONS_INX.

"*---> 12/07/2023 - Migração S4 - LO --> Material não foi utilizado
    CALL FUNCTION 'BAPI_SALESORDER_CHANGE'"#EC CI_USAGE_OK[2438131]
      EXPORTING
        SALESDOCUMENT    = TL_ITENS-VBELN
        ORDER_HEADER_INX = WL_ORDERHEADERINX
        LOGIC_SWITCH     = WL_LOGIC_SWITCH
      TABLES
        CONDITIONS_IN    = TL_CONDITIONS_IN
        CONDITIONS_INX   = TL_CONDITIONS_INX
        RETURN           = TL_RETURN.

    IF ( LINE_EXISTS( TL_RETURN[ TYPE = 'E' ] ) ).
      TL_SAIDA_ALV-MSG = TL_RETURN[ TYPE = 'E' ]-MESSAGE.
    ELSE.
      CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
        EXPORTING
          WAIT = ABAP_TRUE.
    ENDIF.

    MOVE: WL_VBAP-VBELN         TO TL_SAIDA_ALV-VBELN,
          WL_VBAP-POSNR         TO TL_SAIDA_ALV-POSNR.

    APPEND TL_SAIDA_ALV.
  ENDLOOP.

  IF ( TL_SAIDA_ALV[] IS NOT INITIAL ).
    REFRESH ESTRUTURA.
    PERFORM MONTAR_LAYOUT_.
    CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
      EXPORTING
        IT_FIELDCAT           = ESTRUTURA[]
        I_SAVE                = 'A'
        I_SCREEN_START_COLUMN = 3
        I_SCREEN_START_LINE   = 3
        I_SCREEN_END_COLUMN   = 100
        I_SCREEN_END_LINE     = 13
      TABLES
        T_OUTTAB              = TL_SAIDA_ALV.
  ENDIF.
ENDFUNCTION.
