PROCESS BEFORE OUTPUT.
  MODULE STATUS_0133.
*
PROCESS AFTER INPUT.

 MODULE USER_COMMAND_0133.

PROCESS ON VALUE-REQUEST.
  FIELD WL_CHANGE_WERKS-WERKS MODULE HELP_0133_WERKS.
  FIELD WL_CHANGE_WERKS-KOSTL MODULE HELP_0133_KOSTL.
