
PROCESS BEFORE OUTPUT.
  MODULE F_INICIAR_TELA.
  MODULE TRATA_FIELDS.
  MODULE CRIA_OBJETOS.
  MODULE STATUS_0100.
  CALL SUBSCREEN SUB01 INCLUDING SY-REPID WG_SUB01.

PROCESS AFTER INPUT.
  CALL SUBSCREEN  SUB01.

  FIELD WG_ZGLT035-MONAT   MODULE  TROCA_DATA ON CHAIN-REQUEST.
  FIELD WG_ZGLT035-TP_LCTO MODULE  VALIDA_PARAMETROS ON CHAIN-REQUEST.
  CHAIN.
    FIELD WG_ZGLT035-BUDAT.
    FIELD WG_ZGLT035-MONAT.
    FIELD WG_ZGLT035-MOEDA_DOC.
    FIELD WG_ZGLT035-ST_FECHA.
    FIELD WG_ZGLT035-MOEDA_GP_HIST
    MODULE  RECALC_MOEDA_FT ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0100.

PROCESS ON VALUE-REQUEST.
  FIELD WG_ZGLT034-LOTE MODULE SEARCH_LOTE.
  FIELD WG_ZGLT035-DOC_LCTO MODULE SEARCH_DOC.
  FIELD WG_ZGLT035-TP_LCTO MODULE SEARCH_TP.
