
PROCESS BEFORE OUTPUT.
  MODULE TS_100_ACTIVE_TAB_SET.
  MODULE MUDAR_TEXTO.

  CALL SUBSCREEN TS_100_SCA
    INCLUDING G_TS_100-PROG G_TS_100-SUBSCREEN.



PROCESS AFTER INPUT.
  CALL SUBSCREEN TS_100_SCA.
  MODULE TS_100_ACTIVE_TAB_GET.
