
PROCESS BEFORE OUTPUT.
  MODULE CARREGA_LOTES.
  MODULE TRATA_FIELDS.
  MODULE STATUS_0100.
  MODULE CRIA_OBJETOS.

  CALL SUBSCREEN :
    SU_LOTES INCLUDING G_TAB_STRIP_IMP-PROG '0110',
    SU_ESTRA INCLUDING G_TAB_STRIP_IMP-PROG '0120',
    SU_DOCS  INCLUDING G_TAB_STRIP_IMP-PROG '0130',
    SU_DET   INCLUDING G_TAB_STRIP_IMP-PROG WG_SUB01.


PROCESS AFTER INPUT.

  CALL SUBSCREEN:
                 SU_LOTES,
                 SU_ESTRA,
                 SU_DOCS,
                 SU_DET.

  MODULE USER_COMMAND_0100.
  MODULE USER_COMMAND_EXIT AT EXIT-COMMAND.
