PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIT0006 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIT0006-BUKRS .
    FIELD ZFIT0006-BELNR .
    FIELD ZFIT0006-GJAHR .
    FIELD ZFIT0006-TCODE .
    FIELD ZFIT0006-BUKRS_E .
    FIELD ZFIT0006-BELNR_E .
    FIELD ZFIT0006-GJAHR_E .
    FIELD ZFIT0006-TCODE_E .
    FIELD ZFIT0006-LAUFD .
    FIELD ZFIT0006-LAUFI .
    FIELD ZFIT0006-STATUS .
    FIELD ZFIT0006-DATA .
    FIELD ZFIT0006-HORA .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIT0006-BUKRS .
    FIELD ZFIT0006-BELNR .
    FIELD ZFIT0006-GJAHR .
    FIELD ZFIT0006-TCODE .
    FIELD ZFIT0006-BUKRS_E .
    FIELD ZFIT0006-BELNR_E .
    FIELD ZFIT0006-GJAHR_E .
    FIELD ZFIT0006-TCODE_E .
    FIELD ZFIT0006-LAUFD .
    FIELD ZFIT0006-LAUFI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
