
PROCESS BEFORE OUTPUT.
  MODULE INICIAR_TELA.
  MODULE TRATA_FIELDS.

  MODULE STATUS_0100.

PROCESS AFTER INPUT.
  MODULE USER_COMMAND_0100.

PROCESS ON VALUE-REQUEST.
  FIELD WG_ZGLT034-DEP_RESP MODULE SEARCH_DEPTO.
