PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGLT082 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGLT082-OPERACAO .
    FIELD ZGLT082-BUKRS .
    FIELD ZGLT082-WEKRS .
    FIELD ZGLT082-LIFNR .
    FIELD ZGLT082-NFTYPE .
    FIELD ZGLT082-ITMTYP .
    FIELD ZGLT082-CFOP .
    FIELD ZGLT082-OPERTYP .
    FIELD ZGLT082-TAXCODE .
    FIELD ZGLT082-USNAM .
    FIELD ZGLT082-DT_CRIACAO .
    FIELD ZGLT082-HR_CRIACAO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGLT082-OPERACAO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
