PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGLT064 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGLT064-SEQ_TIPO .
    FIELD ZGLT064-DESCR .
    FIELD ZGLT064-IMOBILIZADO .
    FIELD ZGLT064-MERCADORIA .
    FIELD ZGLT064-TP_LCTO .
    FIELD ZGLT064-TP_LCTO_APROP .
    FIELD ZGLT064-TP_LCTO_AR .
    FIELD ZGLT064-TP_LCTO_APOLICE .
    FIELD ZGLT064-DEP_RESP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGLT064-SEQ_TIPO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
