PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGLT092A CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGLT092A-TP_ARRENDAMENTO .
    FIELD ZGLT092A-COD_CONTRATO .
    FIELD ZGLT092A-SERIAL_NO .
    FIELD ZGLT092A-CLASSIFICACAO .
    FIELD ZGLT092A-FORNECEDOR .
    FIELD ZGLT092A-CLIENTE .
    FIELD ZGLT092A-NAME1 .
    FIELD ZGLT092A-RAZAO_ESPECIAL .
    FIELD ZGLT092A-RCOMP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGLT092A-TP_ARRENDAMENTO .
    FIELD ZGLT092A-COD_CONTRATO .
    FIELD ZGLT092A-SERIAL_NO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
