PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGLT060 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGLT060-BUKRS1 .
    FIELD ZGLT060-WAERS .
    FIELD ZGLT060-CTA_LAN .
    FIELD ZGLT060-KOSTL1 .
    FIELD ZGLT060-PRCTR1 .
    FIELD ZGLT060-MATKL1 .
    FIELD ZGLT060-BUKRS2 .
    FIELD ZGLT060-CTA_VIRTUAL .
    FIELD ZGLT060-KOSTL2 .
    FIELD ZGLT060-PRCTR2 .
    FIELD ZGLT060-MATKL2 .
    FIELD ZGLT060-NIVEL .
    FIELD ZGLT060-CK_NSOC_PARCEIRA .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGLT060-BUKRS1 .
    FIELD ZGLT060-WAERS .
    FIELD ZGLT060-CTA_LAN .
    FIELD ZGLT060-KOSTL1 .
    FIELD ZGLT060-PRCTR1 .
    FIELD ZGLT060-MATKL1 .
    FIELD ZGLT060-BUKRS2 .
    FIELD ZGLT060-CTA_VIRTUAL .
    FIELD ZGLT060-KOSTL2 .
    FIELD ZGLT060-PRCTR2 .
    FIELD ZGLT060-MATKL2 .
    FIELD ZGLT060-NIVEL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
