PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGLT037 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGLT037-BUKRS .
    FIELD ZGLT037-BUKRS_ATE .
    FIELD ZGLT037-DEP_RESP .
    FIELD ZGLT037-PGT_FORN .
    FIELD ZGLT037-WAERS .
    FIELD ZGLT037-NIVEL .
    FIELD ZGLT037-APROVADOR .
    FIELD ZGLT037-DT_VAL_DE .
    FIELD ZGLT037-HR_VAL_DE .
    FIELD ZGLT037-DT_VAL_ATE .
    FIELD ZGLT037-HR_VAL_ATE .
    FIELD ZGLT037-VALOR_DE .
    FIELD ZGLT037-VALOR_ATE .
    FIELD ZGLT037-DATA_ATUAL .
    FIELD ZGLT037-HORA_ATUAL .
    FIELD ZGLT037-USUARIO .
    FIELD ZGLT037-MOTIVO .
    FIELD ZGLT037-TRANSF_APROV .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGLT037-BUKRS .
    FIELD ZGLT037-BUKRS_ATE .
    FIELD ZGLT037-DEP_RESP .
    FIELD ZGLT037-PGT_FORN .
    FIELD ZGLT037-WAERS .
    FIELD ZGLT037-NIVEL .
    FIELD ZGLT037-APROVADOR .
    FIELD ZGLT037-DT_VAL_DE .
    FIELD ZGLT037-HR_VAL_DE .
    FIELD ZGLT037-DT_VAL_ATE .
    FIELD ZGLT037-HR_VAL_ATE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
