
PROCESS BEFORE OUTPUT.

  MODULE STATUS_0306.
*
PROCESS AFTER INPUT.

  CHAIN.
    FIELD ZDE_MOV_LCT_BANCO-PARID.
    FIELD ZDE_MOV_LCT_BANCO-UMSKZ.
    MODULE SET_UPDATE_FLAG_0306 ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0306_EXIT AT EXIT-COMMAND.

  MODULE USER_COMMAND_0306.
