PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGLT_DRE_04 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGLT_DRE_04-BUKRS .
    FIELD ZGLT_DRE_04-GJAHR .
    FIELD ZGLT_DRE_04-DOCNR .
    FIELD ZGLT_DRE_04-DOCLN .
    FIELD ZGLT_DRE_04-BELNR .
    FIELD ZGLT_DRE_04-BUZEI .
    FIELD ZGLT_DRE_04-POPER .
    FIELD ZGLT_DRE_04-AWTYP .
    FIELD ZGLT_DRE_04-SAKNR .
    FIELD ZGLT_DRE_04-KTOPL .
    FIELD ZGLT_DRE_04-KOKRS .
    FIELD ZGLT_DRE_04-SHKZG .
    FIELD ZGLT_DRE_04-KOSTL .
    FIELD ZGLT_DRE_04-KOSAR .
    FIELD ZGLT_DRE_04-PRCTR .
    FIELD ZGLT_DRE_04-MATNR .
    FIELD ZGLT_DRE_04-MATKL .
    FIELD ZGLT_DRE_04-AUFNR .
    FIELD ZGLT_DRE_04-VBUND .
    FIELD ZGLT_DRE_04-CK_INTEGRADO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGLT_DRE_04-BUKRS .
    FIELD ZGLT_DRE_04-GJAHR .
    FIELD ZGLT_DRE_04-DOCNR .
    FIELD ZGLT_DRE_04-DOCLN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
