PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGLT041 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGLT041-BUKRS .
    FIELD ZGLT041-SAKNR .
    FIELD ZGLT041-COD_CLAS_BAL .
    FIELD ZGLT041-COD_CLAS_NOT2 .
    FIELD ZGLT041-COD_CLAS_NOT .
    FIELD ZGLT041-CTA_MONET .
    FIELD ZGLT041-CTA_INTERCOMPANY .
    FIELD ZGLT041-DEP_RESP2 .
    FIELD ZGLT041-BNAME2 .
    FIELD ZGLT041-PRAZO_ENTR .
    FIELD ZGLT041-CRIT_VECTO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGLT041-BUKRS .
    FIELD ZGLT041-SAKNR .
    FIELD ZGLT041-COD_CLAS_BAL .
    FIELD ZGLT041-COD_CLAS_NOT2 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
