PROCESS BEFORE OUTPUT.

  MODULE STATUS_0002.
*
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_0002_EXIT AT EXIT-COMMAND.

  FIELD ZGLT_DRE_04-KOSTL MODULE ALTERA_KOSAR_V ON REQUEST.

  CHAIN.
    FIELD ZGLT_DRE_04-BUKRS .
    FIELD ZGLT_DRE_04-GJAHR .
    FIELD ZGLT_DRE_04-DOCNR .
    FIELD ZGLT_DRE_04-DOCLN .
    FIELD ZGLT_DRE_04-BELNR .
    FIELD ZGLT_DRE_04-BUZEI .
    FIELD ZGLT_DRE_04-POPER .
    FIELD ZGLT_DRE_04-BUDAT .
    FIELD ZGLT_DRE_04-AWTYP .
    FIELD ZGLT_DRE_04-SAKNR .
    FIELD ZGLT_DRE_04-KTOPL .
    FIELD ZGLT_DRE_04-KOKRS .
    FIELD ZGLT_DRE_04-SHKZG .
    FIELD ZGLT_DRE_04-KOSTL .
    FIELD ZGLT_DRE_04-KOSAR .
    FIELD ZGLT_DRE_04-PRCTR .
    FIELD ZGLT_DRE_04-MATNR .
    FIELD ZGLT_DRE_04-MATKL .
    FIELD ZGLT_DRE_04-AUFNR .
    FIELD ZGLT_DRE_04-VBUND .
    FIELD ZGLT_DRE_04-RTCUR .
    FIELD ZGLT_DRE_04-VLTSL .
    FIELD ZGLT_DRE_04-VLHSL .
    FIELD ZGLT_DRE_04-VLKSL .
    FIELD ZGLT_DRE_04-VLOSL .
    FIELD ZGLT_DRE_04-RUNIT .
    FIELD ZGLT_DRE_04-QTMSL .
    FIELD ZGLT_DRE_04-TIMESTAMP .
    FIELD ZGLT_DRE_04-CK_INTEGRADO .
    FIELD ZGLT_DRE_04-OBSERVACAO .
    FIELD ZGLT_DRE_04-RUNIT_BASE .
    FIELD ZGLT_DRE_04-QTMSL_BASE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD ZGLT_DRE_04-KOSTL.
    MODULE ALTERA_KOSAR ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0002.
