PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZIB_NFE_DIST_IVA-BUKRS .
    FIELD ZIB_NFE_DIST_IVA-BSART .
    FIELD ZIB_NFE_DIST_IVA-LIFNR .
    FIELD ZIB_NFE_DIST_IVA-INDUSTRY .
    FIELD ZIB_NFE_DIST_IVA-ICMS .
    FIELD ZIB_NFE_DIST_IVA-MWSKZ .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZIB_NFE_DIST_IVA-BUKRS .
    FIELD ZIB_NFE_DIST_IVA-BSART .
    FIELD ZIB_NFE_DIST_IVA-LIFNR .
    FIELD ZIB_NFE_DIST_IVA-INDUSTRY .
    FIELD ZIB_NFE_DIST_IVA-ICMS .
  module detail_pai.
 endchain.
