PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZIB_NFE_DIST_TVO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZIB_NFE_DIST_TVO-CHAVE_NFE .
    FIELD ZIB_NFE_DIST_TVO-DS_ESPECIE .
    FIELD ZIB_NFE_DIST_TVO-NM_QVOL .
    FIELD ZIB_NFE_DIST_TVO-DS_MARCA .
    FIELD ZIB_NFE_DIST_TVO-DS_NVOL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZIB_NFE_DIST_TVO-CHAVE_NFE .
    FIELD ZIB_NFE_DIST_TVO-DS_ESPECIE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
