interface ZIF_TP_OPERACAO_CARGA_ENTRADA
  public .


  constants ST_ENTRADA_FATURA type ZDE_TP_OPERACAO value '01' ##NO_TEXT.
  constants ST_DEVOLUCAO_NOTA_CREDITO type ZDE_TP_OPERACAO value '02' ##NO_TEXT.
  constants ST_DEBITO_POSTERIOR type ZDE_TP_OPERACAO value '03' ##NO_TEXT.
  constants ST_CREDITO_POSTERIOR type ZDE_TP_OPERACAO value '04' ##NO_TEXT.
  constants ST_ENTRADA_TRANSFERENCIA type ZDE_TP_OPERACAO value '05' ##NO_TEXT.
  constants ST_ENTRADA_ARMAZENAGEM type ZDE_TP_OPERACAO value '06' ##NO_TEXT.
  constants ST_DEVOLUCAO_ARMAZENAGEM type ZDE_TP_OPERACAO value '07' ##NO_TEXT.
  constants ST_COMPRA_ENTREGA_FUTURA type ZDE_TP_OPERACAO value '08' ##NO_TEXT.
  constants ST_ENTRADA_ESTOQUE_ARGENTINA type ZDE_TP_OPERACAO value '10' ##NO_TEXT.
  constants ST_RETORNO_ARMAZENAGEM type ZDE_TP_OPERACAO value '11' ##NO_TEXT.
endinterface.
