*&---------------------------------------------------------------------*
*& Include ZIM02_TOP                                         PoolMóds.        ZIM02
*&
*&---------------------------------------------------------------------*

PROGRAM  ZIM02.
DATA: V_APPEND(1).
TABLES: ZIM01_SOL_AP_INV,
        ZIM02_SOL_AP_CTL,
        CSKT, CSKS,
        ZIM01_TEXTOS.

DATA: W_TEXTOS(60).
DATA: BEGIN OF T_INV OCCURS 0.
        INCLUDE STRUCTURE ZIM01_SOL_AP_INV.
DATA: END OF T_INV.

DATA: BEGIN OF T_TEXTO OCCURS 0.
        INCLUDE STRUCTURE ZIM01_TEXTOS.
DATA: END OF T_TEXTO.


DATA: BEGIN OF T_PINV.
        INCLUDE STRUCTURE ZIM01_SOL_AP_INV.
DATA: END OF T_PINV.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TC_INV' ITSELF
CONTROLS: TC_INV TYPE TABLEVIEW USING SCREEN 0110.
DATA: COLS_WA TYPE CXTAB_COLUMN.
*&SPWIZARD: LINES OF TABLECONTROL 'TC_INV'
DATA:     G_TC_INV_LINES  LIKE SY-LOOPC.

DATA:     OK_CODE LIKE SY-UCOMM.

DATA: W_BUKRST        LIKE T001-BUTXT,
      W_GSBERT        LIKE J_1BBRANCH-NAME,
      W_UP,
      W_SAVE,
      W_CRIA,
      V_ANSWER,
      W_PLANEJADO     TYPE ZIM01_SOL_AP_INV-VLR_TOTAL,
      W_APROVADO      TYPE ZIM01_SOL_AP_INV-VLR_TOTAL,
      W_PLANEJADO_USD TYPE ZIM01_SOL_AP_INV-VLR_TOTAL,
      W_APROVADO_USD  TYPE ZIM01_SOL_AP_INV-VLR_TOTAL,
      W_PLANEJADO_EUR TYPE ZIM01_SOL_AP_INV-VLR_TOTAL,
      W_APROVADO_EUR  TYPE ZIM01_SOL_AP_INV-VLR_TOTAL.

DATA: W_PRI,
      W_SEG,
      W_TER.

*Início Alteração Ricardo Furst.
DATA: V_IZWEK TYPE ZIM01_SOL_AP_INV-IZWEK.
*Fim Alteração Ricardo Furst.

DATA W_LINE             TYPE I.
DATA: W_FIELD(30)       TYPE C.

DATA: W_HORA TYPE SY-UZEIT.

DATA: BEGIN OF TG_10 OCCURS 0.
        INCLUDE STRUCTURE ZIM010.
DATA: END OF TG_10.

DATA: BEGIN OF TG_11 OCCURS 0.
        INCLUDE STRUCTURE ZIM011.
DATA: END OF TG_11.
