
PROCESS BEFORE OUTPUT.
  MODULE LISTE_INITIALISIEREN.
  LOOP AT EXTRACT WITH CONTROL
   TCTRL_ZIM02_SOL_AP_CTL CURSOR NEXTLINE.
    MODULE LISTE_SHOW_LISTE.
    MODULE ATUALIZA_DESCRICAO.
  ENDLOOP.
*
PROCESS AFTER INPUT.
  MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
  MODULE LISTE_BEFORE_LOOP.
  LOOP AT EXTRACT.
    MODULE LISTE_INIT_WORKAREA.
    CHAIN.
      FIELD ZIM02_SOL_AP_CTL-BUKRS .
      FIELD ZIM02_SOL_AP_CTL-ANO .
      FIELD ZIM02_SOL_AP_CTL-SAFRA .
      FIELD ZIM02_SOL_AP_CTL-SAFRA2 .
      FIELD ZIM02_SOL_AP_CTL-KOSTL .
      FIELD ZIM02_SOL_AP_CTL-LTEXT .
      FIELD ZIM02_SOL_AP_CTL-ATIVIDADE .
      FIELD ZIM02_SOL_AP_CTL-DT_APROV_IN .
      FIELD ZIM02_SOL_AP_CTL-DT_APROV_FIM .
      FIELD ZIM02_SOL_AP_CTL-APROVADOR .
      FIELD ZIM02_SOL_AP_CTL-FASE .
      FIELD ZIM02_SOL_AP_CTL-DT_INICIO .
      FIELD ZIM02_SOL_AP_CTL-TX_USD .
      FIELD ZIM02_SOL_AP_CTL-TX_EUR .
      FIELD ZIM02_SOL_AP_CTL-RESPONSAVEL .
      FIELD ZIM02_SOL_AP_CTL-BLQ_EXERC .
      MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
      MODULE ATUALIZA_DESCRICAO.
    ENDCHAIN.
    FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
    CHAIN.
      FIELD ZIM02_SOL_AP_CTL-BUKRS .
      FIELD ZIM02_SOL_AP_CTL-ANO .
      FIELD ZIM02_SOL_AP_CTL-SAFRA .
      FIELD ZIM02_SOL_AP_CTL-SAFRA2 .
      FIELD ZIM02_SOL_AP_CTL-KOSTL .
      MODULE LISTE_UPDATE_LISTE.
    ENDCHAIN.
  ENDLOOP.
  MODULE LISTE_AFTER_LOOP.
