
PROCESS BEFORE OUTPUT.
  MODULE INICIALIZA_TELA.
  MODULE TAB_STRIP_IMP_ACTIVE_TAB_SET.
  MODULE TRATA_FIELDS.
  CALL SUBSCREEN   TAB_STRIP_IMP_SCA
  INCLUDING G_TAB_STRIP_IMP-PROG G_TAB_STRIP_IMP-SUBSCREEN.

  MODULE STATUS_0100.
  MODULE CRIA_OBJETOS.
  MODULE INICIA_LCTO.

PROCESS AFTER INPUT.
  MODULE BUS_BAN.
  MODULE COMPLETA_CAMPOS.

  CALL SUBSCREEN TAB_STRIP_IMP_SCA.
  MODULE TAB_STRIP_IMP_ACTIVE_TAB_GET.

  CHAIN.
    FIELD WG_CADLAN-LOTE.
    MODULE  VALIDA_PARAMETROS ON CHAIN-REQUEST.
  ENDCHAIN.
*
  MODULE USER_COMMAND_0100.
  MODULE USER_COMMAND_EXIT AT EXIT-COMMAND.

PROCESS ON VALUE-REQUEST.
  FIELD WG_CADLAN-LOTE MODULE SEARCH_LOTE.
  FIELD WG_CADLAN-COD_IMPOSTO MODULE SEARCH_IMPOSTO.
  FIELD WG_CADLAN-GSBER MODULE SEARCH_FILIAL.
  FIELD WG_CADLAN-DOC_IMPOSTO MODULE SEARCH_DOC.
