PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZIMP_CAMPOS_GUIA CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZIMP_CAMPOS_GUIA-COD_CAMP_GUIA .
    FIELD ZIMP_CAMPOS_GUIA-DESCR_CAMP_GUIA .
    FIELD ZIMP_CAMPOS_GUIA-DATA_ATUAL .
    FIELD ZIMP_CAMPOS_GUIA-HORA_ATUAL .
    FIELD ZIMP_CAMPOS_GUIA-USUARIO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZIMP_CAMPOS_GUIA-COD_CAMP_GUIA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
