"Name: \FU:J_1B_NFE_STATUS\SE:END\EI
ENHANCEMENT 0 ZJ_1BDFE_SERVER_DETERMINATION.
*
  data: tabela TYPE ZJ1BNFE_INBOUND.
  MOVE-CORRESPONDING ls_nfe_inbound to tabela.
  MODIFY ZJ1BNFE_INBOUND FROM tabela.

ENDENHANCEMENT.
