PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLEST0117 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLEST0117-BUKRS .
    FIELD ZLEST0117-WERKS .
    FIELD ZLEST0117-TIPO .
    FIELD ZLEST0117-LIFNR_C .
    FIELD ZLEST0117-OPERACAO .
    FIELD ZLEST0117-LGORT_DEST .
    FIELD ZLEST0117-LGORT_ORIG .
    FIELD ZLEST0117-DT_ULT_MOD .
    FIELD ZLEST0117-HR_ULT_MOD .
    FIELD ZLEST0117-USUARIO_ULT_MOD .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLEST0117-BUKRS .
    FIELD ZLEST0117-WERKS .
    FIELD ZLEST0117-TIPO .
    FIELD ZLEST0117-LIFNR_C .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
