
PROCESS BEFORE OUTPUT.

  MODULE ZM_STATUS.

  MODULE ZM_EXIBE_DADOS.

PROCESS AFTER INPUT.

  CHAIN.
    FIELD: S_TELA-ZDT_MOV   ,
           S_TELA-ZDT_VENCTO,
           S_TELA-NR_CONHEC ,
           S_TELA-SERIES    ,
           S_TELA-ZDT_CONHEC,
           S_TELA-COMP_VALOR,
           S_TELA-COMP_TIPO ,
           S_TELA-IVA       ,
           S_TELA-NFE       ,
           S_TELA-MULTIMODAL,
           S_TELA-COTACAO
    MODULE Z_ATUALIZA_CAMPOS.
  ENDCHAIN.

  MODULE ZM_USER_COMMAND.

  MODULE ZM_EXIT_COMMAND AT EXIT-COMMAND.

PROCESS ON VALUE-REQUEST.

  FIELD S_TELA-IVA MODULE HLP_MWSKZ.
  FIELD S_TELA-COMP_TIPO MODULE HLP_TIPO.
