PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLEST0059 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLEST0059-BUKRS .
    FIELD ZLEST0059-AUART .
    FIELD ZLEST0059-PO_EMBARQUE .
    FIELD ZLEST0059-PO_DESTINO .
    FIELD ZLEST0059-OPERACAO .
    FIELD ZLEST0059-MATNR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLEST0059-BUKRS .
    FIELD ZLEST0059-AUART .
    FIELD ZLEST0059-PO_EMBARQUE .
    FIELD ZLEST0059-PO_DESTINO .
    FIELD ZLEST0059-OPERACAO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
