PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLEST0022 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLEST0022-TRANSPORTADOR .
    FIELD ZLEST0022-POSTO .
    FIELD ZLEST0022-LOTE .
    FIELD ZLEST0022-CHVID .
    FIELD ZLEST0022-TIPTRANSP .
    FIELD ZLEST0022-CTLGLANCTO .
    FIELD ZLEST0022-CONHECIMENTO .
    FIELD ZLEST0022-DOCSAP .
    FIELD ZLEST0022-GJAHR .
    FIELD ZLEST0022-BUKRS .
    FIELD ZLEST0022-OBS_CONFER .
    FIELD ZLEST0022-ACDCTIPO .
    FIELD ZLEST0022-ACDCINFO .
    FIELD ZLEST0022-UNAME .
    FIELD ZLEST0022-OBJ_KEY .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLEST0022-TRANSPORTADOR .
    FIELD ZLEST0022-POSTO .
    FIELD ZLEST0022-LOTE .
    FIELD ZLEST0022-CHVID .
    FIELD ZLEST0022-TIPTRANSP .
    FIELD ZLEST0022-CTLGLANCTO .
    FIELD ZLEST0022-CONHECIMENTO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
