PROCESS BEFORE OUTPUT.
 MODULE STATUS_0200.
*
PROCESS AFTER INPUT.
CHAIN.
    FIELD wg_edit-PERC_TOLER.
    FIELD wg_edit-PESO_TOLER.
    FIELD wg_edit-PESO.
    MODULE REFRESH_TOLERANCIA ON CHAIN-INPUT.
  ENDCHAIN.
 MODULE USER_COMMAND_0200.
