
PROCESS BEFORE OUTPUT.
  CALL SUBSCREEN :
          SU_VINC_NF  INCLUDING SY-REPID '1210'.

  MODULE STATUS_1200.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_1200.
  "MODULE USER_COMMAND_EXIT AT EXIT-COMMAND.

PROCESS ON VALUE-REQUEST.
  FIELD WG_TELA1200-TOMADOR_COD MODULE LIST_TOMADOR.
