FUNCTION ZLES_CADASTRO_AVSEG_CAD.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_CONSULTA) TYPE  CHAR01
*"     REFERENCE(I_CD_AVERBACAO) TYPE  ZDE_CD_AVERBACAO OPTIONAL
*"  EXPORTING
*"     REFERENCE(I_GRAVOU) TYPE  CHAR01
*"  CHANGING
*"     REFERENCE(I_OB_AVERBACAO) TYPE REF TO  ZCL_AVERBACAO_SEGURO
*"       OPTIONAL
*"----------------------------------------------------------------------

  IF I_OB_AVERBACAO IS NOT INITIAL.
    OBJ_AVERBACAO = I_OB_AVERBACAO.
  ELSE.
    CREATE OBJECT OBJ_AVERBACAO.
    IF I_CD_AVERBACAO IS NOT INITIAL.
      OBJ_AVERBACAO->SET_REGISTRO( I_ID_REGISTRO = I_CD_AVERBACAO ).
    ENDIF.
  ENDIF.

  CK_CONSULTA         = I_CONSULTA.
  CK_GRAVADO          = ABAP_FALSE.

  PERFORM CADASTRO_AVERBACAO.

  IF CK_GRAVADO EQ ABAP_TRUE OR I_CONSULTA IS NOT INITIAL.
    I_OB_AVERBACAO = OBJ_AVERBACAO.
    I_GRAVOU = ABAP_TRUE.
  ENDIF.

  CLEAR: OBJ_AVERBACAO.

  "PERFORM LIMPAR_VARIAVEIS.

  I_GRAVOU = CK_GRAVADO.

ENDFUNCTION.
