*&---------------------------------------------------------------------*
*& Report  ZLESR0083
*&
*&---------------------------------------------------------------------*
*&TITULO: NF Terceiros - Chegadas e Saídas – L1, L2 e L3
*&AUTOR : MARCOS FANELI
*&DATA. : 22.04.2014
*&---------------------------------------------------------------------*

REPORT  ZLESR0083.

*----------------------------------------------------------------------*
* TABLES
*----------------------------------------------------------------------*
TABLES: ZLEST0087,
        ZLEST0088,
        LFA1.

*----------------------------------------------------------------------*
* ESTRUTURAS
*----------------------------------------------------------------------*

TYPES:
    BEGIN OF TY_ZLEST0087,
      IDINTER TYPE ZLEST0087-IDINTER,
      TP_MOVI TYPE ZLEST0087-TP_MOVI,
      TP_REG TYPE ZLEST0087-TP_REG,
      BUKRS TYPE ZLEST0087-BUKRS,
      WERKS TYPE ZLEST0087-WERKS,
      NR_NF TYPE ZLEST0087-NR_NF,
      SERIE TYPE ZLEST0087-SERIE,
      CNPJ_PREST_SERV TYPE ZLEST0087-CNPJ_PREST_SERV,
      LIFNR TYPE ZLEST0087-LIFNR,
      PESO_NF TYPE ZLEST0087-PESO_NF,
      PRODUTO TYPE ZLEST0087-PRODUTO,
      DESCARGA_RODO TYPE ZLEST0087-DESCARGA_RODO,
      DT_DESCARGA TYPE ZLEST0087-DT_DESCARGA,
      DTAENVIO TYPE ZLEST0087-DTAENVIO,
      HORAENVIO TYPE ZLEST0087-HORAENVIO,
      ID_REFKEY TYPE ZLEST0087-ID_REFKEY,
      END OF TY_ZLEST0087,

    BEGIN OF TY_ZLEST0088,
      IDINTER TYPE ZLEST0088-IDINTER,
      TP_MOVI TYPE ZLEST0088-TP_MOVI,
      TP_REG TYPE ZLEST0088-TP_REG,
      BUKRS TYPE ZLEST0088-BUKRS,
      WERKS TYPE ZLEST0088-WERKS,
      NR_NF TYPE ZLEST0088-NR_NF,
      SERIE TYPE ZLEST0088-SERIE,
      CNPJ_PREST_SERV TYPE ZLEST0088-CNPJ_PREST_SERV,
      LIFNR TYPE ZLEST0088-LIFNR,
      PESO_NF TYPE ZLEST0088-PESO_NF,
      PRODUTO TYPE ZLEST0088-PRODUTO,
      DCL TYPE ZLEST0088-DCL,
      SERIEDCL TYPE ZLEST0088-SERIEDCL,
      PESO_VAGAO TYPE ZLEST0088-PESO_VAGAO,
      DT_FERRO TYPE ZLEST0088-DT_FERRO,
      HORA_FERRO TYPE ZLEST0088-HORA_FERRO,
      ID_REFKEY TYPE ZLEST0088-ID_REFKEY,
      END OF TY_ZLEST0088,

    BEGIN OF TY_LFA1,
      STCD1 TYPE LFA1-STCD1,
      LIFNR TYPE LFA1-LIFNR,
      NAME1 TYPE LFA1-NAME1,
      END OF TY_LFA1,

    BEGIN OF TY_MAKT,
      MATNR TYPE MAKT-MATNR,
      SPRAS TYPE MAKT-SPRAS,
      MAKTX TYPE MAKT-MAKTX,
      END OF TY_MAKT,

    BEGIN OF TY_SAIDA,
      IDINTER     TYPE ZLEST0087-IDINTER,
      TP_MOVI     TYPE ZLEST0087-TP_MOVI,
      TP_REG TYPE ZLEST0087-TP_REG,
      EMPRESA TYPE ZLEST0087-BUKRS,
      FILIAL TYPE ZLEST0087-WERKS,
      NR_NF_TERCEIRO TYPE ZLEST0087-NR_NF,
      SERIE TYPE ZLEST0087-SERIE,
      COD_DESC_RODO TYPE LFA1-LIFNR,
      NOME_DESC_RODO TYPE LFA1-NAME1,
      PESO_NF TYPE ZLEST0087-PESO_NF,
      PESO_DESC_RODO TYPE ZLEST0087-DESCARGA_RODO,
      DT_DESC_RODO TYPE ZLEST0087-DT_DESCARGA,
      PRODUTO TYPE ZLEST0087-PRODUTO,
      DESCR_PRODUTO TYPE MAKT-MAKTX,
      DT_ENVIO TYPE ZLEST0087-DTAENVIO,
      HR_ENVIO TYPE ZLEST0087-HORAENVIO,
      SERIEDCL TYPE ZLEST0088-SERIEDCL,
      DCL TYPE ZLEST0088-DCL,
      PESO_VAGAO TYPE ZLEST0088-PESO_VAGAO,
      ID_REFKEY  TYPE ZLEST0087-ID_REFKEY,
      END OF TY_SAIDA.

*----------------------------------------------------------------------*
* TABELAS INTERNA
*----------------------------------------------------------------------*
DATA :IT_ZLEST0087 TYPE TABLE OF TY_ZLEST0087,
      IT_ZLEST0087_10 TYPE TABLE OF TY_ZLEST0087,
      IT_LFA1 TYPE TABLE OF TY_LFA1,
      IT_LFA1_2 TYPE TABLE OF TY_LFA1,
      IT_MAKT TYPE TABLE OF TY_MAKT,
      IT_ZLEST0088 TYPE TABLE OF TY_ZLEST0088,
      IT_ZLEST0088_10 TYPE TABLE OF TY_ZLEST0088,
      IT_SAIDA TYPE TABLE OF TY_SAIDA.

*----------------------------------------------------------------------*
* WORK AREA
*----------------------------------------------------------------------*
DATA: WA_ZLEST0087 TYPE TY_ZLEST0087,
      WA_ZLEST0087_10 TYPE TY_ZLEST0087,
      WA_ZLEST0088 TYPE TY_ZLEST0088,
      WA_ZLEST0088_10 TYPE TY_ZLEST0088,
      WA_LFA1 TYPE TY_LFA1,
      WA_MAKT TYPE TY_MAKT,
      WA_SAIDA TYPE TY_SAIDA.

*----------------------------------------------------------------------*
* ALV
*----------------------------------------------------------------------*
TYPE-POOLS: KKBLO.

DATA: VI_LINNO LIKE SY-LINNO,
      VC_REPID LIKE SY-REPID,
      ST_HEADER TYPE KKBLO_LISTHEADER,
      ST_FIELDCAT TYPE KKBLO_FIELDCAT,
      IT_HEADER TYPE KKBLO_T_LISTHEADER,
      IT_FIELDCAT TYPE KKBLO_T_FIELDCAT,
      IT_SORT TYPE SLIS_T_SORTINFO_ALV WITH HEADER LINE,
      IT_FIELDCAT_ALV TYPE SLIS_T_FIELDCAT_ALV,
      IT_SPECIAL_GROUPS TYPE SLIS_T_SP_GROUP_ALV,
      IT_LAYOUT_ALV TYPE SLIS_LAYOUT_ALV,
      ST_LAYOUT TYPE KKBLO_LAYOUT,
      ST_VARIANT TYPE DISVARIANT,
      IT_EVENTOS TYPE SLIS_T_EVENT,
      ST_PRINT TYPE SLIS_PRINT_ALV.

DATA: BEGIN OF IT_OUTTAB OCCURS 0.
DATA:   COLINFO TYPE KKBLO_T_SPECIALCOL.
DATA:   DESCST(10),
END OF IT_OUTTAB.

*----------------------------------------------------------------------*
* TELA DE SELEÇÃO
*----------------------------------------------------------------------*
SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

SELECT-OPTIONS: P_PERI FOR ZLEST0087-DT_DESCARGA OBLIGATORY,
                P_NR_FOR FOR LFA1-LIFNR,
                P_NR_PRE FOR LFA1-LIFNR,
                P_IDENT FOR ZLEST0087-IDINTER  NO-EXTENSION NO INTERVALS .
SELECTION-SCREEN: END OF BLOCK B1.



AT SELECTION-SCREEN OUTPUT.

*  IF NOT P_IDENT-LOW = 'L1' AND
*     NOT P_IDENT-LOW = 'L2' AND
*     NOT P_IDENT-LOW = 'L3' AND
*     NOT P_IDENT-LOW = ''.
*    MESSAGE 'Tipo de modal invalido.' TYPE 'I'.
*    SET CURSOR FIELD 'P_IDENT-LOW' .
*  ENDIF.

START-OF-SELECTION.
  IF 'L1_L2_L3' CS P_IDENT-LOW OR P_IDENT-LOW  IS INITIAL.
    PERFORM:
              F_SELECIONA_DADOS, " Form seleciona dados
              F_SAIDA, " Form de saida
              F_IMPRIME_DADOS.
  ENDIF.

END-OF-SELECTION.

*&---------------------------------------------------------------------*
*&      Form  F_SELECIONA_DADOS
*&---------------------------------------------------------------------*
FORM F_SELECIONA_DADOS .

  SELECT IDINTER TP_MOVI TP_REG BUKRS WERKS NR_NF SERIE CNPJ_PREST_SERV LIFNR PESO_NF PRODUTO DESCARGA_RODO DT_DESCARGA DTAENVIO HORAENVIO ID_REFKEY
  FROM ZLEST0087
  INTO TABLE IT_ZLEST0087
  WHERE LIFNR IN P_NR_FOR
  AND IDINTER IN P_IDENT
  AND TP_REG = '30'
  AND STATUS = ''
  AND DT_DESCARGA IN P_PERI.

  IF IT_ZLEST0087 IS NOT INITIAL.
    SELECT IDINTER TP_MOVI TP_REG BUKRS ZLEST0087~WERKS NR_NF SERIE CNPJ_PREST_SERV ZLEST0087~LIFNR PESO_NF PRODUTO DESCARGA_RODO DT_DESCARGA DTAENVIO HORAENVIO ID_REFKEY
    FROM ZLEST0087
    INNER JOIN LFA1 ON LFA1~STCD1 = ZLEST0087~CNPJ_PREST_SERV
    INTO TABLE IT_ZLEST0087_10
    FOR ALL ENTRIES IN IT_ZLEST0087
    WHERE ID_REFKEY = IT_ZLEST0087-ID_REFKEY
    AND TP_REG = '10'
    AND LFA1~LIFNR IN P_NR_PRE.
  ENDIF.

  SELECT IDINTER TP_MOVI TP_REG BUKRS WERKS NR_NF SERIE CNPJ_PREST_SERV LIFNR PESO_NF PRODUTO DCL SERIEDCL PESO_VAGAO DT_FERRO HORA_FERRO ID_REFKEY
  FROM ZLEST0088
  INTO TABLE IT_ZLEST0088
  WHERE LIFNR IN P_NR_FOR
  AND IDINTER IN P_IDENT
  AND TP_REG = '30'
  AND STATUS = ''
  AND DT_FERRO IN P_PERI.

  IF IT_ZLEST0088 IS NOT INITIAL.
    SELECT IDINTER TP_MOVI TP_REG BUKRS ZLEST0088~WERKS NR_NF SERIE CNPJ_PREST_SERV ZLEST0088~LIFNR PESO_NF PRODUTO DCL SERIEDCL PESO_VAGAO DT_FERRO HORA_FERRO ID_REFKEY
    FROM ZLEST0088
    INNER JOIN LFA1 ON LFA1~STCD1 = ZLEST0088~CNPJ_PREST_SERV
    INTO TABLE IT_ZLEST0088_10
    FOR ALL ENTRIES IN IT_ZLEST0088
    WHERE ID_REFKEY = IT_ZLEST0088-ID_REFKEY
    AND TP_REG = '10'
    AND LFA1~STCD1 IN P_NR_PRE.
  ENDIF.

  IF IT_ZLEST0087[] IS NOT INITIAL .
    SELECT  STCD1 LIFNR NAME1
    FROM LFA1
    INTO TABLE IT_LFA1
    FOR ALL ENTRIES IN IT_ZLEST0087_10
    WHERE STCD1 = IT_ZLEST0087_10-CNPJ_PREST_SERV
    AND STCD1 <> ''.

    SELECT  STCD1 LIFNR NAME1
    FROM LFA1
    APPENDING TABLE IT_LFA1
    FOR ALL ENTRIES IN IT_ZLEST0087
    WHERE LIFNR = IT_ZLEST0087-LIFNR
    AND LIFNR <> ''.

    SELECT MATNR SPRAS MAKTX
    FROM MAKT
    INTO TABLE IT_MAKT
    FOR ALL ENTRIES IN IT_ZLEST0087
    WHERE MATNR EQ IT_ZLEST0087-PRODUTO
    AND SPRAS = SY-LANGU.
  ENDIF.

  IF IT_ZLEST0088[] IS NOT INITIAL .
    SELECT STCD1 LIFNR NAME1
    FROM LFA1
    APPENDING TABLE IT_LFA1
    FOR ALL ENTRIES IN IT_ZLEST0088_10
    WHERE STCD1 = IT_ZLEST0088_10-CNPJ_PREST_SERV.

    SELECT  STCD1 LIFNR NAME1
    FROM LFA1
    APPENDING TABLE IT_LFA1
    FOR ALL ENTRIES IN IT_ZLEST0088
    WHERE LIFNR = IT_ZLEST0088-LIFNR.

    SELECT MATNR SPRAS MAKTX
    FROM MAKT
    APPENDING TABLE IT_MAKT
    FOR ALL ENTRIES IN IT_ZLEST0088
    WHERE MATNR EQ IT_ZLEST0088-PRODUTO
    AND SPRAS = SY-LANGU.
  ENDIF.

ENDFORM.                    "F_SELECIONA_DADOS
*&---------------------------------------------------------------------*
*&      Form  F_SAIDA
*&---------------------------------------------------------------------*
FORM F_SAIDA .
  IT_LFA1_2[] = IT_LFA1[].

  SORT: IT_LFA1 BY STCD1,
        IT_LFA1_2 BY LIFNR,
        IT_MAKT BY MATNR,
        IT_ZLEST0087 BY ID_REFKEY,
        IT_ZLEST0088 BY ID_REFKEY.

  LOOP AT IT_ZLEST0087_10 INTO WA_ZLEST0087_10.
    LOOP AT IT_ZLEST0087 INTO WA_ZLEST0087 WHERE ID_REFKEY = WA_ZLEST0087_10-ID_REFKEY.
      WA_SAIDA-COD_DESC_RODO = WA_ZLEST0087-LIFNR.
      READ TABLE IT_LFA1_2 INTO WA_LFA1 WITH KEY LIFNR = WA_ZLEST0087-LIFNR BINARY SEARCH.
      IF SY-SUBRC = 0.
        WA_SAIDA-NOME_DESC_RODO = WA_LFA1-NAME1.
      ENDIF.

      READ TABLE IT_MAKT INTO WA_MAKT WITH KEY MATNR = WA_ZLEST0087-PRODUTO BINARY SEARCH.
      IF SY-SUBRC = 0.
        WA_SAIDA-DESCR_PRODUTO = WA_MAKT-MAKTX.
      ENDIF.

      WA_SAIDA-IDINTER        = WA_ZLEST0087-IDINTER.
      WA_SAIDA-TP_MOVI        = WA_ZLEST0087-TP_MOVI.
      WA_SAIDA-TP_REG         = WA_ZLEST0087-TP_REG.
      WA_SAIDA-EMPRESA        = WA_ZLEST0087-BUKRS.
      WA_SAIDA-FILIAL         = WA_ZLEST0087-WERKS.
      WA_SAIDA-NR_NF_TERCEIRO = WA_ZLEST0087-NR_NF.
      WA_SAIDA-SERIE          = WA_ZLEST0087-SERIE.
      WA_SAIDA-PESO_NF        = WA_ZLEST0087-PESO_NF.
      WA_SAIDA-PESO_DESC_RODO = WA_ZLEST0087-DESCARGA_RODO.
      WA_SAIDA-DT_DESC_RODO   = WA_ZLEST0087-DT_DESCARGA.
      WA_SAIDA-PRODUTO        = WA_ZLEST0087-PRODUTO.
      WA_SAIDA-DT_ENVIO       = WA_ZLEST0087-DTAENVIO.
      WA_SAIDA-HR_ENVIO       = WA_ZLEST0087-HORAENVIO.
      WA_SAIDA-ID_REFKEY      = WA_ZLEST0087-ID_REFKEY.

      APPEND WA_SAIDA TO IT_SAIDA.
      CLEAR WA_SAIDA.
    ENDLOOP.
    READ TABLE IT_LFA1 INTO WA_LFA1 WITH KEY STCD1 = WA_ZLEST0087_10-CNPJ_PREST_SERV BINARY SEARCH.
    IF SY-SUBRC = 0.
      WA_SAIDA-NOME_DESC_RODO = WA_LFA1-NAME1.
      WA_SAIDA-COD_DESC_RODO  = WA_LFA1-LIFNR.
    ENDIF.
    WA_SAIDA-IDINTER        = WA_ZLEST0087_10-IDINTER.
    WA_SAIDA-TP_MOVI        = WA_ZLEST0087_10-TP_MOVI.
    WA_SAIDA-TP_REG         = WA_ZLEST0087_10-TP_REG.
    WA_SAIDA-EMPRESA        = WA_ZLEST0087_10-BUKRS.
    WA_SAIDA-FILIAL         = WA_ZLEST0087_10-WERKS.
    WA_SAIDA-NR_NF_TERCEIRO = WA_ZLEST0087_10-NR_NF.
    WA_SAIDA-SERIE          = WA_ZLEST0087_10-SERIE.
    WA_SAIDA-PESO_NF        = WA_ZLEST0087_10-PESO_NF.
    WA_SAIDA-DT_ENVIO       = WA_ZLEST0087_10-DTAENVIO.
    WA_SAIDA-HR_ENVIO       = WA_ZLEST0087_10-HORAENVIO.
    WA_SAIDA-ID_REFKEY      = WA_ZLEST0087_10-ID_REFKEY.
    APPEND WA_SAIDA TO IT_SAIDA.
    CLEAR WA_SAIDA.
  ENDLOOP.

  LOOP AT IT_ZLEST0088_10 INTO WA_ZLEST0088_10.
    LOOP AT IT_ZLEST0088 INTO WA_ZLEST0088 WHERE ID_REFKEY = WA_ZLEST0088_10-ID_REFKEY.
      WA_SAIDA-COD_DESC_RODO = WA_ZLEST0088-LIFNR.
      READ TABLE IT_LFA1_2 INTO WA_LFA1 WITH KEY LIFNR = WA_ZLEST0088-LIFNR BINARY SEARCH.
      IF SY-SUBRC = 0.
        WA_SAIDA-NOME_DESC_RODO = WA_LFA1-NAME1.
      ENDIF.

      READ TABLE IT_MAKT INTO WA_MAKT WITH KEY MATNR = WA_ZLEST0088-PRODUTO BINARY SEARCH.
      IF SY-SUBRC = 0.
        WA_SAIDA-DESCR_PRODUTO = WA_MAKT-MAKTX.
      ENDIF.

      WA_SAIDA-IDINTER        = WA_ZLEST0088-IDINTER.
      WA_SAIDA-TP_MOVI        = WA_ZLEST0088-TP_MOVI.
      WA_SAIDA-TP_REG         = WA_ZLEST0088-TP_REG.
      WA_SAIDA-EMPRESA        = WA_ZLEST0088-BUKRS.
      WA_SAIDA-FILIAL         = WA_ZLEST0088-WERKS.
      WA_SAIDA-NR_NF_TERCEIRO = WA_ZLEST0088-NR_NF.
      WA_SAIDA-SERIE          = WA_ZLEST0088-SERIE.
      WA_SAIDA-PESO_NF        = WA_ZLEST0088-PESO_NF.
      WA_SAIDA-DCL            = WA_ZLEST0088-DCL.
      WA_SAIDA-SERIEDCL       = WA_ZLEST0088-SERIEDCL.
      WA_SAIDA-PESO_VAGAO     = WA_ZLEST0088-PESO_VAGAO.
      WA_SAIDA-DT_ENVIO       = WA_ZLEST0088-DT_FERRO.
      WA_SAIDA-HR_ENVIO       = WA_ZLEST0088-HORA_FERRO.
      WA_SAIDA-ID_REFKEY      = WA_ZLEST0088_10-ID_REFKEY.
      APPEND WA_SAIDA TO IT_SAIDA.
      CLEAR WA_SAIDA.
    ENDLOOP.
    READ TABLE IT_LFA1 INTO WA_LFA1 WITH KEY STCD1 = WA_ZLEST0087_10-CNPJ_PREST_SERV BINARY SEARCH.
    IF SY-SUBRC = 0.
      WA_SAIDA-NOME_DESC_RODO = WA_LFA1-NAME1.
      WA_SAIDA-COD_DESC_RODO  = WA_LFA1-LIFNR.
    ENDIF.
    WA_SAIDA-IDINTER        = WA_ZLEST0088_10-IDINTER.
    WA_SAIDA-TP_MOVI        = WA_ZLEST0088_10-TP_MOVI.
    WA_SAIDA-TP_REG         = WA_ZLEST0088_10-TP_REG.
    WA_SAIDA-EMPRESA        = WA_ZLEST0088_10-BUKRS.
    WA_SAIDA-FILIAL         = WA_ZLEST0088_10-WERKS.
    WA_SAIDA-NR_NF_TERCEIRO = WA_ZLEST0088_10-NR_NF.
    WA_SAIDA-SERIE          = WA_ZLEST0088_10-SERIE.
    WA_SAIDA-PESO_NF        = WA_ZLEST0088_10-PESO_NF.
    WA_SAIDA-DCL            = WA_ZLEST0088_10-DCL.
    WA_SAIDA-SERIEDCL       = WA_ZLEST0088_10-SERIEDCL.
    WA_SAIDA-PESO_VAGAO     = WA_ZLEST0088_10-PESO_VAGAO.
    WA_SAIDA-DT_ENVIO       = WA_ZLEST0088-DT_FERRO.
    WA_SAIDA-HR_ENVIO       = WA_ZLEST0088-HORA_FERRO.
    WA_SAIDA-ID_REFKEY      = WA_ZLEST0088_10-ID_REFKEY.
    APPEND WA_SAIDA TO IT_SAIDA.
    CLEAR WA_SAIDA.
  ENDLOOP.

  SORT IT_SAIDA BY ID_REFKEY TP_REG.
ENDFORM.                    " F_SAIDA

*&---------------------------------------------------------------------*
*&      Form  F_IMPRIME_DADOS
*&---------------------------------------------------------------------*
FORM F_IMPRIME_DADOS .
  PERFORM F_CABECALHO.
  PERFORM F_CATALOGO.
  PERFORM F_LAYOUT.
  PERFORM F_RELATORIO.
ENDFORM.                    " F_IMPRIME_DADOS

*&---------------------------------------------------------------------*
*&      Form  F_CABECALHO
*&---------------------------------------------------------------------*
FORM F_CABECALHO .
  DATA V_STR_1(20).
  DATA V_STR_2(20).
*  CLEAR ST_HEADER.
*  ST_HEADER-TYP  = 'H'.
*  ST_HEADER-INFO = 'NF Terceiros - Chegadas e Saídas – L1, L2 e L3'.
*  APPEND ST_HEADER TO IT_HEADER.

*  EXIBE FILTRO USADO NO PERIODO
  CLEAR ST_HEADER.
  ST_HEADER-TYP  = 'S'.
  ST_HEADER-KEY  = 'Periodo:'.

  CONCATENATE P_PERI-LOW+6(2) '/' P_PERI-LOW+4(2) '/' P_PERI-LOW+0(4) INTO V_STR_1.

  IF P_PERI-HIGH IS NOT INITIAL.
    CONCATENATE P_PERI-HIGH+6(2) '/' P_PERI-HIGH+4(2) '/' P_PERI-HIGH+0(4) INTO V_STR_2.
    CONCATENATE V_STR_1 'a' V_STR_2 INTO ST_HEADER-INFO SEPARATED BY SPACE.
  ELSE.
    CONCATENATE 'a partir' V_STR_1 INTO ST_HEADER-INFO SEPARATED BY SPACE.
  ENDIF.

  APPEND ST_HEADER TO IT_HEADER.

*  EXIBE FILTRO USADO NO COD. FORNECEDOR
*-----------------------------------------------------------------
  CLEAR ST_HEADER.
  ST_HEADER-TYP  = 'S'.
  ST_HEADER-KEY  = 'Cod. Fornecedor:'.

  IF P_NR_FOR-LOW IS NOT INITIAL.
    V_STR_1 = P_NR_FOR-LOW.
  ENDIF.

  IF P_NR_FOR-HIGH IS NOT INITIAL.
    V_STR_2 = P_NR_FOR-HIGH.
    CONCATENATE V_STR_1 'a' V_STR_2 INTO ST_HEADER-INFO SEPARATED BY SPACE.
  ELSE.
    ST_HEADER-INFO = V_STR_1.
  ENDIF.

  if P_NR_FOR-LOW IS NOT INITIAL.
    APPEND ST_HEADER TO IT_HEADER.
  ENDIF.

*  EXIBE FILTRO USADO NO CNPJ PRESTADOR
*-----------------------------------------------------------------
  CLEAR ST_HEADER.
  ST_HEADER-TYP  = 'S'.
  ST_HEADER-KEY  = 'Cod. Prestador:'.

  IF P_NR_PRE-LOW IS NOT INITIAL.
    V_STR_1 = P_NR_PRE-LOW.
  ENDIF.

  IF P_NR_PRE-HIGH IS NOT INITIAL.
    V_STR_2 = P_NR_PRE-HIGH.
    CONCATENATE V_STR_1 'a' V_STR_2 INTO ST_HEADER-INFO SEPARATED BY SPACE.
  ELSE.
    ST_HEADER-INFO = V_STR_1.
  ENDIF.

  if P_NR_PRE-LOW IS NOT INITIAL.
    APPEND ST_HEADER TO IT_HEADER.
  ENDIF.

*  EXIBE FILTRO USADO NO IDENTIFICADOR
*-----------------------------------------------------------------
  CLEAR ST_HEADER.
  ST_HEADER-TYP  = 'S'.
  ST_HEADER-KEY  = 'Identificador:'.

  IF P_IDENT-LOW IS NOT INITIAL.
    ST_HEADER-INFO = P_IDENT-LOW.
    APPEND ST_HEADER TO IT_HEADER.
  ENDIF.

ENDFORM.                    " F_CABECALHO

*&---------------------------------------------------------------------*
*&      Form  F_CATALOGO
*&---------------------------------------------------------------------*
FORM F_CATALOGO .
  DATA I TYPE I.

  REFRESH IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'IDINTER'.
  ST_FIELDCAT-OUTPUTLEN     = '2'.
  ST_FIELDCAT-SELTEXT_L     = 'Tp. Modal'.
  ST_FIELDCAT-SELTEXT_M     = 'Tp. Modal'.
  ST_FIELDCAT-SELTEXT_S     = 'Tp. Modal'.
  ST_FIELDCAT-KEY           = 'X'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'TP_MOVI'.
  ST_FIELDCAT-OUTPUTLEN     = '2'.
  ST_FIELDCAT-SELTEXT_L     = 'Tp. Mov.'.
  ST_FIELDCAT-SELTEXT_M     = 'Tp. Mov.'.
  ST_FIELDCAT-SELTEXT_S     = 'Tp. Mov.'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'TP_REG'.
  ST_FIELDCAT-OUTPUTLEN     = '2'.
  ST_FIELDCAT-SELTEXT_L     = 'Tp. Reg'.
  ST_FIELDCAT-SELTEXT_M     = 'Tp. Reg'.
  ST_FIELDCAT-SELTEXT_S     = 'Tp. Reg'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'EMPRESA'.
  ST_FIELDCAT-OUTPUTLEN     = '4'.
  ST_FIELDCAT-SELTEXT_L     = 'Emp.'.
  ST_FIELDCAT-SELTEXT_M     = 'Emp.'.
  ST_FIELDCAT-SELTEXT_S     = 'Emp.'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.


  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'FILIAL'.
  ST_FIELDCAT-OUTPUTLEN     = '4'.
  ST_FIELDCAT-SELTEXT_L     = 'Filial'.
  ST_FIELDCAT-SELTEXT_M     = 'Filial'.
  ST_FIELDCAT-SELTEXT_S     = 'Filial'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'NR_NF_TERCEIRO'.
  ST_FIELDCAT-OUTPUTLEN     = '9'.
  ST_FIELDCAT-SELTEXT_L     = 'Num. NF'.
  ST_FIELDCAT-SELTEXT_M     = 'Num. NF'.
  ST_FIELDCAT-SELTEXT_S     = 'Num. NF'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'SERIE'.
  ST_FIELDCAT-OUTPUTLEN     = '3'.
  ST_FIELDCAT-SELTEXT_L     = 'Série'.
  ST_FIELDCAT-SELTEXT_M     = 'Série'.
  ST_FIELDCAT-SELTEXT_S     = 'Série'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'COD_DESC_RODO'.
  ST_FIELDCAT-OUTPUTLEN     = '9'.
  ST_FIELDCAT-SELTEXT_L     = 'Nº conta do fornecedor'.
  ST_FIELDCAT-SELTEXT_M     = 'Número do Fornecedor'.
  ST_FIELDCAT-SELTEXT_S     = 'Nº. Fornec.'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'NOME_DESC_RODO'.
  ST_FIELDCAT-OUTPUTLEN     = '20'.
  ST_FIELDCAT-SELTEXT_L     = 'Nome do Fornecedor'.
  ST_FIELDCAT-SELTEXT_M     = 'Nome do Fornecedor'.
  ST_FIELDCAT-SELTEXT_S     = 'Nome do Fornecedor'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'PESO_NF'.
  ST_FIELDCAT-OUTPUTLEN     = '13'.
  ST_FIELDCAT-SELTEXT_L     = 'Peso'.
  ST_FIELDCAT-SELTEXT_M     = 'Peso'.
  ST_FIELDCAT-SELTEXT_S     = 'Peso'.
  ST_FIELDCAT-DO_SUM        = ''.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.
  CLEAR ST_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'PESO_DESC_RODO'.
  ST_FIELDCAT-OUTPUTLEN     = '13'.
  ST_FIELDCAT-SELTEXT_L     = 'Quant.'.
  ST_FIELDCAT-SELTEXT_M     = 'Quant.'.
  ST_FIELDCAT-SELTEXT_S     = 'Quant.'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'DT_DESC_RODO'.
  ST_FIELDCAT-OUTPUTLEN     = '8'.
  ST_FIELDCAT-SELTEXT_L     = 'Data Descarregamento.'.
  ST_FIELDCAT-SELTEXT_M     = 'Data Desc.'.
  ST_FIELDCAT-SELTEXT_S     = 'Data Desc.'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'PRODUTO'.
  ST_FIELDCAT-OUTPUTLEN     = '18'.
  ST_FIELDCAT-SELTEXT_L     = 'Produto'.
  ST_FIELDCAT-SELTEXT_M     = 'Prod.'.
  ST_FIELDCAT-SELTEXT_S     = 'Prod.'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'DESCR_PRODUTO'.
  ST_FIELDCAT-OUTPUTLEN     = '40'.
  ST_FIELDCAT-SELTEXT_L     = 'Descrição do Produto'.
  ST_FIELDCAT-SELTEXT_M     = 'Desc. Produção'.
  ST_FIELDCAT-SELTEXT_S     = 'Desc. Prod.'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'DT_ENVIO '.
  ST_FIELDCAT-OUTPUTLEN     = '8'.
  ST_FIELDCAT-SELTEXT_L     = 'Data Envio'.
  ST_FIELDCAT-SELTEXT_M     = 'Dt. Envio'.
  ST_FIELDCAT-SELTEXT_S     = 'Dt. Env.'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'HR_ENVIO'.
  ST_FIELDCAT-OUTPUTLEN     = '6'.
  ST_FIELDCAT-SELTEXT_L     = 'Hora de Envio'.
  ST_FIELDCAT-SELTEXT_M     = 'Hora Envio'.
  ST_FIELDCAT-SELTEXT_S     = 'Hora Env.'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'DCL'.
  ST_FIELDCAT-OUTPUTLEN     = '10'.
  ST_FIELDCAT-SELTEXT_L     = 'DCL'.
  ST_FIELDCAT-SELTEXT_M     = 'DCL'.
  ST_FIELDCAT-SELTEXT_S     = 'DCL'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'SERIEDCL'.
  ST_FIELDCAT-OUTPUTLEN     = '3'.
  ST_FIELDCAT-SELTEXT_L     = 'Série DCL'.
  ST_FIELDCAT-SELTEXT_M     = 'Série DCL'.
  ST_FIELDCAT-SELTEXT_S     = 'Série DCL'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

  I = I + 1.
  CLEAR ST_FIELDCAT.
  ST_FIELDCAT-COL_POS       = I.
  ST_FIELDCAT-FIELDNAME     = 'PESO_VAGAO'.
  ST_FIELDCAT-OUTPUTLEN     = '13'.
  ST_FIELDCAT-SELTEXT_L     = 'Qtd. Vagão'.
  ST_FIELDCAT-SELTEXT_M     = 'Qtd. Vagão'.
  ST_FIELDCAT-SELTEXT_S     = 'Qtd. Vagão'.
  APPEND ST_FIELDCAT TO IT_FIELDCAT.

ENDFORM.                    " F_CATALOGO

*&---------------------------------------------------------------------*
*&      Form  F_LAYOUT
*&---------------------------------------------------------------------*
FORM F_LAYOUT .
  ST_LAYOUT-NO_ZEBRA            = ' '.
  ST_LAYOUT-COLWIDTH_OPTIMIZE   = ' '.

  CALL FUNCTION 'REUSE_ALV_TRANSFER_DATA_BACK'
    EXPORTING
      IT_FIELDCAT       = IT_FIELDCAT
      IS_LAYOUT         = ST_LAYOUT
    IMPORTING
      ET_FIELDCAT       = IT_FIELDCAT_ALV
      ES_LAYOUT         = IT_LAYOUT_ALV
      ET_SPECIAL_GROUPS = IT_SPECIAL_GROUPS.
ENDFORM.                    " F_LAYOUT

*&---------------------------------------------------------------------*
*&      Form  F_RELATORIO
*&---------------------------------------------------------------------*
FORM F_RELATORIO .
  VC_REPID = SY-REPID.
  MOVE VC_REPID TO ST_VARIANT-REPORT.

  ST_PRINT-NO_PRINT_SELINFOS  = 'X'.
  ST_PRINT-NO_PRINT_LISTINFOS = 'X'.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM     = VC_REPID
      IS_LAYOUT              = IT_LAYOUT_ALV
      IT_FIELDCAT            = IT_FIELDCAT_ALV
      IT_SORT                = IT_SORT[]
      I_SAVE                 = 'A'
      I_DEFAULT              = 'X'
      IT_EVENTS              = IT_EVENTOS[]
      I_CALLBACK_TOP_OF_PAGE = 'TOP_OF_PAGE'
    TABLES
      T_OUTTAB               = IT_SAIDA[]
    EXCEPTIONS
      PROGRAM_ERROR          = 1
      OTHERS                 = 2.

  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE 'I' NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    STOP.
  ENDIF.
ENDFORM.                    " F_RELATORIO

*&--------------------------------------------------------------------*
*&      Form  top_of_page
*&--------------------------------------------------------------------*
*       Imprime o cabegalho
*---------------------------------------------------------------------*
FORM TOP_OF_PAGE.
* Para criar um logotipo, deve-se entrar na transagco 0FPM002 e
* preencher:
* - Classe = PICTURES
* - Objeto = OT
* - Item   = Nome do ID da figura

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = IT_HEADER.
*      i_logo             = 'ENJOYSAP_LOGO'.

*  vi_linno = sy-linno.
*
*  skip to line 1.
*  write: at 70  'Pagina:', sy-pagno.
*
*  skip to line vi_linno.
ENDFORM.                    "top_of_page
