PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZLEST0101-ID_ROTA .
    FIELD ZLEST0101-BUKRS .
    FIELD ZLEST0101-BRANCH .
    FIELD ZLEST0101-COUNTRY .
    FIELD ZLEST0101-CD_CID_ORIGEM .
    FIELD ZLEST0101-CD_CID_DESTINO .
    FIELD ZLEST0101-TP_ROTA_PERC .
    FIELD ZLEST0101-ID_ROTA_ADM .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZLEST0101-ID_ROTA .
  module detail_pai.
 endchain.
