
PROCESS BEFORE OUTPUT.

  MODULE STATUS_0502.
*
PROCESS AFTER INPUT.

  CHAIN.
    FIELD ZLEST0101-BUKRS.
    FIELD ZLEST0101-BRANCH.
    MODULE LIMPAR_CIDADES ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0501_EXIT AT EXIT-COMMAND.

  MODULE USER_COMMAND_0502.
