FUNCTION-POOL ZLES_FAT_CONTINGENCIA.        "MESSAGE-ID ..

TYPES: BEGIN OF TY_ESTRUTURA.
         INCLUDE TYPE SLIS_FIELDCAT_MAIN.
         INCLUDE TYPE SLIS_FIELDCAT_ALV_SPEC.
       TYPES: END OF TY_ESTRUTURA.

DATA: GIT_ESTRUTURA    TYPE TABLE OF TY_ESTRUTURA,
      GWA_ESTRUTURA    TYPE TY_ESTRUTURA.

* INCLUDE LZLES_FAT_CONTINGENCIAD...         " Local class definition
