*&---------------------------------------------------------------------*
*&  Include           ZLESR0123_TABELAS
*&---------------------------------------------------------------------*

REPORT ZLESR0123.

TABLES: LFA1, TVRO, TZONE, EKKO, VTTK.


TYPES: BEGIN OF TY_SAIDA,
         SHTYP  TYPE A900-SHTYP,
         TDLNR  TYPE A900-TDLNR,
         ROUTE  TYPE A900-ROUTE,
         LZONEA TYPE A910-LZONEA,
         LZONEZ TYPE A910-LZONEZ,
         ADD01  TYPE A900-ADD01,
         MATNR  TYPE A918-MATNR,
         KBETR  TYPE KONP-KBETR,
         KONWA  TYPE KONP-KONWA,
         KMEIN  TYPE KONP-KMEIN,
         DDTEXT TYPE DD02T-DDTEXT,
         BEZEI  TYPE TVROT-BEZEI,
         VTEXTA TYPE TZONT-VTEXT,
         VTEXTZ TYPE TZONT-VTEXT,
         VSTEL  TYPE A933-VSTEL,
         PSTLZA TYPE A934-PSTLZA,
         VEGR5  TYPE A939-VEGR5,
         SDABW  TYPE A900-SDABW,
         BEZEC  TYPE  TVSAKT-BEZEI,
       END OF TY_SAIDA.


TYPES: BEGIN OF TY_A900,
         KNUMH TYPE A900-KNUMH,
         SHTYP TYPE A900-SHTYP,
         TDLNR TYPE A900-TDLNR,
         ROUTE TYPE A900-ROUTE,
         ADD01 TYPE A900-ADD01,
         KAPPL TYPE A900-KAPPL,
         KSCHL TYPE A900-KSCHL,
         DATBI TYPE A900-DATBI,
         DATAB TYPE A900-DATAB,
         SDABW TYPE A900-SDABW,
       END OF TY_A900.

TYPES: BEGIN OF TY_A911,
         KNUMH TYPE A911-KNUMH,
         SHTYP TYPE A911-SHTYP,
         TDLNR TYPE A911-TDLNR,
         ROUTE TYPE A911-ROUTE,
         KAPPL TYPE A911-KAPPL,
         KSCHL TYPE A911-KSCHL,
         DATBI TYPE A911-DATBI,
         DATAB TYPE A911-DATAB,
         SDABW TYPE A911-SDABW,
       END OF TY_A911.

TYPES: BEGIN OF TY_A910,
         KAPPL  TYPE A910-KAPPL,
         KSCHL  TYPE A910-KSCHL,
         KNUMH  TYPE A910-KNUMH,
         SHTYP  TYPE A910-SHTYP,
         TDLNR  TYPE A910-TDLNR,
         LZONEA TYPE A910-LZONEA,
         LZONEZ TYPE A910-LZONEZ,
       END OF TY_A910.


TYPES: BEGIN OF TY_A915,
         KAPPL  TYPE A915-KAPPL,
         KSCHL  TYPE A915-KSCHL,
         KNUMH  TYPE A915-KNUMH,
         SHTYP  TYPE A915-SHTYP,
         TDLNR  TYPE A915-TDLNR,
         LZONEA TYPE A915-LZONEA,
         LZONEZ TYPE A915-LZONEZ,
         ADD01  TYPE A915-ADD01,
       END OF TY_A915.

TYPES: BEGIN OF TY_A918,
         KAPPL  TYPE A918-KAPPL,
         KSCHL  TYPE A918-KSCHL,
         KNUMH  TYPE A918-KNUMH,
         SHTYP  TYPE A918-SHTYP,
         TDLNR  TYPE A918-TDLNR,
         LZONEA TYPE A918-LZONEA,
         LZONEZ TYPE A918-LZONEZ,
         ADD01  TYPE A918-ADD01,
         MATNR  TYPE A918-MATNR,
       END OF TY_A918.

TYPES: BEGIN OF TY_A919,
         KAPPL  TYPE A919-KAPPL,
         KSCHL  TYPE A919-KSCHL,
         KNUMH  TYPE A919-KNUMH,
         SHTYP  TYPE A919-SHTYP,
         TDLNR  TYPE A919-TDLNR,
         MATNR  TYPE A919-MATNR,
         LZONEA TYPE A919-LZONEA,
         LZONEZ TYPE A919-LZONEZ,
       END OF TY_A919.

TYPES: BEGIN OF TY_A933,
         KAPPL  TYPE A933-KAPPL,
         KSCHL  TYPE A933-KSCHL,
         DATBI  TYPE A933-DATBI,
         DATAB  TYPE A933-DATAB,
         KNUMH  TYPE A933-KNUMH,
         TDLNR  TYPE A933-TDLNR,
         LZONEA TYPE A933-LZONEA,
         LZONEZ TYPE A933-LZONEZ,
         VSTEL  TYPE A933-VSTEL,
         SHTYP  TYPE A933-SHTYP,
       END OF   TY_A933.

TYPES: BEGIN OF TY_A934,
         KAPPL  TYPE A934-KAPPL,
         KSCHL  TYPE A934-KSCHL,
         DATBI  TYPE A934-DATBI,
         DATAB  TYPE A934-DATAB,
         KNUMH  TYPE A934-KNUMH,
         TDLNR  TYPE A934-TDLNR,
         LZONEA TYPE A934-LZONEA,
         LZONEZ TYPE A934-LZONEZ,
         PSTLZA  TYPE A934-PSTLZA,
         SHTYP  TYPE A934-SHTYP,
       END OF   TY_A934.

TYPES: BEGIN OF TY_A938,
         KAPPL  TYPE A938-KAPPL,
         KSCHL  TYPE A938-KSCHL,
         DATBI  TYPE A938-DATBI,
         DATAB  TYPE A938-DATAB,
         KNUMH  TYPE A938-KNUMH,
         TDLNR  TYPE A938-TDLNR,
         LZONEA TYPE A938-LZONEA,
         LZONEZ TYPE A938-LZONEZ,
         PSTLZA  TYPE A938-PSTLZA,
         SHTYP  TYPE A938-SHTYP,
         MATNR  TYPE A938-MATNR,
       END OF   TY_A938.

TYPES: BEGIN OF TY_A939,
         KAPPL  TYPE A939-KAPPL,
         KSCHL  TYPE A939-KSCHL,
         DATBI  TYPE A939-DATBI,
         DATAB  TYPE A939-DATAB,
         KNUMH  TYPE A939-KNUMH,
         TDLNR  TYPE A939-TDLNR,
         LZONEA TYPE A939-LZONEA,
         LZONEZ TYPE A939-LZONEZ,
         VEGR5  TYPE A939-VEGR5,
         SHTYP  TYPE A939-SHTYP,
       END OF   TY_A939.

TYPES: BEGIN OF TY_A940,
         KNUMH TYPE A940-KNUMH,
         SHTYP TYPE A940-SHTYP,
         TDLNR TYPE A940-TDLNR,
         ROUTE TYPE A940-ROUTE,
         KAPPL TYPE A940-KAPPL,
         KSCHL TYPE A940-KSCHL,
         DATBI TYPE A940-DATBI,
         DATAB TYPE A940-DATAB,
         SDABW TYPE A940-SDABW,
       END OF TY_A940.

TYPES: BEGIN OF TY_TROLZ,
         ALAND TYPE TROLZ-ALAND,
         LLAND TYPE TROLZ-LLAND,
         AZONE TYPE TROLZ-AZONE,
         LZONE TYPE TROLZ-LZONE,
         ROUTE TYPE TROLZ-ROUTE,
       END OF TY_TROLZ.


TYPES: BEGIN OF TY_KONP,
         KNUMH TYPE  KONP-KNUMH,
         KAPPL TYPE  KONP-KAPPL,
         KSCHL TYPE  KONP-KSCHL,
         KBETR TYPE  KONP-KBETR,
         KONWA TYPE  KONP-KONWA,
         KMEIN TYPE  KONP-KMEIN,
         KRECH TYPE  KONP-KRECH,
       END OF TY_KONP.

TYPES: BEGIN OF TY_DD02T,
         TABNAME    TYPE DD02T-TABNAME,
         DDLANGUAGE TYPE DD02T-DDLANGUAGE,
         DDTEXT     TYPE DD02T-DDTEXT,
       END OF TY_DD02T.

TYPES: BEGIN OF TY_TVROT,
         ROUTE TYPE TVROT-ROUTE,
         BEZEI TYPE TVROT-BEZEI,
       END OF  TY_TVROT.

TYPES: BEGIN OF TY_TVSAKT,
         SDABW TYPE TVSAKT-SDABW,
         BEZEI TYPE TVSAKT-BEZEI,
       END OF  TY_TVSAKT.

TYPES: BEGIN OF TY_TZONT,
         LAND1 TYPE TZONT-LAND1,
         ZONE1 TYPE TZONT-ZONE1,
         VTEXT TYPE TZONT-VTEXT,
       END OF TY_TZONT.



DATA: T_SAIDA TYPE TABLE OF TY_SAIDA,
      T_A900  TYPE TABLE OF TY_A900,
      T_A911  TYPE TABLE OF TY_A911,
      T_A910  TYPE TABLE OF TY_A910,
      T_A915  TYPE TABLE OF TY_A915,
      T_A918  TYPE TABLE OF TY_A918,
      T_A919  TYPE TABLE OF TY_A919,
      T_A933  TYPE TABLE OF TY_A933,
      T_A934  TYPE TABLE OF TY_A934,
      T_A938  TYPE TABLE OF TY_A938,
      T_A939  TYPE TABLE OF TY_A939,
      T_A940  TYPE TABLE OF TY_A940,
      T_TROLZ TYPE TABLE OF TY_TROLZ,
      T_KONP  TYPE TABLE OF TY_KONP,
      T_DD02T TYPE TABLE OF TY_DD02T,
      T_TVROT TYPE TABLE OF TY_TVROT,
      T_TVSAKT TYPE TABLE OF TY_TVSAKT,
      T_TZONT TYPE TABLE OF TY_TZONT.

DATA: W_SAIDA TYPE TY_SAIDA,
      W_A900  TYPE TY_A900,
      W_A911  TYPE TY_A911,
      W_A910  TYPE TY_A910,
      W_A915  TYPE TY_A915,
      W_A918  TYPE TY_A918,
      W_A919  TYPE TY_A919,
      W_A933  TYPE TY_A933,
      W_A934  TYPE TY_A934,
      W_A938  TYPE TY_A938,
      W_A939  TYPE TY_A939,
      W_A940  TYPE TY_A940,
      W_TROLZ TYPE TY_TROLZ,
      W_KONP  TYPE TY_KONP,
      W_DD02T TYPE TY_DD02T,
      W_TVROT TYPE TY_TVROT,
      W_TZONT TYPE TY_TZONT.



DATA: G_CUSTOM_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      DG_SPLITTER_1      TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
      DG_PARENT_1        TYPE REF TO CL_GUI_CONTAINER,
      DG_SPLITTER_2      TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
      DG_PARENT_2        TYPE REF TO CL_GUI_CONTAINER,
      DG_PARENT_2A       TYPE REF TO CL_GUI_CONTAINER,
      DG_PARENT_ALV      TYPE REF TO CL_GUI_CONTAINER,
      PICTURE            TYPE REF TO CL_GUI_PICTURE,
      GS_LAYOUT          TYPE LVC_S_LAYO,
      GS_VARIANT         TYPE DISVARIANT,
      CTL_ALV            TYPE REF TO CL_GUI_ALV_GRID,
      IT_FIELDCATALOG    TYPE LVC_T_FCAT,
      WA_FIELDCATALOG    TYPE LVC_S_FCAT,
      GS_SCROLL_COL      TYPE  LVC_S_COL,
      GS_SCROLL_ROW      TYPE LVC_S_ROID,
      IT_EXCLUDE_FCODE   TYPE UI_FUNCTIONS,
      WA_EXCLUDE_FCODE   LIKE LINE OF IT_EXCLUDE_FCODE,
      DG_DYNDOC_ID       TYPE REF TO CL_DD_DOCUMENT,
      TABLE_ELEMENT      TYPE REF TO CL_DD_TABLE_ELEMENT,
      COLUMN             TYPE REF TO CL_DD_AREA,
      TABLE_ELEMENT2     TYPE REF TO CL_DD_TABLE_ELEMENT,
      COLUMN_1           TYPE REF TO CL_DD_AREA,
      COLUMN_2           TYPE REF TO CL_DD_AREA,
      COLUMN_3           TYPE REF TO CL_DD_AREA,
      DG_HTML_CNTRL      TYPE REF TO CL_GUI_HTML_VIEWER,
      IT_HEADER          TYPE KKBLO_T_LISTHEADER WITH HEADER LINE.   "Cabeçalho

DATA: TAB(50) TYPE C.


SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS:
                P_LIFNR FOR LFA1-LIFNR NO INTERVALS,
                P_SHTYP FOR VTTK-SHTYP NO INTERVALS,
                P_ROUTE FOR TVRO-ROUTE NO INTERVALS,
                P_DATA  FOR EKKO-BEDAT OBLIGATORY NO INTERVALS,
                P_ZONE1 FOR TZONE-ZONE1 NO INTERVALS,
                P_ZONE2 FOR TZONE-ZONE1 NO INTERVALS.

SELECTION-SCREEN END OF BLOCK B1.
