PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLEST0101 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLEST0101-ID_ROTA .
    FIELD ZLEST0101-BUKRS .
    FIELD ZLEST0101-BRANCH .
    FIELD ZLEST0101-COUNTRY .
    FIELD ZLEST0101-CD_CID_ORIGEM .
    FIELD ZLEST0101-CD_CID_DESTINO .
    FIELD ZLEST0101-TP_ROTA_PERC .
    FIELD ZLEST0101-ID_ROTA_ADM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLEST0101-ID_ROTA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
