PROCESS BEFORE OUTPUT.

  MODULE STATUS_0100.

  CALL SUBSCREEN: SUB0100 INCLUDING SY-REPID ENTREGA_DYNNR_000.

PROCESS AFTER INPUT.

  MODULE: USER_COMMAND_0100,
          TAB_ACTIVE_ENTREGA.

  CALL SUBSCREEN: SUB0100.
