PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLEST0053 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLEST0053-BUKRS .
    FIELD ZLEST0053-EMBARCACAO .
    FIELD ZLEST0053-NOME .
    FIELD ZLEST0053-APELIDO .
    FIELD ZLEST0053-TP_BARCACA .
    FIELD ZLEST0053-INSC_MARINHA .
    FIELD ZLEST0053-IRIN .
    FIELD ZLEST0053-PROPRIETARIO .
    FIELD ZLEST0053-NAME1 .
    FIELD ZLEST0053-USUARIO .
    FIELD ZLEST0053-DT_CADASTRO .
    FIELD ZLEST0053-HR_CADASTRO .
    FIELD ZLEST0053-COD_TP_EMB_MIN .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLEST0053-BUKRS .
    FIELD ZLEST0053-EMBARCACAO .
    FIELD ZLEST0053-NOME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
