TYPES:
        BEGIN OF TY_CABECALHO,
          NR_VIAGEM   TYPE ZLEST0056-NR_VIAGEM,
          ANO_VIAGEM  TYPE ZLEST0056-ANO_VIAGEM,
          NAME1_EMI   TYPE LFA1-NAME1,
          STREET      TYPE ADRC-STREET,
          HOUSE_NUM1  TYPE ADRC-HOUSE_NUM1,
          CITY1       TYPE ADRC-CITY1,
          REGION      TYPE ADRC-REGION,
          STCD1       TYPE J_1BBRANCH-STCD1,
          STATE_INSC  TYPE J_1BBRANCH-STATE_INSC,
          PO_EMBARQUE TYPE LFA1-NAME1,
          ORT01_EMB   TYPE LFA1-ORT01,
          PO_DESTINO  TYPE KNA1-NAME1,
          ORT01_DEST  TYPE KNA1-ORT01,
          NOME_EMB    TYPE ZLEST0063-NOME_EMB,
          DT_PREVISTA TYPE ZLEST0056-DT_PREVISTA,
        END OF TY_CABECALHO,

        BEGIN OF TY_SAIDA_BALSA,
          NOME_EMB      TYPE ZLEST0057-NOME_EMB,
          TOTAL_PESO    TYPE BRGEW,
          TOTAL_PRODUTO TYPE ZLEST0057-VALOR_VINCULADO,
          TOTAL_FRETE   TYPE ZLEST0061-VLR_BRL,
        END OF TY_SAIDA_BALSA,

        BEGIN OF TY_TOTAL,
          TOTAL_PESO_SUM    TYPE BRGEW,
          TOTAL_PRODUTO_SUM TYPE ZLEST0057-VALOR_VINCULADO,
          TOTAL_FRETE_SUM   TYPE ZLEST0061-VLR_BRL,
        END OF TY_TOTAL.


TYPES:
       TY_SAIDA_B TYPE TABLE OF  TY_SAIDA_BALSA.
