FUNCTION Z_PFE_EXIBE_ARQUIVOS.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_CAMINHO) TYPE  STRING
*"  TABLES
*"      TE_FILENAME STRUCTURE  SDOKPATH
*"  EXCEPTIONS
*"      DIRETORIO_NOT_FOUND
*"----------------------------------------------------------------------

  DATA: TL_FILE_TABLE TYPE TABLE OF  SDOKPATH WITH HEADER LINE,
        TL_DIR_TABLE  TYPE TABLE OF  SDOKPATH WITH HEADER LINE,
        V_REPORT     LIKE SY-REPID.
*        WL_CAMINHO(255).

  REFRESH: TL_FILE_TABLE, TL_DIR_TABLE, ESTRUTURA, EVENTS, TG_FILENAME,
           TG_SAIDA_ARQ.

  WG_CAMINHO = I_CAMINHO.
  CALL FUNCTION 'TMP_GUI_DIRECTORY_LIST_FILES'
    EXPORTING
      DIRECTORY  = WG_CAMINHO
    TABLES
      FILE_TABLE = TL_FILE_TABLE
      DIR_TABLE  = TL_DIR_TABLE.

  IF SY-SUBRC EQ 0.
    LOOP AT TL_FILE_TABLE.
      TG_SAIDA_ARQ-FILENAME = TL_FILE_TABLE-PATHNAME.

      APPEND TG_SAIDA_ARQ.
      CLEAR: TG_SAIDA_ARQ.
    ENDLOOP.


    CALL SCREEN 020 STARTING AT 3 3 ENDING AT 100 13.
    TE_FILENAME[] = TG_FILENAME[].


  ELSE.
    RAISE DIRETORIO_NOT_FOUND.
  ENDIF.




ENDFUNCTION.
