FUNCTION ZLES_CADASTRO_AVSEG_URI.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_FILTRO) TYPE  ZDE_ZLEST0144_FILTRO
*"----------------------------------------------------------------------

  DATA: OBJETO         TYPE REF TO ZCL_AVERBACAO_SEGURO_URI,
        IT_ZLEST0144_R TYPE ZDE_ZLEST0144_T.

  CREATE OBJECT OBJETO.

  OBJETO->ZIF_PESQUISA~PESQUISAR( EXPORTING I_FILTROS = I_FILTRO IMPORTING E_REGISTROS = IT_ZLEST0144_R ).
  LOOP AT IT_ZLEST0144_R INTO DATA(WA_ZLEST0144_R).
    APPEND WA_ZLEST0144_R TO IT_ZLEST0144.
  ENDLOOP.
  LC_FILTRO_44 = I_FILTRO.
  CALL SCREEN 0003.

  CLEAR: OBJETO.

ENDFUNCTION.
