PROCESS BEFORE OUTPUT.
  MODULE STATUS_0207.

  CALL SUBSCREEN SUB_FN
       INCLUDING G_ABAS_FAT-PROG '0208'.

  CALL SUBSCREEN SUB_FG
     INCLUDING G_ABAS_FAT-PROG '0209'.

PROCESS AFTER INPUT.

  FIELD WG_FAT_CAB-COD_CLIENTE
    MODULE SELECIONA_DADOS ON REQUEST.

  MODULE USER_COMMAND_0207.

  CALL SUBSCREEN SUB_FN.
  CALL SUBSCREEN SUB_FG.
