PROCESS BEFORE OUTPUT.

  MODULE STATUS_0102.

  MODULE SELECIONA_0102.

  MODULE ABAS_SET.
  CALL SUBSCREEN ABAS_SCA INCLUDING G_ABAS-PROG G_ABAS-SUBSCREEN.

PROCESS AFTER INPUT.

  CALL SUBSCREEN ABAS_SCA.

  MODULE ABAS_GET.

  MODULE USER_COMMAND_0102.
