TYPES: BEGIN OF TY_BKPF,
         BUKRS TYPE BKPF-BUKRS,
         GJAHR TYPE BKPF-GJAHR,
         BUDAT TYPE BKPF-BUDAT,
         BELNR TYPE BKPF-BELNR,
       END OF TY_BKPF,

       BEGIN OF TY_FAGLFLEXA,
         RYEAR  TYPE FAGLFLEXA-RYEAR,
         DOCNR  TYPE FAGLFLEXA-DOCNR,
         RBUKRS TYPE FAGLFLEXA-RBUKRS,
         RLDNR  TYPE FAGLFLEXA-RLDNR,
         RCNTR  TYPE FAGLFLEXA-RCNTR,
         RACCT  TYPE FAGLFLEXA-RACCT,
         HSL    TYPE FAGLFLEXA-HSL,
         DRCRK  TYPE FAGLFLEXA-DRCRK,
       END OF TY_FAGLFLEXA,

         BEGIN OF TY_SKAT,
         KTOPL TYPE SKAT-KTOPL,
         SAKNR TYPE SKAT-SAKNR,
         TXT50 TYPE SKAT-TXT50,
       END OF TY_SKAT,

       BEGIN OF TY_T001,
         BUKRS TYPE T001-BUKRS,
         BUTXT TYPE T001-BUTXT,
         adrnr TYPE t001-adrnr,
       END OF TY_T001,

       BEGIN OF TY_SAIDA,
         FECHA   TYPE BKPF-BUDAT,
*        N_COMPR  TYPE BKPF-BELNR,
         N_CTA    TYPE FAGLFLEXA-RACCT,
         NOMBRE   TYPE SKAT-TXT50,
         DEBITOS  TYPE FAGLFLEXA-HSL,
         CREDITOS TYPE FAGLFLEXA-HSL,
         C_COSTO  TYPE FAGLFLEXA-RCNTR,
       END OF TY_SAIDA.


TYPES: T_BKPF      TYPE TABLE OF TY_BKPF,
       T_FAGLFLEXA TYPE TABLE OF TY_FAGLFLEXA,
       T_SKAT      TYPE TABLE OF TY_SKAT,
       T_T001      TYPE TABLE OF TY_T001,
       T_SAIDA     TYPE TABLE OF TY_SAIDA.















