FUNCTION ZENQUEUE_MATERIAL.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(MATNR) TYPE  MATNR
*"     REFERENCE(_SCOPE) DEFAULT '2'
*"     REFERENCE(_WAIT) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT SPACE
*"  EXCEPTIONS
*"      FOREIGN_LOCK
*"      SYSTEM_FAILURE
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __WAIT      TYPE DDENQWAIT.

  __WAIT = _WAIT.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_ZMATNR,
*       Argumento bloqueio p/tab.ZDCO_NF_ENTRADA
          MANDT TYPE SY-MANDT,
          MATNR TYPE MATNR,
        END OF %A_ZMATNR.
* Inicialização argumento bloqueio:
  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_ZMATNR.

  MOVE: MATNR TO %A_ZMATNR-MATNR.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_ZMATNR-MANDT.
  ENDIF.

* Preencher tab.bloqueio:

  __SEQTA_TAB-GNAME = 'ZMATNR'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG = %A_ZMATNR.
  APPEND __SEQTA_TAB.

* Fixar bloqueio:
  PERFORM SEND_ENQUEUE(SAPLSENA) TABLES __SEQTA_TAB USING '1' __SCOPE __WAIT ' ' 'EZMATNR' _COLLECT.

ENDFUNCTION.
