FUNCTION ZDEQUEUE_MATERIAL.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(MATNR) TYPE  MATNR
*"     REFERENCE(_SCOPE) DEFAULT '3'
*"     REFERENCE(_SYNCHRON) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT ' '
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __SYNCHRON  TYPE DDENQSYNC.

  __SYNCHRON = _SYNCHRON.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_ZMATNR,
*       Argumento bloqueio p/tab.ZDCO_NF_ENTRADA
              MANDT TYPE SY-MANDT,
              MATNR TYPE MATNR,
        END OF %A_ZMATNR.

* Inicialização argumento bloqueio:
  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_ZMATNR.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_ZMATNR-MANDT.
  ENDIF.

  MOVE: MATNR TO %A_ZMATNR-MATNR.

* Preencher tab.bloqueio:
  __SEQTA_TAB-GNAME = 'ZMATNR'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG = %A_ZMATNR.
  APPEND __SEQTA_TAB.

* Lock assigned:
  PERFORM SEND_ENQUEUE(SAPLSENA) TABLES __SEQTA_TAB USING '2' __SCOPE ' ' __SYNCHRON 'ZMATNR' _COLLECT.

ENDFUNCTION.
