** Busca header
SELECT SINGLE *
  FROM ZDOC_MEMORANDO
    INTO WA_ZDOC_MEMORANDO
      WHERE NR_MEMORANDO EQ NR_MEMORANDO.

** Busca notas
    IF WA_ZDOC_MEMORANDO-CANCELADO IS INITIAL.
    SELECT NFNUM SERIES MENGE DOCDAT MAKTX MEINS MATNR NFENUM BUKRS
        FROM ZDOC_MEMO_NOTA
        INTO TABLE TG_ZDOC_MEMO_NOTA
       WHERE NR_MEMORANDO EQ NR_MEMORANDO.
    ELSE.
    SELECT NFNUM SERIES MENGE DOCDAT MAKTX MEINS MATNR NFENUM BUKRS
        FROM ZDOC_MEMO_NOTA_C
        INTO  TABLE TG_ZDOC_MEMO_NOTA
      WHERE NR_MEMORANDO EQ NR_MEMORANDO.
    ENDIF.

*SELECT NFNUM SERIES MENGE DOCDAT MAKTX MEINS MATNR NFENUM BUKRS
*  FROM ZDOC_MEMO_NOTA
*    INTO TABLE TG_ZDOC_MEMO_NOTA
*      WHERE NR_MEMORANDO EQ NR_MEMORANDO.

READ TABLE TG_ZDOC_MEMO_NOTA INTO WA_ZDOC_MEMO_NOTA INDEX 1.

SELECT SINGLE *
  FROM T006A
  INTO WA_T006A
   WHERE SPRAS EQ SY-LANGU
     AND MSEHI EQ WA_ZDOC_MEMO_NOTA-MEINS.

SELECT SINGLE *
  FROM MARC
  INTO WA_MARC
   WHERE MATNR EQ WA_ZDOC_MEMO_NOTA-MATNR.

**Busca Dados do representante
SELECT *
  FROM LFA1
   INTO TABLE TG_LFA1
     WHERE LIFNR EQ WA_ZDOC_MEMORANDO-REPRESENTANTE.

** Busca dados do Remetente
SELECT *
  FROM LFA1
   APPENDING TABLE TG_LFA1
     WHERE LIFNR EQ WA_ZDOC_MEMORANDO-REMETENTE.

