TYPE-POOL ZMEMO.

*----------------------------------------------------------------------*
* Tipos de Dados
*----------------------------------------------------------------------*
TYPES: BEGIN OF ZMEMO_MEMORANDO.
        INCLUDE STRUCTURE ZDOC_MEMORANDO.
TYPES:  PROPRIO	        TYPE Z_MEMO_PROPRIO,
        SERIE	          TYPE J_1BSERIES,
        NUMERO_NOTA	    TYPE J_1BNFNUM9,
        NFE	            TYPE J_1BNFE,
        EMISSOR	        TYPE LIFNR,
        EMISSORN        TYPE NAME1_GP,
        EMISSORCNPJ	    TYPE CHAR18,
        DOCNUM          TYPE J_1BDOCNUM,
        DT_EMISSAO_NOTA	TYPE J_1BDOCDAT,
        MATERIAL        TYPE MATNR,
        MATERIALN       TYPE MAKTG,
        QUANTIDADE      TYPE J_1BNETQTY,
        UNIDADE	        TYPE MEINS,
        MOEDA	          TYPE WAERK,
        VALOR_TOTAL	    TYPE J_1BNETVAL,
        VALOR_UNITARIO  TYPE J_1BNETPRI,
        REMETENTEN      TYPE NAME1_GP,
        REMETENTECNPJ   TYPE CHAR18,
        REPRESENTAN     TYPE NAME1_GP,
        REPRESENTACNPJ  TYPE CHAR18,
        MAKTG	          TYPE MAKTG,
        MARK            TYPE C LENGTH 1,
        ICONE           TYPE C LENGTH 4,
        TXTFINALIDADE   TYPE C LENGTH 60,
        TXTSTATUS       TYPE C LENGTH 60,
        TXTDIRECAO      TYPE C LENGTH 60,
        CHV_NFE_TERC    TYPE C LENGTH 44.
TYPES: END OF ZMEMO_MEMORANDO.

TYPES: BEGIN OF ZMEMO_NOTA_EXP.
        INCLUDE TYPE ZDOC_MEMO_NF_EXP.
TYPES:  EMISSORN     TYPE NAME1_GP,
        EMISSORCNPJ	 TYPE CHAR18,
        MATERIALN    TYPE MAKTG,
        QUANT_VINC   TYPE J_1BNETQTY,
        SALDO_DISP   TYPE J_1BNETQTY,
        QUANT_VINC_2 TYPE J_1BNETQTY,
        SALDO_DISP_2 TYPE J_1BNETQTY,
        DANFE        TYPE ZIB_NFE-DS_URL_DANFE,
        CHARG	       TYPE CHARG_D.
TYPES: END OF ZMEMO_NOTA_EXP.

TYPES: BEGIN OF ZMEMO_MEMORANDO_TELA.
        INCLUDE STRUCTURE ZDOC_MEMORANDO.
TYPES:  VG_NOME_REPRESENTANTE TYPE NAME1_GP,
        VG_NOME_REMETENTE     TYPE NAME1_GP,
        VG_NOME_TRANSPORTADOR TYPE NAME1_GP,
        VG_NOME_PAIS_ORIGEM   TYPE LANDX,
        VG_NOME_PAIS_DESTINO  TYPE LANDX,
        VG_NOME_UF_ORIGEM     TYPE BEZEI20,
        SEQ                   TYPE I,
        MARK                  TYPE C LENGTH 1,
        ICONE                 TYPE C LENGTH 4.
TYPES: END OF ZMEMO_MEMORANDO_TELA.

TYPES: BEGIN OF ZMEMO_MEMORANDO_CONHEC.
        INCLUDE STRUCTURE ZDOC_MEMO_NOMEAC.
TYPES:   MARK TYPE C LENGTH 1,
         SEQU TYPE I.
TYPES: END OF ZMEMO_MEMORANDO_CONHEC.

TYPES: BEGIN OF ZMEMO_NOTAS_VINCULADAS.
        INCLUDE STRUCTURE ZDOC_MEMO_NOTA.
TYPES: MARK         TYPE C LENGTH 1.
TYPES: END OF ZMEMO_NOTAS_VINCULADAS.

TYPES: BEGIN OF ZMEMO_NOTAS_VINCULADAS_S.
        INCLUDE STRUCTURE ZDOC_MEMO_NOTA_S.
TYPES: MARK         TYPE C LENGTH 1.
TYPES: END OF ZMEMO_NOTAS_VINCULADAS_S.

TYPES: BEGIN OF ZMEMO_NOTAS_LIVRES,
         NR_MEMORANDO	TYPE Z_MEMORANDO,
         DOCNUM	      TYPE J_1BDOCNUM,
         ITMNUM	      TYPE J_1BITMNUM,
         DOCDAT	      TYPE J_1BDOCDAT,
         MODEL        TYPE J_1BMODEL,
         SERIES	      TYPE J_1BSERIES,
         NFNUM        TYPE J_1BNFNUMB,
         NFE          TYPE J_1BNFE,
         NFENUM	      TYPE J_1BNFNUM9,
         MATNR        TYPE MATNR,
         NBM          TYPE STEUC,
         MENGE        TYPE J_1BNETQTY,
         MEINS        TYPE J_1BNETUNT,
         MAKTX        TYPE MAKTX,
         SALDO        TYPE J_1BNETQTY,
         BUKRS        TYPE BUKRS,
         BRANCH	      TYPE J_1BBRANC_,
         MARK         TYPE C LENGTH 1,
         VINCULAR     TYPE J_1BNETQTY.
TYPES: END OF ZMEMO_NOTAS_LIVRES.

TYPES: BEGIN OF ZMEMO_EXPORT_ACOMP.
        INCLUDE STRUCTURE ZEXPORT_ACOMP.
TYPES:  MARK       TYPE CHAR1,
        DT_EMISSAO TYPE ZEXPORT_NOTAS-DT_EMISSAO.
TYPES: END OF ZMEMO_EXPORT_ACOMP.

TYPES: BEGIN OF ZMEMO_NF_.
TYPES:   DOCNUM	TYPE J_1BDOCNUM,
         ITMNUM	TYPE J_1BITMNUM,
         MATNR  TYPE MATNR,
         REFTYP	TYPE J_1BREFTYP,
         REFKEY	TYPE J_1BREFKEY,
         REFITM	TYPE J_1BREFITM,
         REFK10 TYPE BELNR_D,
         GJAHR  TYPE GJAHR.
TYPES: END OF ZMEMO_NF_.

TYPES: BEGIN OF ZMEMO_PRODUTO.
TYPES:   MATNR TYPE MATNR,
         MAKTG TYPE MAKTG.
TYPES: END OF ZMEMO_PRODUTO.

TYPES: BEGIN OF ZMEMO_CLIENTE.
TYPES:   COD  TYPE KUNNR,
         NOME TYPE NAME1_GP,
         CNPJ TYPE CHAR18.
TYPES: END OF ZMEMO_CLIENTE.

TYPES: BEGIN OF ZMEMO_PROTOCOLO.
        INCLUDE STRUCTURE ZDOC_MEMO_PROTOC.
TYPES:  MARK          TYPE CHAR1,
        NM_EMISSOR    TYPE NAME1_GP,
        NM_EMPRESA_EM TYPE BUTXT,
        NM_FILIAL_EM  TYPE NAME1,
        NM_DESTINO    TYPE NAME1_GP,
        NM_EMPRESA_DE TYPE BUTXT,
        NM_FILIAL_DE  TYPE NAME1.
TYPES: END OF ZMEMO_PROTOCOLO.

TYPES: BEGIN OF ZMEMO_PROTOCOLO_MEMO.
        INCLUDE STRUCTURE ZDOC_MEMO_PRO_ME.
TYPES:  NR_NOTA_EXP     TYPE Z_MEMORANDO,
        FORMULARIO      TYPE Z_MEMO_NUMERO,
        DT_EMISSAO_MEMO TYPE J_1BDOCDAT,
        QUANTIDADE_MEMO	TYPE J_1BNETQTY,
        NUMERO_NOTA	    TYPE J_1BNFNUM9,
        EMISSOR	        TYPE LIFNR,
        EMISSORN        TYPE NAME1_GP,
        EMISSORCNPJ	    TYPE CHAR18,
        MATERIAL        TYPE MATNR,
        MATERIALN       TYPE MAKTG,
        REMETENTE       TYPE LIFNR,
        REMETENTEN      TYPE NAME1_GP,
        REMETENTECNPJ   TYPE CHAR18,
        NUMERO_MEMO     TYPE Z_MEMO_NUMERO,
        MARK            TYPE C LENGTH 1,
        ICONE           TYPE C LENGTH 4.
TYPES: END OF ZMEMO_PROTOCOLO_MEMO.


TYPES: BEGIN OF ZMEMO_BUKRS,
         SIGN      TYPE C,
         OPTION(2) TYPE C,
         LOW       TYPE C LENGTH 4,
         HIGH      TYPE C LENGTH 4,
       END OF ZMEMO_BUKRS,

       BEGIN OF ZMEMO_BRANCH,
         SIGN      TYPE C,
         OPTION(2) TYPE C,
         LOW       TYPE C LENGTH 4,
         HIGH      TYPE C LENGTH 4,
       END OF ZMEMO_BRANCH,

       BEGIN OF ZMEMO_MATNR,
         SIGN      TYPE C,
         OPTION(2) TYPE C,
* ---> S4 Migration - 10/06/2023 - DG
*         LOW       TYPE C LENGTH 18,
*         HIGH      TYPE C LENGTH 18,
         LOW       TYPE C LENGTH 40,
         HIGH      TYPE C LENGTH 40,
* <--- S4 Migration - 10/06/2023 - DG

       END OF ZMEMO_MATNR,

       BEGIN OF ZMEMO_CFOP,
         SIGN      TYPE C,
         OPTION(2) TYPE C,
         LOW       TYPE C LENGTH 10,
         HIGH      TYPE C LENGTH 10,
       END OF ZMEMO_CFOP,

       BEGIN OF ZMEMO_REMET,
         SIGN      TYPE C,
         OPTION(2) TYPE C,
         LOW       TYPE C LENGTH 10,
         HIGH      TYPE C LENGTH 10,
       END OF ZMEMO_REMET.
