FUNCTION-POOL ZMEMORANDO MESSAGE-ID ZMEMORANDO.

TYPE-POOLS: ZMEMO, ICON.

CONSTANTS: C_2                  TYPE C LENGTH 1 VALUE '2',
           C_1                  TYPE C LENGTH 1 VALUE '1',
           C_5                  TYPE C LENGTH 1 VALUE '5',
           C_6                  TYPE C LENGTH 1 VALUE '6',
           C_B                  TYPE C LENGTH 1 VALUE 'B',
           C_C                  TYPE C LENGTH 1 VALUE 'C',
           C_V                  TYPE C LENGTH 1 VALUE 'V',
           C_X                  TYPE C LENGTH 1 VALUE 'X',
           QTD_LINHAS_PERMITIDA TYPE I VALUE 11.

DATA: VG_CANCEL TYPE J_1BCANCEL.

DATA: T_MATNR TYPE TABLE OF ZMEMO_MATNR,
      T_BUKRS TYPE TABLE OF ZMEMO_BUKRS,
      T_WERKS TYPE TABLE OF ZMEMO_BRANCH,
      T_CFOP  TYPE TABLE OF ZMEMO_CFOP,
      T_REMET TYPE TABLE OF ZMEMO_REMET.

DATA: WA_NF_EXPORT TYPE ZMEMO_NF_,
      WA_NOTAS     TYPE ZEXPORT_NOTAS,
      WA_J_1BNFDOC TYPE J_1BNFDOC,
      WA_J_1BNFLIN TYPE J_1BNFLIN,
      WA_PRODUTOS  TYPE ZMEMO_PRODUTO,
      WA_ACOMP1    TYPE ZEXPORT_ACOMP,
      WA_ACOMP     TYPE ZEXPORT_ACOMP.

DATA: IT_NF_EXPORT TYPE TABLE OF ZMEMO_NF_ INITIAL SIZE 0 WITH HEADER LINE,
      IT_NF        TYPE TABLE OF ZMEMO_NF_ INITIAL SIZE 0 WITH HEADER LINE,
      IT_NF_ITEM   TYPE TABLE OF ZMEMO_NF_ INITIAL SIZE 0 WITH HEADER LINE,
      IT_J_1BNFLIN TYPE TABLE OF J_1BNFLIN INITIAL SIZE 0 WITH HEADER LINE,
      IT_PRODUTOS  TYPE TABLE OF ZMEMO_PRODUTO INITIAL SIZE 0 WITH HEADER LINE.
