FUNCTION-POOL ZMMG_PEDIDO_COMPRA MESSAGE-ID ZMMPED.

* INCLUDE LZMMG_PEDIDO_COMPRAD...            " Local class definition
TABLES: ZDE_EKPO_HELP_CAB.

DATA: GB_MENGE_SALDO       TYPE BSTMG,
      GB_EKPO              TYPE EKPO,
      GB_SALDO_ITEM        TYPE ZDE_EKPO_HELP_SALDO.

DATA: IT_PEDIDOS_ITENS     TYPE TABLE OF ZDE_EKPO_HELP_SALDO WITH HEADER LINE,
      IT_PEDIDOS_HISTORICO TYPE TABLE OF ZDE_EKPO_HELP_SALDO WITH HEADER LINE,
      CK_SELECIONOU_PEDIDO TYPE CHAR01.

DATA: OK_CODE TYPE SY-UCOMM.

CONSTANTS: OK_SELECIONAR TYPE SY-UCOMM VALUE 'SELECIONAR'.
