PROCESS BEFORE OUTPUT.
  MODULE TRATA_FIED.
  MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
  CHAIN.

    FIELD  WA_TELA-MATRICULA.
    FIELD  WA_TELA-CPF.
    FIELD  WA_TELA-NOME.
    FIELD  WA_TELA-FILIAL     MODULE PREENCHE_FILIAL
    ON CHAIN-INPUT.
  ENDCHAIN.

  MODULE USER_COMMAND_0100.

PROCESS ON VALUE-REQUEST.

  FIELD WA_TELA-FILIAL MODULE BUSCA_FILIAL.
