*&---------------------------------------------------------------------*
*& Report  ZMMR019_07
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZMMR019_07.


FORM ADD_PIS_COFINS
  USING P_ENTRADA  TYPE ZMMT_EE_ZGR
  CHANGING VL_IMPOSTO TYPE BAPI_RMWWR
           VL_ITEM    TYPE BAPIWRBTR.

  DATA: VL_IMPOSTO_PIS TYPE BAPI_RMWWR.
  DATA: VL_IMPOSTO_COFINS TYPE BAPI_RMWWR.
  "DATA: VL_TOTAL TYPE J_1BNFTOT.

  SELECT SINGLE * INTO @DATA(WA_ZMMT0125)
    FROM ZMMT0125
   WHERE MWSKZ EQ @P_ENTRADA-TAX_CODE.

  VL_IMPOSTO_PIS =  0.
  VL_IMPOSTO_COFINS = 0.

  IF SY-SUBRC IS INITIAL.

    IF WA_ZMMT0125-NM_ALI_PIS IS NOT INITIAL.
      VL_IMPOSTO_PIS = P_ENTRADA-VR_BRUTO * ( WA_ZMMT0125-NM_ALI_PIS / 100 ).
    ENDIF.

    IF WA_ZMMT0125-NM_ALI_COFINS IS NOT INITIAL.
      VL_IMPOSTO_COFINS = P_ENTRADA-VR_BRUTO * ( WA_ZMMT0125-NM_ALI_COFINS / 100 ).
    ENDIF.

    ADD VL_IMPOSTO_PIS TO VL_IMPOSTO.
    ADD VL_IMPOSTO_COFINS TO VL_IMPOSTO.

    "VL_TOTAL = VL_IMPOSTO_PIS + VL_IMPOSTO_COFINS.

    EXPORT P1 = VL_ITEM TO MEMORY ID 'MZMMR019VLRITEM'.
    EXPORT P1 = VL_IMPOSTO_PIS TO MEMORY ID 'MZMMR019VLRITEMPIS'.
    EXPORT P1 = VL_IMPOSTO_COFINS TO MEMORY ID 'MZMMR019VLRITEMCOFINS'.

    VL_ITEM = VL_ITEM - ( VL_IMPOSTO_PIS + VL_IMPOSTO_COFINS ).

  ENDIF.

ENDFORM.
