PROCESS BEFORE OUTPUT.

  MODULE STATUS_9001.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_9001_EXIT AT EXIT-COMMAND.

  FIELD PSAFRA MODULE VALIDAR_PSAFRA ON REQUEST.
  FIELD PFILIA MODULE VALIDAR_PFILIA ON REQUEST.

  MODULE USER_COMMAND_9001.
