
PROCESS BEFORE OUTPUT.

  MODULE STATUS_0302.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_EXIT0301 AT EXIT-COMMAND.

  CHAIN.
    FIELD IT_0301_VT-ZVLR_FRETE.
    MODULE ALTEROU_VALOR_FRETE ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD WA_0301_TER-ZDT_VENCTO.
    FIELD IT_0301_VT-ZVLR_FRETE.
    FIELD IT_0301_VT-PESO_CHEGADA.
    FIELD IT_0301_VT-PESO_ORIGEM.
    FIELD WA_0301_TER-ZBVTYP.
    FIELD WA_0301_TER-MWSKZ.
    MODULE ALTEROU_INFORMACAO_FRETE ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0302.
