PROCESS BEFORE OUTPUT.

  MODULE STATUS_0304.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_0303_EXIT AT EXIT-COMMAND.

  FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_UMI MODULE PERC_01 ON REQUEST.
  FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_IMP MODULE PERC_02 ON REQUEST.
  FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_AVA MODULE PERC_03 ON REQUEST.
  FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_ARD MODULE PERC_04 ON REQUEST.
  FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_QUE MODULE PERC_05 ON REQUEST.
  FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_ESV MODULE PERC_06 ON REQUEST.
  FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_CAR MODULE PERC_07 ON REQUEST.

  CHAIN.
    FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_UMI .
    FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_IMP.
    FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_AVA.
    FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_ARD.
    FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_QUE.
    FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_ESV.
    FIELD ZDE_ZSDT0001CG_ALV-NR_PERC_CAR.
    MODULE ATRIBUI_INFO_CARGA ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0304.
