PROCESS BEFORE OUTPUT.

  MODULE STATUS_9002.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_9002_EXIT AT EXIT-COMMAND.

  CHAIN.
    FIELD WA_ADD_NFE_9002-N55_CHAVE_ACESSO.
    MODULE ATRIBUI_INFO_CHAVE ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_9002.
