REPORT  ZMMR104.

TYPE-POOLS ICON.
TABLES: T001W.


TYPES: BEGIN OF TY_ITENS.
        INCLUDE           TYPE ZMMT0064.
TYPES: STATUS  TYPE ICON-ID,
*       ITENS_CLAS LIKE GT_ITEM_0200,
       T_WERKS TYPE QC_WERKS_RANGE,
       ESTILO  TYPE LVC_T_STYL,
       END OF TY_ITENS,

       BEGIN OF TY_CARGA,
         EMATN   TYPE ZMMT0064-EMATN, "material
         KTMNG   TYPE ZMMT0064-KTMNG, "Quantidade
         NETPR   TYPE ZMMT0064-NETPR, "valou unit
         LGORT   TYPE ZMMT0064-LGORT, "deposito
         MWSKZ   TYPE ZMMT0064-MWSKZ, "iva
         PEINH   TYPE ZMMT0064-PEINH, "Por
         T_WERKS TYPE QC_WERKS_RANGE, "Centros
       END OF TY_CARGA,

       BEGIN OF TY_SERVICOS,
         ITEM_NO TYPE ZMMT0064-EVRTP,
         SRVPOS  TYPE SRVPOS,   "Nº servico
         KTEXT1  TYPE SH_TEXT1, "Descrição
         MENGE   TYPE MENGEV,  "Quantidade
         MEINS   TYPE MEINS,   "Unid medida
         TBTWR   TYPE SBRTWR,  "Preço bruto,
         WAERS   TYPE WAERS,   "Moeda
         KOSTL   TYPE KOSTL,   "Centrocusto
         AUFNR   TYPE AUFNR,   "Ordem
         STYLE   TYPE LVC_T_STYL,
       END OF TY_SERVICOS,

       BEGIN OF TY_FIELDS,
         CAMPO     TYPE CHAR30,
         GROUP1    TYPE CHAR3,
         GROUP2    TYPE CHAR3,
         VALUE     TYPE CHAR1,
         INVISIBLE TYPE CHAR1,
       END OF TY_FIELDS,

       BEGIN OF TY_FIELDS_STYLE,
         FIELDNAME TYPE LVC_FNAME,
       END OF TY_FIELDS_STYLE,

       BEGIN OF TY_QPCT,
         CODE     TYPE QPCT-CODE,
         KURZTEXT TYPE QPCT-KURZTEXT,
       END OF TY_QPCT,

       BEGIN OF TY_HISTORY,
         EVRTP     TYPE EVRTP,
         FNAME     TYPE FIELDNAME,
         FTEXT     TYPE SCRTEXT_M,
         CHANGEID  TYPE ZMMT0068-CHANGEID,
         ACTION    TYPE MECDACTION,
         VALUE_OLD TYPE ZMMT0068-VALUE_OLD,
         VALUE_NEW TYPE ZMMT0068-VALUE_NEW,
*---> 01/06/2023 - Migração S4 - JS
*         USERNAME  TYPE AENUSER,
         USERNAME  TYPE CHAR12,
*<--- 01/06/2023 - Migração S4 - JS
         DATA      TYPE AENDDATE,
         HORA      TYPE AENUHR,
       END OF TY_HISTORY,

       BEGIN OF TY_MENU_TREE,
         NODE_PAI         TYPE LVC_VALUE,
         NODE_FILHO       TYPE LVC_VALUE,
         NODE_IMAGE_PAI   TYPE TV_IMAGE,
         NODE_IMAGE_FILHO TYPE TV_IMAGE,
       END OF TY_MENU_TREE.

DATA BEGIN OF S_EKPO.
        INCLUDE STRUCTURE EKPO.
DATA END OF S_EKPO.

TYPES: ITEM_TABLE_TYPE TYPE STANDARD TABLE OF MTREEITM.

RANGES: R_WERKS  FOR EKPO-WERKS.
FIELD-SYMBOLS <FS_SAIDA_ITENS> TYPE TY_ITENS.

DATA: GT_FCAT_0100        TYPE TABLE OF LVC_S_FCAT,
      GT_FCAT_0110        TYPE TABLE OF LVC_S_FCAT,
      GT_FCAT_0120        TYPE TABLE OF LVC_S_FCAT,
      GT_FCAT_0200        TYPE TABLE OF LVC_S_FCAT,
      GT_FCAT_0400        TYPE TABLE OF LVC_S_FCAT,
      GT_SAIDA_ITENS      TYPE TABLE OF TY_ITENS,
      GT_SAIDA_SERVICOS   TYPE TABLE OF TY_SERVICOS,
      GT_MSG_RETURN       TYPE TABLE OF ZFIWRS0002,
      GT_SELECTED_ROWS    TYPE LVC_T_ROW,
      GT_SELECTEDCELL     TYPE LVC_T_CELL,
      GT_ESTILO           TYPE LVC_T_STYL WITH HEADER LINE,
      GT_RETURN_TAB       TYPE TABLE OF DDSHRETVAL WITH HEADER LINE,
      GT_DSELC            TYPE TABLE OF DSELC      WITH HEADER LINE,
      GT_RETURN           TYPE TABLE OF BAPIRET2,
      GT_FIELDS           TYPE TABLE OF TY_FIELDS,
      GT_FIELDS_STYLE     TYPE TABLE OF TY_FIELDS_STYLE,
      GT_MARA             TYPE TABLE OF MARA,
      GT_EKPO             TYPE TABLE OF EKPO,
      GT_ZMMT0064         TYPE TABLE OF ZMMT0064,
      GT_MAKT             TYPE TABLE OF MAKT,
      GT_WERKS_SELECTED   TYPE TABLE OF WERKS,
      GT_QPCT_INCO        TYPE TABLE OF TY_QPCT,
      GT_MENU_TREE        TYPE TABLE OF TY_MENU_TREE,
      GT_NODE_TABLE       TYPE TREEV_NTAB,
      GT_ITEM_TABLE       TYPE TABLE OF MTREEITM,
      OBJ_CUSTOM_0110     TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      OBJ_CUSTOM_0200     TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
*      OBJ_CUSTOM_0400     TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
*      OBJ_CUSTOM_0600     TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      OBJ_ALV_0110        TYPE REF TO CL_GUI_ALV_GRID,
      OBJ_ALV_0200        TYPE REF TO CL_GUI_ALV_GRID,
      OBJ_ALV_0400        TYPE REF TO CL_GUI_ALV_GRID,
      OBJ_ALV_TREE_0100   TYPE REF TO CL_GUI_ALV_TREE,
      OBJ_ALV_TREE_0120   TYPE REF TO CL_GUI_COLUMN_TREE,
      OBJ_TOOLBAR_MANAGER TYPE REF TO CL_ALV_GRID_TOOLBAR_MANAGER,
      GW_HEADER           TYPE TREEV_HHDR,
      GT_EVENTS           TYPE CNTL_SIMPLE_EVENTS,
      GW_MENU_TREE        TYPE TY_MENU_TREE,
      GW_EVENT            TYPE CNTL_SIMPLE_EVENT,
      WL_SAIDA_CABECALHO  TYPE ZMMT0063,
      WL_FIELDS           TYPE TY_FIELDS,
      WA_RETURN           TYPE BAPIRET2,
      WL_MARA             TYPE MARA,
      WL_EKPO             TYPE EKPO,
*      WL_ITEM_0200        TYPE TY_CLAS_CONTABIL_ITEM,
      WL_MAKT             TYPE MAKT,
      WL_SELECTEDCELL     TYPE LVC_S_CELL,
      WL_ZMMT0064         TYPE ZMMT0064,
      WL_FCAT             TYPE LVC_S_FCAT,
      WL_RETURN           TYPE BAPIRET2,
      WL_SELECTED_ROWS    TYPE LVC_S_ROW,
      WL_FIELDS_STYLE     TYPE TY_FIELDS_STYLE,
      WL_LAYOUT           TYPE LVC_S_LAYO,
      WL_STABLE           TYPE LVC_S_STBL,
      WL_EXCLUDE          TYPE UI_FUNCTIONS,
      WL_MENSAGEM         TYPE CHAR30,
      WL_MSG_RETURN       TYPE ZFIWRS0002,
      WL_SAIDA_ITENS      TYPE TY_ITENS,
      WL_SAIDA_ITENS_AUX  TYPE TY_ITENS,
      WL_SAIDA_SERVICOS   TYPE TY_SERVICOS,
      WL_ESTILO           TYPE LVC_S_STYL,
      WL_FORNECEDOR       TYPE CHAR30,
      WL_CELL             TYPE LVC_S_CELL,
      WL_OBJ(30),
      VG_OP_MODE          TYPE CHAR20,
      WL_WERKS            LIKE LINE OF R_WERKS,
      VG_OK_CODE          LIKE SY-UCOMM,
      VG_SCREEN_COLLAPSE  TYPE CHAR4 VALUE 0500,
      VG_LINES            TYPE SY-TABIX,
      VG_ITEM_0400        TYPE ZMMT0064-EVRTP,
      VG_SEQ              TYPE ZMMT0064-EVRTP,
      VG_SCREEN_PRINCIPAL TYPE CHAR4 VALUE '0110',
      BTN_DISPLAY_WERKS   TYPE ICON-ID VALUE ICON_ENTER_MORE,
      P_FILE              TYPE RLGRAP-FILENAME VALUE ''.

DATA: T_EXCEL  LIKE ALSMEX_TABLINE OCCURS 0 WITH HEADER LINE,
      T_EXCEL2 LIKE ALSMEX_TABLINE OCCURS 0 WITH HEADER LINE,
      T_CARGA  TYPE TABLE OF TY_CARGA,
      W_CARGA  TYPE TY_CARGA.

CONSTANTS:
  C_SEARCH            TYPE CHAR20 VALUE 'SEARCH',
  C_NOVO              TYPE CHAR20 VALUE 'NEW',
  C_GERA_CONTRATO     TYPE CHAR20 VALUE 'GERAR',
  C_ALLOW_ALL         TYPE CHAR20 VALUE 'BTN_ALLOW_ALL',
  C_CANC              TYPE CHAR20 VALUE 'CANC',
  C_BACK              TYPE CHAR20 VALUE 'BACK',
  C_ENTER             TYPE CHAR20 VALUE 'ENTER',
  C_SAVE              TYPE CHAR20 VALUE 'SAVE',
  C_COPY              TYPE CHAR4  VALUE 'COPY',
  C_DELETE            TYPE CHAR6  VALUE 'DELETE',
  C_DB_CLICK          TYPE CHAR10 VALUE 'DB_CLICK',
  C_EDIT              TYPE CHAR4  VALUE 'EDIT',
  C_SHOW_MSG          TYPE CHAR20 VALUE 'SHOW_MSGRE',
  C_VIEW_ITEM         TYPE CHAR9  VALUE 'VIEW_ITEM',
  C_EXIT              TYPE CHAR20 VALUE 'EXIT',
  C_BTN_DISPLAY_WERKS TYPE CHAR20 VALUE 'BTN_DISPLAY_WERKS',

  BEGIN OF C_COLUMN,
    COLUMN1 TYPE TV_ITMNAME VALUE 'Contrato',
    COLUMN2 TYPE TV_ITMNAME VALUE 'Item',
    COLUMN3 TYPE TV_ITMNAME VALUE 'Display',
    COLUMN4 TYPE TV_ITMNAME VALUE 'Allow',
    COLUMN5 TYPE TV_ITMNAME VALUE 'Reject',
    COLUMN6 TYPE TV_ITMNAME VALUE 'Centro',
  END OF C_COLUMN.

DEFINE D_SET_EVENT.
  GW_EVENT-EVENTID    = &1.
  GW_EVENT-APPL_EVENT = &2.
  APPEND GW_EVENT TO GT_EVENTS.
END-OF-DEFINITION.

INITIALIZATION.
  CALL SCREEN 0100.
