PROCESS BEFORE OUTPUT.
  MODULE INICIALIZA.
  MODULE TRATA_FIELDS.
  MODULE CRIA_OBJETOS.
  MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
  CHAIN.
    FIELD WG_CADMAT-EXPANSAO.
    MODULE  M_MUDA ON CHAIN-REQUEST.
  ENDCHAIN.
  MODULE USER_COMMAND_0100.

  FIELD WG_CADMAT-MAKTX   MODULE  PESQUISA_TEXTO ON CHAIN-REQUEST.

PROCESS ON VALUE-REQUEST.
  FIELD WG_CADMAT-NUREQ MODULE SEARCH_DOC.
  FIELD WG_CADMAT-MAKTX MODULE PESQUISA_TEXTO.
