PROCESS BEFORE OUTPUT.
  MODULE OUTPUT.

  CALL SUBSCREEN SUBSCREEN_VINCULACAO
    INCLUDING
      SY-REPID
      SCREEN_VINCULACAO.

PROCESS AFTER INPUT.
  CALL SUBSCREEN SUBSCREEN_VINCULACAO.

  MODULE INPUT.
