
PROCESS BEFORE OUTPUT.

  MODULE STATUS_0201.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_EXIT0201 AT EXIT-COMMAND.

  CHAIN.
    FIELD WA_TELA_NXX-ZVLR_FRETE.
    FIELD WA_TELA_NXX-ZVLR_MERCADORIA.
    FIELD WA_TELA_NXX-ZMATNR_MERC.
    FIELD WA_TELA_NXX-PESO_ORIGEM.
    FIELD WA_TELA_NXX-PESO_CHEGADA.
    FIELD WA_TELA_NXX-ZPESO_DIFERENCA.
    FIELD WA_TELA_NXX-ZQUEBRA.
    FIELD WA_TELA_NXX-ZPERDA.
    FIELD WA_TELA_NXX-ZVLR_QUEBRA.
    FIELD WA_TELA_NXX-ZVLR_PERDA.
    FIELD WA_TELA_NXX-ZVLR_LIQ_PAGAR.
    "MODULE SET_UPDATE_FLAG_NXX ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0201.
