PROCESS BEFORE OUTPUT.
 MODULE STATUS_0800.
*
PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0800.

FIELD WG_COPLAN-NRO_SOL_CP MODULE SEARCH_NRO_SOL_CP ON CHAIN-REQUEST.

PROCESS ON VALUE-REQUEST.
  FIELD WG_COPLAN-NRO_SOL_CP MODULE SEARCH_NRO_SOL_CP.
