
PROCESS BEFORE OUTPUT.
  MODULE: STATUS_0100,
          CRIA_OBJETO.

  CALL SUBSCREEN SUB_01 INCLUDING SY-REPID '0102'.
  CALL SUBSCREEN SUB_02 INCLUDING SY-REPID SC_TELA.

PROCESS AFTER INPUT.
CALL SUBSCREEN SUB_01.
CALL SUBSCREEN SUB_02.

  MODULE USER_COMMAND_0100.
