PROCESS BEFORE OUTPUT.

  MODULE STATUS_9009.

PROCESS AFTER INPUT.

  FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-ID_ENTRADA
  MODULE GET_ENTRA2 ON REQUEST.

  FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-ID_MOD_FISCAL
  MODULE SET_MODEL2 ON REQUEST.

  FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-NR_FORNECEDOR_IE
  MODULE GET_FORNE2 ON REQUEST.

  CHAIN.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-ID_NUMERO.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-ID_ENTRADA.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-DS_ENTRADA.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-ID_MOD_FISCAL.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-NR_FORNECEDOR_IE.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-NR_NOTA.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-NM_SERIE.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-DT_EMISSAO.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-NR_CHAVE_NFE.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-NR_QUANTIDADE.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-NR_VALOR.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-DT_VENCIMENTO_FORM.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-ID_FORNECEDOR.
    FIELD ZDE_ZSDT0001CG_VALIDA_NOTA-DS_FORNECEDOR.
    MODULE CH_VAL ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_9009.
