PROCESS BEFORE OUTPUT.

  MODULE STATUS_0311.
*
  CALL SUBSCREEN: SUB0305 INCLUDING SY-CPROG VG_TL_0305,
                  SUB0312 INCLUDING SY-CPROG VG_TL_0312.

PROCESS AFTER INPUT.

  FIELD ZDE_ZSDT0001CG_ALV-NM_PESO_BRUTO MODULE ALTERA_BRUTO ON REQUEST.

  FIELD ZDE_ZSDT0001CG_ALV-NM_PESO_TARA MODULE ALTERA_TARA ON REQUEST.

  FIELD ZDE_ZSDT0001CG_ALV-NM_PESO_SUBTOTAL
   MODULE VALIDA_SUBTOTAL ON REQUEST.

  CHAIN.
    FIELD ZDE_ZSDT0001CG_ALV-NM_PESO_BRUTO.
    FIELD ZDE_ZSDT0001CG_ALV-NM_PESO_TARA.
    MODULE ATRIBUI_INFO_CARGA ON CHAIN-REQUEST.
  ENDCHAIN.

  CALL SUBSCREEN: SUB0305,
                  SUB0312.

* MODULE USER_COMMAND_0311.
