PROCESS BEFORE OUTPUT.
  MODULE STATUS_0100.
  MODULE TRATA_FIELDS.
  MODULE CRIA_OBJETOS.
*
PROCESS AFTER INPUT.
  MODULE USER_COMMAND_0100.

PROCESS ON VALUE-REQUEST.
  FIELD WG_ZMMT0083-CD_AGRU MODULE SEARCH_GRU.
