PROCESS BEFORE OUTPUT.

  MODULE STATUS_8002.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_8002_EXIT AT EXIT-COMMAND.

  FIELD ZDE_ZSDT0001CG_ALV-NR_ORDEM MODULE VALIDAR_NR_ORDEM ON REQUEST.

  CHAIN.
    "FRETE
    FIELD ZDE_ZSDT0001CG_ALV-NR_ORDEM.
    FIELD ZDE_ZSDT0001CG_ALV-ID_MOTORISTA.
    FIELD ZDE_ZSDT0001CG_ALV-ID_AGENT_FRETE.
    FIELD ZDE_ZSDT0001CG_ALV-ID_PROPRIETARIO.
    FIELD ZDE_ZSDT0001CG_ALV-DS_PLACA_TRATOR.
    FIELD ZDE_ZSDT0001CG_ALV-DS_PLACA_REBOQ_1.
    FIELD ZDE_ZSDT0001CG_ALV-DS_PLACA_REBOQ_2.
    FIELD ZDE_ZSDT0001CG_ALV-DS_PLACA_REBOQ_3.
    MODULE ATRIBUI_INFO_FRETE ON CHAIN-REQUEST.
  ENDCHAIN.

  FIELD ZDE_ZSDT0001CG_ALV-NR_ORDEM MODULE SET_ORDEM_CARREG ON REQUEST.

  MODULE USER_COMMAND_8002.
