PROCESS BEFORE OUTPUT.

  MODULE STATUS_9001.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_9001_EXIT AT EXIT-COMMAND.

  CHAIN.
    FIELD  ZDE_NFE_DIST_ITM_ALV-PROD_QTD_COMERCI.
    MODULE ALTEROU_QUANTIDADE ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_9001.
