PROCESS BEFORE OUTPUT.
  MODULE OUTPUT_MAIN.

PROCESS AFTER INPUT.
  MODULE INPUT_MAIN.

PROCESS ON VALUE-REQUEST.
  FIELD CADASTRO-SENHA     MODULE SEARCH_ICON.
  FIELD CADASTRO-SENHA2    MODULE SEARCH_ICON.
  FIELD SEARCH_ID MODULE SEARCH_DOC.
