PROCESS BEFORE OUTPUT.

  MODULE STATUS_0200.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_0200_EXIT AT EXIT-COMMAND.

  CHAIN.
    MODULE GET_SCROLL_INFO.
    MODULE GET_SELECTED_ROWS.
  ENDCHAIN.

  MODULE USER_COMMAND_0200.
