*----------------------------------------------------------------------*
***INCLUDE ZMMR105_0104 .
*----------------------------------------------------------------------*

*----------------------------------------------------------------------*
*       CLASS LCL_ALV_TOOLBAR_N55 DEFINITION
*----------------------------------------------------------------------*
CLASS LCL_ALV_TOOLBAR_N01 DEFINITION.
  PUBLIC SECTION.
*Constructor
    METHODS: CONSTRUCTOR         IMPORTING IO_ALV_GRID TYPE REF TO CL_GUI_ALV_GRID,
      ON_TOOLBAR          FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID IMPORTING E_OBJECT,
      HANDLE_USER_COMMAND FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID IMPORTING E_UCOMM.
ENDCLASS.                    "lcl_alv_toolbar DEFINITION

DATA: CTL_ALV_N01              TYPE REF TO CL_GUI_ALV_GRID,
      C_ALV_TOOLBARMANAGER_N01 TYPE REF TO CL_ALV_GRID_TOOLBAR_MANAGER.

DATA: IT_SELECTED_N01 TYPE LVC_T_ROW,
      WA_SELECTED_N01 TYPE LVC_S_ROW,
      WA_ADD_NF_0104  TYPE TY_ADD_NF,
      CK_ALTERACAO    TYPE CHAR01.

*----------------------------------------------------------------------*
*       CLASS LCL_ALV_TOOLBAR_N01 IMPLEMENTATION
*----------------------------------------------------------------------*
*
*----------------------------------------------------------------------*
CLASS LCL_ALV_TOOLBAR_N01 IMPLEMENTATION.

  METHOD CONSTRUCTOR.
    CREATE OBJECT C_ALV_TOOLBARMANAGER_N01
      EXPORTING
        IO_ALV_GRID = IO_ALV_GRID.
  ENDMETHOD.                    "constructor

  METHOD ON_TOOLBAR.
    DATA: TY_TOOLBAR   TYPE STB_BUTTON.
*    "Separador

    CLEAR: TY_TOOLBAR.
    TY_TOOLBAR-BUTN_TYPE = 3.
    APPEND TY_TOOLBAR TO E_OBJECT->MT_TOOLBAR.
    CLEAR TY_TOOLBAR.

    "Verifica Permissão
    DATA(CK_PERMISSAO) = ZCL_CTE_DIST_G=>AUTORIZADO( EXPORTING I_CD_CHAVE_CTE = ZIB_CTE_DIST_TER-CD_CHAVE_CTE I_TP_APROVACAO = '07' ).

    "Incluir Nota Fiscal
    CLEAR: TY_TOOLBAR.
    TY_TOOLBAR-ICON      = ICON_INSERT_ROW.
    TY_TOOLBAR-FUNCTION  = 'ADD'.
    TY_TOOLBAR-QUICKINFO = TEXT-016.
    TY_TOOLBAR-BUTN_TYPE = 0.
    IF ZIB_CTE_DIST_TER-CK_FINALIZADO IS NOT INITIAL OR CK_PERMISSAO IS INITIAL.
      TY_TOOLBAR-DISABLED  = ABAP_TRUE.
    ENDIF.
    APPEND TY_TOOLBAR TO E_OBJECT->MT_TOOLBAR.

    "Editar Nota Fiscal
    CLEAR: TY_TOOLBAR.
    TY_TOOLBAR-ICON      = ICON_CHANGE.
    TY_TOOLBAR-FUNCTION  = 'EDT'.
    TY_TOOLBAR-QUICKINFO = TEXT-017.
    TY_TOOLBAR-BUTN_TYPE = 0.
    IF ZIB_CTE_DIST_TER-CK_FINALIZADO IS NOT INITIAL OR CK_PERMISSAO IS INITIAL.
      TY_TOOLBAR-DISABLED  = ABAP_TRUE.
    ENDIF.
    APPEND TY_TOOLBAR TO E_OBJECT->MT_TOOLBAR.

    "Excluir Nota Fiscal
    CLEAR: TY_TOOLBAR.
    TY_TOOLBAR-ICON      = ICON_DELETE_ROW.
    TY_TOOLBAR-FUNCTION  = 'DEL'.
    TY_TOOLBAR-QUICKINFO = TEXT-018.
    TY_TOOLBAR-BUTN_TYPE = 0.
    IF ZIB_CTE_DIST_TER-CK_FINALIZADO IS NOT INITIAL OR CK_PERMISSAO IS INITIAL.
      TY_TOOLBAR-DISABLED  = ABAP_TRUE.
    ENDIF.
    APPEND TY_TOOLBAR TO E_OBJECT->MT_TOOLBAR.

    CLEAR: TY_TOOLBAR.
    TY_TOOLBAR-BUTN_TYPE = 3.
    APPEND TY_TOOLBAR TO E_OBJECT->MT_TOOLBAR.

    "Rateio de Documento Eletrônico
    CLEAR TY_TOOLBAR.
    TY_TOOLBAR-ICON      = ICON_WF_WORKITEM_ERROR.
    TY_TOOLBAR-FUNCTION  = 'RNF'.
    TY_TOOLBAR-QUICKINFO = TEXT-015.
    TY_TOOLBAR-BUTN_TYPE = 0.
    APPEND TY_TOOLBAR TO E_OBJECT->MT_TOOLBAR.
    CLEAR TY_TOOLBAR.

    CALL METHOD C_ALV_TOOLBARMANAGER_N01->REORGANIZE
      EXPORTING
        IO_ALV_TOOLBAR = E_OBJECT.

  ENDMETHOD.                    "on_toolbar

  METHOD HANDLE_USER_COMMAND.

    CLEAR: IT_SELECTED_N01, IT_SELECTED_N01[].

    CALL METHOD CTL_ALV_N01->GET_SELECTED_ROWS
      IMPORTING
        ET_INDEX_ROWS = IT_SELECTED_N01.

    CLEAR: IT_CTE_N01_SEL[].

    LOOP AT IT_SELECTED_N01 INTO WA_SELECTED_N01.
      READ TABLE IT_CTE_N01 INTO WA_CTE_N01 INDEX WA_SELECTED_N55-INDEX.
      APPEND WA_CTE_N01 TO IT_CTE_N01_SEL.
    ENDLOOP.

    CASE E_UCOMM.
      WHEN 'ADD'.
        PERFORM INCLUIR_NF_PROCESSO.
      WHEN 'EDT'.
        PERFORM EDITAR_NF_PROCESSO.
      WHEN 'DEL'.
        PERFORM DELETAR_NF_PROCESSO.
      WHEN 'RNF'.
        PERFORM MOSTRA_RATEIO_DOC_N01.
    ENDCASE.

  ENDMETHOD. "zm_handle_user_command

ENDCLASS.                    "LCL_ALV_TOOLBAR_N55 IMPLEMENTATION


DATA: CTL_CON_N01       TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GS_LAY_N01        TYPE LVC_S_LAYO,
      GS_VAR_N01        TYPE DISVARIANT,
      GS_SCROLL_COL_N01 TYPE LVC_S_COL,
      GS_SCROLL_ROW_N01 TYPE LVC_S_ROID,
      IT_CATALOG_N01    TYPE LVC_T_FCAT,
      OBG_TOOLBAR_N01   TYPE REF TO LCL_ALV_TOOLBAR_N01.

DATA: IT_EXCLUDE_N01 TYPE UI_FUNCTIONS,
      WA_EXCLUDE_N01 LIKE LINE OF IT_EXCLUDE_FCODE.

*&--------------------------------------------------------------------&*
*& Classes Locais                                                     &*
*&--------------------------------------------------------------------&*

*---------- Definition -----------------------------------------------*
CLASS LCL_EVENT_HANDLER_N01 DEFINITION.
  PUBLIC SECTION.
    METHODS HANDLE_HOTSPOT_CLICK FOR EVENT HOTSPOT_CLICK OF CL_GUI_ALV_GRID IMPORTING E_COLUMN_ID ES_ROW_NO.
ENDCLASS.                    "lcl_event_handler DEFINITION

DATA: EVENT_HANDLER_N01      TYPE REF TO LCL_EVENT_HANDLER_N01.

*---------- Implementation -------------------------------------------*
CLASS LCL_EVENT_HANDLER_N01 IMPLEMENTATION.
  METHOD HANDLE_HOTSPOT_CLICK.
    PERFORM HANDLE_HOTSPOT_CLICK_N01 USING ES_ROW_NO-ROW_ID E_COLUMN_ID-FIELDNAME.
  ENDMETHOD.                    "handle_hotspot_click
ENDCLASS.                    "lcl_event_handler IMPLEMENTATION

*&---------------------------------------------------------------------*
*&      Module  STATUS_0104  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_0104 OUTPUT.

  IF CTL_CON_N01 IS INITIAL.

    CREATE OBJECT CTL_CON_N01
      EXPORTING
        CONTAINER_NAME = 'ALV_N01'.

    CREATE OBJECT CTL_ALV_N01
      EXPORTING
        I_PARENT = CTL_CON_N01.

    CREATE OBJECT OBG_TOOLBAR_N01
      EXPORTING
        IO_ALV_GRID = CTL_ALV_N01.

    SET HANDLER OBG_TOOLBAR_N01->ON_TOOLBAR FOR CTL_ALV_N01.
    SET HANDLER OBG_TOOLBAR_N01->HANDLE_USER_COMMAND FOR CTL_ALV_N01.

    PERFORM FILL_IT_FIELDCATALOG_N01.
*   Fill info for layout variant

    PERFORM FILL_GS_VARIANT_N01.
*   Set layout parameters for ALV grid

    GS_LAY_N01-SEL_MODE   = SPACE.
    GS_LAY_N01-ZEBRA      = ABAP_TRUE.

    CALL METHOD CTL_ALV_N01->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT            = GS_LAY_N01
        IS_VARIANT           = GS_VAR_N01
        I_DEFAULT            = SPACE
        I_SAVE               = 'A'
        IT_TOOLBAR_EXCLUDING = IT_EXCLUDE_N01
      CHANGING
        IT_FIELDCATALOG      = IT_CATALOG_N01
        IT_OUTTAB            = IT_CTE_N01.

    CREATE OBJECT EVENT_HANDLER_N01.
    SET HANDLER EVENT_HANDLER_N01->HANDLE_HOTSPOT_CLICK FOR CTL_ALV_N01.
  ELSE.
    CALL METHOD CTL_ALV_N01->REFRESH_TABLE_DISPLAY.
  ENDIF.

  CALL METHOD CTL_ALV_N01->GET_SCROLL_INFO_VIA_ID
    IMPORTING
      ES_COL_INFO = GS_SCROLL_COL_N01
      ES_ROW_NO   = GS_SCROLL_ROW_N01.

ENDMODULE.                 " STATUS_0104  OUTPUT

*&---------------------------------------------------------------------*
*&      Form  FILL_IT_FIELDCATALOG_N55
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM FILL_IT_FIELDCATALOG_N01 .

  FIELD-SYMBOLS: <FS_CAT_N01> TYPE LVC_S_FCAT.

  CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
    EXPORTING
      I_STRUCTURE_NAME = 'ZDE_CTE_DIST_N01_ALV'
    CHANGING
      CT_FIELDCAT      = IT_CATALOG_N01.

  LOOP AT IT_CATALOG_N01 ASSIGNING <FS_CAT_N01>.
    CASE <FS_CAT_N01>-FIELDNAME.
      WHEN 'IC_EDITAR'.
        <FS_CAT_N01>-KEY     = ABAP_TRUE.
        <FS_CAT_N01>-HOTSPOT = ABAP_TRUE.
        <FS_CAT_N01>-JUST    = 'C'.
      WHEN 'DOCNUM_NFE' OR 'TKNUM' OR 'FKNUM' OR 'LBLNI' OR 'EBELN' OR 'BELNR' OR 'VBELN_VF' OR 'VBELN_VL' OR 'VBELN_RE' OR 'MBLNR'.
        <FS_CAT_N01>-HOTSPOT = ABAP_TRUE.
      WHEN 'ZVLR_FRETE' OR 'ZVLR_MERCADORIA' OR 'ZVLR_QUEBRA' OR 'ZVLR_PERDA' OR 'ZVLR_LIQ_PAGAR'.
        <FS_CAT_N01>-DO_SUM = ABAP_TRUE.
    ENDCASE.
  ENDLOOP.

ENDFORM.                    " FILL_IT_FIELDCATALOG_N55

*&---------------------------------------------------------------------*
*&      Form  FILL_GS_VARIANT_N55
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM FILL_GS_VARIANT_N01 .

  GS_VAR_N01-REPORT      = SY-REPID.
  GS_VAR_N01-HANDLE      = '0003'.
  GS_VAR_N01-LOG_GROUP   = ABAP_FALSE.
  GS_VAR_N01-USERNAME    = ABAP_FALSE.
  GS_VAR_N01-VARIANT     = ABAP_FALSE.
  GS_VAR_N01-TEXT        = ABAP_FALSE.
  GS_VAR_N01-DEPENDVARS  = ABAP_FALSE.

ENDFORM.                    " FILL_GS_VARIANT_N55

*&---------------------------------------------------------------------*
*&      Form  HANDLE_HOTSPOT_CLICK_N55
*&---------------------------------------------------------------------*
FORM HANDLE_HOTSPOT_CLICK_N01
         USING VALUE(ROW_ID)    LIKE LVC_S_ROID-ROW_ID
               VALUE(FIELDNAME) LIKE LVC_S_COL-FIELDNAME.

  READ TABLE IT_CTE_N01 INDEX ROW_ID INTO WA_CTE_N01.

  CASE FIELDNAME.
    WHEN 'IC_EDITAR'.
      PERFORM EDITAR_LINHA_NOTA_N01 USING ROW_ID CHANGING WA_CTE_N01.
    WHEN 'DOCNUM_NF'.
      PERFORM MOSTRAR_DOC_FISCAL USING WA_CTE_N01-DOCNUM_NF.
    WHEN 'TKNUM' .
      PERFORM MOSTRAR_DOC_TRANSPORTE USING WA_CTE_N01-TKNUM.
    WHEN 'FKNUM'.
      PERFORM MOSTRAR_DOC_CUSTO_TRANS USING WA_CTE_N01-FKNUM.
    WHEN 'LBLNI' .
      "PERFORM MOSTRAR_ USING WA_CTE_N55-FKNUM.
    WHEN 'EBELN' .
      PERFORM MOSTRAR_PEDIDO USING WA_CTE_N01-EBELN.
    WHEN 'BELNR' .
      PERFORM MOSTRAR_FATURA USING WA_CTE_N01-BELNR WA_CTE_N01-GJAHR.
    WHEN 'VBELN_VF' .
      PERFORM MOSTRAR_FATURA_VF USING WA_CTE_N01-VBELN_VF.
    WHEN 'VBELN_VL' .
      PERFORM MOSTRAR_REMESSA_VL USING WA_CTE_N01-VBELN_VL.
    WHEN 'VBELN_RE'.
      PERFORM MOSTRAR_FATURA USING WA_CTE_N01-VBELN_RE WA_CTE_N01-GJAHR_RE.
    WHEN 'MBLNR'.
      PERFORM MOSTRAR_DOC_MATERIAL USING WA_CTE_N01-MBLNR WA_CTE_N01-MJAHR.
  ENDCASE.

ENDFORM.                    " HANDLE_HOTSPOT_CLICK

*&---------------------------------------------------------------------*
*&      Module  GET_SCROLL_INFO_N01  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE GET_SCROLL_INFO_N01 INPUT.
  CALL METHOD CTL_ALV_N01->GET_SCROLL_INFO_VIA_ID
    IMPORTING
      ES_COL_INFO = GS_SCROLL_COL_N01
      ES_ROW_NO   = GS_SCROLL_ROW_N01.
ENDMODULE.                 " GET_SCROLL_INFO_N01  INPUT

*&---------------------------------------------------------------------*
*&      Module  GET_SELECTED_ROWS_N01  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE GET_SELECTED_ROWS_N01 INPUT.

  CLEAR IT_SELECTED_N01.

  CALL METHOD CTL_ALV_N01->GET_SELECTED_ROWS
    IMPORTING
      ET_INDEX_ROWS = IT_SELECTED_N01.

  CLEAR: IT_SELECTED_N01[], IT_CTE_N01_SEL[].

  LOOP AT IT_SELECTED_N01 INTO WA_SELECTED_N01.
    READ TABLE IT_CTE_N01 INTO WA_CTE_N01 INDEX WA_SELECTED_N55-INDEX.
    APPEND WA_CTE_N01 TO IT_CTE_N01_SEL.
  ENDLOOP.

ENDMODULE.                 " GET_SELECTED_ROWS_N01  INPUT

*&---------------------------------------------------------------------*
*&      Form  MOSTRA_RATEIO_DOC_N01
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM MOSTRA_RATEIO_DOC_N01 .

  IF IT_CTE_N01_SEL[] IS INITIAL.
    MESSAGE S022.
    RETURN.
  ENDIF.

  READ TABLE IT_CTE_N01_SEL INTO WA_CTE_N01 INDEX 1.

  CLEAR: IT_CTE_D01[].

  SELECT * INTO TABLE IT_CTE_D01
    FROM ZIB_CTE_DIST_D01
   WHERE CD_CHAVE_CTE     EQ WA_CTE_N01-CD_CHAVE_CTE
     AND N01_MODELO_NF    EQ WA_CTE_N01-N01_MODELO_NF
     AND N01_NUMR_SERIE   EQ WA_CTE_N01-N01_NUMR_SERIE
     AND N01_NR_NF        EQ WA_CTE_N01-N01_NR_NF.

  IF IT_CTE_D01[] IS NOT INITIAL.
    CALL SCREEN 0110 STARTING AT 30 5.
  ELSE.
    MESSAGE S129.
  ENDIF.

ENDFORM.                    " MOSTRA_RATEIO_DOC_N01

FORM DELETAR_NF_PROCESSO.

  DATA: CK_ALT_NF TYPE CHAR01.

  IF IT_CTE_N01_SEL[] IS INITIAL.
    MESSAGE S022.
    RETURN.
  ENDIF.

  CK_ALT_NF = ABAP_FALSE.

  LOOP AT IT_CTE_N01_SEL INTO WA_CTE_N01.
    DELETE FROM ZIB_CTE_DIST_N01
     WHERE CD_CHAVE_CTE     EQ WA_CTE_N01-CD_CHAVE_CTE
       AND N01_MODELO_NF    EQ WA_CTE_N01-N01_MODELO_NF
       AND N01_NUMR_SERIE   EQ WA_CTE_N01-N01_NUMR_SERIE
       AND N01_NR_NF        EQ WA_CTE_N01-N01_NR_NF.
    CK_ALT_NF = ABAP_TRUE.
  ENDLOOP.

  IF CK_ALT_NF EQ ABAP_TRUE.
    COMMIT WORK.

    CALL METHOD OBJ_CTE->LER_DADOS_XI
      EXPORTING
        P_CHAVE_CTE = ZIB_CTE_DIST_TER-CD_CHAVE_CTE.

    SELECT SINGLE * INTO ZIB_CTE_DIST_TER
      FROM ZIB_CTE_DIST_TER
     WHERE CD_CHAVE_CTE EQ ZIB_CTE_DIST_TER-CD_CHAVE_CTE.

    PERFORM BUSCA_INFO_NOTAS_CTE_CTE.
    LEAVE TO SCREEN 0101.
  ENDIF.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  INCLUIR_NF_PROCESSO
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM INCLUIR_NF_PROCESSO .

  DATA: WA_N01 TYPE ZIB_CTE_DIST_N01.

  CLEAR: WA_ADD_NF_0104.
  WA_ADD_NF_0104-CD_CHAVE_CTE = ZIB_CTE_DIST_TER-CD_CHAVE_CTE.
  WA_ADD_NF_0104-CK_INCLUIR   = ABAP_TRUE.
  CK_ALTERACAO = 'I'.
  CALL SCREEN 0304 STARTING AT 15 01.

  IF WA_ADD_NF_0104-CK_INCLUIR EQ ABAP_TRUE.
    WA_N01-CD_CHAVE_CTE     = WA_ADD_NF_0104-CD_CHAVE_CTE.
    WA_N01-N01_MODELO_NF    = WA_ADD_NF_0104-N01_MODELO_NF.
    WA_N01-N01_NUMR_SERIE   = WA_ADD_NF_0104-N01_NUMR_SERIE.
    WA_N01-N01_NR_NF        = WA_ADD_NF_0104-N01_NR_NF.
    WA_N01-N01_DATA_EMISSAO = WA_ADD_NF_0104-N01_DATA_EMISSAO.
    WA_N01-N01_VL_BASE_ICMS = WA_ADD_NF_0104-N01_VL_BASE_ICMS.
    WA_N01-N01_VL_ICMS      = WA_ADD_NF_0104-N01_VL_ICMS.
    WA_N01-N01_VL_BICMS_ST  = WA_ADD_NF_0104-N01_VL_BICMS_ST.
    WA_N01-N01_VL_ICMS_ST   = WA_ADD_NF_0104-N01_VL_ICMS_ST.
    WA_N01-N01_VL_PRODUTOS  = WA_ADD_NF_0104-N01_VL_PRODUTOS.
    WA_N01-N01_VL_NOTA      = WA_ADD_NF_0104-N01_VL_NOTA.
    WA_N01-N01_CODG_CFOP    = WA_ADD_NF_0104-N01_CODG_CFOP.
    WA_N01-N01_VL_PESO      = WA_ADD_NF_0104-N01_VL_PESO.
    WA_N01-N01_PIN_SUFRAMA  = WA_ADD_NF_0104-N01_PIN_SUFRAMA.
    WA_N01-CK_INC_MANUAL    = ABAP_TRUE.
    MODIFY ZIB_CTE_DIST_N01 FROM WA_N01.
    COMMIT WORK.

    CALL METHOD OBJ_CTE->LER_DADOS_XI
      EXPORTING
        P_CHAVE_CTE = WA_ADD_NF_0104-CD_CHAVE_CTE.

    SELECT SINGLE * INTO ZIB_CTE_DIST_TER
      FROM ZIB_CTE_DIST_TER
     WHERE CD_CHAVE_CTE EQ WA_ADD_NF_0104-CD_CHAVE_CTE.

    PERFORM BUSCA_INFO_NOTAS_CTE_CTE.
    LEAVE TO SCREEN 0101.
  ENDIF.

  CLEAR: OK_CODE.

ENDFORM.                    " INCLUIR_NF_PROCESSO

*&---------------------------------------------------------------------*
*&      Form  EDITAR_NF_PROCESSO
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM EDITAR_NF_PROCESSO .

  DATA: WA_N01_BANCO TYPE ZIB_CTE_DIST_N01.

  IF IT_CTE_N01_SEL[] IS INITIAL.
    MESSAGE S022.
    RETURN.
  ENDIF.

  READ TABLE IT_CTE_N01_SEL INTO DATA(WA_N01) INDEX 1.
  CK_ALTERACAO = 'A'.

  SELECT SINGLE * INTO WA_N01_BANCO
    FROM ZIB_CTE_DIST_N01
   WHERE CD_CHAVE_CTE     EQ WA_N01-CD_CHAVE_CTE
     AND N01_MODELO_NF    EQ WA_N01-N01_MODELO_NF
     AND N01_NUMR_SERIE   EQ WA_N01-N01_NUMR_SERIE
     AND N01_NR_NF        EQ WA_N01-N01_NR_NF.

  WA_ADD_NF_0104-CD_CHAVE_CTE     = WA_N01_BANCO-CD_CHAVE_CTE.
  WA_ADD_NF_0104-N01_MODELO_NF    = WA_N01_BANCO-N01_MODELO_NF.
  WA_ADD_NF_0104-N01_NUMR_SERIE   = WA_N01_BANCO-N01_NUMR_SERIE.
  WA_ADD_NF_0104-N01_NR_NF        = WA_N01_BANCO-N01_NR_NF.
  WA_ADD_NF_0104-N01_DATA_EMISSAO = WA_N01_BANCO-N01_DATA_EMISSAO.
  WA_ADD_NF_0104-N01_VL_BASE_ICMS = WA_N01_BANCO-N01_VL_BASE_ICMS.
  WA_ADD_NF_0104-N01_VL_ICMS      = WA_N01_BANCO-N01_VL_ICMS.
  WA_ADD_NF_0104-N01_VL_BICMS_ST  = WA_N01_BANCO-N01_VL_BICMS_ST.
  WA_ADD_NF_0104-N01_VL_ICMS_ST   = WA_N01_BANCO-N01_VL_ICMS_ST.
  WA_ADD_NF_0104-N01_VL_PRODUTOS  = WA_N01_BANCO-N01_VL_PRODUTOS.
  WA_ADD_NF_0104-N01_VL_NOTA      = WA_N01_BANCO-N01_VL_NOTA.
  WA_ADD_NF_0104-N01_CODG_CFOP    = WA_N01_BANCO-N01_CODG_CFOP.
  WA_ADD_NF_0104-N01_VL_PESO      = WA_N01_BANCO-N01_VL_PESO.
  WA_ADD_NF_0104-N01_PIN_SUFRAMA  = WA_N01_BANCO-N01_PIN_SUFRAMA.
  WA_ADD_NF_0104-CK_INCLUIR       = ABAP_TRUE.
  CALL SCREEN 0304 STARTING AT 15 01.

  IF WA_ADD_NF_0104-CK_INCLUIR EQ ABAP_TRUE.
    WA_N01_BANCO-CD_CHAVE_CTE     = WA_ADD_NF_0104-CD_CHAVE_CTE.
    WA_N01_BANCO-N01_MODELO_NF    = WA_ADD_NF_0104-N01_MODELO_NF.
    WA_N01_BANCO-N01_NUMR_SERIE   = WA_ADD_NF_0104-N01_NUMR_SERIE.
    WA_N01_BANCO-N01_NR_NF        = WA_ADD_NF_0104-N01_NR_NF.
    WA_N01_BANCO-N01_DATA_EMISSAO = WA_ADD_NF_0104-N01_DATA_EMISSAO.
    WA_N01_BANCO-N01_VL_BASE_ICMS = WA_ADD_NF_0104-N01_VL_BASE_ICMS.
    WA_N01_BANCO-N01_VL_ICMS      = WA_ADD_NF_0104-N01_VL_ICMS.
    WA_N01_BANCO-N01_VL_BICMS_ST  = WA_ADD_NF_0104-N01_VL_BICMS_ST.
    WA_N01_BANCO-N01_VL_ICMS_ST   = WA_ADD_NF_0104-N01_VL_ICMS_ST.
    WA_N01_BANCO-N01_VL_PRODUTOS  = WA_ADD_NF_0104-N01_VL_PRODUTOS.
    WA_N01_BANCO-N01_VL_NOTA      = WA_ADD_NF_0104-N01_VL_NOTA.
    WA_N01_BANCO-N01_CODG_CFOP    = WA_ADD_NF_0104-N01_CODG_CFOP.
    WA_N01_BANCO-N01_VL_PESO      = WA_ADD_NF_0104-N01_VL_PESO.
    WA_N01_BANCO-N01_PIN_SUFRAMA  = WA_ADD_NF_0104-N01_PIN_SUFRAMA.
    WA_N01_BANCO-CK_INC_MANUAL    = ABAP_TRUE.
    MODIFY ZIB_CTE_DIST_N01 FROM WA_N01_BANCO.
    COMMIT WORK.

    CALL METHOD OBJ_CTE->LER_DADOS_XI
      EXPORTING
        P_CHAVE_CTE = WA_ADD_NF_0104-CD_CHAVE_CTE.

    SELECT SINGLE * INTO ZIB_CTE_DIST_TER
      FROM ZIB_CTE_DIST_TER
     WHERE CD_CHAVE_CTE EQ WA_ADD_NF_0104-CD_CHAVE_CTE.

    PERFORM BUSCA_INFO_NOTAS_CTE_CTE.
    LEAVE TO SCREEN 0101.
  ENDIF.

  CLEAR: OK_CODE.



ENDFORM.                    " EDITAR_NF_PROCESSO
