*&---------------------------------------------------------------------*
*&  Include           ZMMR182_TOP
*&---------------------------------------------------------------------*

TABLES: ekko,
        ekpo,
        ekbe.

TYPES:
  BEGIN OF ty_principal,
    ebeln  TYPE ekbe-ebeln,
    ebelp  TYPE ekbe-ebelp,
    zekkn  TYPE ekbe-zekkn,
    belnr  TYPE ekbe-belnr,
    lfbnr  TYPE ekbe-lfbnr,
    budat  TYPE ekbe-budat,
    menge  TYPE ekbe-menge,
    werks  TYPE ekbe-werks,
    gjahr  TYPE ekbe-gjahr,
    dmbtr  TYPE ekbe-dmbtr,
    bukrs  TYPE ekko-bukrs,
    bsart  TYPE ekko-bsart,
    bwart  TYPE ekbe-bwart,
    vgabe  TYPE ekbe-vgabe,
    matnr  TYPE ekbe-matnr,
    shkzg  TYPE bseg-shkzg,
    dmbtr2 TYPE ekbe-dmbtr,
    menge2 TYPE ekbe-menge,
    awkey  TYPE bkpf-awkey,
  END OF ty_principal,

  BEGIN OF ty_folha,
    ebeln TYPE ekbe-ebeln,
    ebelp TYPE ekbe-ebelp,
    lfbnr TYPE ekbe-lfbnr,
    belnr TYPE ekbe-belnr,
    gjahr TYPE ekbe-gjahr,
    vgabe TYPE ekbe-vgabe,
    dmbtr TYPE ekbe-dmbtr,
  END OF ty_folha,

  BEGIN OF ty_migo,
    ebeln TYPE ekbe-ebeln,
    ebelp TYPE ekbe-ebelp,
    belnr TYPE ekbe-belnr,
    lfbnr TYPE ekbe-lfbnr,
  END OF ty_migo,

  BEGIN OF ty_migo2,
    ebeln TYPE ekbe-ebeln,
    ebelp TYPE ekbe-ebelp,
    zekkn TYPE ekbe-zekkn,
    belnr TYPE ekbe-belnr,
    lfbnr TYPE ekbe-lfbnr,
    gjahr TYPE ekbe-gjahr,
    budat TYPE ekbe-budat,
    menge TYPE ekbe-menge,
    dmbtr TYPE ekbe-dmbtr,
  END OF ty_migo2,

  BEGIN OF ty_saida,
    bukrs      TYPE ekko-bukrs,
    werks      TYPE ekbe-werks,
    ebeln      TYPE ekbe-ebeln,
    ebelp      TYPE ekbe-ebelp,
    matnr      TYPE ekbe-matnr,
    migo       TYPE ekbe-belnr,
    anomigo    TYPE ekbe-gjahr,
    dtamigo    TYPE ekbe-budat,
    qtdmigo    TYPE ekbe-menge,
    folha      TYPE ekbe-lfbnr,
    vlrmigo    TYPE ekbe-dmbtr,
    miro       TYPE ekbe-belnr,
    anomiro    TYPE ekbe-gjahr,
    dtamiro    TYPE ekbe-budat,
    qtdmiro    TYPE ekbe-menge,
    vlrmiro    TYPE ekbe-dmbtr,
    diferencaq TYPE ekbe-menge,
    diferencav TYPE ekbe-menge,
  END OF ty_saida.


DATA: t_ekbe       TYPE TABLE OF ty_principal,
      t_ekbe_aux   TYPE TABLE OF ty_principal,
      t_ekbe_miro  TYPE TABLE OF ty_principal,
      t_ekbe_folha TYPE TABLE OF ty_folha,
      t_ekbe_migo  TYPE TABLE OF ty_migo2,
      t_ekbe_migo2 TYPE TABLE OF ty_migo2,
      t_bkpf       TYPE TABLE OF bkpf,
      t_bseg       TYPE TABLE OF bseg,
      t_bseg_tot   TYPE TABLE OF ty_principal,
      w_bseg_tot   TYPE ty_principal,
      t_saida      TYPE TABLE OF ty_saida,
      t_saida_aux  TYPE TABLE OF ty_saida.

DATA: gr_alv       TYPE REF TO cl_salv_table.
