************************************************************************
* Responsável ...: Amaggi Exportação & Importação Ltda                 *
* Data desenv ...: 29.07.2016                                          *
* Objetivo    ...: Relatório EKKO EKPO LFA1 EKKN                       *
* Transação   ...:                                                     *
************************************************************************
* Data Modif    Autor         Descriçao      Hora           Request    *
************************************************************************
* 27.07.2016  Welgem Barbosa   Criação      08:00                      *
************************************************************************

REPORT ZMMR107.

TABLES: VBAK.
SELECTION-SCREEN: BEGIN OF SCREEN 0104 AS SUBSCREEN.
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: DATA FOR VBAK-ERDAT OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.
SELECTION-SCREEN: END OF SCREEN 0104.

DATA: IT_EKKO TYPE TABLE OF EKKO,
      IT_EKPO TYPE TABLE OF EKPO,
      IT_LFA1 TYPE TABLE OF LFA1,
      IT_EKKN TYPE TABLE OF EKKN,
      WA_EKKO TYPE EKKO,
      WA_EKPO TYPE EKPO,
      WA_LFA1 TYPE LFA1,
      WA_EKKN TYPE EKKN.


DATA: WA_LAYOUT TYPE LVC_S_LAYO,
      FCAT_EKKO TYPE LVC_T_FCAT,
      FCAT_EKPO TYPE LVC_T_FCAT,
      FCAT_LFA1 TYPE LVC_T_FCAT,
      FCAT_EKKN TYPE LVC_T_FCAT,
      CONT_EKKO TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      CONT_EKPO TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      CONT_LFA1 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      CONT_EKKN TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      ALV_EKKO  TYPE REF TO CL_GUI_ALV_GRID,
      ALV_EKPO  TYPE REF TO CL_GUI_ALV_GRID,
      ALV_LFA1  TYPE REF TO CL_GUI_ALV_GRID,
      ALV_EKKN  TYPE REF TO CL_GUI_ALV_GRID.

START-OF-SELECTION.
  CALL SCREEN 0100.

END-OF-SELECTION.

FORM SELECIONA_DADOS.

  SELECT * FROM EKKO
    INTO TABLE IT_EKKO
  WHERE BEDAT IN DATA.

  CHECK NOT IT_EKKO IS INITIAL.

  SELECT * FROM EKPO
    INTO TABLE IT_EKPO
      FOR ALL ENTRIES IN IT_EKKO
  WHERE EBELN EQ IT_EKKO-EBELN.

  SELECT * FROM LFA1
    INTO TABLE IT_LFA1
      FOR ALL ENTRIES IN IT_EKKO
  WHERE LIFNR EQ IT_EKKO-LIFNR.

  SELECT * FROM EKKN
    INTO TABLE IT_EKKN
      FOR ALL ENTRIES IN IT_EKKO
  WHERE EBELN EQ IT_EKKO-EBELN.


ENDFORM.

FORM MONTA_GRIDS.

  IF CONT_EKKO IS INITIAL.

    CREATE OBJECT CONT_EKKO EXPORTING CONTAINER_NAME = 'T_EKKO'.
    CREATE OBJECT ALV_EKKO EXPORTING I_PARENT = CONT_EKKO.

    WA_LAYOUT-GRID_TITLE = 'Pedidos'.
    CALL METHOD ALV_EKKO->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT        = WA_LAYOUT
        I_STRUCTURE_NAME = 'EKKO'
      CHANGING
        IT_OUTTAB        = IT_EKKO.

  ELSE.
    CALL METHOD ALV_EKKO->REFRESH_TABLE_DISPLAY.
  ENDIF.


  IF CONT_EKPO IS INITIAL.

    CREATE OBJECT CONT_EKPO EXPORTING CONTAINER_NAME = 'T_EKPO'.
    CREATE OBJECT ALV_EKPO EXPORTING I_PARENT = CONT_EKPO.

    WA_LAYOUT-GRID_TITLE = 'Item do Pedido'.
    CALL METHOD ALV_EKPO->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT        = WA_LAYOUT
        I_STRUCTURE_NAME = 'EKPO'
      CHANGING
        IT_OUTTAB        = IT_EKPO.

  ELSE.
    CALL METHOD ALV_EKPO->REFRESH_TABLE_DISPLAY.
  ENDIF.

  IF CONT_LFA1 IS INITIAL.

    CREATE OBJECT CONT_LFA1 EXPORTING CONTAINER_NAME = 'T_LFA1'.
    CREATE OBJECT ALV_LFA1 EXPORTING I_PARENT = CONT_LFA1.

    WA_LAYOUT-GRID_TITLE = 'Fornecedores'.
    CALL METHOD ALV_LFA1->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT        = WA_LAYOUT
        I_STRUCTURE_NAME = 'LFA1'
      CHANGING
        IT_OUTTAB        = IT_LFA1.

  ELSE.
    CALL METHOD ALV_LFA1->REFRESH_TABLE_DISPLAY.
  ENDIF.

  IF CONT_EKKN IS INITIAL.

    CREATE OBJECT CONT_EKKN EXPORTING CONTAINER_NAME = 'T_EKKN'.
    CREATE OBJECT ALV_EKKN EXPORTING I_PARENT = CONT_EKKN.

    WA_LAYOUT-GRID_TITLE = 'Documento Contábil Compra'.
    CALL METHOD ALV_EKKN->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT        = WA_LAYOUT
        I_STRUCTURE_NAME = 'EKKN'
      CHANGING
        IT_OUTTAB        = IT_EKKN.

  ELSE.
    CALL METHOD ALV_EKKN->REFRESH_TABLE_DISPLAY.
  ENDIF.

ENDFORM.

*&      Module  PBO  OUTPUT
MODULE PBO OUTPUT.
  SET PF-STATUS 'T_0100'.
  SET TITLEBAR 'S_0100'.
ENDMODULE.

*&      Module  PAI  INPUT
MODULE PAI INPUT.
  CASE SY-UCOMM.
    WHEN 'EXE'.

      PERFORM SELECIONA_DADOS.
      PERFORM MONTA_GRIDS.

    WHEN 'BACK'.
      LEAVE PROGRAM.
  ENDCASE.
ENDMODULE.
