
PROCESS BEFORE OUTPUT.
  MODULE: STATUS_0100,
          PBO_0100.

  CALL SUBSCREEN SUB_PRINCIPAL INCLUDING SY-REPID VG_SCREEN_PRINCIPAL.

PROCESS AFTER INPUT.
  CALL SUBSCREEN SUB_PRINCIPAL.
  MODULE PAI_0100.
