READ TABLE T_ZMMR0001 INTO ST_ZMMR001_AUX INDEX 1.

  IF CAB_1 IS INITIAL
    AND ST_ZMMR001_AUX-ELG IS NOT INITIAL.
      CAB_1  = 'ELG'.
  ELSEIF CAB_1 IS INITIAL
    AND ST_ZMMR001_AUX-LEAF IS NOT INITIAL.
      CAB_1  = 'LEAF'.
  ELSEIF CAB_1 IS INITIAL
    AND ST_ZMMR001_AUX-CG IS NOT INITIAL.
      CAB_1  = 'CG'.
  ENDIF.

  IF ST_ZMMR001_AUX-LEAF IS NOT INITIAL
    AND CAB_1 NE 'LEAF'.
      CAB_2 = 'LEAF'.
  ELSEIF CAB_2 IS INITIAL
    AND ST_ZMMR001_AUX-CG IS NOT INITIAL
    AND CAB_1 NE 'CG'.
      CAB_2 = 'CG'.
  ENDIF.

IF ST_ZMMR001_AUX-CG IS NOT INITIAL
  AND CAB_2 NE 'CG' AND CAB_1 NE 'CG'.
  CAB_3 = 'CG'.
ENDIF.















