DATA ITEMS_RESERVATION TYPE RSIS_T_RANGE.
DATA GW_ITEM_EPI       TYPE TY_ITEM_EPI.
DATA V_DATA(8).
DATA WA_ZMMT0088       TYPE ZMMT0088.

ZCL_HRST_COMMONS=>GET_EMPLOYEE(
   EXPORTING
     MATRICULA      = MATRICULA
   RECEIVING
     EMPLOYEE       = EMPLOYEE_DATA
   EXCEPTIONS
     DATA_NOT_FOUND = 1
     OTHERS         = 2
 ).

CLEAR V_DATA.
SELECT SINGLE *
  FROM ZMMT0088
  INTO WA_ZMMT0088
   WHERE MATRICULA  EQ EMPLOYEE_DATA-MATRICULA
   AND   DT_VAL_DE  LE SY-DATUM
   AND   DT_VAL_ATE GE SY-DATUM.

IF SY-SUBRC NE 0.
  SELECT SINGLE *
   FROM ZMMT0088
   INTO WA_ZMMT0088
    WHERE MATRICULA  EQ EMPLOYEE_DATA-MATRICULA.
ENDIF.
IF SY-SUBRC EQ 0.
  IF WA_ZMMT0088-DT_VAL_DE NE  '19000101'  AND WA_ZMMT0088-DT_VAL_DE IS NOT INITIAL. "Cadastro inicial. "Cadastro inicial
    V_DATA = WA_ZMMT0088-DT_VAL_DE.
  ENDIF.
  USER_DIGITAL_LEFT  = |DIGITAL_LEFT_{ EMPLOYEE_DATA-MATRICULA }{ V_DATA }|.
  USER_DIGITAL_RIGHT = |DIGITAL_RIGHT_{ EMPLOYEE_DATA-MATRICULA }{ V_DATA }|.
ELSE.
  CLEAR: USER_DIGITAL_LEFT, USER_DIGITAL_RIGHT.
ENDIF.


IF EMPLOYEE_DATA-DT_DEMISSAO = '31/12/9999'.
  CLEAR EMPLOYEE_DATA-DT_DEMISSAO.
ENDIF.

IF EMPLOYEE_DATA-AREA  NE 'TERCEIRO'.
  EMPLOYEE_DATA-CPF = EMPLOYEE_DATA-MATRICULA.
ELSE.
  EMPLOYEE_DATA-AREA = EMPLOYEE_DATA-NOME_EMPRESA.
ENDIF.
