

LOOP AT IMPOSTO WHERE  BELNR = WA_MIRO-BELNR AND
                       GJAHR = WA_MIRO-GJAHR.

  WA_IMPOSTO-BELNR     = IMPOSTO-BELNR.
  WA_IMPOSTO-GJAHR     = IMPOSTO-GJAHR.
  WA_IMPOSTO-WITHT     = IMPOSTO-WITHT.
  WA_IMPOSTO-WT_WITHCD = IMPOSTO-WT_WITHCD.
  WA_IMPOSTO-WT_QSSHB  = IMPOSTO-WT_QSSHB.
  WA_IMPOSTO-WT_QBUIHB = IMPOSTO-WT_QBUIHB.
  WA_IMPOSTO-TEXT40    = IMPOSTO-TEXT40.

  APPEND WA_IMPOSTO TO T_IMPOSTO.
ENDLOOP.
