PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZMMT0180-CHAVE_NFE .
    FIELD ZMMT0180-QTDE_EXC .
    FIELD ZMMT0180-USUARIO .
    FIELD ZMMT0180-DATA .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZMMT0180-CHAVE_NFE .
  module detail_pai.
 endchain.
