PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZMMT0070-KUNNR .
    FIELD ZMMT0070-LIFNR .
    FIELD ZMMT0070-NOME_K .
    FIELD ZMMT0070-NOME_L .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZMMT0070-KUNNR .
    FIELD ZMMT0070-LIFNR .
  module detail_pai.
 endchain.
