FUNCTION ZNFE_INBOUND_MIGO_MIRO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_AVISO_RECEBIMENTO) TYPE  VBELN_VL
*"  EXPORTING
*"     REFERENCE(E_NFE_INBOUND) TYPE  ZIB_NFE_DIST_TER
*"     REFERENCE(E_DOCNUM_NFE) TYPE  J_1BDOCNUM
*"     REFERENCE(E_MBLNR) TYPE  MBLNR
*"     REFERENCE(E_MJAHR) TYPE  MJAHR
*"     REFERENCE(E_BELNR) TYPE  RE_BELNR
*"     REFERENCE(E_GJAHR) TYPE  GJAHR
*"  EXCEPTIONS
*"      ERRO
*"----------------------------------------------------------------------

  DATA: ERRO_NFE   TYPE REF TO ZCX_NFE_INBOUND_EXCEPTION,
        ERRO_CAD   TYPE REF TO ZCX_CADASTRO,
        ERRO_PED   TYPE REF TO ZCX_PEDIDO_COMPRA_EXCEPTION,
        ERRO_CHARG TYPE REF TO ZCX_CHARG_EXCEPTION.

  TRY .

      DATA(R_GEROU) =
      ZCL_NFE_INBOUND=>NFE_INBOUND_ACEITE_AVISO( EXPORTING
                                                     I_AVISO_RECEBIMENTO  = I_AVISO_RECEBIMENTO
                                                    IMPORTING
                                                      E_DOCNUM_NFE  = E_DOCNUM_NFE
                                                      E_MBLNR       = E_MBLNR
                                                      E_MJAHR       = E_MJAHR
                                                      E_BELNR       = E_BELNR
                                                      E_GJAHR       = E_GJAHR
                                                      E_NFE_INBOUND = E_NFE_INBOUND ).

    CATCH ZCX_NFE_INBOUND_EXCEPTION INTO ERRO_NFE.

      SY-MSGV1 = CONV #( ERRO_NFE->IF_T100_MESSAGE~T100KEY-ATTR1 ).
      SY-MSGV2 = CONV #( ERRO_NFE->IF_T100_MESSAGE~T100KEY-ATTR2 ).
      SY-MSGV3 = CONV #( ERRO_NFE->IF_T100_MESSAGE~T100KEY-ATTR3 ).
      SY-MSGV4 = CONV #( ERRO_NFE->IF_T100_MESSAGE~T100KEY-ATTR4 ).

      MESSAGE ID ERRO_NFE->IF_T100_MESSAGE~T100KEY-MSGID TYPE ERRO_NFE->MSGTY
       NUMBER ERRO_NFE->IF_T100_MESSAGE~T100KEY-MSGNO
         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING ERRO.

    CATCH ZCX_CADASTRO INTO ERRO_CAD.

      SY-MSGV1 = CONV #( ERRO_CAD->IF_T100_MESSAGE~T100KEY-ATTR1 ).
      SY-MSGV2 = CONV #( ERRO_CAD->IF_T100_MESSAGE~T100KEY-ATTR2 ).
      SY-MSGV3 = CONV #( ERRO_CAD->IF_T100_MESSAGE~T100KEY-ATTR3 ).
      SY-MSGV4 = CONV #( ERRO_CAD->IF_T100_MESSAGE~T100KEY-ATTR4 ).

      MESSAGE ID ERRO_CAD->IF_T100_MESSAGE~T100KEY-MSGID TYPE ERRO_CAD->MSGTY
       NUMBER ERRO_CAD->IF_T100_MESSAGE~T100KEY-MSGNO
         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING ERRO.

    CATCH ZCX_PEDIDO_COMPRA_EXCEPTION INTO ERRO_PED.

      SY-MSGV1 = CONV #( ERRO_PED->IF_T100_MESSAGE~T100KEY-ATTR1 ).
      SY-MSGV2 = CONV #( ERRO_PED->IF_T100_MESSAGE~T100KEY-ATTR2 ).
      SY-MSGV3 = CONV #( ERRO_PED->IF_T100_MESSAGE~T100KEY-ATTR3 ).
      SY-MSGV4 = CONV #( ERRO_PED->IF_T100_MESSAGE~T100KEY-ATTR4 ).

      MESSAGE ID ERRO_PED->IF_T100_MESSAGE~T100KEY-MSGID TYPE ERRO_PED->MSGTY
       NUMBER ERRO_PED->IF_T100_MESSAGE~T100KEY-MSGNO
         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING ERRO.

    CATCH ZCX_CHARG_EXCEPTION INTO ERRO_CHARG.

      SY-MSGV1 = CONV #( ERRO_CHARG->IF_T100_MESSAGE~T100KEY-ATTR1 ).
      SY-MSGV2 = CONV #( ERRO_CHARG->IF_T100_MESSAGE~T100KEY-ATTR2 ).
      SY-MSGV3 = CONV #( ERRO_CHARG->IF_T100_MESSAGE~T100KEY-ATTR3 ).
      SY-MSGV4 = CONV #( ERRO_CHARG->IF_T100_MESSAGE~T100KEY-ATTR4 ).

      MESSAGE ID ERRO_CHARG->IF_T100_MESSAGE~T100KEY-MSGID TYPE ERRO_CHARG->MSGTY
       NUMBER ERRO_CHARG->IF_T100_MESSAGE~T100KEY-MSGNO
         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING ERRO.

  ENDTRY.

ENDFUNCTION.
