FUNCTION ZNFE_CADASTRO_DEPARTAMENTO_CAD.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_CONSULTA) TYPE  CHAR01
*"     REFERENCE(I_CD_DEPARTAMENTO) TYPE  ZDE_DEPARTAMENTO OPTIONAL
*"  EXPORTING
*"     REFERENCE(I_GRAVOU) TYPE  CHAR01
*"  CHANGING
*"     REFERENCE(I_OB_DEPARTAMENTO) TYPE REF TO  ZCL_MM_DEPARTAMENTO
*"       OPTIONAL
*"----------------------------------------------------------------------

  IF I_OB_DEPARTAMENTO IS NOT INITIAL.
    OBJ_DEPARTAMENTO = I_OB_DEPARTAMENTO.
  ELSE.
    CREATE OBJECT OBJ_DEPARTAMENTO
      EXPORTING
        I_CD_DEPARTAMENTO = I_CD_DEPARTAMENTO.
  ENDIF.

  CK_CONSULTA         = I_CONSULTA.
  CK_GRAVADO          = ABAP_FALSE.

  PERFORM CADASTRO_DEPARTAMENTO.

  IF CK_GRAVADO EQ ABAP_TRUE OR I_CONSULTA IS NOT INITIAL.
    I_OB_DEPARTAMENTO = OBJ_DEPARTAMENTO.
    I_GRAVOU = ABAP_TRUE.
  ENDIF.

  CLEAR: OBJ_DEPARTAMENTO.

  PERFORM LIMPAR_VARIAVEIS.

  I_GRAVOU = CK_GRAVADO.

ENDFUNCTION.
