FUNCTION ZNFE_CADASTRO_DEPARTAMENTO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_FILTRO) TYPE  ZDE_ZMMT0072_FILTRO
*"  RAISING
*"      ZCX_NFE_INBOUND_EXCEPTION
*"----------------------------------------------------------------------

  DATA: OBJETO        TYPE REF TO ZCL_MM_DEPARTAMENTO,
        IT_ZMMT0072_R TYPE ZDE_ZMMT0072_T.

  CREATE OBJECT OBJETO.

  OBJETO->ZIF_PESQUISA~PESQUISAR( EXPORTING I_FILTROS = I_FILTRO IMPORTING E_REGISTROS = IT_ZMMT0072_R ).
  LOOP AT IT_ZMMT0072_R INTO DATA(WA_ZMMT0072_R).
    APPEND WA_ZMMT0072_R TO IT_ZMMT0072.
  ENDLOOP.
  LC_FILTRO = I_FILTRO.
  CALL SCREEN 0001.

  CLEAR: OBJETO.

ENDFUNCTION.
