PROCESS BEFORE OUTPUT.

  MODULE STATUS_1504.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_1504_EXIT AT EXIT-COMMAND.

  CHAIN.
    FIELD ZDE_NFE_DIST_ITM_PRECO_PED-BRTWR.
    FIELD ZDE_NFE_DIST_ITM_PRECO_PED-BICMS.
    FIELD ZDE_NFE_DIST_ITM_PRECO_PED-PICMS.
    FIELD ZDE_NFE_DIST_ITM_PRECO_PED-BPIS.
    FIELD ZDE_NFE_DIST_ITM_PRECO_PED-PPIS.
    FIELD ZDE_NFE_DIST_ITM_PRECO_PED-BCOFINS.
    FIELD ZDE_NFE_DIST_ITM_PRECO_PED-PCOFINS.
    MODULE ALTEROU_VALOR_PRECO_PED ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_1504.
