PROCESS BEFORE OUTPUT.

  MODULE STATUS_1000.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_1000_EXIT AT EXIT-COMMAND.

  CHAIN.
    FIELD ZMMT0072-CD_DEPARTAMENTO.
    FIELD ZMMT0072-DS_DEPARTAMENTO.
    FIELD ZMMT0072-CK_SEM_RET_GRUPO.
    FIELD ZMMT0072-CK_SEM_RET_PEDIDO.
    MODULE ALTEROU_DEPARTAMENTO ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_1000.
