PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZNOM_TRANSPORTE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZNOM_TRANSPORTE-ID_NOMEACAO_TRAN .
    FIELD ZNOM_TRANSPORTE-NR_ANO .
    FIELD ZNOM_TRANSPORTE-NR_MES .
    FIELD ZNOM_TRANSPORTE-DS_PORTO .
    FIELD ZNOM_TRANSPORTE-DS_TERMINAL .
    FIELD ZNOM_TRANSPORTE-ID_TRANSPORTE .
    FIELD ZNOM_TRANSPORTE-DS_NOME_TRANSPOR .
    FIELD ZNOM_TRANSPORTE-NR_QTDE_NOMEADA .
    FIELD ZNOM_TRANSPORTE-NR_VIAGEM .
    FIELD ZNOM_TRANSPORTE-IN_STATUS_COMEX .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZNOM_TRANSPORTE-ID_NOMEACAO_TRAN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
