PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZNOTA_IMPORT-DOCNUM .
    FIELD ZNOTA_IMPORT-ITMNUM .
    FIELD ZNOTA_IMPORT-ITDIDOC .
    FIELD ZNOTA_IMPORT-NDI .
    FIELD ZNOTA_IMPORT-DDI .
    FIELD ZNOTA_IMPORT-XLOCDESEMB .
    FIELD ZNOTA_IMPORT-UFDESEMB .
    FIELD ZNOTA_IMPORT-DDESEMB .
    FIELD ZNOTA_IMPORT-CEXPORTADOR .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZNOTA_IMPORT-DOCNUM .
    FIELD ZNOTA_IMPORT-ITMNUM .
    FIELD ZNOTA_IMPORT-ITDIDOC .
  module detail_pai.
 endchain.
