PROCESS BEFORE OUTPUT.

 MODULE STATUS_0003.
*
PROCESS AFTER INPUT.

*  CHAIN.
*    FIELD WA_NOTAS-O_VBC.
*    FIELD WA_NOTAS-O_VDESPADU.
*    FIELD WA_NOTAS-O_VII.
*    FIELD WA_NOTAS-O_VIOF.
*  ENDCHAIN.

  MODULE USER_COMMAND_0003.
