PROCESS BEFORE OUTPUT.
  MODULE TB_ZTPARAM.
  MODULE STATUS_0400.
*
PROCESS AFTER INPUT.
  MODULE USER_COMMAND_0400.
*
PROCESS ON VALUE-REQUEST.
  FIELD V_TIPO_ORDEM  MODULE BUSCA_ZVAL. "Tipo de ordem.
