*&---------------------------------------------------------------------*
*& Include ZPM_APONT_MEDIC_EQUIPAM_TOP                       PoolMóds.        ZPM_APONT_MEDIC_EQUIPAM
*&
*&---------------------------------------------------------------------*
PROGRAM ZPM_APONT_MEDIC_EQUIPAM.
*
TABLES: MHIO, EQUI.
*-> Tabelas internas
***********************************************************************
TYPES: BEGIN OF Y_REG,
         POINT TYPE IMPTT-POINT,
         ATNAM TYPE V_MKM_ZU_KLS_BEZ-ATNAM,
         MRNGU TYPE T006A-MSEH3,
         PTTXT TYPE IMPTT-PTTXT,
         LOCAS TYPE IMPTT-LOCAS,
         MRMAC TYPE IMRC_TOTAC,   "RIMR0-MRMAC,
         MRMIC TYPE IMRC_TOTAC,   "RIMR0-MRMIC,
         RDANT TYPE IMRC_TOTAC,
         RDATU TYPE IMRC_TOTAC,
       END OF Y_REG.
*
TYPES: BEGIN OF Y_NOTAS_P,
         WARPL   TYPE MPOS-WARPL,
         QMNUM   TYPE MHIO-QMNUM,
         EQUNR   TYPE EQKT-EQUNR,
         EQKTX   TYPE EQKT-EQKTX,
         OBJNR   TYPE VIQMEL-OBJNR,
         IWERK   TYPE VIQMEL-IWERK,
         MARC(1) TYPE C,
         KOSTL   TYPE ITOB-KOSTL,
       END OF Y_NOTAS_P.
*
TYPES: BEGIN OF Y_NOTAS,
         QMNUM   TYPE MHIO-QMNUM,
         EQUNR   TYPE EQKT-EQUNR,
         EQKTX   TYPE EQKT-EQKTX,
         OBJNR   TYPE VIQMEL-OBJNR,
         IWERK   TYPE VIQMEL-IWERK,
         MARC(1) TYPE C,
       END OF Y_NOTAS.
*
TYPES: BEGIN OF Y_MPOS,
         WAPOS TYPE MPOS-WAPOS,
         WARPL TYPE MPOS-WARPL,
         BAUTL TYPE MPOS-BAUTL,
         QMNUM TYPE MPOS-QMNUM,
         GEWRK TYPE MPOS-GEWRK,
         ARBPL TYPE CRHD-ARBPL,
       END OF Y_MPOS.
*
TYPES: BEGIN OF Y_EQUIP,
         EQUNR   TYPE EQKT-EQUNR,
         EQKTX   TYPE EQKT-EQKTX,
         OBJNR   TYPE VIQMEL-OBJNR,
         IWERK   TYPE VIQMEL-IWERK,
         MARC(1) TYPE C,
       END OF Y_EQUIP.
*
TYPES: BEGIN OF Y_DESCR,
         EQUNR TYPE EQKT-EQUNR,
         EQKTX TYPE EQKT-EQKTX,
       END OF Y_DESCR.
*
TYPES: BEGIN OF Y_JEST,
         OBJNR TYPE JEST-OBJNR,
         STAT  TYPE JEST-STAT,
       END OF Y_JEST.
*
TYPES: BEGIN OF Y_PARAM,
         ZVAL  TYPE ZTPARAM-ZVAL,
         CONST TYPE ZTPARAM-CONST,
       END OF Y_PARAM.

TYPES: BEGIN OF TY_VIQMEL,
         EQUNR TYPE VIQMEL-EQUNR,
         KOSTL TYPE VIQMEL-KOSTL,
       END OF TY_VIQMEL.

TYPES: BEGIN OF

         TY_ORDEM_PREDIT,
         PARAM TYPE ZTPARAM-PARAM,
         WERKS TYPE AUFK-WERKS,
         AUART TYPE AUFK-AUART,
       END OF TY_ORDEM_PREDIT.

TYPES: BEGIN OF TY_ZTPARAM,
         PARAM TYPE ZTPARAM-PARAM,
         ZVAL  TYPE ZTPARAM-ZVAL,
         CONST TYPE ZTPARAM-CONST,
       END OF TY_ZTPARAM.

TYPES: BEGIN OF TY_IMPTT,
         PTTXT TYPE IMPTT-PTTXT,
         LOCAS TYPE IMPTT-LOCAS,
         MRNGU TYPE IMPTT-MRNGU,
         MRMIN TYPE IMPTT-MRMIN,
         MRMAX TYPE IMPTT-MRMAX,
         POINT TYPE IMPTT-POINT,
         MPOBJ TYPE IMPTT-MPOBJ,
         INACT TYPE IMPTT-INACT,
         ATINN TYPE IMPTT-ATINN,
         DECIM TYPE IMPTT-DECIM,
         MPTYP TYPE IMPTT-MPTYP,
       END OF TY_IMPTT.

TYPES: BEGIN OF TY_EQUI,
         EQUNR TYPE EQUI-EQUNR,
         OBJNR TYPE EQUI-OBJNR,
       END OF TY_EQUI.


*
DATA: IT_REG          TYPE TABLE OF Y_REG   WITH HEADER LINE,
      IT_DIMPT        TYPE STANDARD TABLE OF DIIMPT WITH HEADER LINE,
      IT_IMPTT        TYPE STANDARD TABLE OF TY_IMPTT WITH HEADER LINE,
      IT_T006A        TYPE STANDARD TABLE OF T006A WITH HEADER LINE,
      IT_CABN        TYPE STANDARD TABLE OF CABN  WITH HEADER LINE,
      IT_RET_DI       LIKE BAPIRET2 OCCURS 0,
      IT_MPOS         TYPE TABLE OF Y_MPOS  WITH HEADER LINE,
      IT_NOTAS_P      TYPE TABLE OF Y_NOTAS_P WITH HEADER LINE,
      IT_NOTAS        TYPE TABLE OF Y_NOTAS WITH HEADER LINE,
      IT_EQUI         TYPE TABLE OF TY_EQUI WITH HEADER LINE,
      IT_JEST         TYPE TABLE OF Y_JEST  WITH HEADER LINE,
      IT_EQUIP        TYPE TABLE OF Y_EQUIP WITH HEADER LINE,
      IT_VIQMEL       TYPE TABLE OF TY_VIQMEL WITH HEADER LINE,
      IT_DESCR        TYPE TABLE OF Y_DESCR WITH HEADER LINE,
      IT_RETURN       TYPE TABLE OF DDSHRETVAL,
      IT_PARAM        TYPE TABLE OF Y_PARAM WITH HEADER LINE,
      WA_VALUE        TYPE IMRG,
      WA_RETURN       LIKE LINE OF  IT_RETURN,
      VL_VAPLZ        TYPE AUFK-VAPLZ,
      IT_ORDEM_PREDIT TYPE TABLE OF TY_ORDEM_PREDIT WITH HEADER LINE,
      IT_TP_ORDER     TYPE TABLE OF TY_ORDEM_PREDIT WITH HEADER LINE,
      IT_V_AUART      TYPE STANDARD TABLE OF V_AUART,
      IT_ZTPARAM      TYPE TABLE OF TY_ZTPARAM,
      WA_ZTPARAM      TYPE TY_ZTPARAM.

* Tabelas usadas no Batch Input
DATA: T_BDCDATA    TYPE STANDARD TABLE OF BDCDATA WITH HEADER LINE,
      T_MESSAGE    TYPE STANDARD TABLE OF BDCMSGCOLL WITH HEADER LINE,
      T_AC_MESSAGE LIKE TLINE OCCURS 0 WITH HEADER LINE.
*
* Variáveis de tela
DATA: V_DATA     TYPE MHIO-ADDAT,
      V_HR_TELA  TYPE MHIO-ADTIME,
      V_TIPOBJ   TYPE EQUI-EQART,
      V_DESCRSAP TYPE T370K_T-EARTX,
      V_WARPL    TYPE MHIO-WARPL,
      V_PRIOK    TYPE CAUFVD-PRIOK,
      V_VAPLZ    TYPE CAUFVD-VAPLZ,
      V_QMNUM    TYPE MHIO-QMNUM,
      V_IWERK    TYPE VIQMEL-IWERK,
      V_EQUNR    TYPE VIQMEL-EQUNR,
      V_PLTXT    TYPE IFLO-PLTXT,
      V_KOSTL    TYPE VIQMEL-KOSTL.


* Variáveis programa
DATA: LV_CODE       TYPE QCODE,
      LV_VALOR      TYPE IMRC_TOTAC,
      LV_STATUS     TYPE BSVX-STTXT,
      LV_VALUE      TYPE RIMR0-RECDC,
      LV_CONT       TYPE RIHIMRG-PYEAC,
      LV_OBJNR      TYPE VIQMEL-OBJNR,
      LV_IMRC_MDOCM TYPE IMRC_MDOCM,
      LV_MODE(1)    TYPE C VALUE 'N',
      LV_DESVIO     TYPE ZE_DESVIO.

DATA: TP_ORDEM     TYPE AUFK-AUART,
      V_TIPO_ORDEM TYPE AUFK-AUART.

DATA: TL_RETURN_TAB TYPE TABLE OF DDSHRETVAL WITH HEADER LINE,
      TL_DSELC      TYPE TABLE OF DSELC      WITH HEADER LINE.
*
* Constantes
CONSTANTS: LC_FPN(8)       VALUE 'FPN-0010',
           LC_BACK(4)      VALUE 'BACK',
           LC_EXIT(4)      VALUE 'EXIT',
           LC_CANC(4)      VALUE 'CANC',
           LC_CRIA(9)      VALUE 'BTN_APONT',
           LC_SAVEP(10)    VALUE 'BTN_SALVAR',
           LC_SAVE(4)      VALUE 'SAVE',
           LC_ZPM3         VALUE 'ZPM3',
           LC_OS_PREDIT(9) VALUE 'OS_PREDIT',
           LC_REFNUMBER(6) VALUE '000001',
           LC_HEADER(6)    VALUE 'HEADER',
           LC_METHOD(6)    VALUE 'CREATE',
           LC_I0068(5)     VALUE 'I0068',    "MSPN
           LC_I0070(5)     VALUE 'I0070',    "MSPR
*           LC_OBJECTKEY(12)  VALUE '%00000000001',
*           LC_OPERATION(9)   VALUE 'OPERATION',
*           LC_OBJECTLIST(10) VALUE 'OBJECTLIST',
*           LC_COMPONENT(10)  VALUE 'COMPONENT',
           LC_IWO_BAPI2(9) VALUE 'IWO_BAPI2',
           LC_VOLT(6)      VALUE 'VOLTAR',
           LC_MSPN(4)      VALUE 'MSPN',
           LC_MSPR(4)      VALUE 'MSPR',
           LC_IW34(4)      VALUE 'IW34',
           LC_IW(2)        VALUE 'IW',
           LC_085(3)       VALUE '085',
           LC_P(1)         VALUE 'P',
           LC_X(1)         VALUE 'X',
           LC_S(1)         VALUE 'S'.

DATA: IT_METHODS      TYPE TABLE OF BAPI_ALM_ORDER_METHOD,
      IT_HEADER       TYPE TABLE OF BAPI_ALM_ORDER_HEADERS_I,
      IT_OPERATION    TYPE TABLE OF BAPI_ALM_ORDER_OPERATION,
      IT_OPERATION_UP TYPE TABLE OF BAPI_ALM_ORDER_OPERATION_UP,
      IT_METHODS_     TYPE TABLE OF BAPI_ALM_ORDER_METHOD,
      IT_HEADER_      TYPE TABLE OF BAPI_ALM_ORDER_HEADERS_I,
      IT_OPERATION_   TYPE TABLE OF BAPI_ALM_ORDER_OPERATION,
      IT_RETURN_      TYPE TABLE OF BAPIRET2 WITH HEADER LINE,
      IT_RETURN_2     TYPE TABLE OF BAPIRET2 WITH HEADER LINE,
      IT_NOTIFICATION TYPE STANDARD TABLE OF BAPI2080_1.

DATA: WA_METHODS            TYPE BAPI_ALM_ORDER_METHOD,
      WA_HEADER             TYPE BAPI_ALM_ORDER_HEADERS_I,
      WA_OPERATION          TYPE BAPI_ALM_ORDER_OPERATION,
      WA_METHODS_           TYPE BAPI_ALM_ORDER_METHOD,
      WA_HEADER_            TYPE BAPI_ALM_ORDER_HEADERS_I,
      WA_OPERATION_         TYPE BAPI_ALM_ORDER_OPERATION,
      WA_DATA_GENERAL       TYPE BAPI_ITOB,
      WA_DATA_GENERALX      TYPE BAPI_ITOBX,
      WA_DATA_SPECIFIC      TYPE BAPI_ITOB_EQ_ONLY,
      WA_DATA_SPECIFICX     TYPE BAPI_ITOB_EQ_ONLYX,
      WA_RETURN_BAPI_EQMT   TYPE BAPIRETURN,
      WA_RETURN_            TYPE BAPIRET2,
      WA_RETURN_2           TYPE BAPIRET2,
      WA_NOTIFHEADER_EXPORT TYPE BAPI2080_NOTHDRE,
      WA_NOTIFHEADER        TYPE BAPI2080_NOTHDRI,
      WA_PLKO               TYPE PLKO,
      WA_SYSSTAT            TYPE BAPI2080_NOTSTI.

DATA:     AT_NUMERO_ORDEM         TYPE CHAR12,
          AT_NUMERO_ORDEM_REMONTA TYPE CHAR12,
          AT_NUMERO_ORDEM_ABASTEC TYPE CHAR12,
          AT_ID_EQUIPMENT         TYPE NUM8.

DATA: SHORT_TEXT              TYPE CHAR40.
DATA: CONT                    TYPE N LENGTH 4.
