PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'CRL_NOTAS'
  MODULE CRL_NOTAS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE CRL_NOTAS_CHANGE_COL_ATTR.
  LOOP AT   IT_NOTAS
       WITH CONTROL CRL_NOTAS
       CURSOR CRL_NOTAS-CURRENT_LINE.
    MODULE CRL_NOTAS_GET_LINES.
*&SPWIZARD:   MODULE CRL_NOTAS_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE STATUS_0200.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'CRL_NOTAS'
  LOOP AT IT_NOTAS.
    CHAIN.
      FIELD IT_NOTAS-QMNUM.
      FIELD IT_NOTAS-EQUNR.
      FIELD IT_NOTAS-EQKTX.
    endchain.
    FIELD IT_NOTAS-MARC
      MODULE CRL_NOTAS_MARK ON REQUEST.
  ENDLOOP.
  MODULE CRL_NOTAS_USER_COMMAND.
*&SPWIZARD: MODULE CRL_NOTAS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE CRL_NOTAS_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0200.
