*&---------------------------------------------------------------------*
*& Include ZPM_VIEW_10_SAAFTOP                               PoolMóds.        ZPM_VIEW_10_SAAF
*&
*&---------------------------------------------------------------------*
PROGRAM ZPM_VIEW_10_SAAF.
*
*-> Tabelas internas
***********************************************************************
TABLES: ZTPM_VEI_OP_SAAF.
*
TYPES: BEGIN OF Y_VIEW,
         MARC     TYPE C,
         EQART    TYPE ZTPM_VEI_OP_SAAF-EQART,
         EARTX    TYPE ZTPM_VEI_OP_SAAF-EARTX,
         TYPBZ    TYPE ZTPM_VEI_OP_SAAF-TYPBZ,
         CODE     TYPE ZTPM_VEI_OP_SAAF-CODE,
         KURZTEXT TYPE ZTPM_VEI_OP_SAAF-KURZTEXT,
         CONSUMO  TYPE ZTPM_VEI_OP_SAAF-CONSUMO,
         DESVIO   TYPE ZTPM_VEI_OP_SAAF-DESVIO,
       END OF Y_VIEW.
*
TYPES: BEGIN OF Y_CODE,
         CODE     TYPE QPCT-CODE,
         KURZTEXT TYPE QPCT-KURZTEXT,
       END OF Y_CODE.
*
TYPES: BEGIN OF Y_EQART,
         EQART TYPE T370K_T-EQART,
         EARTX TYPE T370K_T-EARTX,
       END OF  Y_EQART.
*
TYPES: BEGIN OF Y_TYPBZ,
         TYPBZ TYPE EQUI-TYPBZ,
       END OF  Y_TYPBZ.
*
TYPES: BEGIN OF Y_PARAM,
         ZVAL  TYPE ZTPARAM-ZVAL,
         CONST TYPE ZTPARAM-CONST,
       END OF Y_PARAM.
*
TYPES: BEGIN OF Y_ZVAL,
         ZVAL TYPE EQUI-EQTYP,
       END OF Y_ZVAL.

DATA: T_VIEW    TYPE TABLE OF Y_VIEW WITH HEADER LINE,
      IT_RETURN TYPE TABLE OF DDSHRETVAL,
      WA_RETURN LIKE LINE OF  IT_RETURN,
      IT_ZTPM   LIKE TABLE OF ZTPM_VEI_OP_SAAF WITH HEADER LINE,
      IT_PARAM  TYPE TABLE OF Y_PARAM WITH HEADER LINE,
      IT_ZVAL   TYPE TABLE OF Y_ZVAL WITH HEADER LINE,
      IT_EQART  TYPE TABLE OF Y_EQART WITH HEADER LINE,
      IT_TYPBZ  TYPE TABLE OF Y_TYPBZ WITH HEADER LINE,
      IT_CODE   TYPE TABLE OF Y_CODE WITH HEADER LINE.
*
DATA: V_CODE       TYPE QCODE,
      V_DESC_CODE  TYPE KURZTEXT,
      V_EQART      TYPE EQART,
      V_DESC_EQART TYPE EARTX,
      V_TYPBZ      TYPE TYPBZ,
      V_CONSUMO    TYPE ZE_CONSUMO,
      V_DESVIO     TYPE ZE_DESVIO.
*
* Constantes
CONSTANTS: LC_FPN(8)    VALUE 'FPN-0010',
           LC_TP_OBJ(6) VALUE 'TP_OBJ',
           LC_PT(2)     VALUE 'PT',
           LC_X(1)      VALUE 'X',
           LC_S(1)      VALUE 'S'.
