PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPMT0043 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPMT0043-SUPERIOR .
    FIELD ZPMT0043-NAME .
    FIELD ZPMT0043-EMPRESTADOR .
    FIELD ZPMT0043-NAME1 .
    FIELD ZPMT0043-SUBSTITUTO .
    FIELD ZPMT0043-NAME2 .
    FIELD ZPMT0043-DT_INICIO .
    FIELD ZPMT0043-DT_FIM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPMT0043-SUPERIOR .
    FIELD ZPMT0043-NAME  MODULE GET_NAME.
    FIELD ZPMT0043-EMPRESTADOR .
    FIELD ZPMT0043-NAME1 MODULE GET_NAME1.
    FIELD ZPMT0043-SUBSTITUTO .
    FIELD ZPMT0043-NAME2 MODULE GET_NAME2.
    FIELD ZPMT0043-DT_INICIO .
    FIELD ZPMT0043-DT_FIM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.

MODULE LISTE_AFTER_LOOP.
