PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TABLE_APONT'
  MODULE TABLE_APONT_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TABLE_APONT_CHANGE_COL_ATTR.
  LOOP AT   IT_SAIDA
       INTO WA_SAIDA
       WITH CONTROL TABLE_APONT
       CURSOR TABLE_APONT-CURRENT_LINE.
    MODULE TABLE_APONT_GET_LINES.
*&SPWIZARD:   MODULE TABLE_APONT_CHANGE_FIELD_ATTR
  ENDLOOP.

  MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TABLE_APONT'
  LOOP AT IT_SAIDA.
    CHAIN.
      FIELD WA_SAIDA-AUFNR.
      FIELD WA_SAIDA-EQUNR.
      FIELD WA_SAIDA-EQKTX.
      FIELD WA_SAIDA-KTEXT.
      FIELD WA_SAIDA-DESCR.
      FIELD WA_SAIDA-TOTCC.
      FIELD WA_SAIDA-ZPERC_F.
      FIELD WA_SAIDA-ZPERC_C.
      FIELD WA_SAIDA-VLR_F.
      FIELD WA_SAIDA-VLR_C.
      MODULE TABLE_APONT_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
  ENDLOOP.
  MODULE TABLE_APONT_USER_COMMAND.
*&SPWIZARD: MODULE TABLE_APONT_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TABLE_APONT_CHANGE_COL_ATTR.

  MODULE USER_COMMAND_0100_EXIT AT EXIT-COMMAND.
  MODULE USER_COMMAND_0100.
