PROCESS BEFORE OUTPUT.
 MODULE STATUS_0201.

  LOOP AT T_ABA1
     INTO GS_ABA1
     WITH CONTROL ZABA1
   CURSOR ZABA1-CURRENT_LINE.
  ENDLOOP.
*
PROCESS AFTER INPUT.

  LOOP AT T_ABA1.
    CHAIN.
      FIELD GS_ABA1-EBELP.
      FIELD GS_ABA1-ACCTASSCAT.
      FIELD GS_ABA1-MWSKZ.
      FIELD GS_ABA1-GL_ACCOUNT.
      FIELD GS_ABA1-MATNR.
      FIELD GS_ABA1-DESC_MATERIAL.
      FIELD GS_ABA1-MENGE.
      FIELD GS_ABA1-UND.
      FIELD GS_ABA1-DATA_REMESSA.
      FIELD GS_ABA1-POR.
      FIELD GS_ABA1-VLR_UNT.
      FIELD GS_ABA1-NETPR.
      FIELD GS_ABA1-BRUTO.
      FIELD GS_ABA1-CENTRO.
      FIELD GS_ABA1-MARK.
      MODULE ATUALIZA_ABA1.
      MODULE MARK.
    ENDCHAIN.

  ENDLOOP.
* MODULE USER_COMMAND_0201.
