*&---------------------------------------------------------------------*
*&  Include           ZPMR0042_TOPO
*&---------------------------------------------------------------------*

TABLES: VIAUFKST, AUFK, EQUI, AFVC, COEP, IMRG.

DATA:
  "Informações para 1º ALV.
  G_CONTAINER      TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Conteiner ALV
  CTL_ALV          TYPE REF TO CL_GUI_ALV_GRID,
  GS_VARIANT       TYPE DISVARIANT,
  IT_EXCLUDE_FCODE TYPE UI_FUNCTIONS,
  WA_EXCLUDE_FCODE LIKE LINE OF IT_EXCLUDE_FCODE,
  GS_LAYOUT        TYPE LVC_S_LAYO, "Layout da ALV
  IT_FIELDCATALOG  TYPE LVC_T_FCAT, "Catálogo de campos para controle visor de listas
  WA_FIELDCATALOG  TYPE LVC_S_FCAT, "Controle VLA: catálogo de campos
  IT_SORT          TYPE LVC_T_SORT,
  LS_STABLE        TYPE LVC_S_STBL,
  DG_SPLITTER_1    TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
  DG_PARENT_1      TYPE REF TO CL_GUI_CONTAINER,
  DG_SPLITTER_2    TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
  DG_PARENT_2      TYPE REF TO CL_GUI_CONTAINER,
  DG_PARENT_2A     TYPE REF TO CL_GUI_CONTAINER,
  DG_PARENT_ALV    TYPE REF TO CL_GUI_CONTAINER,
  PICTURE          TYPE REF TO CL_GUI_PICTURE.

DATA: URL(255)                TYPE C,
      P_TEXT                  TYPE SDYDO_TEXT_ELEMENT,
      P_TEXT_2                TYPE SDYDO_TEXT_ELEMENT,
      SDYDO_TEXT_ELEMENT(255),
      VL_CONT                 TYPE I,
      P_TEXT_TABLE            TYPE SDYDO_TEXT_TABLE,
      P_TEXT_TABLE_2          TYPE SDYDO_TEXT_TABLE.

DATA:
  DG_DYNDOC_ID   TYPE REF TO CL_DD_DOCUMENT,
  TABLE_ELEMENT  TYPE REF TO CL_DD_TABLE_ELEMENT,
  COLUMN         TYPE REF TO CL_DD_AREA,
  TABLE_ELEMENT2 TYPE REF TO CL_DD_TABLE_ELEMENT,
  COLUMN_1       TYPE REF TO CL_DD_AREA,
  DG_HTML_CNTRL  TYPE REF TO CL_GUI_HTML_VIEWER.

DATA: FLTP_CHAR     TYPE IMRC_TOTAC.
DATA:  GS_IMRG       TYPE TABLE OF IMRG.
DATA: T_CONTADOR    TYPE CHAR5.

SELECTION-SCREEN BEGIN OF BLOCK A1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: P_IWERK FOR VIAUFKST-IWERK NO-EXTENSION NO INTERVALS OBLIGATORY,
*                P_EQUNR FOR EQUI-EQUNR,
                P_GJAHR FOR COEP-GJAHR NO-EXTENSION NO INTERVALS OBLIGATORY,
                P_PERIO FOR COEP-PERIO NO-EXTENSION OBLIGATORY.
SELECTION-SCREEN: END OF BLOCK A1.

SELECTION-SCREEN BEGIN OF BLOCK A2 WITH FRAME TITLE TEXT-002.
SELECT-OPTIONS: P_KOSTL FOR VIAUFKST-KOSTL NO-EXTENSION NO INTERVALS OBLIGATORY.
SELECTION-SCREEN: END OF BLOCK A2.
