PROCESS BEFORE OUTPUT.
  MODULE: STATUS_0400,
    TS_SET_ACTIVE_TAB.

  CALL SUBSCREEN TS_0100_SCA
     INCLUDING G_TS_0100-PROGRAM G_TS_0100-SUBSCREEN.
*
PROCESS AFTER INPUT.

  CALL SUBSCREEN: TS_0100_SCA.

  MODULE: USER_COMMAND_0400,
          TS_GET_ACTIVE_TAB.
