*&---------------------------------------------------------------------*
*&  Include           ZPPR001VIE
*&---------------------------------------------------------------------*

"// View
CLASS DISPLAY_VIEW DEFINITION INHERITING FROM ZSAPMVC_VIEW.
  PUBLIC SECTION.
    METHODS CHANGE_NOTIFICATION REDEFINITION.

  PRIVATE SECTION.
    DATA MAIN_CONTROLLER TYPE REF TO MAIN_CONTROLLER.
    DATA PRINT_IS_OPEN   TYPE ABAP_BOOL.
ENDCLASS.

CLASS DISPLAY_VIEW IMPLEMENTATION.
  METHOD CHANGE_NOTIFICATION.
    CALL METHOD CL_UTILS=>MESSAGE_PROCESS_INDICATOR
      EXPORTING
        PERCENTAGE = SY-TABIX
        MESSAGE    = TEXT-029.

    CLEAR GT_PLANNINGS.
    CLEAR GW_ORDER.

    SY-UCOMM = 'REFRESH'.
    EDIT_ON  = ABAP_FALSE.

    LEAVE TO SCREEN 0001.
  ENDMETHOD.                    "CHANGE_NOTIFICATION
ENDCLASS.
