PROCESS BEFORE OUTPUT.
  MODULE SCREEN.
  MODULE STATUS_0100.

  CALL SUBSCREEN: SUB01 INCLUDING SY-REPID TELA-TELA1,
                  SUB02 INCLUDING SY-REPID TELA-TELA2,
                  SUB03 INCLUDING SY-REPID TELA-TELA3.
*
PROCESS AFTER INPUT.

  CALL SUBSCREEN: SUB01, SUB02, SUB03.

  MODULE USER_COMMAND_0100.
