PROCESS BEFORE OUTPUT.
  MODULE TBCONTROL_CHANGE_TC_ATTR.

  LOOP AT   GT_SAIDA
       INTO GW_SAIDA
       WITH CONTROL TBCONTROL
       CURSOR TBCONTROL-CURRENT_LINE.
    MODULE TBCONTROL_GET_LINES.
  ENDLOOP.

  MODULE MAIN_PBO.

PROCESS AFTER INPUT.

  LOOP AT GT_SAIDA.
    CHAIN.
      FIELD GW_SAIDA-MATNR.
      FIELD GW_SAIDA-BDMNG.
      FIELD GW_SAIDA-MAKTX.
      FIELD GW_SAIDA-LGORT.
      MODULE TBCONTROL_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
    FIELD GW_SAIDA-MARK
      MODULE TBCONTROL_MARK ON REQUEST.
  ENDLOOP.
  MODULE TBCONTROL_USER_COMMAND.

  MODULE MAIN_PAI.

PROCESS ON VALUE-REQUEST.
  FIELD SOLICITACAO-SOLDF MODULE HELP_ID.
