*&---------------------------------------------------------------------*
*&  Include           ZPPR001TOP
*&---------------------------------------------------------------------*
REPORT ZPPR001 MESSAGE-ID ZPPM001.

TABLES: VBAP, VBAK.
TYPE-POOLS COL.

"// Types
TYPES:
  BEGIN OF TY_ORDENS,
    ORDEM                   TYPE VBEP-VBELN,
    ITEM                    TYPE VBAP-POSNR,
    CENTRO                  TYPE VBAP-WERKS,
    EMISSOR                 TYPE STRING,
    MATERIAL                TYPE STRING,
    QTD_ORDEM_VENDA         TYPE P LENGTH 13,
    QTD_DISPONIVEL_PRODUCAO TYPE P LENGTH 13,
    QTD_PLANEJADA           TYPE P LENGTH 13,
    QTD_DISPONIVEL          TYPE P LENGTH 13,
    QTD_CARREGADA           TYPE P LENGTH 13,
    QTD_FATURADA            TYPE P LENGTH 13,
    QTD_EM_ANDAMENTO        TYPE P LENGTH 13,
    QTD_EM_TRANSITO         TYPE P LENGTH 13,
  END OF TY_ORDENS,

  BEGIN OF TY_PLANNING,
    VBELN         TYPE ZPPT0008-VBELN,
    POSNR         TYPE ZPPT0008-POSNR,
    EDATU         TYPE ZPPT0008-EDATU,
    WMENG         TYPE ZPPT0008-WMENG,
    WCARR         TYPE ZPPT0008-WMENG,
    WDISP         TYPE ZPPT0008-WDISP,
    CREATED_BY    TYPE ZPPT0008-CREATEDBY,
    CHANGED_BY    TYPE ZPPT0008-CHANGEDBY,
    CREATED_DT    TYPE ZPPT0008-CREATEDDT,
    CHANGED_DT    TYPE ZPPT0008-CHANGEDDT,
    STYLE         TYPE LVC_T_STYL,
    IOPUS         TYPE CHAR4,
    STATUS_TEXT   TYPE ICON-ID,
    QTD_CAMINHOES TYPE STRING,
    T_SHIPMENTS   TYPE ZPPCT002,
    T_TRANSITS    TYPE ZPPCT003,
  END OF TY_PLANNING,

  BEGIN OF TY_QUANTITY,
    RELEASED  TYPE WMENG,
    AVAILABLE TYPE WMENG,
    PLANNED   TYPE WMENG,
    LOADED    TYPE WMENG,
    WATING    TYPE WMENG,
  END OF TY_QUANTITY,

  BEGIN OF TY_EDITOR,
    LINE(100),
  END OF TY_EDITOR,

  BEGIN OF TY_SOLICITATION,
    NRO_SOL     TYPE ZSDT0082-NRO_SOL,
    SEQ_LIB     TYPE ZSDT0082-SEQ_LIB,
    DT_LIBER    TYPE ZSDT0082-DT_LIBER,
    USUARIO_LIB TYPE ZSDT0082-USUARIO_LIB,
    QTE_LIB     TYPE ZSDT0082-QTE_LIB,
    DT_ENTREGA  TYPE ZSDT0082-DT_ENTREGA,
  END OF TY_SOLICITATION,

  BEGIN OF TY_ETIQUETA,
    TEXTO          TYPE STRING,
    QTD_ADICIONAIS TYPE I,
  END OF TY_ETIQUETA,

  BEGIN OF TY_SHIPMENTS,
    PLACA       TYPE ZPPET001-PLACA,
    ORDEMCARREG TYPE ZPPET001-ORDEMCARREG,
    AUFNR       TYPE ZPPET001-AUFNR,
    PSMNG       TYPE ZPPET001-PSMNG,
    WEMNG       TYPE ZPPET001-WEMNG,
    ERDAT       TYPE ZPPET001-ERDAT,
    TXT04       TYPE ZPPET001-TXT04,
    TXT30       TYPE ZPPET001-TXT30,
    ROWCOLOR(4) TYPE C.
TYPES: END OF TY_SHIPMENTS,


TY_T_PLANNING          TYPE TABLE OF TY_PLANNING     WITH DEFAULT KEY,
  TY_T_SOLICITATION      TYPE TABLE OF TY_SOLICITATION WITH KEY NRO_SOL SEQ_LIB,
  TY_T_SHIPMENTS         TYPE TABLE OF TY_SHIPMENTS    WITH DEFAULT KEY,
  TY_T_SHIPMENTS_TRANSIT TYPE TABLE OF ZPPT0009 WITH DEFAULT KEY.

"// Tables
DATA GW_ORDER       TYPE TY_ORDENS.
DATA GW_ETIQUETA    TYPE TY_ETIQUETA.
DATA GT_ORDENS      TYPE TABLE OF TY_ORDENS.
DATA GT_SHIPMENTS   TYPE TABLE OF TY_SHIPMENTS.
DATA GT_ORDEM_OPUS  TYPE TABLE OF ZSDT0001OD.
DATA GT_PLANNINGS   TYPE TABLE OF TY_PLANNING.
DATA NODES          TYPE LVC_T_NKEY.

"// Objects
*DATA MODEL_NOTIFICATION TYPE REF TO ZSAPMVC_MODEL.
*DATA VIEW_NOTIFICATION  TYPE REF TO ZIF_SAPMVC_VIEW.

DATA VIEW              TYPE REF TO ZIF_SAPMVC_VIEW.
DATA CONTROLLER        TYPE REF TO ZIF_SAPMVC_CONTROLLER.
DATA EXCEPTION         TYPE REF TO ZCX_SAPMVC.

"// Datas
DATA SUBSCREEN_DISPLAY TYPE SY-DYNNR.
DATA DYNPRO            TYPE SY-DYNNR.
DATA PROGRAM           TYPE SY-REPID.
DATA CELL              TYPE LVC_S_CELL.
DATA FIELD             TYPE CHAR30.
DATA STATUS_ERROR      TYPE CHAR30.
DATA NUMBER_FRAGMENTS  TYPE NUMC10.
DATA DIALOG_IS_OPEN    TYPE ABAP_BOOL.
DATA EDIT_ON           TYPE ABAP_BOOL.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
SELECT-OPTIONS: S_VBELN FOR VBAP-VBELN,            "N. OV
                S_DTLIB FOR SY-DATUM   OBLIGATORY, "Data Liberação
                S_WERKS FOR VBAP-WERKS OBLIGATORY, "Centro
                S_KUNNR FOR VBAK-KUNNR,            "Emissor da Ordem
                S_MATNR FOR VBAP-MATNR.            "Material
SELECTION-SCREEN END OF BLOCK B1.

START-OF-SELECTION.
  CALL SCREEN 0001.
