*&---------------------------------------------------------------------*
*& Report  ZRD_ZFIYT0034_EXIT
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZRD_ZFIYT0034_EXIT.

FORM F_EXIT_ZFIYT0034_0001 CHANGING P_REGISTRO_MANTER TYPE ANY.

  DATA: WL_ZFIYT0034 TYPE ZFIYT0034.

  CLEAR: WL_ZFIYT0034.

  WL_ZFIYT0034-DT_REGISTRO = SY-DATUM.
  WL_ZFIYT0034-HR_REGISTRO = SY-UZEIT.
  WL_ZFIYT0034-US_REGISTRO = SY-UNAME.

  MOVE-CORRESPONDING WL_ZFIYT0034 TO P_REGISTRO_MANTER.

ENDFORM.
FORM F_EXIT_ZFIYT0034_0002 USING P_REGISTRO_MANTER TYPE ANY
                       CHANGING P_ERROR.

  DATA: WL_ZFIYT0034 TYPE ZFIYT0034.

  CLEAR: WL_ZFIYT0034.

  MOVE-CORRESPONDING P_REGISTRO_MANTER TO WL_ZFIYT0034.

  CLEAR: P_ERROR.

  IF WL_ZFIYT0034-COD_FECHTO IS INITIAL.
    P_ERROR = ABAP_TRUE.
    MESSAGE 'Código Obrigatório!' TYPE 'S'.
    EXIT.
  ENDIF.

    IF WL_ZFIYT0034-DESCR_FECHTO IS INITIAL.
    P_ERROR = ABAP_TRUE.
    MESSAGE 'Descrição Fechamento Cambio Obrigatório!' TYPE 'S'.
    EXIT.
  ENDIF.

ENDFORM.

FORM F_EXIT_ZFIYT0034_0003 CHANGING P_REGISTRO_MANTER TYPE ANY.

  DATA: WL_ZFIYT0034 TYPE ZFIYT0034.

  CLEAR: WL_ZFIYT0034.

  MOVE-CORRESPONDING P_REGISTRO_MANTER TO WL_ZFIYT0034.

  WL_ZFIYT0034-DT_REGISTRO = SY-DATUM.
  WL_ZFIYT0034-HR_REGISTRO = SY-UZEIT.
  WL_ZFIYT0034-US_REGISTRO = SY-UNAME.

  MOVE-CORRESPONDING WL_ZFIYT0034 TO P_REGISTRO_MANTER.

ENDFORM.

FORM F_EXIT_ZFIYT0034_0004 CHANGING P_SAIDA TYPE ANY.

  DATA: WL_ZFIYT0034_OUT TYPE ZFIYT0034_OUT.

  CLEAR: WL_ZFIYT0034_OUT.

  MOVE-CORRESPONDING P_SAIDA TO WL_ZFIYT0034_OUT.


  MOVE-CORRESPONDING WL_ZFIYT0034_OUT TO P_SAIDA.

ENDFORM.
