*&---------------------------------------------------------------------*
*& Report  ZRD_ZFIT0150_EXIT
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZRD_ZLEST0206_EXIT.

FORM F_EXIT_ZLEST0206_0005 CHANGING P_REGISTRO_MANTER TYPE ANY.

  DATA: WA_ZLEST0206_AUX TYPE ZDE_ZLEST0206.

  MOVE-CORRESPONDING P_REGISTRO_MANTER TO WA_ZLEST0206_AUX.

  CLEAR: WA_ZLEST0206_AUX-DESCRICAO,
         WA_ZLEST0206_AUX-NAME1.

  IF WA_ZLEST0206_AUX-LOCAL_DESCARGA IS NOT INITIAL.

    SELECT SINGLE * INTO @DATA(WA_ZLEST0104)
      FROM ZLEST0104
     WHERE LOCAL_DESCARGA EQ @WA_ZLEST0206_AUX-LOCAL_DESCARGA.

    IF SY-SUBRC IS INITIAL.
      WA_ZLEST0206_AUX-DESCRICAO = WA_ZLEST0104-DESCRICAO.
    ENDIF.

  ENDIF.

  IF WA_ZLEST0206_AUX-PO_EMBARQUE IS NOT INITIAL.

    SELECT SINGLE * INTO @DATA(WA_LFA1)
      FROM LFA1
     WHERE LIFNR EQ @WA_ZLEST0206_AUX-PO_EMBARQUE.

    IF SY-SUBRC IS INITIAL.
      WA_ZLEST0206_AUX-NAME1 = WA_LFA1-NAME1.
    ENDIF.

  ENDIF.

  MOVE-CORRESPONDING WA_ZLEST0206_AUX TO P_REGISTRO_MANTER.

ENDFORM.

FORM F_EXIT_ZLEST0206_0007 TABLES P_TABLE.

  DATA: IT_ZLEST0206 TYPE TABLE OF ZDE_ZLEST0206.

  CHECK P_TABLE[] IS NOT INITIAL.

  IT_ZLEST0206[] = P_TABLE[].

  SELECT * INTO TABLE @DATA(IT_ZLEST0104)
    FROM ZLEST0104
     FOR ALL ENTRIES IN @IT_ZLEST0206
   WHERE LOCAL_DESCARGA EQ @IT_ZLEST0206-LOCAL_DESCARGA.

  SORT IT_ZLEST0104 BY LOCAL_DESCARGA.

  SELECT * INTO TABLE @DATA(IT_LFA1)
 FROM LFA1
 FOR ALL ENTRIES IN @IT_ZLEST0206
 WHERE LIFNR EQ @IT_ZLEST0206-PO_EMBARQUE
 ORDER BY PRIMARY KEY .

  LOOP AT IT_ZLEST0206 ASSIGNING FIELD-SYMBOL(<FS_ZLEST0206>) .

    READ TABLE IT_ZLEST0104
    WITH KEY LOCAL_DESCARGA = <FS_ZLEST0206>-LOCAL_DESCARGA
    BINARY SEARCH INTO DATA(WA_ZLEST0206).

    IF SY-SUBRC IS INITIAL.
      <FS_ZLEST0206>-DESCRICAO = WA_ZLEST0206-DESCRICAO.
    ENDIF.

    READ TABLE IT_LFA1
    WITH KEY LIFNR = <FS_ZLEST0206>-PO_EMBARQUE
    BINARY SEARCH INTO DATA(WA_LFA1).

    IF SY-SUBRC IS INITIAL.
      <FS_ZLEST0206>-NAME1 = WA_LFA1-NAME1.
    ENDIF.

  ENDLOOP.

  P_TABLE[] = IT_ZLEST0206[].

ENDFORM.
