*&---------------------------------------------------------------------*
*& Report  ZRD_ZMMT0112_EXIT
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZRD_ZMMT0112_EXIT.

FORM F_EXIT_ZMMT0112_0001 CHANGING P_REGISTRO_MANTER TYPE ANY.

  DATA: WL_ZMMT0112 TYPE ZMMT0112.

  CLEAR: WL_ZMMT0112.

  WL_ZMMT0112-DATA = SY-DATUM.
  WL_ZMMT0112-HORA = SY-UZEIT.
  WL_ZMMT0112-USUARIO = SY-UNAME.

  MOVE-CORRESPONDING WL_ZMMT0112 TO P_REGISTRO_MANTER.

ENDFORM.

FORM F_EXIT_ZMMT0112_0002 USING P_REGISTRO_MANTER TYPE ANY
                       CHANGING P_ERROR.

  DATA: WL_ZMMT0112 TYPE ZMMT0112.

  CLEAR: WL_ZMMT0112.

  MOVE-CORRESPONDING P_REGISTRO_MANTER TO WL_ZMMT0112.

  CLEAR: P_ERROR.

  IF WL_ZMMT0112-JUSTIFICA IS INITIAL.
    P_ERROR = ABAP_TRUE.
    MESSAGE 'Informe a justificativa!' TYPE 'S'.
    EXIT.
  ENDIF.


ENDFORM.
