*&---------------------------------------------------------------------*
*& Report  ZRD_ZFIT0165_EXIT
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZRD_ZFIT0165_EXIT.

FORM F_EXIT_ZFIT0165_0001 CHANGING P_REGISTRO_MANTER TYPE ANY.

  DATA: WL_ZFIT0165 TYPE ZFIT0165.

  CLEAR: WL_ZFIT0165.

  WL_ZFIT0165-DT_REGISTRO = SY-DATUM.
  WL_ZFIT0165-HR_REGISTRO = SY-UZEIT.
  WL_ZFIT0165-US_REGISTRO = SY-UNAME.

  MOVE-CORRESPONDING WL_ZFIT0165 TO P_REGISTRO_MANTER.

ENDFORM.

FORM F_EXIT_ZFIT0165_0002 USING P_REGISTRO_MANTER TYPE ANY
                       CHANGING P_ERROR.

  DATA: WL_ZFIT0165 TYPE ZFIT0165.

  CLEAR: WL_ZFIT0165.

  MOVE-CORRESPONDING P_REGISTRO_MANTER TO WL_ZFIT0165.

  CLEAR: P_ERROR.

  IF WL_ZFIT0165-SOURCE_CODE IS INITIAL.
    P_ERROR = ABAP_TRUE.
    MESSAGE 'Source Code é um campo obrigatório!' TYPE 'S'.
    EXIT.
  ENDIF.

ENDFORM.

FORM F_EXIT_ZFIT0165_0003 CHANGING P_REGISTRO_MANTER TYPE ANY.

  DATA: WL_ZFIT0165 TYPE ZFIT0165.

  CLEAR: WL_ZFIT0165.

  MOVE-CORRESPONDING P_REGISTRO_MANTER TO WL_ZFIT0165.

  WL_ZFIT0165-DT_REGISTRO = SY-DATUM.
  WL_ZFIT0165-HR_REGISTRO = SY-UZEIT.
  WL_ZFIT0165-US_REGISTRO = SY-UNAME.

  MOVE-CORRESPONDING WL_ZFIT0165 TO P_REGISTRO_MANTER.

ENDFORM.

FORM F_EXIT_ZFIT0165_0004 CHANGING P_SAIDA TYPE ANY.

  DATA: WL_ZFIT0165_OUT TYPE ZFIT0165_OUT.

  CLEAR: WL_ZFIT0165_OUT.

  MOVE-CORRESPONDING P_SAIDA TO WL_ZFIT0165_OUT.

  "WL_ZFIT0165_OUT-BUTXT = ''.

  MOVE-CORRESPONDING WL_ZFIT0165_OUT TO P_SAIDA.

ENDFORM.
