PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZREG_EXPORTACAO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZREG_EXPORTACAO-ID_REGISTRO_EXPO .
    FIELD ZREG_EXPORTACAO-NR_REGISTRO_EXPO .
    FIELD ZREG_EXPORTACAO-ID_EXPORTADOR .
    FIELD ZREG_EXPORTACAO-ID_IMPORTADOR .
    FIELD ZREG_EXPORTACAO-CD_MATERIAL .
    FIELD ZREG_EXPORTACAO-DT_REGISTRO_EXPO .
    FIELD ZREG_EXPORTACAO-NR_QTDE .
    FIELD ZREG_EXPORTACAO-NR_VALOR_TM .
    FIELD ZREG_EXPORTACAO-NR_VALOR_TOTAL .
    FIELD ZREG_EXPORTACAO-ID_REGISTRO_VEND .
    FIELD ZREG_EXPORTACAO-ID_NOMEACAO_TRAN .
    FIELD ZREG_EXPORTACAO-IN_PERFORMANCE .
    FIELD ZREG_EXPORTACAO-IN_STATUS_COMEX .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZREG_EXPORTACAO-ID_REGISTRO_EXPO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
