FUNCTION Z_REPOM_MONITOR_PEDAGIO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_INCLUIR) TYPE  CHAR01
*"     REFERENCE(I_TKNUM) TYPE  TKNUM
*"     REFERENCE(I_VTTKVB) TYPE  VTTKVB OPTIONAL
*"     REFERENCE(I_CD_CID_ORIGEM) TYPE  ZDE_CIDADE_ORIGEM OPTIONAL
*"     REFERENCE(I_CD_CID_DESTINO) TYPE  ZDE_CIDADE_DESTINO OPTIONAL
*"     REFERENCE(I_QTD_EIXOS) TYPE  ZQT_EIXO OPTIONAL
*"  EXPORTING
*"     REFERENCE(E_ID_PROC_CLIENTE) TYPE  ZDE_ID_PROC_CLIENTE
*"     REFERENCE(E_AUTORIZADO) TYPE  CHAR01
*"  EXCEPTIONS
*"      NAO_ENCONTRADO
*"----------------------------------------------------------------------

  DATA: IT_ZLEST0123 TYPE TABLE OF ZLEST0123 WITH HEADER LINE.

  DATA: I_FILTROS   TYPE ZDE_ZLEST0123_FILTRO.

  DATA: P_GRAVOU    TYPE CHAR01.

  CLEAR: IT_ZLEST0123_ALV[], I_FILTROS, E_AUTORIZADO, P_GRAVOU.

  IF I_INCLUIR EQ ABAP_TRUE.
    E_ID_PROC_CLIENTE =
      ZCL_REPOM_VIAGEM_VPR=>CRIAR_VIAGEM(
                               EXPORTING
                                 I_TKNUM          = I_TKNUM
                                 I_VTTKVB         = I_VTTKVB
                                 I_CD_CID_ORIGEM 	= I_CD_CID_ORIGEM
                                 I_CD_CID_DESTINO	= I_CD_CID_DESTINO
                                 "I_QTD_EIXOS      = I_QTD_EIXOS
                               IMPORTING
                                 E_GRAVOU = P_GRAVOU ).
  ELSE.
    CALL METHOD ZCL_REPOM_VIAGEM_VPR=>GET_ID_PROC_CLIENTE_VT
      EXPORTING
        I_TKNUM           = I_TKNUM
      RECEIVING
        E_ID_PROC_CLIENTE = E_ID_PROC_CLIENTE
      EXCEPTIONS
        NAO_ENCONTRADO    = 1
        OTHERS            = 2.

    CASE SY-SUBRC.
      WHEN 0.
        P_GRAVOU = ABAP_TRUE.
      WHEN 1 OR 2.
        MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING NAO_ENCONTRADO.
    ENDCASE.

  ENDIF.

  CHECK P_GRAVOU EQ ABAP_TRUE.

  "PERFORM CHAMA_MONITOR(SAPMZREPOM) USING P_ID_PROC_CLIENTE.
  I_FILTROS-ID_PROC_CLIENTE = VALUE #( ( SIGN = 'I' OPTION = 'EQ' LOW = E_ID_PROC_CLIENTE HIGH = E_ID_PROC_CLIENTE ) ).

  CALL FUNCTION 'Z_REPOM_CHAMA_MONITOR'
    EXPORTING
      I_FILTROS    = I_FILTROS
      I_INDIVIDUAL = ABAP_TRUE.

  E_AUTORIZADO = ZCL_REPOM_VIAGEM_VPR=>GET_AUTORIZADO( EXPORTING I_ID_PROC_CLIENTE = E_ID_PROC_CLIENTE ).

ENDFUNCTION.
