PROCESS BEFORE OUTPUT.

  MODULE STATUS_0100.
*
PROCESS AFTER INPUT.

  CHAIN.
    FIELD ZDE_ZLEST0121_ALV-BUKRS.
    FIELD ZDE_ZLEST0121_ALV-BUTXT.
    FIELD ZDE_ZLEST0121_ALV-BRANCH.
    FIELD ZDE_ZLEST0121_ALV-NAME.
    FIELD ZDE_ZLEST0121_ALV-CD_CID_ORIGEM.
    FIELD ZDE_ZLEST0121_ALV-DS_CID_ORIGEM.
    FIELD ZDE_ZLEST0121_ALV-CD_CID_DESTINO.
    FIELD ZDE_ZLEST0121_ALV-DS_CID_DESTINO.
    FIELD ZDE_ZLEST0121_ALV-TP_PROC_TRANSP.
    FIELD ZDE_ZLEST0121_ALV-TP_IDA_VOLTA.
    FIELD ZDE_ZLEST0121_ALV-DS_OBSERVACAO.
    FIELD ZDE_ZLEST0121_ALV-TP_ST_ROTA.
    FIELD ZDE_ZLEST0121_ALV-CK_ATIVO.
    MODULE ALTEROU_ATRIBUTOS ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0100_EXIT AT EXIT-COMMAND.

  MODULE USER_COMMAND_0100.
