FUNCTION Z_REPOM_VALIDA_CARTAO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_CARTAO) TYPE  ZDE_REPOM_CARTAO
*"  EXPORTING
*"     REFERENCE(E_VALIDO) TYPE  CHAR01
*"     REFERENCE(E_ERROS) TYPE  ZDE_REPOM_ERROS_T
*"  EXCEPTIONS
*"      ERRO
*"----------------------------------------------------------------------

  DATA: OBJETO TYPE REF TO ZCL_REPOM_CARTAO.

  CREATE OBJECT OBJETO
    EXPORTING
      I_NR_CARTAO = I_CARTAO-NR_CARTAO.

  OBJETO->SET_BUKRS( EXPORTING I_BUKRS = I_CARTAO-BUKRS ).

  OBJETO->SET_BRANCH( EXPORTING I_BRANCH = I_CARTAO-BRANCH ).

  CALL METHOD OBJETO->CONSULTAR_VALIDADE_CARTAO
    IMPORTING
      E_ERROS                    = E_ERROS
    RECEIVING
      I_VALIDOU                  = E_VALIDO
    EXCEPTIONS
      SERVICO_NAO_ENCONTRADO     = 1
      HTTP_COMMUNICATION_FAILURE = 2
      HTTP_INVALID_STATE         = 3
      HTTP_PROCESSING_FAILED     = 4
      HTTP_INVALID_TIMEOUT       = 5
      ERRO                       = 6
      OTHERS                     = 7.

  IF SY-SUBRC IS NOT INITIAL.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING ERRO.
  ENDIF.

  CLEAR: OBJETO.

ENDFUNCTION.
