FUNCTION-POOL ZREPOM.                       "MESSAGE-ID ..

* INCLUDE LZREPOMD...                        " Local class definition

TABLES: ZLEST0121, ZDE_ZLEST0121_ALV, ZDE_REPOM_CARTAO, ZDE_ZLEST0123_ALV, ZLEST0124,
        ZDE_ZLEST0122_ALV.

DATA: CK_ALTEROU_0100      TYPE C LENGTH 1,
      CK_ALTEROU_0300      TYPE C LENGTH 1,
      CK_ALTEROU_0300_MOTO TYPE C LENGTH 1,
      CK_ALTEROU_0300_PLC  TYPE C LENGTH 1,
      CK_ALTEROU_0300_PL1  TYPE C LENGTH 1,
      CK_ALTEROU_0300_PL2  TYPE C LENGTH 1,
      CK_ALTEROU_0300_PL3  TYPE C LENGTH 1,
      CK_ALTEROU_0300_PER  TYPE C LENGTH 1,
      CK_ALTEROU_PERCURSO  TYPE C LENGTH 1.

DATA: CK_NOVA_ROTA     TYPE C LENGTH 1,
      CK_NOVO_PEDAGIO  TYPE C LENGTH 1,
      CK_CONSULTA      TYPE C LENGTH 1,
      CK_GRAVADO       TYPE C LENGTH 1,
      CK_INDIVIDUAL    TYPE C LENGTH 1,
      CK_PERMISSAO     TYPE C LENGTH 1,
      CK_PERMISSAO_08  TYPE C LENGTH 1, "08	Cadastrar Pedágio
      CK_PERMISSAO_09  TYPE C LENGTH 1, "09	Editar Pedágio
      CK_PERMISSAO_10  TYPE C LENGTH 1, "10	Excluir Pedágio
      CK_PERMISSAO_11  TYPE C LENGTH 1, "11	Autorizar Pedágio - WebService
      CK_PERMISSAO_12  TYPE C LENGTH 1, "12	Cancelar Pedágio - WebService
      CK_PERMISSAO_13  TYPE C LENGTH 1, "13	Imprimir Pedágio
      CK_INFORMADO     TYPE CHAR01,
      CK_INFORMADO_DOC TYPE CHAR01,
      WA_REPOM_CARTAO  TYPE ZDE_REPOM_CARTAO.

DATA: OBJ_ROTA    TYPE REF TO ZCL_REPOM_ROTA,
      OBJ_PEDAGIO TYPE REF TO ZCL_REPOM_VIAGEM_VPR.

DATA: IT_UCOMM TYPE TABLE OF SY-UCOMM.

DATA: WA_ZLEST0121     TYPE ZLEST0121,
      IT_ZLEST0122     TYPE TABLE OF ZLEST0122 WITH HEADER LINE,
      WA_ZLEST0122_ALV TYPE ZDE_ZLEST0122_ALV,
      IT_ZLEST0122_ALV TYPE TABLE OF ZDE_ZLEST0122_ALV WITH HEADER LINE,
      IT_ZLEST0122_SEL TYPE TABLE OF ZDE_ZLEST0122_ALV WITH HEADER LINE,
      IT_ZLEST0123     TYPE TABLE OF ZLEST0123 WITH HEADER LINE,
      IT_ZLEST0123_ALV TYPE TABLE OF ZDE_ZLEST0123_ALV WITH HEADER LINE,
      IT_ZLEST0127_ALV TYPE TABLE OF ZDE_ZLEST0127_ALV WITH HEADER LINE,
      IT_ZLEST0123_SEL TYPE TABLE OF ZDE_ZLEST0123_ALV WITH HEADER LINE,
      IT_ZLEST0124     TYPE TABLE OF ZLEST0124 WITH HEADER LINE,
      IT_ZLEST0124_ALV TYPE TABLE OF ZLEST0124 WITH HEADER LINE,
      IT_ZLEST0124_SEL TYPE TABLE OF ZLEST0124 WITH HEADER LINE,
      WA_ZLEST0122     TYPE ZLEST0122,
      WA_ZLEST0123     TYPE ZLEST0123,
      WA_ZLEST0124     TYPE ZLEST0124,
      E_ERROS          TYPE ZDE_REPOM_ERROS_T,
      WA_ERRO          TYPE ZDE_REPOM_ERROS.

DATA: LC_FILTROS       TYPE  ZDE_ZLEST0123_FILTRO.

DATA: OK_CODE TYPE SY-UCOMM.

CONSTANTS:
  OK_GRAVAR        TYPE SY-UCOMM VALUE 'GRAVAR',
  OK_CANCELAR      TYPE SY-UCOMM VALUE 'CANCELAR',
  OK_CONFIRMAR     TYPE SY-UCOMM VALUE 'CONFIRMAR',
  OK_CANCEL        TYPE SY-UCOMM VALUE 'CANCEL',
  OK_PNOVO         TYPE SY-UCOMM VALUE 'PNOVO',
  OK_PEDITAR       TYPE SY-UCOMM VALUE 'PEDITAR',
  OK_PABRIR        TYPE SY-UCOMM VALUE 'PABRIR',
  OK_PEXCLUIR      TYPE SY-UCOMM VALUE 'PEXCLUIR',
  OK_ATUALIZAR     TYPE SY-UCOMM VALUE 'ATUALIZAR',
  OK_AUTORIZAR     TYPE SY-UCOMM VALUE 'AUTORIZAR',
  OK_PPRINT        TYPE SY-UCOMM VALUE 'PPRINT',
  OK_VALIDAR       TYPE SY-UCOMM VALUE 'VALIDAR',
  OK_CARTAO_PED    TYPE SY-UCOMM VALUE 'CARTAO_PED',
  OK_INFO_CARTAO   TYPE SY-UCOMM VALUE 'INFO_CARTAO',
  OK_INFO_PERCURSO TYPE SY-UCOMM VALUE 'INFO_PERCURSO'.
