PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZRSI_MONO_FUEL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZRSI_MONO_FUEL-FILIAL .
    FIELD ZRSI_MONO_FUEL-DT_INICIAL .
    FIELD ZRSI_MONO_FUEL-DT_FINAL .
    FIELD ZRSI_MONO_FUEL-UF .
    FIELD ZRSI_MONO_FUEL-MATNR .
    FIELD ZRSI_MONO_FUEL-P_ORIG .
    FIELD ZRSI_MONO_FUEL-P_BIO .
    FIELD ZRSI_MONO_FUEL-MAKTX .
    FIELD ZRSI_MONO_FUEL-ERDAT .
    FIELD ZRSI_MONO_FUEL-ERNAM .
    FIELD ZRSI_MONO_FUEL-AEDAT .
    FIELD ZRSI_MONO_FUEL-AENAM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZRSI_MONO_FUEL-FILIAL .
    FIELD ZRSI_MONO_FUEL-DT_INICIAL .
    FIELD ZRSI_MONO_FUEL-DT_FINAL .
    FIELD ZRSI_MONO_FUEL-UF .
    FIELD ZRSI_MONO_FUEL-MATNR .
    FIELD ZRSI_MONO_FUEL-P_ORIG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
