PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZRSI_ICMS_MONO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZRSI_ICMS_MONO-NCM .
    FIELD ZRSI_ICMS_MONO-MATNR .
    FIELD ZRSI_ICMS_MONO-VALIDFROM .
    FIELD ZRSI_ICMS_MONO-VALIDTO .
    FIELD ZRSI_ICMS_MONO-AMOUNT .
    FIELD ZRSI_ICMS_MONO-FACTOR .
    FIELD ZRSI_ICMS_MONO-UNIT .
    FIELD ZRSI_ICMS_MONO-WAERS .
    FIELD ZRSI_ICMS_MONO-TAXLAW .
    FIELD ZRSI_ICMS_MONO-P_DIF .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZRSI_ICMS_MONO-NCM .
    FIELD ZRSI_ICMS_MONO-MATNR .
    FIELD ZRSI_ICMS_MONO-VALIDFROM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
