PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSDT0123 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSDT0123-CHARG .
    FIELD ZSDT0123-LIFNR .
    FIELD ZSDT0123-MATNR .
    FIELD ZSDT0123-CD_CERTIFICACAO .
    FIELD ZSDT0123-DT_INI .
    FIELD ZSDT0123-DT_FIM .
    FIELD ZSDT0123-MENGE .
    FIELD ZSDT0123-CERT_TOT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSDT0123-CHARG .
    FIELD ZSDT0123-LIFNR .
    FIELD ZSDT0123-MATNR .
    FIELD ZSDT0123-CD_CERTIFICACAO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
