PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSDT0094 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSDT0094-DATA_REGISTRO .
    FIELD ZSDT0094-HORA_REGISTRO .
    FIELD ZSDT0094-PROGRAMA .
    FIELD ZSDT0094-NRO_SOL_OV .
    FIELD ZSDT0094-FIXACAO .
    FIELD ZSDT0094-DATA_VENC .
    FIELD ZSDT0094-DATA_LIB .
    FIELD ZSDT0094-CADENCIA_QTE .
    FIELD ZSDT0094-ZIEME .
    FIELD ZSDT0094-TOTAL_PROPORC .
    FIELD ZSDT0094-TAXA_CURVA .
    FIELD ZSDT0094-TAXA_CAMBIO .
    FIELD ZSDT0094-FRETE_CIF .
    FIELD ZSDT0094-FRETE_PORTO .
    FIELD ZSDT0094-TIPO .
    FIELD ZSDT0094-BEZEI .
    FIELD ZSDT0094-ESTORNO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSDT0094-DATA_REGISTRO .
    FIELD ZSDT0094-HORA_REGISTRO .
    FIELD ZSDT0094-PROGRAMA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
