DATA V_KUNNR TYPE KNA1-KUNNR.
DATA INT TYPE N.

SELECT SINGLE LTX
  FROM T247
  INTO MES_
  WHERE SPRAS EQ SY-LANGU
      AND MNR EQ WA_ITENIV-DATA+4(2).

INT  = SY-TABIX.
VAR_ROMANO = ZCL_UTIL=>CONVERT_ROMANOS( INT ).
VAR_ROMANO = |{ VAR_ROMANO CASE = LOWER }|.

VAR_S_F_D = SWITCH #( WA_ITENIV-SPART
WHEN '04' THEN |Sementes de { SWITCH #( WA_IMPORT-CULTURA
          WHEN 'ML' THEN 'Milho'
          WHEN 'SJ' THEN 'Soja'
          ) } prevista(s) na(s)|
WHEN '02' THEN |Fertilizantes prevista(s) na(s)|
WHEN '03' THEN |Defensivos prevista(s) na(s|
                    ).

VAR_INCO = |{ COND #( WHEN WA_ITENIV-INCO ne 'FOB'
THEN 'na propriedade denominada'
ELSE 'na unidade da VENDEDORA' ) } |.

RUA = WA_IMPORT-RUA.
CIDADE = WA_IMPORT-CIDADE.
ESTADO = WA_IMPORT-ESTADO.
LOCAL = | { WA_IMPORT-LOCAL }|.

CLEAR VAR_INCO1.

CHECK WA_ITENIV-INCO EQ 'FOB'.

VAR_INCO1 = SWITCH #( WA_ITENIV-INCO
WHEN 'FOB' THEN | a disposição para ser retirado sobre | &&
     |rodas pela parte COMPRADORA |
ELSE ''
).

CLEAR: RUA, CIDADE, ESTADO, LOCAL.

WA_ITENIV-WERKS = |{ WA_ITENIV-WERKS ALPHA = IN }|.
V_KUNNR = |{ WA_ITENIV-WERKS ALPHA = IN }|.

SELECT SINGLE STRAS MCOD3 REGIO
  FROM KNA1
  INTO (RUA, CIDADE, UF)
  WHERE KUNNR EQ V_KUNNR.

SELECT SINGLE BEZEI
  FROM T005U
    INTO ESTADO
    WHERE LAND1 EQ 'BR'
    AND SPRAS EQ SY-LANGU
    AND BLAND EQ UF.

ZCL_SOLICITACAO_OV=>UPPER_LOWER( CHANGING EXPORT = RUA ).
ZCL_SOLICITACAO_OV=>UPPER_LOWER( CHANGING EXPORT = CIDADE ).
