DATA: _LIFNR TYPE LIFNR.

CLEAR WA_TOTAL-BALES.

_LIFNR = |{ HEADER-WERKS ALPHA = IN }|.

SELECT SINGLE *
  FROM ZSDT0143
  INTO WA_143
  WHERE CONTRATO EQ HEADER-CONTRATO.

LOOP AT ITENS INTO DATA(WA).
  ADD WA-QTD_FARDOS  TO WA_TOTAL-BALES.
ENDLOOP.

SHIFT WA_TOTAL-BALES LEFT DELETING LEADING '0'.

SELECT SINGLE *
  FROM KNA1
  INTO WA_KNA1
  WHERE KUNNR EQ HEADER-KUNNR.

SELECT SINGLE *
  FROM LFA1
  INTO WA_LFA1
  WHERE LIFNR = _LIFNR.

SELECT SINGLE KTX
  FROM T247
  INTO MES
  WHERE MNR EQ SY-DATUM+4(2).

DIA = SY-DATUM+6(2).

CASE DIA.
  WHEN '11' OR '12' OR '13'.
    DIA = |{ DIA }th|.
  WHEN OTHERS.
    DATA(VLR) = DIA MOD 10.
    CASE VLR.
      WHEN 1. DIA = |{ DIA }st|.
      WHEN 2. DIA = |{ DIA }nd|.
      WHEN 3. DIA = |{ DIA }rd|.
      WHEN OTHERS. DIA = |{ DIA }th|.
    ENDCASE.
ENDCASE.
