DATA: TAXA_CONVERSAO TYPE P DECIMALS 2,
      TAXA_FIXA      TYPE P DECIMALS 4 VALUE '2.2046'.

*BREAK-POINT.

SELECT SINGLE *
  FROM ZPPT0002 AS A
  INNER JOIN ZPPT0004 AS B ON B~VERID EQ A~VERID
                          AND B~WERKS EQ A~WERKS
  INTO @DATA(WA_0002)
    WHERE A~WERKS    EQ @WA_ITENS-WERKS
      AND CD_SAFRA EQ @WA_ITENS-SAFRA
      AND LGORT    EQ @WA_ITENS-LOTE.

TAXA_CONVERSAO = WA_0002-B-TARA.

WA_GRID = VALUE #(
                   LOT       = WA_ITENS-LOTE
                   SHIPPING  = WA_ITENS-TIPO
                   BALES     = WA_ITENS-QTD_FARDOS
                   GROSS     = ( WA_ITENS-QTD_FARDOS * TAXA_CONVERSAO ) + WA_ITENS-PESO_LOTE
                   TARE      = WA_ITENS-QTD_FARDOS * TAXA_CONVERSAO
                   NET       = WA_ITENS-PESO_LOTE
                   PRICE_CTR = WA_ITENS-PRECO_FINAL
                   PRICE     = WA_ITENS-PRECO_FINAL * TAXA_FIXA
                   TOTAL     = WA_ITENS-PRECO_FINAL * WA_ITENS-PESO_LOTE * TAXA_FIXA
                 ).
"Mota totais do Radapé
ADD WA_GRID-BALES TO WA_TOTAL-BALES.
ADD WA_GRID-GROSS TO WA_TOTAL-GROSS.
ADD WA_GRID-NET   TO WA_TOTAL-NET.
ADD WA_GRID-TOTAL TO WA_TOTAL-TOTAL.

WRITE WA_GRID-TARE TO WA_GRID-TARE NO-ZERO.
WRITE WA_TOTAL-BALES TO WA_TOTAL-BALES NO-ZERO.
CONDENSE WA_GRID-TARE NO-GAPS.
CONDENSE WA_TOTAL-BALES NO-GAPS.

WA_TOTAL-PREPAYMENT = WA_TOTAL-TOTAL * ( WA_143-PCTGEM_ANT / 100 ).
