 TYPES BEGIN OF TY_GRID.
 TYPES: LOT      TYPE CHARG_D,
        SHIPPING TYPE NORMT,
        BALES    TYPE NUMC10,
        NET      TYPE DMBTR.
 TYPES END OF TY_GRID.

 TYPES BEGIN OF TY_TOTAL.
 TYPES: BALES TYPE NUMC10,
        NET   TYPE DMBTR.
 TYPES END OF TY_TOTAL.

 TYPES BEGIN OF TY_PARAGRAFO.
 TYPES: P01 TYPE STRING,
        P02 TYPE STRING,
        P03 TYPE STRING,
        P04 TYPE STRING,
        P05 TYPE STRING,
        P06 TYPE STRING,
        P07 TYPE STRING,
        P08 TYPE STRING,
        P09 TYPE STRING,
        P10 TYPE STRING,
        P11 TYPE STRING,
        P12 TYPE STRING,
        P13 TYPE STRING,
        P14 TYPE STRING,
        P15 TYPE STRING,
        P16 TYPE STRING,
        P17 TYPE STRING,
        P18 TYPE STRING,
        P19 TYPE STRING,
        P20 TYPE STRING,
        P21 TYPE STRING,
        P22 TYPE STRING,
        P23 TYPE STRING,
        P24 TYPE STRING,
        P25 TYPE STRING,
        P26 TYPE STRING,
        P27 TYPE STRING,
        P28 TYPE STRING,
        P29 TYPE STRING,
        P30 TYPE STRING.
 TYPES END OF TY_PARAGRAFO.
