
PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TAB_VINC_GRUPO'
  MODULE tab_vinc_grupo_change_tc_attr.
*&SPWIZARD: MODULE TAB_VINC_GRUPO_CHANGE_COL_ATTR.
  LOOP AT   t_grupo
       INTO w_grupo
       WITH CONTROL tab_vinc_grupo
       CURSOR tab_vinc_grupo-current_line.
*&SPWIZARD:   MODULE TAB_VINC_GRUPO_CHANGE_FIELD_ATTR
  ENDLOOP.

* MODULE STATUS_0004.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TAB_VINC_GRUPO'
  LOOP AT t_grupo.
    CHAIN.
      FIELD w_grupo-fiscal.
      FIELD w_grupo-uf.
      FIELD w_grupo-nome.
      FIELD w_grupo-volume.
    ENDCHAIN.
  ENDLOOP.
*&SPWIZARD: MODULE TAB_VINC_GRUPO_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TAB_VINC_GRUPO_CHANGE_COL_ATTR.

* MODULE USER_COMMAND_0004.
