PROCESS BEFORE OUTPUT.
 MODULE PBO_0101.

   CALL SUBSCREEN: SUB_01 INCLUDING SY-REPID '0100',
                   SUB_02 INCLUDING SY-REPID '0102'.

PROCESS AFTER INPUT.

   CALL SUBSCREEN: SUB_01,
                   SUB_02.

 MODULE PAI_0101.
