*&---------------------------------------------------------------------*
*&  Include           ZSDR0057_CLASS
*&---------------------------------------------------------------------*

CLASS LCL_ALV_TOOLBAR_0100 IMPLEMENTATION.
  METHOD CONSTRUCTOR.
*   Create ALV toolbar manager instance
    CREATE OBJECT C_ALV_TOOLBARMANAGER
      EXPORTING
        IO_ALV_GRID = IO_ALV_GRID.
  ENDMETHOD.                    "constructor

  METHOD ON_TOOLBAR.

*    TY_TOOLBAR-ICON      = ICON_REFRESH.
*    TY_TOOLBAR-FUNCTION  = 'REFRESH'.
*    TY_TOOLBAR-TEXT      = 'Atualizar'.
*    TY_TOOLBAR-BUTN_TYPE = 0.
*    APPEND TY_TOOLBAR TO E_OBJECT->MT_TOOLBAR.
*    CLEAR TY_TOOLBAR.

*    CALL METHOD C_ALV_TOOLBARMANAGER->REORGANIZE
*      EXPORTING
*        IO_ALV_TOOLBAR = E_OBJECT.

  ENDMETHOD.                    "on_toolbar

  METHOD HANDLE_USER_COMMAND.

    CASE E_UCOMM.
      WHEN ''.
    ENDCASE.

  ENDMETHOD.                    "HANDLE_USER_COMMAND

ENDCLASS.                    "

CLASS LCL_ALV_TOOLBAR_0100_RES IMPLEMENTATION.
  METHOD CONSTRUCTOR.
*   Create ALV toolbar manager instance
    CREATE OBJECT C_ALV_TOOLBARMANAGER
      EXPORTING
        IO_ALV_GRID = IO_ALV_GRID.
  ENDMETHOD.                    "constructor

  METHOD ON_TOOLBAR.

*    TY_TOOLBAR-ICON      = ICON_REFRESH.
*    TY_TOOLBAR-FUNCTION  = 'REFRESH'.
*    TY_TOOLBAR-TEXT      = 'Atualizar'.
*    TY_TOOLBAR-BUTN_TYPE = 0.
*    APPEND TY_TOOLBAR TO E_OBJECT->MT_TOOLBAR.
*    CLEAR TY_TOOLBAR.

*    CALL METHOD C_ALV_TOOLBARMANAGER->REORGANIZE
*      EXPORTING
*        IO_ALV_TOOLBAR = E_OBJECT.

  ENDMETHOD.                    "on_toolbar

  METHOD HANDLE_USER_COMMAND.

    CASE E_UCOMM.
      WHEN ''.
    ENDCASE.

  ENDMETHOD.                    "HANDLE_USER_COMMAND

ENDCLASS.

CLASS LCL_EVENT_HANDLER_0100 IMPLEMENTATION.                 "

  METHOD HANDLE_HOTSPOT_CLICK.
    PERFORM HANDLE_HOTSPOT_CLICK USING '0100' E_ROW_ID E_COLUMN_ID ES_ROW_NO.
  ENDMETHOD.

ENDCLASS.           "lcl_event_handler_0102 IMPLEMENTA

CLASS LCL_EVENT_HANDLER_0100_RES IMPLEMENTATION.                 "

  METHOD HANDLE_HOTSPOT_CLICK.
    PERFORM HANDLE_HOTSPOT_CLICK USING '0100_RES' E_ROW_ID E_COLUMN_ID ES_ROW_NO.
  ENDMETHOD.

ENDCLASS.           "lcl_event_handler_0102 IMPLEMENTA

CLASS LCL_EVENT_HANDLER_0101 IMPLEMENTATION.                 "

  METHOD HANDLE_HOTSPOT_CLICK.
    PERFORM HANDLE_HOTSPOT_CLICK USING '0101' E_ROW_ID E_COLUMN_ID ES_ROW_NO.
  ENDMETHOD.

ENDCLASS.           "lcl_event_handler_0102 IMPLEMENTA
