PROCESS BEFORE OUTPUT.
  MODULE: PBO_0700,
          CREATE_OBJ.
*
PROCESS AFTER INPUT.

  CHAIN.
    FIELD VAR_VENC_NEW.
    MODULE CHECK_VENCIMENTO ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE PAI_0700.
