PROCESS BEFORE OUTPUT.
  MODULE PBO_0100.

  CALL SUBSCREEN: SUB01 INCLUDING SY-REPID C_TELA,
                  SUB02 INCLUDING SY-REPID '0103',
                  SUB03 INCLUDING SY-REPID '0104'.

PROCESS AFTER INPUT.
  CALL SUBSCREEN: SUB02,
                  SUB03.
  MODULE PAI_0100.
