PROCESS BEFORE OUTPUT.
  MODULE MODIFY_SCREEN.
* MODULE STATUS_0108.
*
PROCESS AFTER INPUT.
* MODULE USER_COMMAND_0108.

  CHAIN.
    FIELD WA_BL-NR_CONHEC.
    FIELD WA_BL-NR_QTDE.
    FIELD WA_BL-DT_DATA.
    MODULE ATUALIZA_DADOS ON CHAIN-REQUEST.
  ENDCHAIN.
