PROCESS BEFORE OUTPUT.
  MODULE MODIFY_SCREEN.
  MODULE PBO_0105.
*
PROCESS AFTER INPUT.
  MODULE PAI_0105.

  CHAIN.
    FIELD WA_NOMEACAO-INSTRUCAO.
    MODULE BLOCK_DADOS ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD WA_NOMEACAO-DS_NOME_TRANSPOR.
    FIELD WA_NOMEACAO-NR_ANO.
    FIELD WA_NOMEACAO-NR_MES.
    FIELD WA_NOMEACAO-BOOKING.
    FIELD WA_NOMEACAO-WERKS.
    FIELD WA_NOMEACAO-NRO_SOL_OV.
    FIELD WA_NOMEACAO-NR_QTDE_NOMEADA.
    FIELD WA_NOMEACAO-INSTRUCAO.
    MODULE ATUALIZA_DADOS ON CHAIN-REQUEST.
  ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD WA_NOMEACAO-DS_NOME_TRANSPOR MODULE F4_DS_NOME_TRANSPOR.
  FIELD WA_NOMEACAO-NRO_SOL_OV MODULE F4_NRO_SOL_OV.
  FIELD WA_NOMEACAO-INSTRUCAO MODULE F4_INSTRUCAO.
