PROCESS BEFORE OUTPUT.
 MODULE STATUS_0102.
*
PROCESS AFTER INPUT.

CHAIN.
    FIELD WA_T001W-WERKS.
    FIELD WA_LFA1_PC-LIFNR.
    FIELD WA_LFA1_PC-LZONE.
    FIELD WA_FILIAL_DEST-WERKS.
    FIELD WA_KNA1-LZONE.
    FIELD WA_MAKT-MATNR.
    FIELD WA_ZSDT0158_SAIDA-QUANTIDADE.
    FIELD WA_ZSDT0158_SAIDA-SAFRA.
    FIELD TVV3T-KVGR3.
    FIELD TINCT-INCO1.

    MODULE MODIFY_PED_TRANSF ON CHAIN-REQUEST.

  ENDCHAIN.

 MODULE USER_COMMAND_0103.

   PROCESS ON VALUE-REQUEST. "F4

      FIELD WA_SAIDA-NRO_SOL_OV MODULE HELP_NRO_SOL_OV.
