PROCESS BEFORE OUTPUT.

  MODULE TAB_STRIP_ACTIVE_TAB_SET.
  CALL SUBSCREEN TAB_STRIP_SCA
         INCLUDING G_TAB_STRIP-PROG G_TAB_STRIP-SUBSCREEN.
  MODULE MODIFY_SCREEN.

PROCESS AFTER INPUT.
  CALL SUBSCREEN TAB_STRIP_SCA.
  MODULE TAB_STRIP_ACTIVE_TAB_GET.
