PROCESS BEFORE OUTPUT.
  MODULE MODIFY_SCREEN.
  MODULE PBO_0100.
  CALL SUBSCREEN: SUB01 INCLUDING SY-REPID '0101',
                  SUB02 INCLUDING SY-REPID X_SCREEN.

PROCESS AFTER INPUT.
  CALL SUBSCREEN: SUB01, SUB02.
  MODULE PAI_0100.
