PROCESS BEFORE OUTPUT.
  MODULE STATUS_0400.
*
PROCESS AFTER INPUT.
  MODULE USER_COMMAND_0400.

  CHAIN.
    FIELD WA_PROJECAO-EMPRESA.
    FIELD WA_PROJECAO-FAZENDA.
    MODULE GET_PROJECAO ON CHAIN-REQUEST.
  ENDCHAIN.
