*&---------------------------------------------------------------------*
*&  Include           ZSDR0057_PBO
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Module  STATUS_0100  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_0100 OUTPUT.
  SET PF-STATUS 'PF0100'.
  SET TITLEBAR 'T0100'.
ENDMODULE.


MODULE CRIAR_OBJETOS_0100 OUTPUT.

  IF OBJ_CONTAINER_0100 IS INITIAL.

    PERFORM REFRESH_OBJETOS.
    PERFORM CRIAR_FIELD_CATALOG USING '0100'.

    CREATE OBJECT OBJ_CONTAINER_0100
      EXPORTING
        CONTAINER_NAME = 'CC_ALV_0100'.

    CREATE OBJECT OBJ_ALV_0100
      EXPORTING
        I_PARENT = OBJ_CONTAINER_0100.

    CREATE OBJECT OBJ_TOOLBAR_0100
      EXPORTING
        IO_ALV_GRID = OBJ_ALV_0100.

    GS_LAYOUT-ZEBRA    = 'X'.
    GS_VARIANT-REPORT  = SY-REPID.

    SET HANDLER: OBJ_TOOLBAR_0100->ON_TOOLBAR          FOR OBJ_ALV_0100,
                 OBJ_TOOLBAR_0100->HANDLE_USER_COMMAND FOR OBJ_ALV_0100.

    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_INSERT_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_DELETE_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_MOVE_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE_NEW_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_UNDO.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_CUT.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_REFRESH.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.

    CALL METHOD OBJ_ALV_0100->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT            = GS_LAYOUT
        I_SAVE               = 'A'
        IT_TOOLBAR_EXCLUDING = IT_EXCLUDE_FCODE
        IS_VARIANT           = GS_VARIANT_C
      CHANGING
        IT_FIELDCATALOG      = IT_FCAT
        IT_OUTTAB            = IT_SAIDA_0100.

    SET HANDLER LCL_EVENT_HANDLER_0100->HANDLE_HOTSPOT_CLICK FOR OBJ_ALV_0100.

    CALL METHOD OBJ_ALV_0100->REGISTER_EDIT_EVENT
      EXPORTING
        I_EVENT_ID = CL_GUI_ALV_GRID=>MC_EVT_ENTER.

*    CALL METHOD OBJ_ALV_0100->SET_READY_FOR_INPUT
*      EXPORTING
*        I_READY_FOR_INPUT = 1.

  ELSE.
    CALL METHOD OBJ_ALV_0100->REFRESH_TABLE_DISPLAY
       EXPORTING
         IS_STABLE = WA_STABLE.
  ENDIF.

  IF OBJ_CONTAINER_0100_RES IS INITIAL.

    PERFORM REFRESH_OBJETOS.
    PERFORM CRIAR_FIELD_CATALOG USING '0100_RES'.

    CREATE OBJECT OBJ_CONTAINER_0100_RES
      EXPORTING
        CONTAINER_NAME = 'CC_ALV_0100_RES'.

    CREATE OBJECT OBJ_ALV_0100_RES
      EXPORTING
        I_PARENT = OBJ_CONTAINER_0100_RES.

    CREATE OBJECT OBJ_TOOLBAR_0100_RES
      EXPORTING
        IO_ALV_GRID = OBJ_ALV_0100_RES.

    GS_LAYOUT-ZEBRA    = 'X'.
    GS_VARIANT-REPORT  = SY-REPID.

    SET HANDLER: OBJ_TOOLBAR_0100_RES->ON_TOOLBAR          FOR OBJ_ALV_0100_RES,
                 OBJ_TOOLBAR_0100_RES->HANDLE_USER_COMMAND FOR OBJ_ALV_0100_RES.

    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_INSERT_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_DELETE_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_MOVE_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE_NEW_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_UNDO.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_CUT.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_REFRESH.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.

    CALL METHOD OBJ_ALV_0100_RES->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT            = GS_LAYOUT
        I_SAVE               = 'A'
        IT_TOOLBAR_EXCLUDING = IT_EXCLUDE_FCODE
        "IS_VARIANT           = GS_VARIANT
      CHANGING
        IT_FIELDCATALOG      = IT_FCAT
        IT_OUTTAB            = IT_SAIDA_0100_RES.

    SET HANDLER LCL_EVENT_HANDLER_0100_RES->HANDLE_HOTSPOT_CLICK FOR OBJ_ALV_0100_RES.

    CALL METHOD OBJ_ALV_0100_RES->REGISTER_EDIT_EVENT
      EXPORTING
        I_EVENT_ID = CL_GUI_ALV_GRID=>MC_EVT_ENTER.

*    CALL METHOD OBJ_ALV_0100->SET_READY_FOR_INPUT
*      EXPORTING
*        I_READY_FOR_INPUT = 1.

  ELSE.
    CALL METHOD OBJ_ALV_0100_RES->REFRESH_TABLE_DISPLAY
       EXPORTING
         IS_STABLE = WA_STABLE.
  ENDIF.


ENDMODULE.

MODULE STATUS_0101 OUTPUT.
  SET PF-STATUS 'PF0101'.
  SET TITLEBAR 'T0101'.
ENDMODULE.

MODULE CRIAR_OBJETOS_0101 OUTPUT.


  IF OBJ_ALV_0101 IS INITIAL.

    PERFORM REFRESH_OBJETOS.

    IF VG_LAYOUT_0101 = 'E'.
      PERFORM CRIAR_FIELD_CATALOG USING '0101_E'.
    ELSE.
      PERFORM CRIAR_FIELD_CATALOG USING '0101_S'.
    ENDIF.

    IF OBJ_CONTAINER_0101 IS INITIAL.
      CREATE OBJECT OBJ_CONTAINER_0101
        EXPORTING
          CONTAINER_NAME = 'CC_ALV_0101'.
    ENDIF.

    CREATE OBJECT OBJ_ALV_0101
      EXPORTING
        I_PARENT = OBJ_CONTAINER_0101.

*    CREATE OBJECT OBJ_TOOLBAR_0101
*      EXPORTING
*        IO_ALV_GRID = OBJ_ALV_0101.

    GS_LAYOUT-ZEBRA    = 'X'.
    GS_VARIANT-REPORT  = SY-REPID.

*    SET HANDLER: OBJ_TOOLBAR_0101->ON_TOOLBAR          FOR OBJ_ALV_0101,
*                 OBJ_TOOLBAR_0101->HANDLE_USER_COMMAND FOR OBJ_ALV_0101.

    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_INSERT_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_DELETE_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_MOVE_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE_NEW_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_UNDO.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY_ROW.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_LOC_CUT.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.
    WA_EXCLUDE_FCODE = CL_GUI_ALV_GRID=>MC_FC_REFRESH.
    APPEND WA_EXCLUDE_FCODE TO IT_EXCLUDE_FCODE.

    CALL METHOD OBJ_ALV_0101->SET_TABLE_FOR_FIRST_DISPLAY
      EXPORTING
        IS_LAYOUT            = GS_LAYOUT
        I_SAVE               = 'A'
        IT_TOOLBAR_EXCLUDING = IT_EXCLUDE_FCODE
        "IS_VARIANT           = GS_VARIANT_C
      CHANGING
        IT_FIELDCATALOG      = IT_FCAT
        IT_OUTTAB            = IT_SAIDA_0101.

    SET HANDLER LCL_EVENT_HANDLER_0101->HANDLE_HOTSPOT_CLICK FOR OBJ_ALV_0101.


  ELSE.
    CALL METHOD OBJ_ALV_0101->REFRESH_TABLE_DISPLAY
       EXPORTING
         IS_STABLE = WA_STABLE.
  ENDIF.


ENDMODULE.
