PROCESS BEFORE OUTPUT.
  MODULE MODIFY_SCREEN.
* MODULE STATUS_0107.
*
PROCESS AFTER INPUT.

  CHAIN.
*    FIELD WA_DDE-NR_REGISTRO_EXPO.
    FIELD WA_DDE-DT_DDE.
*    FIELD WA_DDE-NR_QTDE.
    FIELD WA_DDE-NR_DDE.
    FIELD WA_DDE-DT_AVERBACAO.
*    FIELD WA_DDE-NR_VALOR.
    MODULE ATUALIZA_DADOS ON CHAIN-REQUEST.
  ENDCHAIN.

*PROCESS ON VALUE-REQUEST.
*  FIELD WA_DDE-NR_REGISTRO_EXPO MODULE F4_NR_REGISTRO_EXPO.
* MODULE USER_COMMAND_0107.
