*&---------------------------------------------------------------------*
*& Report  ZSDR0053
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZSDR0053.

DATA: IT_ZSDT0023  TYPE TABLE OF ZSDT0023,
      WA_ZSDT0023  TYPE ZSDT0023,
      WA_MSEG      TYPE MSEG,
      WA_LIKP      TYPE LIKP,
      WA_MKPF      TYPE MKPF,
      WA_ZLEST0100 TYPE ZLEST0100,

      IT_LIPS      TYPE TABLE OF LIPS WITH HEADER LINE,
      IT_VBAK      TYPE TABLE OF VBAK WITH HEADER LINE,

      T_RETURN     TYPE TABLE OF BAPIRET2 WITH HEADER LINE.

DATA: GOODSMVT_HEADRET TYPE BAPI2017_GM_HEAD_RET,
      MSG_TEXT         TYPE STRING,
      VL_PONTEIRO      TYPE ZLEST0100-CONT,
      VG_JOB           TYPE I,
      V_HORA_SEG       TYPE CPUTM,
      V_HORA           TYPE CPUTM.

SELECT SINGLE COUNT(*) INTO VG_JOB
  FROM TBTCO
 WHERE JOBNAME EQ 'ZLES0106_ESTORNA'
   AND STATUS EQ 'R'.

 DATA(lva_data_base) = sy-datum.

 lva_data_base = SY-DATUM - 2.

IF ( VG_JOB EQ 1 ).
  " Saidas não estornadas pela ZOPUS
  SELECT *
    FROM ZSDT0023
    INTO TABLE IT_ZSDT0023
    WHERE MBLNR_S NE ''
    AND   MBLNR_E EQ ''
    AND   ES_MBLNR_S EQ ''.

  SELECT *
   FROM ZSDT0023
   APPENDING TABLE IT_ZSDT0023
   WHERE MBLNR_S NE ''
   AND   ES_MBLNR_S EQ ''
   AND   DT_SAIDA   GE lva_data_base "data de corte
   AND   NOT EXISTS ( SELECT * FROM LIKP WHERE VBELN = ZSDT0023~VBELN ).

  SELECT *
  FROM ZSDT0023
  APPENDING TABLE IT_ZSDT0023
  WHERE MBLNR_E NE ''
  AND   ES_MBLNR_E EQ ''
  AND   DT_SAIDA   GE lva_data_base  "data de corte
  AND   NOT EXISTS ( SELECT * FROM LIKP WHERE VBELN = ZSDT0023~VBELN ).

  DELETE IT_ZSDT0023 WHERE dt_saida LT lva_data_base.

  SORT IT_ZSDT0023 BY VBELN.
  DELETE ADJACENT DUPLICATES FROM IT_ZSDT0023 COMPARING ALL FIELDS.

  IF IT_ZSDT0023[] IS NOT INITIAL.
    CLEAR: IT_LIPS[], IT_VBAK[].
    SELECT *
      FROM LIPS INTO TABLE IT_LIPS
       FOR ALL ENTRIES IN IT_ZSDT0023
     WHERE VBELN = IT_ZSDT0023-VBELN.

    IF IT_LIPS[] IS NOT INITIAL.
      SELECT *
        FROM VBAK INTO TABLE IT_VBAK
         FOR ALL ENTRIES IN IT_LIPS
       WHERE VBELN = IT_LIPS-VGBEL.

      IF IT_VBAK[] IS NOT INITIAL.
        LOOP AT IT_ZSDT0023 INTO WA_ZSDT0023.
          DATA(_TABIX) = SY-TABIX.

          READ TABLE IT_LIPS WITH KEY VBELN = WA_ZSDT0023-VBELN.
          CHECK SY-SUBRC EQ 0.

          READ TABLE IT_VBAK WITH KEY VBELN = IT_LIPS-VGBEL.
          CHECK ( SY-SUBRC EQ 0 ) AND ( IT_VBAK-AUART EQ 'ZRAN' ).

          DELETE IT_ZSDT0023 INDEX _TABIX.
        ENDLOOP.
      ENDIF.
    ENDIF.
  ENDIF.


  V_HORA_SEG = 120.
  LOOP AT IT_ZSDT0023 INTO WA_ZSDT0023.
    SELECT SINGLE *
      FROM MKPF
      INTO WA_MKPF
      WHERE MBLNR  EQ WA_ZSDT0023-MBLNR_S
      AND   MJAHR  EQ WA_ZSDT0023-MJAHR_S.

    V_HORA  = SY-UZEIT -  WA_MKPF-CPUTM.
    IF SY-DATUM =  WA_MKPF-CPUDT.
      IF V_HORA LT V_HORA_SEG.
        CONTINUE.
      ENDIF.
    ENDIF.
    "SAIDA
    IF WA_ZSDT0023-ES_MBLNR_S IS INITIAL. "doc estono não gerado.
      SELECT SINGLE *
        FROM MSEG
        INTO WA_MSEG
        WHERE SMBLN = WA_ZSDT0023-MBLNR_S AND SJAHR =  WA_ZSDT0023-MJAHR_S
        AND   SMBLN  NE ''.
      IF SY-SUBRC = 0. "Já esta estornado
        UPDATE ZSDT0023 SET ES_MBLNR_S = WA_MSEG-MBLNR
                            ES_MJAHR_S = WA_MSEG-MJAHR
                            EST_JOB    = 'X'
       WHERE VBELN = WA_ZSDT0023-VBELN.
      ELSE.
        REFRESH  T_RETURN.
        CLEAR GOODSMVT_HEADRET.
        CALL FUNCTION 'BAPI_GOODSMVT_CANCEL'
          EXPORTING
            MATERIALDOCUMENT    = WA_ZSDT0023-MBLNR_S
            MATDOCUMENTYEAR     = WA_ZSDT0023-MJAHR_S
            GOODSMVT_PSTNG_DATE = SY-DATUM
          IMPORTING
            GOODSMVT_HEADRET    = GOODSMVT_HEADRET
          TABLES
            RETURN              = T_RETURN.


        READ TABLE T_RETURN WITH KEY TYPE = 'E'.
        IF NOT SY-SUBRC IS INITIAL.
          IF GOODSMVT_HEADRET-MAT_DOC IS NOT INITIAL.
            UPDATE ZSDT0023 SET ES_MBLNR_S = GOODSMVT_HEADRET-MAT_DOC
                                ES_MJAHR_S = GOODSMVT_HEADRET-DOC_YEAR
                                EST_JOB    = 'X'
            WHERE VBELN = WA_ZSDT0023-VBELN.

            CLEAR VL_PONTEIRO.
            SELECT  MAX( CONT )
                  FROM ZLEST0100
                  INTO VL_PONTEIRO
                  WHERE CH_REFERENCIA = WA_ZSDT0023-CH_REFERENCIA.

            IF SY-SUBRC = 0.
              ADD 1 TO VL_PONTEIRO.
            ELSE.
              VL_PONTEIRO = 1.
            ENDIF.

            CONCATENATE 'Doc.Material ' WA_ZSDT0023-MBLNR_S 'Estornado por ' GOODSMVT_HEADRET-MAT_DOC INTO MSG_TEXT SEPARATED BY SPACE.
            WA_ZLEST0100-MANDT      = SY-MANDT.
            WA_ZLEST0100-CH_REFERENCIA   = WA_ZSDT0023-CH_REFERENCIA.
            WA_ZLEST0100-MSGTYP     = 'S'.
            WA_ZLEST0100-MSGSPRA    = SY-LANGU.
            WA_ZLEST0100-MSGID      = 'JOB'.
            WA_ZLEST0100-MSGNR      = '000'.
            WA_ZLEST0100-MSGV1      = MSG_TEXT.
            WA_ZLEST0100-DATA       = SY-DATUM.
            WA_ZLEST0100-HORA       = SY-UZEIT.
            WA_ZLEST0100-USUARIO    = SY-UNAME.
            WA_ZLEST0100-CONT       = VL_PONTEIRO.

            MODIFY  ZLEST0100 FROM WA_ZLEST0100.
            ADD 1 TO VL_PONTEIRO.
            COMMIT WORK.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDIF.

    "ENTRADA
    IF WA_ZSDT0023-ES_MBLNR_E IS INITIAL. "doc estono não gerado.
      SELECT SINGLE *
        FROM MSEG
        INTO WA_MSEG
        WHERE SMBLN = WA_ZSDT0023-MBLNR_E AND SJAHR =  WA_ZSDT0023-MJAHR_E
        AND   SMBLN  NE ''.
      IF SY-SUBRC = 0. "Já esta estornado
        UPDATE ZSDT0023 SET ES_MBLNR_E = WA_MSEG-MBLNR
                            ES_MJAHR_E = WA_MSEG-MJAHR
                            EST_JOB    = 'X'
       WHERE VBELN = WA_ZSDT0023-VBELN.
      ELSEIF WA_ZSDT0023-MBLNR_E IS NOT INITIAL.
        REFRESH  T_RETURN.
        CLEAR GOODSMVT_HEADRET.
        CALL FUNCTION 'BAPI_GOODSMVT_CANCEL'
          EXPORTING
            MATERIALDOCUMENT    = WA_ZSDT0023-MBLNR_E
            MATDOCUMENTYEAR     = WA_ZSDT0023-MJAHR_E
            GOODSMVT_PSTNG_DATE = SY-DATUM
          IMPORTING
            GOODSMVT_HEADRET    = GOODSMVT_HEADRET
          TABLES
            RETURN              = T_RETURN.


        READ TABLE T_RETURN WITH KEY TYPE = 'E'.
        IF NOT SY-SUBRC IS INITIAL.
          IF GOODSMVT_HEADRET-MAT_DOC IS NOT INITIAL.
            UPDATE ZSDT0023 SET ES_MBLNR_E = GOODSMVT_HEADRET-MAT_DOC
                                ES_MJAHR_E = GOODSMVT_HEADRET-DOC_YEAR
                                EST_JOB    = 'X'
            WHERE VBELN = WA_ZSDT0023-VBELN.

            CLEAR VL_PONTEIRO.
            SELECT  MAX( CONT )
                  FROM ZLEST0100
                  INTO VL_PONTEIRO
                  WHERE CH_REFERENCIA = WA_ZSDT0023-CH_REFERENCIA.

            IF SY-SUBRC = 0.
              ADD 1 TO VL_PONTEIRO.
            ELSE.
              VL_PONTEIRO = 1.
            ENDIF.

            CONCATENATE 'Doc.Material ' WA_ZSDT0023-MBLNR_E 'Estornado por ' GOODSMVT_HEADRET-MAT_DOC INTO MSG_TEXT SEPARATED BY SPACE.
            WA_ZLEST0100-MANDT      = SY-MANDT.
            WA_ZLEST0100-CH_REFERENCIA   = WA_ZSDT0023-CH_REFERENCIA.
            WA_ZLEST0100-MSGTYP     = 'S'.
            WA_ZLEST0100-MSGSPRA    = SY-LANGU.
            WA_ZLEST0100-MSGID      = 'JOB'.
            WA_ZLEST0100-MSGNR      = '000'.
            WA_ZLEST0100-MSGV1      = MSG_TEXT.
            WA_ZLEST0100-DATA       = SY-DATUM.
            WA_ZLEST0100-HORA       = SY-UZEIT.
            WA_ZLEST0100-USUARIO    = SY-UNAME.
            WA_ZLEST0100-CONT       = VL_PONTEIRO.

            MODIFY  ZLEST0100 FROM WA_ZLEST0100.
            ADD 1 TO VL_PONTEIRO.
            COMMIT WORK.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDIF.

  ENDLOOP.
ENDIF.
