PROCESS BEFORE OUTPUT.
  MODULE MODIFY_SCREEN.
* MODULE STATUS_0106.
*
PROCESS AFTER INPUT.
  CHAIN.
    FIELD WA_RE-NR_REGISTRO_EXPO.
    FIELD WA_RE-ID_PAIS_DESTINO.
    FIELD WA_RE-WERKS.
    FIELD WA_RE-NR_VALOR_TOTAL.
    FIELD WA_RE-DT_REGISTRO_EXPO.
    FIELD WA_RE-NR_QTDE.
*    FIELD WA_RE-ID_EXPORTADOR.
    FIELD WA_RE-NR_VALOR_TM.
    FIELD WA_RE-ID_IMPORTADOR.
    MODULE ATUALIZA_DADOS ON CHAIN-REQUEST.
  ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD WA_RE-ID_PAIS_DESTINO MODULE F4_PAIS.

* MODULE USER_COMMAND_0106.
