TYPES: BEGIN OF ty_header,
         nro_sol_ov TYPE zsdt0051-nro_sol_ov,
         org_vendas TYPE bezei20,
         emissor    TYPE name1_gp,
         endereco   TYPE stras_gp,
         municipio  TYPE ort01_gp,
         cnpj       TYPE stcd1,
         cpf        TYPE stcd2,
         ie(15),
         uf         TYPE regio,
         cep        TYPE pstl2,
         cidade     TYPE ort01,
         vkaus      TYPE zsdt0051-vkaus,
         logistica  TYPE zsdt0051-coment_logistica,
         data       TYPE zsdt0051-data_atual,
         bezei      TYPE tvkbt-bezei,
         smtp_addr  TYPE adr6-smtp_addr,
         obs_line1  TYPE tline-tdline,
       END OF ty_header,

       BEGIN OF ty_cond_pgto,
         forma_pgto(23),
         condicao(23),
         vencimento(10),
         frete          TYPE zsdt0051-inco1,
         banco(50),
         ag(11),
         moeda(5),
         conta(18),
         dig(2),
         prazo_ret01    TYPE zsdt0051-dtde_logist,
         prazo_ret02    TYPE zsdt0051-dtate_logist,
       END OF ty_cond_pgto.

TYPES: ty_mara      TYPE TABLE OF mara,
       ty_makt      TYPE TABLE OF makt,
       ty_itens     TYPE TABLE OF zsdt0053,
       ty_lines     TYPE TABLE OF tline,
       ty_logistica TYPE TABLE OF zsdt0055.

TYPES: ty_qtd         TYPE adge_soowa,
       ty_tot_sc(14)  TYPE p DECIMALS 2,
       ty_vlr_tot(14) TYPE p DECIMALS 2.
