
PROCESS BEFORE OUTPUT.
  MODULE INICIALIZA_TELA100.
  MODULE TRATA_FIELDS.
  MODULE STATUS_0100.
  MODULE CRIA_OBJETOS.
*
PROCESS AFTER INPUT.
  MODULE USER_COMMAND_0100.

PROCESS ON VALUE-REQUEST.
  FIELD WG_CADLAN-WERKS     MODULE SEARCH_FILIAL.
  FIELD WG_CADLAN-INSTRUCAO MODULE SEARCH_INSTRUCAO.
