PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSDT0037 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSDT0037-BUKRS .
    FIELD ZSDT0037-VAL_DE .
    FIELD ZSDT0037-MATKL .
    FIELD ZSDT0037-FILIAL_ORIGEM .
    FIELD ZSDT0037-MEINS .
    FIELD ZSDT0037-FILIAL_DESTINO .
    FIELD ZSDT0037-WAERS .
    FIELD ZSDT0037-VAL_ATE .
    FIELD ZSDT0037-VLR_FRETE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSDT0037-BUKRS .
    FIELD ZSDT0037-VAL_DE .
    FIELD ZSDT0037-MATKL .
    FIELD ZSDT0037-FILIAL_ORIGEM .
    FIELD ZSDT0037-MEINS .
    FIELD ZSDT0037-FILIAL_DESTINO .
    FIELD ZSDT0037-WAERS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
