PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSDT_DEPARA_CEN CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSDT_DEPARA_CEN-VKORG .
    FIELD ZSDT_DEPARA_CEN-CENTRO_REAL .
    FIELD ZSDT_DEPARA_CEN-CENTROV_1 .
    FIELD ZSDT_DEPARA_CEN-TP_CENTRO_VIRTUAL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSDT_DEPARA_CEN-VKORG .
    FIELD ZSDT_DEPARA_CEN-CENTRO_REAL .
    FIELD ZSDT_DEPARA_CEN-CENTROV_1 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
