PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSDT0418 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSDT0418-CONTA .
    FIELD ZSDT0418-FORNECEDOR .
    FIELD ZSDT0418-CLIENTE .
    FIELD ZSDT0418-PONTO_COLETA .
    FIELD ZSDT0418-FILIAL .
    FIELD ZSDT0418-LOCAL_ENTREGA .
    FIELD ZSDT0418-TRANSPORTADORA .
    FIELD ZSDT0418-MOTORISTA .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSDT0418-CONTA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
