PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSDT0042 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSDT0042-WITHT .
    FIELD ZSDT0042-CULTURA .
    FIELD ZSDT0042-WAERK .
    FIELD ZSDT0042-ESTADO .
    FIELD ZSDT0042-VAL_DE .
    FIELD ZSDT0042-VAL_ATE .
    FIELD ZSDT0042-SAFRA .
    FIELD ZSDT0042-VLR_PERC .
    FIELD ZSDT0042-VLR_ALIQ .
    FIELD ZSDT0042-VLR_PERC1 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSDT0042-WITHT .
    FIELD ZSDT0042-CULTURA .
    FIELD ZSDT0042-WAERK .
    FIELD ZSDT0042-ESTADO .
    FIELD ZSDT0042-VAL_DE .
    FIELD ZSDT0042-VAL_ATE .
    FIELD ZSDT0042-SAFRA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
