PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZSDT_DEPARA_DEPO-WERKS .
    FIELD ZSDT_DEPARA_DEPO-LIFNR .
    FIELD ZSDT_DEPARA_DEPO-OPERACAO .
    FIELD ZSDT_DEPARA_DEPO-WERKS_V .
    FIELD ZSDT_DEPARA_DEPO-LGORT .
*    FIELD ZSDT_DEPARA_DEPO-TP_DEP .
    FIELD ZSDT_DEPARA_DEPO-LGORT_T .
    FIELD ZSDT_DEPARA_DEPO-LGORT_F .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZSDT_DEPARA_DEPO-WERKS .
    FIELD ZSDT_DEPARA_DEPO-LIFNR .
    FIELD ZSDT_DEPARA_DEPO-OPERACAO .
  module detail_pai.
 endchain.
