*&---------------------------------------------------------------------*
*& Report  ZSDY0003
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZSDY0003.

TABLES: ZSDYT0051, ZDE_ZSDYT0051.

DATA: IT_ZSDYT0051     TYPE TABLE OF ZSDYT0051     WITH HEADER LINE,
      IT_ZSDYT0051_ALV TYPE TABLE OF ZDE_ZSDYT0051 WITH HEADER LINE,
      IT_ZSDYT0051_SEL TYPE TABLE OF ZDE_ZSDYT0051 WITH HEADER LINE,
      IT_KNA1          TYPE TABLE OF KNA1  WITH HEADER LINE,
      IT_TVKOT         TYPE TABLE OF TVKOT WITH HEADER LINE,
      IT_TVTWT         TYPE TABLE OF TVTWT WITH HEADER LINE,
      IT_TSPAT         TYPE TABLE OF TSPAT WITH HEADER LINE.


DATA: OK_CODE     TYPE SY-UCOMM,
      LC_OPERACO  TYPE CHAR01,
      CK_PRIMEIRO TYPE CHAR01.

CONSTANTS: OK_NEW    TYPE SY-UCOMM VALUE 'NEW',
           OK_EDIT   TYPE SY-UCOMM VALUE 'EDIT',
           OK_DELETE TYPE SY-UCOMM VALUE 'DELETE',
           OK_SALVAR TYPE SY-UCOMM VALUE 'SALVAR',
           OK_CANCEL TYPE SY-UCOMM VALUE 'CANCEL'.


"FIELD-SYMBOLS: <FS_0051> TYPE ZDE_ZSDYT0051.

SELECTION-SCREEN BEGIN OF BLOCK B1.
SELECT-OPTIONS: CLIEN  FOR ZSDYT0051-KUNNR,
                ORGNI  FOR ZSDYT0051-VKORG DEFAULT '0100',
                CANAL  FOR ZSDYT0051-VTWEG,
                SETOR  FOR ZSDYT0051-SPART.
SELECTION-SCREEN END OF BLOCK B1.

INITIALIZATION.

  ORGNI-LOW = '0100'.

START-OF-SELECTION.

  PERFORM PESQUISAR.

  CALL SCREEN '0100'.

  INCLUDE ZSDY0003_0100.

*&---------------------------------------------------------------------*
*&      Form  PESQUISAR
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM PESQUISAR .

  CLEAR: IT_ZSDYT0051[], IT_ZSDYT0051_ALV[], IT_KNA1[].

  SELECT * INTO
   TABLE IT_ZSDYT0051
    FROM ZSDYT0051
   WHERE KUNNR IN CLIEN
     AND VKORG IN ORGNI
     AND VTWEG IN CANAL
     AND SPART IN SETOR.

  IF IT_ZSDYT0051[] IS NOT INITIAL.

    SELECT * INTO TABLE IT_KNA1
      FROM KNA1
       FOR ALL ENTRIES IN IT_ZSDYT0051
     WHERE KUNNR EQ IT_ZSDYT0051-KUNNR.

    SORT IT_KNA1 BY KUNNR.

    SELECT * INTO TABLE IT_TVKOT
       FROM TVKOT
        FOR ALL ENTRIES IN IT_ZSDYT0051
      WHERE SPRAS EQ SY-LANGU
        AND VKORG EQ IT_ZSDYT0051-VKORG.

    SORT IT_TVKOT BY VKORG.

    SELECT * INTO TABLE IT_TVTWT
      FROM TVTWT
       FOR ALL ENTRIES IN IT_ZSDYT0051
     WHERE SPRAS EQ SY-LANGU
       AND VTWEG EQ IT_ZSDYT0051-VTWEG.

    SORT IT_TVTWT BY VTWEG.

    SELECT * INTO TABLE IT_TSPAT
      FROM TSPAT
       FOR ALL ENTRIES IN IT_ZSDYT0051
     WHERE SPRAS EQ SY-LANGU
       AND SPART EQ IT_ZSDYT0051-SPART.

    SORT IT_TSPAT BY SPART.

    LOOP AT IT_ZSDYT0051.

      CLEAR: IT_ZSDYT0051_ALV.

*KUNNR  1 Type  KUNNR CHAR  10  0 Número de deudor
*NAME1  1 Type  NAME1_GP  CHAR  35  0 Nombre 1
*VKORG  1 Type  VKORG CHAR  4 0 Organización de ventas
*VTEXT_O  1 Type  VTXTK CHAR  20  0 Denominación
*VTWEG  1 Type  VTWEG CHAR  2 0 Canal de distribución
*VTEXT_C  1 Type  VTXTK CHAR  20  0 Denominación
*SPART  1 Type  SPART CHAR  2 0 Sector
*VTEXT_S  1 Type  VTXTK CHAR  20  0 Denominación

      MOVE-CORRESPONDING IT_ZSDYT0051 TO IT_ZSDYT0051_ALV.

      READ TABLE IT_KNA1 WITH KEY KUNNR = IT_ZSDYT0051-KUNNR BINARY SEARCH.
      IF SY-SUBRC IS INITIAL.
        IT_ZSDYT0051_ALV-NAME1 = IT_KNA1-NAME1.
      ENDIF.

      READ TABLE IT_TVKOT WITH KEY VKORG = IT_ZSDYT0051-VKORG BINARY SEARCH.
      IF SY-SUBRC IS INITIAL.
        IT_ZSDYT0051_ALV-VTEXT_O = IT_TVKOT-VTEXT.
      ENDIF.

      READ TABLE IT_TVTWT WITH KEY VTWEG = IT_ZSDYT0051-VTWEG BINARY SEARCH.
      IF SY-SUBRC IS INITIAL.
        IT_ZSDYT0051_ALV-VTEXT_C = IT_TVTWT-VTEXT.
      ENDIF.

      READ TABLE IT_TSPAT WITH KEY SPART = IT_ZSDYT0051-SPART BINARY SEARCH.
      IF SY-SUBRC IS INITIAL.
        IT_ZSDYT0051_ALV-VTEXT_S = IT_TSPAT-VTEXT.
      ENDIF.

      APPEND IT_ZSDYT0051_ALV.

    ENDLOOP.

  ENDIF.

ENDFORM.
