PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSE01_APROPR_SEG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSE01_APROPR_SEG-CHAVE .
    FIELD ZSE01_APROPR_SEG-BUKRS .
    FIELD ZSE01_APROPR_SEG-DBBDT .
    FIELD ZSE01_APROPR_SEG-DBEDT .
    FIELD ZSE01_APROPR_SEG-DBMON .
    FIELD ZSE01_APROPR_SEG-DBTAG .
    FIELD ZSE01_APROPR_SEG-XFWHW .
    FIELD ZSE01_APROPR_SEG-XBLLT .
    FIELD ZSE01_APROPR_SEG-BLART .
    FIELD ZSE01_APROPR_SEG-XBLNR .
    FIELD ZSE01_APROPR_SEG-BKTXT .
    FIELD ZSE01_APROPR_SEG-WAERS .
    FIELD ZSE01_APROPR_SEG-WWERT .
    FIELD ZSE01_APROPR_SEG-NEWBS_D .
    FIELD ZSE01_APROPR_SEG-NEWKO_D .
    FIELD ZSE01_APROPR_SEG-WRBTR_D .
    FIELD ZSE01_APROPR_SEG-BUPLA_D .
    FIELD ZSE01_APROPR_SEG-KOSTL_D .
    FIELD ZSE01_APROPR_SEG-AUFNR_D .
    FIELD ZSE01_APROPR_SEG-GSBER_D .
    FIELD ZSE01_APROPR_SEG-ZUONR_D .
    FIELD ZSE01_APROPR_SEG-SGTXT_D .
    FIELD ZSE01_APROPR_SEG-NEWBS_C .
    FIELD ZSE01_APROPR_SEG-NEWKO_C .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSE01_APROPR_SEG-CHAVE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
