FUNCTION ZSMARTFORMS_AUTENTICA.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_SMARTFORM) TYPE  TDSFNAME
*"  EXPORTING
*"     REFERENCE(E_CD_AUTENTICACAO) TYPE  ZDE_ID_AUTENTICACAO
*"     REFERENCE(E_AUTENTICA) TYPE  STRING
*"----------------------------------------------------------------------

  DATA: LC_NAME                TYPE RS38L_FNAM,
        LC_CLEAR_TEXT_PASSWORD TYPE CHAR30,
        LC_ENCODED_PASSWORD    TYPE DBCON_PWD,
        WA_ZSMT0001            TYPE ZSMT0001.

  CALL FUNCTION 'NUMBER_GET_NEXT'
    EXPORTING
      NR_RANGE_NR   = '01'
      OBJECT        = 'ZSMART'
      QUANTITY      = '00000000000000000001'
      IGNORE_BUFFER = 'X'
    IMPORTING
      NUMBER        = WA_ZSMT0001-CD_AUTENTICACAO.

  WA_ZSMT0001-NM_SMARTFORM  = I_SMARTFORM.
  WA_ZSMT0001-DT_REGISTRO   = SY-DATUM.
  WA_ZSMT0001-HR_REGISTRO   = SY-UZEIT.
  WA_ZSMT0001-US_REGISTRO   = SY-UNAME.

  LC_CLEAR_TEXT_PASSWORD = WA_ZSMT0001-CD_AUTENTICACAO && WA_ZSMT0001-DT_REGISTRO && WA_ZSMT0001-HR_REGISTRO.
  WA_ZSMT0001-TX_AUTENTICAR = LC_CLEAR_TEXT_PASSWORD.

  CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
    EXPORTING
      FORMNAME = I_SMARTFORM
    IMPORTING
      FM_NAME  = LC_NAME.

  WA_ZSMT0001-DS_FUNCNAME = LC_NAME.

  CALL FUNCTION 'DB_CRYPTO_PASSWORD'
    EXPORTING
      CLEAR_TEXT_PASSWORD = LC_CLEAR_TEXT_PASSWORD
    IMPORTING
      ENCODED_PASSWORD    = LC_ENCODED_PASSWORD.

  WA_ZSMT0001-DS_AUTENTICACAO = LC_ENCODED_PASSWORD.
  MODIFY ZSMT0001 FROM WA_ZSMT0001.
  COMMIT WORK.

  E_CD_AUTENTICACAO = WA_ZSMT0001-CD_AUTENTICACAO.
  E_AUTENTICA = WA_ZSMT0001-DS_AUTENTICACAO.

ENDFUNCTION.
