PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTAB_PENSAO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTAB_PENSAO-PERNR .
    FIELD ZTAB_PENSAO-COD_REC .
    FIELD ZTAB_PENSAO-ENDDA .
    FIELD ZTAB_PENSAO-CPF .
    FIELD ZTAB_PENSAO-DNASC .
    FIELD ZTAB_PENSAO-NOME .
    FIELD ZTAB_PENSAO-TDEP .
    FIELD ZTAB_PENSAO-VALOR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTAB_PENSAO-PERNR .
    FIELD ZTAB_PENSAO-COD_REC .
    FIELD ZTAB_PENSAO-ENDDA .
    FIELD ZTAB_PENSAO-CPF .
    FIELD ZTAB_PENSAO-DNASC .
    FIELD ZTAB_PENSAO-NOME .
    FIELD ZTAB_PENSAO-TDEP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
