FUNCTION ZDENQUEUE_CPROG.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(CPROG) TYPE  SYST_CPROG
*"     REFERENCE(_SCOPE) DEFAULT '3'
*"     REFERENCE(_SYNCHRON) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT ' '
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __SYNCHRON  TYPE DDENQSYNC.

  __SYNCHRON = _SYNCHRON.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_CPROG,
          MANDT	TYPE SY-MANDT,
          CPROG TYPE SYST_CPROG,
        END OF %A_CPROG.

  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_CPROG.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_CPROG-MANDT.
  ENDIF.

  MOVE: CPROG TO %A_CPROG-CPROG.

* Preencher tab.bloqueio:

  __SEQTA_TAB-GNAME = 'SYCPROG'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG  = %A_CPROG.
  APPEND __SEQTA_TAB.

* Lock assigned:
  PERFORM SEND_ENQUEUE(SAPLSENA) TABLES __SEQTA_TAB USING '2' __SCOPE ' ' __SYNCHRON 'ESYCPROG' _COLLECT.

ENDFUNCTION.
