"Name: \FU:MAP2I_BAPISHIPMENTHEADER_VTTK\SE:END\EI
ENHANCEMENT 0 ZVTTK_MAGGI_CAMPOS.
*

  "ZVTTK_MAGGI
  "sdjsdlfjksdl
  MOVE BAPISHIPMENTHEADER-ZID_CARGA
  TO VTTK-ID_CARGA.

  MOVE BAPISHIPMENTHEADER-ZID_ROMANEIO
  TO VTTK-ID_ROMANEIO.

  MOVE BAPISHIPMENTHEADER-ZID_ORDEM
  TO VTTK-ID_ORDEM.

  MOVE BAPISHIPMENTHEADER-ZID_VIAGEM
  TO VTTK-ID_VIAGEM.

ENDENHANCEMENT.
