PROCESS BEFORE OUTPUT.
  MODULE cria_objetos.
  MODULE trata_fields.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_MSG_NF'
  MODULE tc_msg_nf_change_tc_attr.
*&SPWIZARD: MODULE TC_MSG_NF_CHANGE_COL_ATTR.
  LOOP AT   tg_mensagems
       WITH CONTROL tc_msg_nf
       CURSOR tc_msg_nf-current_line.
       MODULE md_change_screen. "PSA
*&SPWIZARD:   MODULE TC_MSG_NF_CHANGE_FIELD_ATTR
  ENDLOOP.

* MODULE STATUS_0110.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_MSG_NF'
  LOOP AT tg_mensagems.
    CHAIN.
      FIELD tg_mensagems-message.
      MODULE tc_msg_nf_modify ON CHAIN-REQUEST.
    ENDCHAIN.
  ENDLOOP.

  CHAIN.
    FIELD gv_text_sd.
    MODULE tc_text_sd ON CHAIN-REQUEST.
  ENDCHAIN.

*&SPWIZARD: MODULE TC_MSG_NF_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_MSG_NF_CHANGE_COL_ATTR.

  MODULE user_command_0203.
