PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_MOVEST'
  MODULE TC_MOVEST_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_MOVEST_CHANGE_COL_ATTR.
  LOOP AT   TG_MOVEST
       WITH CONTROL TC_MOVEST
       CURSOR TC_MOVEST-CURRENT_LINE.
*&SPWIZARD:   MODULE TC_MOVEST_CHANGE_FIELD_ATTR
  ENDLOOP.

* MODULE STATUS_0110.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_MOVEST'
  LOOP AT TG_MOVEST.
    CHAIN.
      FIELD TG_MOVEST-BWART.
      FIELD TG_MOVEST-TCODE.
      FIELD TG_MOVEST-MWSKZ1.
      FIELD TG_MOVEST-estorno.
    endchain.
  ENDLOOP.
*&SPWIZARD: MODULE TC_MOVEST_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_MOVEST_CHANGE_COL_ATTR.

* MODULE USER_COMMAND_0110.
