
PROCESS BEFORE OUTPUT.
  MODULE SET_SUBSCREEN.
  CALL SUBSCREEN SUB_HEADER INCLUDING SY-REPID VG_SUBSCREEN1. "'213'.
  CALL SUBSCREEN SUB_ITENS INCLUDING SY-REPID  VG_SUBSCREEN2. "'214'.
* MODULE STATUS_0110.
*
PROCESS AFTER INPUT.
  MODULE CALL_SUBCREEN.
  CALL SUBSCREEN SUB_HEADER.
  CALL SUBSCREEN SUB_ITENS.
* MODULE USER_COMMAND_0110.
