
PROCESS BEFORE OUTPUT.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_CONTAB'
  MODULE TC_CONTAB_CHANGE_TC_ATTR.
  MODULE TRATA_FIELDS.
*&SPWIZARD: MODULE TC_CONTAB_CHANGE_COL_ATTR.
  LOOP AT   TG_CONTAB
       WITH CONTROL TC_CONTAB
       CURSOR TC_CONTAB-CURRENT_LINE.
    MODULE TC_CONTAB_GET_LINES.
    MODULE MD_CHANGE_SCREEN.
*&SPWIZARD:   MODULE TC_CONTAB_CHANGE_FIELD_ATTR
  ENDLOOP.

* MODULE STATUS_0110.
*
PROCESS AFTER INPUT.

*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_CONTAB'
  LOOP AT TG_CONTAB.
    CHAIN.
      FIELD TG_CONTAB-BSCHL.
      FIELD TG_CONTAB-HKONT.
      FIELD TG_CONTAB-ESTORNO.
      FIELD TG_CONTAB-UMSKZ.
      FIELD TG_CONTAB-TAXTYP.
      FIELD TG_CONTAB-NEWBW.
      MODULE TC_CONTAB_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
    FIELD TG_CONTAB-MARK
      MODULE TC_CONTAB_MARK ON REQUEST.
*    field tg_contab-estorno
*      module mark_estono on request.
  ENDLOOP.
  MODULE TC_CONTAB_USER_COMMAND.
*&SPWIZARD: MODULE TC_CONTAB_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_CONTAB_CHANGE_COL_ATTR.

* MODULE USER_COMMAND_0110.
