PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_CONTAB'
  MODULE trata_fields.
  MODULE busca_valor_cont.
  MODULE CRIA_OBJETOS.
* MODULE STATUS_0110.
*
PROCESS AFTER INPUT.
* MODULE USER_COMMAND_0110.
