PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_IMPOSTOS'
  MODULE TC_IMPOSTOS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_IMPOSTOS_CHANGE_COL_ATTR.
  LOOP AT   TG_IMPO
       WITH CONTROL TC_IMPOSTOS
       CURSOR TC_IMPOSTOS-CURRENT_LINE.
*&SPWIZARD:   MODULE TC_IMPOSTOS_CHANGE_FIELD_ATTR
  ENDLOOP.

* MODULE STATUS_0110.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_IMPOSTOS'
  LOOP AT TG_IMPO.
    CHAIN.
      FIELD TG_IMPO-TAXTYP.
      FIELD TG_IMPO-TTYPETXT.
      FIELD TG_IMPO-TAXGRP.
      FIELD TG_IMPO-BASE.
      FIELD TG_IMPO-RATE.
      FIELD TG_IMPO-TAXVAL.
      FIELD TG_IMPO-EXCBAS.
      FIELD TG_IMPO-OTHBAS.
    endchain.
  ENDLOOP.
*&SPWIZARD: MODULE TC_IMPOSTOS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_IMPOSTOS_CHANGE_COL_ATTR.

* MODULE USER_COMMAND_0110.
