
PROCESS BEFORE OUTPUT.
  MODULE CRIA_OBJETOS.
  MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
  MODULE USER_COMMAND_0100.


PROCESS ON VALUE-REQUEST.
  FIELD P_PARID    MODULE SEARCH_PARID.
  FIELD P_OPERA    MODULE SEARCH_OPER.
