FUNCTION Z_MONTA_XML_CTA_CORRECAO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(P_DOCNUM) TYPE  J_1BDOCNUM
*"     REFERENCE(P_TXT_CORREC) TYPE  CHAR1000SF
*"----------------------------------------------------------------------

  DATA: BEGIN OF WA_NOTA.
          INCLUDE STRUCTURE ZOB_NOTA_FISCAL_SAP.
  DATA: END OF WA_NOTA.

  DATA: WA_ACT_NOTA  TYPE J_1BNFE_ACTIVE,
        WA_J_1BNFDOC TYPE J_1BNFDOC.

  DATA: VL_CHAVE TYPE C LENGTH 44,
         XML      TYPE ZXML.
  DATA: IT_NOTA LIKE STANDARD TABLE OF WA_NOTA.


  SELECT SINGLE *
    INTO WA_J_1BNFDOC
    FROM J_1BNFDOC
   WHERE DOCNUM EQ P_DOCNUM.

  SELECT SINGLE *
    INTO WA_ACT_NOTA
    FROM J_1BNFE_ACTIVE
   WHERE DOCNUM EQ P_DOCNUM.

  CONCATENATE WA_ACT_NOTA-REGIO
              WA_ACT_NOTA-NFYEAR
              WA_ACT_NOTA-NFMONTH
              WA_ACT_NOTA-STCD1
              WA_ACT_NOTA-MODEL
              WA_ACT_NOTA-SERIE
              WA_ACT_NOTA-NFNUM9
              WA_ACT_NOTA-DOCNUM9
              WA_ACT_NOTA-CDV INTO VL_CHAVE.

  PERFORM CTNAB USING CCENFECHAVE  XML."Inicio TAG de grupo das informações da CC-e
  PERFORM CTNAV USING CC_CHNFE     VL_CHAVE     XML."Chave de acesso da NF-e E A01 C 1-1 44
  PERFORM CTNAV USING CC_XCORRECAO P_TXT_CORREC XML."Correção a ser considerada, texto livre.  E A01 C 1-1 15- 1000    Informar a correção a ser considerada. A Correção mais recente substitui as anteriores.
  PERFORM CTNFE USING CCENFECHAVE  XML."Fim TAG de grupo das informações da CC-e


  WA_NOTA-TP_AUTHCOD       = '3'.
  WA_NOTA-NU_DOCUMENTO_SAP = WA_J_1BNFDOC-DOCNUM.
  WA_NOTA-ID_EMPRESA       = WA_J_1BNFDOC-BUKRS.
  WA_NOTA-ID_FILIAL        = WA_J_1BNFDOC-BRANCH.
  WA_NOTA-TB_DIRECAO       = WA_J_1BNFDOC-DIRECT.
  WA_NOTA-NR_NFE           = WA_J_1BNFDOC-NFENUM.
  WA_NOTA-SR_NFE           = WA_J_1BNFDOC-SERIES.
  WA_NOTA-DT_EMISSAO       = WA_J_1BNFDOC-DOCDAT.
  WA_NOTA-ID_DESTINATARIO  = WA_J_1BNFDOC-PARID.
  WA_NOTA-TX_XML           = XML(4000).

  APPEND WA_NOTA TO IT_NOTA.

  SELECT SINGLE *
    FROM SETLEAF INTO @DATA(WL_SETLEAF)
   WHERE SETNAME EQ 'MAGGI_CTG_NFE_SAP'.

  IF ( SY-SUBRC = 0 ) AND ( WL_SETLEAF-VALFROM IS NOT INITIAL ).

    DATA: WL_ZOB_NFE_SAP TYPE ZOB_NFE_SAP.

    MOVE-CORRESPONDING WA_NOTA TO WL_ZOB_NFE_SAP.

    CALL FUNCTION 'Z_GRAVAR_XML_NFE_CTE'
      EXPORTING
        I_XML01            = XML
        I_TIPO             = '1' "NF-e
     CHANGING
        I_ZOB_NFE_SAP      = WL_ZOB_NFE_SAP.

  ELSE.

    CALL FUNCTION 'Z_SD_OUTBOUND_NFE_XML' IN BACKGROUND TASK
      DESTINATION 'XI_XML'
      AS SEPARATE UNIT
      TABLES
        IT_SAIDA = IT_NOTA.

  ENDIF.

  COMMIT WORK.


ENDFUNCTION.
