FUNCTION Z_EMAIL_NFE_CTE_PENDENTES.
*"----------------------------------------------------------------------
*"*"Interface local:
*"----------------------------------------------------------------------

  TYPES: BEGIN OF TY_MODEL,
            SIGN   TYPE CHAR1,
            OPTION TYPE	CHAR2,
            LOW	   TYPE	J_1BMODEL,
            HIGH   TYPE J_1BMODEL,
         END OF TY_MODEL,

         BEGIN OF TY_DOCSTA,
            SIGN   TYPE CHAR1,
            OPTION TYPE	CHAR2,
            LOW	   TYPE	J_1BNFEDOCSTATUS,
            HIGH   TYPE J_1BNFEDOCSTATUS,
         END OF TY_DOCSTA.

  DATA: IT_J_1BNFE_ACTIVE TYPE TABLE OF J_1BNFE_ACTIVE INITIAL SIZE 0 WITH HEADER LINE,
        WA_J_1BNFE_ACTIVE TYPE J_1BNFE_ACTIVE,
        IT_J_1BNFDOC      TYPE TABLE OF J_1BNFDOC INITIAL SIZE 0 WITH HEADER LINE,
        WA_J_1BNFDOC      TYPE J_1BNFDOC,
        IT_J_1BNFDOC2     TYPE TABLE OF J_1BNFDOC INITIAL SIZE 0 WITH HEADER LINE,
        VG_CANCEL         TYPE J_1BCANCEL,
        VG_FORM           TYPE J_1BFORM,
        WA_MODEL          TYPE TY_MODEL,
        IT_MODEL          TYPE TABLE OF TY_MODEL INITIAL SIZE 0 WITH HEADER LINE,
        WA_DOCSTA         TYPE TY_DOCSTA,
        IT_DOCSTA         TYPE TABLE OF TY_DOCSTA INITIAL SIZE 0 WITH HEADER LINE,
        VG_CRENAM         TYPE J_1BCRENAM,
        IT_HTML           TYPE TABLE OF W3HTML INITIAL SIZE 0,
        PACKING_LIST      TYPE TABLE OF SOPCKLSTI1 WITH HEADER LINE,
        DOCUMENT_DATA     TYPE SODOCCHGI1,
        RECEIVERS         TYPE TABLE OF SOMLRECI1 WITH HEADER LINE,
        IT_ETP_TEXT       TYPE TABLE OF DD07V WITH KEY DOMVALUE_L,
        WA_DMO_TEXT       TYPE DD07V,
        IT_ZSDT0034       TYPE TABLE OF ZSDT0034 INITIAL SIZE 0 WITH HEADER LINE,
        IT_ZSDT00342      TYPE TABLE OF ZSDT0034 INITIAL SIZE 0 WITH HEADER LINE,
        WA_ZSDT0034       TYPE ZSDT0034,
        WA_ZSDT00342      TYPE ZSDT0034,
        VG_DOCDAT         LIKE J_1BNFDOC-DOCDAT.

  WA_MODEL-SIGN   = 'I'.
  WA_MODEL-OPTION = 'EQ'.
  WA_MODEL-LOW    = '55'.
  WA_MODEL-HIGH   = '55'.
  APPEND WA_MODEL TO IT_MODEL.

  WA_MODEL-HIGH   = '57'.
  WA_MODEL-HIGH   = '57'.
  APPEND WA_MODEL TO IT_MODEL.

  WA_DOCSTA-SIGN   = 'I'.
  WA_DOCSTA-OPTION = 'EQ'.
  WA_DOCSTA-LOW    = ' '.
  WA_DOCSTA-HIGH   = ' '.
  APPEND WA_DOCSTA TO IT_DOCSTA.

  WA_DOCSTA-LOW    = '3'.
  WA_DOCSTA-HIGH   = '3'.
  APPEND WA_DOCSTA TO IT_DOCSTA.

  VG_CRENAM = 'INTERFACE'.
  "CONCATENATE SY-DATUM(4) '0101' INTO VG_DOCDAT.
  VG_DOCDAT = SY-DATUM - 90.

  SELECT * INTO TABLE IT_J_1BNFE_ACTIVE
    FROM J_1BNFE_ACTIVE
   WHERE DOCSTA IN IT_DOCSTA
     AND CANCEL EQ VG_CANCEL
     AND MODEL  IN IT_MODEL
     AND FORM   NE VG_FORM
     AND CRENAM NE VG_CRENAM.

  IF SY-SUBRC IS INITIAL.

    SELECT * INTO TABLE IT_J_1BNFDOC
      FROM J_1BNFDOC
       FOR ALL ENTRIES IN IT_J_1BNFE_ACTIVE
     WHERE DOCNUM EQ IT_J_1BNFE_ACTIVE-DOCNUM
       AND CANCEL EQ VG_CANCEL
       AND DOCDAT GE VG_DOCDAT.

  ENDIF.

  IF NOT IT_J_1BNFDOC[] IS INITIAL.

    SORT IT_J_1BNFE_ACTIVE BY DOCNUM.

    CALL FUNCTION 'Z_VALORES_DOMINIO'
      EXPORTING
        NAME      = 'J_1BNFE_ACTION_REQUIRED'
      TABLES
        DD07V_TAB = IT_ETP_TEXT.

    PERFORM MONTA_CABECALHO TABLES IT_HTML.

    SORT IT_J_1BNFDOC BY BUKRS BRANCH DOCDAT.

    LOOP AT IT_J_1BNFDOC INTO WA_J_1BNFDOC.
      READ TABLE IT_J_1BNFE_ACTIVE INTO WA_J_1BNFE_ACTIVE WITH KEY DOCNUM = WA_J_1BNFDOC-DOCNUM BINARY SEARCH.
      READ TABLE IT_ETP_TEXT INTO WA_DMO_TEXT WITH KEY DOMVALUE_L = WA_J_1BNFE_ACTIVE-ACTION_REQU.
      PERFORM MONTA_DETALHE TABLES IT_HTML USING WA_J_1BNFDOC WA_J_1BNFE_ACTIVE WA_DMO_TEXT.
    ENDLOOP.

    PERFORM MONTA_FIM TABLES IT_HTML PACKING_LIST USING DOCUMENT_DATA.

    IF SY-MANDT EQ '300'.
      RECEIVERS-RECEIVER = 'indiretos.fiscal@grupomaggi.com.br'.
      RECEIVERS-REC_TYPE = 'U'.
      RECEIVERS-EXPRESS  = 'X'.
      APPEND RECEIVERS.
      RECEIVERS-RECEIVER = 'adelson.silva@grupomaggi.com.br'.
      RECEIVERS-REC_TYPE = 'U'.
      RECEIVERS-EXPRESS  = 'X'.
      APPEND RECEIVERS.
    ELSE.
      RECEIVERS-RECEIVER = 'suporte.desenv@grupomaggi.com.br'.
      RECEIVERS-REC_TYPE = 'U'.
      RECEIVERS-EXPRESS  = 'X'.
      APPEND RECEIVERS.
    ENDIF.

    CALL FUNCTION 'ZHTML_ENVIA_EMAIL_CP'
      EXPORTING
        I_TITULO      = 'Documentos Eletrônicos NF-e/CT-e'
        DOCUMENT_DATA = DOCUMENT_DATA
      TABLES
        PACKING_LIST  = PACKING_LIST
        HTML          = IT_HTML
        RECEIVERS     = RECEIVERS.

    SELECT * INTO TABLE IT_ZSDT0034 FROM ZSDT0034 WHERE STATUS EQ '2'.

    MOVE IT_ZSDT0034[] TO IT_ZSDT00342[].
    SORT IT_ZSDT00342 BY BUKRS BRANCH.
    DELETE ADJACENT DUPLICATES FROM IT_ZSDT00342 COMPARING BUKRS BRANCH.

    LOOP AT IT_ZSDT00342 INTO WA_ZSDT00342.

      CLEAR: IT_J_1BNFDOC2[],
             IT_HTML[],
             PACKING_LIST[],
             RECEIVERS[],
             DOCUMENT_DATA.

      MOVE IT_J_1BNFDOC[] TO IT_J_1BNFDOC2[].
      DELETE IT_J_1BNFDOC2 WHERE BUKRS  NE WA_ZSDT00342-BUKRS.
      DELETE IT_J_1BNFDOC2 WHERE BRANCH NE WA_ZSDT00342-BRANCH.

      IF NOT IT_J_1BNFDOC2[] IS INITIAL.

        PERFORM MONTA_CABECALHO TABLES IT_HTML.

        SORT IT_J_1BNFDOC2 BY BUKRS BRANCH DOCDAT.

        LOOP AT IT_J_1BNFDOC2 INTO WA_J_1BNFDOC.
          READ TABLE IT_J_1BNFE_ACTIVE INTO WA_J_1BNFE_ACTIVE WITH KEY DOCNUM = WA_J_1BNFDOC-DOCNUM BINARY SEARCH.
          READ TABLE IT_ETP_TEXT INTO WA_DMO_TEXT WITH KEY DOMVALUE_L = WA_J_1BNFE_ACTIVE-ACTION_REQU.
          PERFORM MONTA_DETALHE TABLES IT_HTML USING WA_J_1BNFDOC WA_J_1BNFE_ACTIVE WA_DMO_TEXT.
        ENDLOOP.

        PERFORM MONTA_FIM TABLES IT_HTML PACKING_LIST USING DOCUMENT_DATA.

      ENDIF.

      LOOP AT IT_ZSDT0034 INTO WA_ZSDT0034 WHERE BUKRS  EQ WA_ZSDT00342-BUKRS
                                             AND BRANCH EQ WA_ZSDT00342-BRANCH.

        RECEIVERS-RECEIVER = WA_ZSDT0034-SMTP_ADDR.
        RECEIVERS-REC_TYPE = 'U'.
        RECEIVERS-EXPRESS  = 'X'.
        APPEND RECEIVERS.
      ENDLOOP.

      CALL FUNCTION 'ZHTML_ENVIA_EMAIL_CP'
        EXPORTING
          I_TITULO      = 'Documentos Eletrônicos NF-e/CT-e'
          DOCUMENT_DATA = DOCUMENT_DATA
        TABLES
          PACKING_LIST  = PACKING_LIST
          HTML          = IT_HTML
          RECEIVERS     = RECEIVERS.

    ENDLOOP.

  ENDIF.

ENDFUNCTION.
