FUNCTION Z_MONTA_XML_CTE_CORRECAO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(P_DOCNUM) TYPE  J_1BDOCNUM
*"     REFERENCE(P_ID_CC) TYPE  NUM
*"----------------------------------------------------------------------

  DATA: BEGIN OF WA_CONHEC.
          INCLUDE STRUCTURE ZOB_CONHECIMENTO_SAP.
  DATA: END OF WA_CONHEC.

  DATA: WA_ACT_NOTA  TYPE J_1BNFE_ACTIVE,
        WA_J_1BNFDOC TYPE J_1BNFDOC.

  DATA: VL_CHAVE TYPE C LENGTH 44,
         XML      TYPE ZXML,
        VL_VALOR_ALT TYPE STRING.

  DATA: IT_CONHEC     LIKE STANDARD TABLE OF WA_CONHEC,
        IT_ZSDT0081   TYPE TABLE OF ZSDT0081,
        WA_ZSDT0081   TYPE          ZSDT0081,
        V_XCONDUSO    TYPE STRING.

  CONCATENATE  '“A Carta de Correcao e disciplinada pelo Art.'
               '58-B do CONVENIO/SINIEF 06/89: Fica'
               'permitida a utilização de carta de correcao,'
               'para regularização de erro ocorrido na'
               'emissao de documentos fiscais relativos a'
               'prestacao de servico de transporte, desde'
               'que o erro não esteja relacionado com: I - as'
               'variaveis que determinam o valor do imposto'
               'tais como: base de cálculo, alíquota,'
               'diferença de preço, quantidade, valor da'
               'prestacao;II - a correcao de dados'
               'cadastrais que implique mudança do'
               'emitente, tomador, remetente ou do'
               'destinatario;III - a data de emissao ou de'
               'saída.”'
               INTO  V_XCONDUSO  SEPARATED BY SPACE.

  V_XCONDUSO = ZCL_STRING=>TIRA_ACENTOS( I_TEXTO =  ZCL_STRING=>CONVERT_TO_UTF8( I_TEXTO = V_XCONDUSO ) ).


  SELECT SINGLE *
     INTO WA_J_1BNFDOC
     FROM J_1BNFDOC
    WHERE DOCNUM EQ P_DOCNUM.

  SELECT SINGLE *
    INTO WA_ACT_NOTA
    FROM J_1BNFE_ACTIVE
   WHERE DOCNUM EQ P_DOCNUM.

  SELECT *
    FROM ZSDT0081
    INTO TABLE IT_ZSDT0081
    WHERE DOCNUM = P_DOCNUM
    AND   ID_CC  = P_ID_CC.

  CONCATENATE WA_ACT_NOTA-REGIO
              WA_ACT_NOTA-NFYEAR
              WA_ACT_NOTA-NFMONTH
              WA_ACT_NOTA-STCD1
              WA_ACT_NOTA-MODEL
              WA_ACT_NOTA-SERIE
              WA_ACT_NOTA-NFNUM9
              WA_ACT_NOTA-DOCNUM9
              WA_ACT_NOTA-CDV INTO VL_CHAVE.

  PERFORM CTNAB USING CCECTECHAVE  XML.
  PERFORM CTNAV USING CHCTE VL_CHAVE     XML.
  "PERFORM CTNAB USING EVCCECTE  XML.
  "PERFORM CTNAV USING DESCEVENTO 'Carta de Correcao'     XML.

  LOOP AT IT_ZSDT0081 INTO WA_ZSDT0081.
    CLEAR: VL_VALOR_ALT.

    PERFORM CTNAB USING INFCORRECAO  XML.
    PERFORM CTNAV USING GRUPOALTERADO WA_ZSDT0081-GRUPO   XML.
    PERFORM CTNAV USING CAMPOALTERADO WA_ZSDT0081-CAMPO   XML.

    CONCATENATE WA_ZSDT0081-VALOR
                WA_ZSDT0081-VALOR1
                WA_ZSDT0081-VALOR2
                WA_ZSDT0081-VALOR3
           INTO VL_VALOR_ALT SEPARATED BY SPACE.

    PERFORM CTNAV USING VALORALTERADO VL_VALOR_ALT  XML.

    IF ( WA_ZSDT0081-CHAVE_NFE IS NOT INITIAL ).
      PERFORM CTNAV USING NROITEMALTERADO WA_ZSDT0081-CHAVE_NFE XML.
    ENDIF.

    IF WA_ZSDT0081-ITEM > 0.
      PERFORM CTNAV USING NROITEMALTERADO WA_ZSDT0081-ITEM XML.
    ENDIF.
    PERFORM CTNFE USING INFCORRECAO  XML.
  ENDLOOP.

  PERFORM CTNAV USING XCONDUSO V_XCONDUSO XML.

  PERFORM CTNFE USING CCECTECHAVE  XML.


  CLEAR WA_CONHEC.
  CONCATENATE WA_J_1BNFDOC-CREDAT(4) '-' WA_J_1BNFDOC-CREDAT+4(2) '-' WA_J_1BNFDOC-CREDAT+6(2) '*'
              WA_J_1BNFDOC-CRETIM(2) ':' WA_J_1BNFDOC-CRETIM+2(2) ':' WA_J_1BNFDOC-CRETIM+4(2) INTO VG_DT_HORA.
  REPLACE '*' WITH SPACE INTO VG_DT_HORA.

  WA_CONHEC-NU_DOCUMENTO_SAP = P_DOCNUM.
  WA_CONHEC-ID_EMPRESA       = WA_J_1BNFDOC-BUKRS.
  WA_CONHEC-ID_FILIAL        = WA_J_1BNFDOC-BRANCH.
  WA_CONHEC-TP_AUTHCOD       = '3'.
  WA_CONHEC-TB_DIRECAO       = WA_J_1BNFDOC-DIRECT.
  WA_CONHEC-NR_NFE           = WA_J_1BNFDOC-NFENUM.
  WA_CONHEC-SR_NFE           = WA_J_1BNFDOC-SERIES.
  WA_CONHEC-DATA_HORA        = VG_DT_HORA.
  WA_CONHEC-ID_DESTINATARIO  = WA_J_1BNFDOC-PARID.

  CALL FUNCTION 'EFG_GEN_GET_USER_EMAIL'
    EXPORTING
      I_UNAME         = SY-UNAME
    IMPORTING
      E_EMAIL_ADDRESS = WA_CONHEC-DS_EMAIL.

  IF WA_CONHEC-DS_EMAIL IS INITIAL.
    WA_CONHEC-DS_EMAIL = 'indiretos.fiscal@grupomaggi.com.br'.
  ENDIF.

  WA_CONHEC-TX_XML  = XML(4000).
  WA_CONHEC-TX_XML2 = XML+4000(4000).
  WA_CONHEC-TX_XML3 = XML+8000(4000).

  APPEND WA_CONHEC TO IT_CONHEC.

  SELECT SINGLE *
    FROM SETLEAF INTO @DATA(WL_SETLEAF)
   WHERE SETNAME EQ 'MAGGI_CTG_CTE_SAP'.

  IF ( SY-SUBRC = 0 ) AND ( WL_SETLEAF-VALFROM IS NOT INITIAL ).

    DATA: WL_ZOB_CTE_SAP TYPE ZOB_CTE_SAP.

    MOVE-CORRESPONDING WA_CONHEC TO WL_ZOB_CTE_SAP.

    CALL FUNCTION 'Z_GRAVAR_XML_NFE_CTE'
      EXPORTING
        I_XML01            = XML
        I_TIPO             = '2' "CT-e
      CHANGING
        I_ZOB_CTE_SAP      = WL_ZOB_CTE_SAP.

  ELSE.

    CALL FUNCTION 'Z_SD_OUTBOUND_CTE_XML' IN BACKGROUND TASK
      DESTINATION 'XI_XML_CTE'
      AS SEPARATE UNIT
      TABLES
        IT_SAIDA = IT_CONHEC.

  ENDIF.

  COMMIT WORK.
ENDFUNCTION.
