
PROCESS BEFORE OUTPUT.

  MODULE STATUS_6009.
*
PROCESS AFTER INPUT.

  CHAIN.
    FIELD ZCTE_CIOT-MT_CODIGO.
    FIELD ZCTE_CIOT-MT_NOME.
    FIELD ZCTE_CIOT-MT_RAZAO.
    FIELD ZCTE_CIOT-MT_CPF.
    FIELD ZCTE_CIOT-MT_LOGRADOURO.
    FIELD ZCTE_CIOT-MT_NUMERO.
    FIELD ZCTE_CIOT-MT_COMPLEMENTO.
    FIELD ZCTE_CIOT-MT_BAIRRO.
    FIELD ZCTE_CIOT-MT_UF.
    FIELD ZCTE_CIOT-MT_MUNICIPIO.
    FIELD ZCTE_CIOT-MT_CEP.
    FIELD ZCTE_CIOT-MT_RG.
    FIELD ZCTE_CIOT-MT_CNH.
    FIELD ZCTE_CIOT-MT_PIS.
    FIELD ZCTE_CIOT-MT_UF_RG.
    FIELD ZCTE_CIOT-MT_UF_CNH.
    FIELD ZCTE_CIOT-MT_FONE.
    FIELD ZCTE_CIOT-MT_NOMEMAE.
    FIELD ZCTE_CIOT-MT_SEXO.
    FIELD ZCTE_CIOT-MT_DT_NASCIMENTO.
    FIELD ZCTE_CIOT-MT_ORG_RG.
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
  ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD ZCTE_CIOT-MT_MUNICIPIO MODULE CTE_BUSCA_MUN_MT.
