FUNCTION Z_SD_INBOUND_NFE_XML.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  TABLES
*"      IT_NOTAS STRUCTURE  ZIB_NOTA_FISCAL_SAP OPTIONAL
*"----------------------------------------------------------------------
  DATA: LS_ACTTAB     TYPE J_1BNFE_ACTIVE,
        LS_ACTTAB_NEW TYPE J_1BNFE_ACTIVE,
        LS_DOC        TYPE J_1BNFDOC,
        LS_DOC_NEW    TYPE J_1BNFDOC,
        LS_ZSDT0102   TYPE ZSDT0102,
        LS_ZSDT0127   TYPE ZSDT0127.


  SORT IT_NOTAS BY AUTHCOD.

  LOOP AT IT_NOTAS.

    SELECT SINGLE * INTO @DATA(WA_ZSDT0231)
      FROM ZSDT0231
     WHERE DOCNUM EQ @IT_NOTAS-NU_DOCUMENTO_SAP
       AND DOCNUM NE @SPACE.

    IF SY-SUBRC IS INITIAL.
      CONTINUE.
    ENDIF.

    CLEAR: LS_ACTTAB, LS_DOC.

    IF ( IT_NOTAS-TP_AUTHCOD = '4' ) OR
       ( IT_NOTAS-TP_AUTHCOD = '5' ) OR
       ( IT_NOTAS-TP_AUTHCOD = '6' ).

      "Manifestão Destinatario NF-e
      IF ( IT_NOTAS-TP_AUTHCOD = '4'  ) AND
         ( IT_NOTAS-MODEL      = '55' ).

        SELECT SINGLE * INTO LS_ZSDT0127
          FROM ZSDT0127
         WHERE DOC_MANIFESTO EQ IT_NOTAS-NU_DOCUMENTO_SAP.

        IF SY-SUBRC EQ 0.

          CLEAR: LS_ACTTAB_NEW, LS_DOC_NEW.

          PERFORM ALTERA_STATUS USING IT_NOTAS LS_ACTTAB_NEW LS_DOC_NEW.

          COMMIT WORK.

        ENDIF.

      ELSE. "MDF-e

        SELECT SINGLE * INTO LS_ZSDT0102
          FROM ZSDT0102
         WHERE DOCNUM EQ IT_NOTAS-NU_DOCUMENTO_SAP.

        IF SY-SUBRC EQ 0.

          CLEAR: LS_ACTTAB_NEW, LS_DOC_NEW.

          PERFORM ALTERA_STATUS USING IT_NOTAS LS_ACTTAB_NEW LS_DOC_NEW.

          COMMIT WORK.

        ENDIF.

      ENDIF.

    ELSE.

*   Get current status of NF-e
      CALL FUNCTION 'J_1B_NFE_XML_RAED_ACTIVE_TAB'
        EXPORTING
          I_DOCNUM = IT_NOTAS-NU_DOCUMENTO_SAP
*         i_acckey = is_acckey
        IMPORTING
          E_ACTTAB = LS_ACTTAB
        EXCEPTIONS
          NO_ENTRY = 1
          OTHERS   = 2.

      IF SY-SUBRC EQ 0.

        SELECT SINGLE * INTO LS_DOC
          FROM J_1BNFDOC
         WHERE DOCNUM EQ IT_NOTAS-NU_DOCUMENTO_SAP.

        IF SY-SUBRC EQ 0.

          MOVE-CORRESPONDING LS_ACTTAB TO LS_ACTTAB_NEW.
          MOVE-CORRESPONDING LS_DOC    TO LS_DOC_NEW.

          PERFORM ALTERA_STATUS USING IT_NOTAS LS_ACTTAB_NEW LS_DOC_NEW.

          COMMIT WORK.

        ENDIF.

      ENDIF.

    ENDIF.

  ENDLOOP.


ENDFUNCTION.
